namespace Gothic_II_Classic {

	ZENGIN_REGISTER_CLASS(oCAISound);
	ZENGIN_REGISTER_METHOD(oCAISound, &oCAISound::RemoveSlideSound, 0x006426B0);
	ZENGIN_REGISTER_METHOD(oCAISound, &oCAISound::CheckSlideSound, 0x006426D0);
	ZENGIN_REGISTER_METHOD(oCAISound, &oCAISound::GetSoundMaterial, 0x00642760);
	ZENGIN_REGISTER_METHOD(oCAISound, &oCAISound::StartCollisionSound, 0x006428E0);
	ZENGIN_REGISTER_METHOD(oCAISound, &oCAISound::_GetClassDef, 0x00642CC0);

	ZENGIN_REGISTER_CLASS(oCAIArrowBase);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::oCAIArrowBase_OnInit, 0x00643950);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::AddIgnoreCDVob, 0x00643BB0);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::ClearIgnoreCDVob, 0x00643BD0);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::CreateTrail, 0x00643C40);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::_GetClassDef, 0x00643A40);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::Archive, 0x00644470);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::Unarchive, 0x006444F0);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::DoAI, 0x00643E60);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::ReportCollisionToAI, 0x00644160);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::HasAIDetectedCollision, 0x00643A50);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::AICollisionResponseSelfDetected, 0x00643A60);

	ZENGIN_REGISTER_CLASS(oCAIArrow);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::oCAIArrow_OnInit, 0x006445B0);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::SetTarget, 0x00644790);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::ClearUsedVobs, 0x006447D0);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::SetupAIVob, 0x00644880);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::_GetClassDef, 0x00644660);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::Archive, 0x00645440);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::Unarchive, 0x00645510);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::DoAI, 0x00644BE0);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::CanThisCollideWith, 0x00644C10);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::ReportCollisionToAI, 0x00644CB0);

	ZENGIN_REGISTER_CLASS(oCAIDrop);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::oCAIDrop_OnInit, 0x00645620);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::AddIgnoreCDVob, 0x006458B0);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::ClearIgnoreCDVob, 0x006458D0);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::SetupAIVob, 0x00645940);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::SetVelocity, 0x00645C60);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::SetStartPosition, 0x00645D10);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::_GetClassDef, 0x00645700);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::Archive, 0x00645E90);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::Unarchive, 0x00645EA0);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::DoAI, 0x00645BA0);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::CanThisCollideWith, 0x00645720);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::ReportCollisionToAI, 0x00645C10);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::HasAIDetectedCollision, 0x00645710);

	ZENGIN_REGISTER_CLASS(oCAIVobMove);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::oCAIVobMove_OnInit, 0x00642A50);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::AddIgnoreCDVob, 0x00643400);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::ClearIgnoreCDVob, 0x00643420);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::_GetClassDef, 0x00642B20);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::Archive, 0x006432B0);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::Unarchive, 0x00643310);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::DoAI, 0x006430F0);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::CanThisCollideWith, 0x00642B30);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::ReportCollisionToAI, 0x00643260);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::Init, 0x00642D70);

	ZENGIN_REGISTER_CLASS(oCAIVobMoveTorch);
	ZENGIN_REGISTER_METHOD(oCAIVobMoveTorch, &oCAIVobMoveTorch::oCAIVobMoveTorch_OnInit, 0x00643490);
	ZENGIN_REGISTER_METHOD(oCAIVobMoveTorch, &oCAIVobMoveTorch::CheckWater, 0x006436C0);
	ZENGIN_REGISTER_METHOD(oCAIVobMoveTorch, &oCAIVobMoveTorch::BurnedOut, 0x00643770);
	ZENGIN_REGISTER_METHOD(oCAIVobMoveTorch, &oCAIVobMoveTorch::_GetClassDef, 0x00643520);
	ZENGIN_REGISTER_METHOD(oCAIVobMoveTorch, &oCAIVobMoveTorch::DoAI, 0x00643690);
	ZENGIN_REGISTER_METHOD(oCAIVobMoveTorch, &oCAIVobMoveTorch::Init, 0x00643670);

} // namespace Gothic_II_Classic
