namespace Gothic_II_Classic {

	ZENGIN_REGISTER_CLASS(oCItemContainer);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::oCItemContainer_OnInit, 0x006A7270);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetNextContainerLeft, 0x006A7130);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetNextContainerRight, 0x006A71D0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::JumpOffset, 0x006A8FC0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::ActivateNextContainer, 0x006AC660);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::HandleEvent, 0x006ACB50);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Open, 0x006AAA60);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::OpenPassive, 0x006AABE0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetName, 0x006A7480);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::SetName, 0x006A74D0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetMode, 0x006A7610);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::SetMode, 0x006A7620);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Close, 0x006AB440);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Activate, 0x006AB740);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Deactivate, 0x006AB7A0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::IsOpen, 0x006AB710);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::IsActive, 0x006A7640);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::IsEmpty, 0x006AC320);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::IsSplitScreen, 0x006AC350);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::SetContents, 0x006AAA00);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetContents, 0x006AAA50);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Insert, 0x006AB870);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCItemContainer, &oCItemContainer::Remove, void(oCItemContainer::*)(oCItem*), 0x006AB940);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCItemContainer, &oCItemContainer::Remove, oCItem*(oCItemContainer::*)(oCItem*, int), 0x006AB9F0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::RemoveByPtr, 0x006AB9E0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetSelectedItem, 0x006AB7D0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetSelectedItemCount, 0x006AB800);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetSize, 0x006A8F80);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::DisableManipulateItems, 0x006A7650);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::CanManipulateItems, 0x006A7660);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::DisableTransferMoreThanOneItem, 0x006A7670);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::CanTransferMoreThanOneItem, 0x006A7690);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::IsPassive, 0x006AB430);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetTransferCount, 0x006A76A0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::SetTransferCount, 0x006A76B0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::IncTransferCount, 0x006A76C0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Archive, 0x006AC780);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Unarchive, 0x006AC970);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Init, 0x006A8D80);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetPosition, 0x006A8FA0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::LoadGrafix, 0x006A8940);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::DeleteContents, 0x006ABAA0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::NextItem, 0x006ABC50);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::NextItemLine, 0x006ABEB0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::PrevItem, 0x006AC010);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::PrevItemLine, 0x006AC240);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::CheckSelectedItem, 0x006ABB70);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::TransferItem, 0x006AC450);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Draw, 0x006A9BC0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::DrawCategory, 0x006A9070);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::DrawItemInfo, 0x006A9350);

	ZENGIN_REGISTER_CLASS(oCStealContainer);
	ZENGIN_REGISTER_METHOD(oCStealContainer, &oCStealContainer::oCStealContainer_OnInit, 0x006AD100);
	ZENGIN_REGISTER_METHOD(oCStealContainer, &oCStealContainer::HandleEvent, 0x006AD5A0);
	ZENGIN_REGISTER_METHOD(oCStealContainer, &oCStealContainer::SetOwner, 0x006AD2C0);
	ZENGIN_REGISTER_METHOD(oCStealContainer, &oCStealContainer::GetOwner, 0x006AD2E0);
	ZENGIN_REGISTER_METHOD(oCStealContainer, &oCStealContainer::CreateList, 0x006AD2F0);

	ZENGIN_REGISTER_CLASS(oCNpcContainer);
	ZENGIN_REGISTER_METHOD(oCNpcContainer, &oCNpcContainer::oCNpcContainer_OnInit, 0x006AD8D0);
	ZENGIN_REGISTER_METHOD(oCNpcContainer, &oCNpcContainer::HandleEvent, 0x006ADC00);
	ZENGIN_REGISTER_METHOD(oCNpcContainer, &oCNpcContainer::Insert, 0x006ADF00);
	ZENGIN_REGISTER_METHOD(oCNpcContainer, &oCNpcContainer::Remove, 0x006ADF40);
	ZENGIN_REGISTER_METHOD(oCNpcContainer, &oCNpcContainer::CreateList, 0x006ADA80);

	ZENGIN_REGISTER_CLASS(oCNpcInventory);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::oCNpcInventory_OnInit, 0x0081FEC2);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::ClearInventory, 0x006AE2C0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::SetOwner, 0x006AE840);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetOwner, 0x006AE850);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetNumItemsInCategory, 0x006AE860);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetItem, 0x006AE970);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetCategory, 0x006AEBB0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetAmount, 0x006AEE80);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::HandleTrade, 0x006B02E0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::CheckForEquippedItems, 0x006B1800);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::CanCarry, 0x006B1940);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::SetPackAbility, 0x006B1A70);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::UnpackCategory, 0x006B1A90);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetNumItemsInPackString, 0x006B1AA0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetPackedItemBySlot, 0x006B1B90);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::CreateFromPackString, 0x006B1CD0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetPackedItemInfo, 0x006B1D60);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::PackSingleItem, 0x006B2010);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::PackAllItems, 0x006B2380);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::UnpackAllItems, 0x006B2390);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::PackItemsInCategory, 0x006B23A0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::UnpackItemsInCategory, 0x006B2D80);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::HandleEvent, 0x006B0520);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::Open, 0x006AE420);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::Close, 0x006AE810);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::Insert, 0x006AEC50);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::Remove, oCItem*(oCNpcInventory::*)(int, int), 0x006AF590);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::Remove, oCItem*(oCNpcInventory::*)(zSTRING const&, int), 0x006AF680);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::RemoveByPtr, 0x006AF180);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::Archive, 0x006AF6F0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::Unarchive, 0x006AFA30);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::Draw, 0x006AE830);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::DrawCategory, 0x006B00B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::Remove, void(oCNpcInventory::*)(oCItem*), 0x006AF0F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::Remove, oCItem*(oCNpcInventory::*)(oCItem*, int), 0x006AF330);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::IsIn, oCItem*(oCNpcInventory::*)(oCItem*, int), 0x006AEF90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::IsIn, oCItem*(oCNpcInventory::*)(int, int), 0x006AF000);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::IsIn, oCItem*(oCNpcInventory::*)(zSTRING const&, int), 0x006AEFD0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::IsEmpty, int(oCNpcInventory::*)(), 0x006AC320);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::IsEmpty, int(oCNpcInventory::*)(int), 0x006AF6B0);

} // namespace Gothic_II_Classic
