namespace Gothic_II_Classic {

	ZENGIN_REGISTER_CLASS(oCMOB);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::oCMOB_OnInit, 0x006BD860);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::SetMoveable, 0x006BDE70);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::IsMoveable, 0x006BDE90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCMOB, &oCMOB::SetOwner, void(oCMOB::*)(zSTRING const&, zSTRING const&), 0x006BDEF0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCMOB, &oCMOB::SetOwner, void(oCMOB::*)(int, int), 0x006BE0E0);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::IsOwner, 0x006BE140);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::Hit, 0x006BE190);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::InsertInIgnoreList, 0x006BE400);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::RemoveFromIgnoreList, 0x006BE430);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::_GetClassDef, 0x006BD990);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::Archive, 0x006BE4D0);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::Unarchive, 0x006BE610);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::OnDamage, 0x006BDE30);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::OnMessage, 0x006BDE40);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::CanThisCollideWith, 0x006BE490);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::SetVisual, 0x006BDB60);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::IsOwnedByGuild, 0x006BE100);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::IsOwnedByNpc, 0x006BE120);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::GetSoundMaterial_AM, 0x006BDED0);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::SetSoundMaterial, 0x006BDEA0);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::GetSoundMaterial, 0x006BDEC0);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::SetName, 0x006BDB80);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::GetName, 0x006BDBA0);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::GetModel, 0x006BDE50);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::GetScemeName, 0x006BDC70);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::Destroy, 0x006BE1A0);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::AllowDiscardingOfSubtree, 0x006BEC30);

	ZENGIN_REGISTER_CLASS(oCMobInter);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::oCMobInter_OnInit, 0x006BEF80);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::SetTempState, 0x006BF4B0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::IsTempStateChanged, 0x006BF4F0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::SetStateToTempState, 0x006BF500);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::SetMobBodyState, 0x006BF580);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::HasUseWithItem, 0x006BFAD0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::ScanIdealPositions, 0x006BFBA0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::GetFreePosition, 0x006BFEC0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::SetHeading, 0x006C0160);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::SetIdealPosition, 0x006C01B0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::SendStateChange, 0x006C0D00);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::SendEndInteraction, 0x006C0FF0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::StartTransitionAniNpc, 0x006C20C0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::IsMultiMob, 0x006C2E20);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::IsAvailable, 0x006C2E30);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::MarkAsUsed, 0x006C2E90);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::_GetClassDef, 0x006BF100);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::Archive, 0x006C4280);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::Unarchive, 0x006C4320);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::OnTrigger, 0x006C0740);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::OnUntrigger, 0x006C0A30);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::OnDamage, 0x006BF8B0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::OnMessage, 0x006BF8C0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::OnTick, 0x006C06C0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::SetVisual, 0x006BF330);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::GetTriggerTarget, 0x006BAC50);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::GetScemeName, 0x006BFB50);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::GetState, 0x006BABF0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::GetStateNum, 0x006BAC00);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::GetDirection, 0x006BAC10);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::SetDirection, 0x006BAC20);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::SetUseWithItem, 0x006BF970);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::GetUseWithItem, 0x006BFAB0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::Reset, 0x006C0400);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::Interact, 0x006C1180);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::EndInteraction, 0x006C38C0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::InterruptInteraction, 0x006C2C50);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::StopInteraction, 0x006C3B90);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::CanInteractWith, 0x006C2EB0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::IsInteractingWith, 0x006C34C0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::IsOccupied, 0x006BAC30);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::AI_UseMobToState, 0x006C3E70);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::IsIn, 0x006BAC40);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::IsInState, 0x006C1A70);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::StartInteraction, 0x006C34F0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::StartStateChange, 0x006C1E10);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::CheckStateChange, 0x006C23B0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::CanChangeState, 0x006C1BB0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::GetTransitionNames, 0x006C1550);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::OnBeginStateChange, 0x006C2BE0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::OnEndStateChange, 0x006C2BF0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::CallOnStateFunc, 0x006C27E0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::SendCallOnStateFunc, 0x006C2A40);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::SearchFreePosition, 0x006BFF30);

	ZENGIN_REGISTER_CLASS(oCMobBed);
	ZENGIN_REGISTER_METHOD(oCMobBed, &oCMobBed::oCMobBed_OnInit, 0x006C4DC0);
	ZENGIN_REGISTER_METHOD(oCMobBed, &oCMobBed::_GetClassDef, 0x006BAC90);
	ZENGIN_REGISTER_METHOD(oCMobBed, &oCMobBed::GetScemeName, 0x006C5210);
	ZENGIN_REGISTER_METHOD(oCMobBed, &oCMobBed::StartInteraction, 0x006C5190);
	ZENGIN_REGISTER_METHOD(oCMobBed, &oCMobBed::OnBeginStateChange, 0x006C51A0);
	ZENGIN_REGISTER_METHOD(oCMobBed, &oCMobBed::OnEndStateChange, 0x006C51B0);
	ZENGIN_REGISTER_METHOD(oCMobBed, &oCMobBed::SearchFreePosition, 0x006C52C0);

	ZENGIN_REGISTER_CLASS(oCMobSwitch);
	ZENGIN_REGISTER_METHOD(oCMobSwitch, &oCMobSwitch::oCMobSwitch_OnInit, 0x006C5450);
	ZENGIN_REGISTER_METHOD(oCMobSwitch, &oCMobSwitch::_GetClassDef, 0x006BAFD0);
	ZENGIN_REGISTER_METHOD(oCMobSwitch, &oCMobSwitch::Archive, 0x006C5740);
	ZENGIN_REGISTER_METHOD(oCMobSwitch, &oCMobSwitch::Unarchive, 0x006C57E0);

	ZENGIN_REGISTER_CLASS(oCMobItemSlot);
	ZENGIN_REGISTER_METHOD(oCMobItemSlot, &oCMobItemSlot::oCMobItemSlot_OnInit, 0x006C9DF0);
	ZENGIN_REGISTER_METHOD(oCMobItemSlot, &oCMobItemSlot::_GetClassDef, 0x006BCA70);
	ZENGIN_REGISTER_METHOD(oCMobItemSlot, &oCMobItemSlot::Archive, 0x006CA3A0);
	ZENGIN_REGISTER_METHOD(oCMobItemSlot, &oCMobItemSlot::Unarchive, 0x006CA470);
	ZENGIN_REGISTER_METHOD(oCMobItemSlot, &oCMobItemSlot::GetUseWithItem, 0x006CA020);
	ZENGIN_REGISTER_METHOD(oCMobItemSlot, &oCMobItemSlot::CanInteractWith, 0x006CA060);
	ZENGIN_REGISTER_METHOD(oCMobItemSlot, &oCMobItemSlot::IsIn, 0x006CA370);
	ZENGIN_REGISTER_METHOD(oCMobItemSlot, &oCMobItemSlot::GetInsertedItem, 0x006CA080);
	ZENGIN_REGISTER_METHOD(oCMobItemSlot, &oCMobItemSlot::PlaceItem, 0x006CA090);
	ZENGIN_REGISTER_METHOD(oCMobItemSlot, &oCMobItemSlot::RemoveItem, 0x006CA330);

	ZENGIN_REGISTER_CLASS(oCMobLockable);
	ZENGIN_REGISTER_METHOD(oCMobLockable, &oCMobLockable::oCMobLockable_OnInit, 0x006C5890);
	ZENGIN_REGISTER_METHOD(oCMobLockable, &oCMobLockable::CanOpen, 0x006C6460);
	ZENGIN_REGISTER_METHOD(oCMobLockable, &oCMobLockable::_GetClassDef, 0x006BB580);
	ZENGIN_REGISTER_METHOD(oCMobLockable, &oCMobLockable::Archive, 0x006C7320);
	ZENGIN_REGISTER_METHOD(oCMobLockable, &oCMobLockable::Unarchive, 0x006C7410);
	ZENGIN_REGISTER_METHOD(oCMobLockable, &oCMobLockable::OnMessage, 0x006BB830);
	ZENGIN_REGISTER_METHOD(oCMobLockable, &oCMobLockable::Interact, 0x006C5C60);
	ZENGIN_REGISTER_METHOD(oCMobLockable, &oCMobLockable::CanInteractWith, 0x006C5C30);
	ZENGIN_REGISTER_METHOD(oCMobLockable, &oCMobLockable::CanChangeState, 0x006C6250);
	ZENGIN_REGISTER_METHOD(oCMobLockable, &oCMobLockable::OnEndStateChange, 0x006C62A0);
	ZENGIN_REGISTER_METHOD(oCMobLockable, &oCMobLockable::SetLocked, 0x006BB590);
	ZENGIN_REGISTER_METHOD(oCMobLockable, &oCMobLockable::SetKeyInstance, 0x006BB5B0);
	ZENGIN_REGISTER_METHOD(oCMobLockable, &oCMobLockable::SetPickLockStr, 0x006BB6F0);
	ZENGIN_REGISTER_METHOD(oCMobLockable, &oCMobLockable::Lock, 0x006C7130);
	ZENGIN_REGISTER_METHOD(oCMobLockable, &oCMobLockable::Unlock, 0x006C69E0);
	ZENGIN_REGISTER_METHOD(oCMobLockable, &oCMobLockable::PickLock, 0x006C6770);

	ZENGIN_REGISTER_CLASS(oCMobContainer);
	ZENGIN_REGISTER_METHOD(oCMobContainer, &oCMobContainer::oCMobContainer_OnInit, 0x006C7750);
	ZENGIN_REGISTER_METHOD(oCMobContainer, &oCMobContainer::_GetClassDef, 0x006BB900);
	ZENGIN_REGISTER_METHOD(oCMobContainer, &oCMobContainer::Archive, 0x006C85F0);
	ZENGIN_REGISTER_METHOD(oCMobContainer, &oCMobContainer::Unarchive, 0x006C8790);
	ZENGIN_REGISTER_METHOD(oCMobContainer, &oCMobContainer::OnMessage, 0x006C7B20);
	ZENGIN_REGISTER_METHOD(oCMobContainer, &oCMobContainer::Destroy, 0x006C7C20);
	ZENGIN_REGISTER_METHOD(oCMobContainer, &oCMobContainer::Reset, 0x006C7DD0);
	ZENGIN_REGISTER_METHOD(oCMobContainer, &oCMobContainer::IsIn, 0x006C8430);
	ZENGIN_REGISTER_METHOD(oCMobContainer, &oCMobContainer::Open, 0x006C8470);
	ZENGIN_REGISTER_METHOD(oCMobContainer, &oCMobContainer::Close, 0x006C85B0);
	ZENGIN_REGISTER_METHOD(oCMobContainer, &oCMobContainer::Insert, 0x006C7F30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCMobContainer, &oCMobContainer::Remove, void(oCMobContainer::*)(oCItem*), 0x006C7F60);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCMobContainer, &oCMobContainer::Remove, oCItem*(oCMobContainer::*)(oCItem*, int), 0x006C7FF0);
	ZENGIN_REGISTER_METHOD(oCMobContainer, &oCMobContainer::CreateContents, 0x006C8100);

	ZENGIN_REGISTER_CLASS(oCMobDoor);
	ZENGIN_REGISTER_METHOD(oCMobDoor, &oCMobDoor::oCMobDoor_OnInit, 0x006C8920);
	ZENGIN_REGISTER_METHOD(oCMobDoor, &oCMobDoor::_GetClassDef, 0x006BC390);
	ZENGIN_REGISTER_METHOD(oCMobDoor, &oCMobDoor::GetScemeName, 0x006C8CD0);
	ZENGIN_REGISTER_METHOD(oCMobDoor, &oCMobDoor::SearchFreePosition, 0x006C8D80);
	ZENGIN_REGISTER_METHOD(oCMobDoor, &oCMobDoor::Open, 0x006BC3A0);
	ZENGIN_REGISTER_METHOD(oCMobDoor, &oCMobDoor::Close, 0x006BC3B0);

	ZENGIN_REGISTER_CLASS(oCMobFire);
	ZENGIN_REGISTER_METHOD(oCMobFire, &oCMobFire::oCMobFire_OnInit, 0x006C43D0);
	ZENGIN_REGISTER_METHOD(oCMobFire, &oCMobFire::DeleteEffects, 0x006C47C0);
	ZENGIN_REGISTER_METHOD(oCMobFire, &oCMobFire::_GetClassDef, 0x006BC7C0);
	ZENGIN_REGISTER_METHOD(oCMobFire, &oCMobFire::Archive, 0x006C4BD0);
	ZENGIN_REGISTER_METHOD(oCMobFire, &oCMobFire::Unarchive, 0x006C4CE0);
	ZENGIN_REGISTER_METHOD(oCMobFire, &oCMobFire::OnTrigger, 0x006C48F0);
	ZENGIN_REGISTER_METHOD(oCMobFire, &oCMobFire::OnUntrigger, 0x006C4B00);
	ZENGIN_REGISTER_METHOD(oCMobFire, &oCMobFire::OnDamage, 0x006C4810);
	ZENGIN_REGISTER_METHOD(oCMobFire, &oCMobFire::OnEndStateChange, 0x006C4860);
	ZENGIN_REGISTER_METHOD(oCMobFire, &oCMobFire::PreSave, 0x006C4B70);
	ZENGIN_REGISTER_METHOD(oCMobFire, &oCMobFire::PostSave, 0x006C4CB0);

	ZENGIN_REGISTER_CLASS(oCMobWheel);
	ZENGIN_REGISTER_METHOD(oCMobWheel, &oCMobWheel::oCMobWheel_OnInit, 0x006C8F10);
	ZENGIN_REGISTER_METHOD(oCMobWheel, &oCMobWheel::_GetClassDef, 0x006BBC50);
	ZENGIN_REGISTER_METHOD(oCMobWheel, &oCMobWheel::OnTrigger, 0x006C9040);
	ZENGIN_REGISTER_METHOD(oCMobWheel, &oCMobWheel::OnUntrigger, 0x006C9150);
	ZENGIN_REGISTER_METHOD(oCMobWheel, &oCMobWheel::Interact, 0x006C9250);

	ZENGIN_REGISTER_CLASS(oCMobLadder);
	ZENGIN_REGISTER_METHOD(oCMobLadder, &oCMobLadder::oCMobLadder_OnInit, 0x006C9430);
	ZENGIN_REGISTER_METHOD(oCMobLadder, &oCMobLadder::_GetClassDef, 0x006BBFB0);
	ZENGIN_REGISTER_METHOD(oCMobLadder, &oCMobLadder::DoFocusCheckBBox, 0x006BBFC0);
	ZENGIN_REGISTER_METHOD(oCMobLadder, &oCMobLadder::Interact, 0x006C99D0);
	ZENGIN_REGISTER_METHOD(oCMobLadder, &oCMobLadder::EndInteraction, 0x006C9DD0);
	ZENGIN_REGISTER_METHOD(oCMobLadder, &oCMobLadder::CanInteractWith, 0x006C9950);
	ZENGIN_REGISTER_METHOD(oCMobLadder, &oCMobLadder::StartInteraction, 0x006C9740);
	ZENGIN_REGISTER_METHOD(oCMobLadder, &oCMobLadder::CanChangeState, 0x006C9900);
	ZENGIN_REGISTER_METHOD(oCMobLadder, &oCMobLadder::SearchFreePosition, 0x006C9960);

	ZENGIN_REGISTER_CLASS(oCDummyVobGenerator);
	ZENGIN_REGISTER_METHOD(oCDummyVobGenerator, &oCDummyVobGenerator::oCDummyVobGenerator_OnInit, 0x006CA560);
	ZENGIN_REGISTER_METHOD(oCDummyVobGenerator, &oCDummyVobGenerator::_GetClassDef, 0x006BCD30);
	ZENGIN_REGISTER_METHOD(oCDummyVobGenerator, &oCDummyVobGenerator::OnTrigger, 0x006CA5D0);

	ZENGIN_REGISTER_CLASS(oCMobMsg);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCMobMsg, &oCMobMsg::oCMobMsg_OnInit, void(oCMobMsg::*)(oCMobMsg::TMobMsgSubType, oCNpc*), 0x006BD190);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCMobMsg, &oCMobMsg::oCMobMsg_OnInit, void(oCMobMsg::*)(), 0x006BD310);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCMobMsg, &oCMobMsg::oCMobMsg_OnInit, void(oCMobMsg::*)(oCMobMsg::TMobMsgSubType, oCNpc*, int), 0x006BD440);
	ZENGIN_REGISTER_METHOD(oCMobMsg, &oCMobMsg::_GetClassDef, 0x006BD170);
	ZENGIN_REGISTER_METHOD(oCMobMsg, &oCMobMsg::IsNetRelevant, 0x006BD180);
	ZENGIN_REGISTER_METHOD(oCMobMsg, &oCMobMsg::MD_GetNumOfSubTypes, 0x006BD6B0);
	ZENGIN_REGISTER_METHOD(oCMobMsg, &oCMobMsg::MD_GetSubTypeString, 0x006BD6C0);
	ZENGIN_REGISTER_METHOD(oCMobMsg, &oCMobMsg::Pack, 0x006BD590);
	ZENGIN_REGISTER_METHOD(oCMobMsg, &oCMobMsg::Unpack, 0x006BD610);

} // namespace Gothic_II_Classic
