namespace Gothic_II_Classic {

	ZENGIN_REGISTER_CLASS(oCSVMManager);
	ZENGIN_REGISTER_METHOD(oCSVMManager, &oCSVMManager::oCSVMManager_OnInit, 0x0071A130);
	ZENGIN_REGISTER_METHOD(oCSVMManager, &oCSVMManager::GetOU, 0x0071A410);

	ZENGIN_REGISTER_CLASS(oCSVM);
	ZENGIN_REGISTER_METHOD(oCSVM, &oCSVM::oCSVM_OnInit, 0x0071A820);
	ZENGIN_REGISTER_METHOD(oCSVM, &oCSVM::InitByScript, 0x0071A850);
	ZENGIN_REGISTER_METHOD(oCSVM, &oCSVM::GetOU, 0x0071AB00);

} // namespace Gothic_II_Classic
