namespace Gothic_II_Classic {

	ZENGIN_REGISTER_CLASS(oCTrajectory);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::Calc, 0x00486300);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::Changed, 0x00486690);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::Interpolate, 0x004866A0);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::InterpolateN, 0x00486AD0);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::Draw, 0x00486BE0);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::Clear, 0x00486EA0);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::RecalcByColl, 0x00486F70);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::ApplyGrav, 0x004873E0);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::SetByList, 0x00487450);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::VobCross, 0x004875C0);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::InsertKey, 0x0048F5B0);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::GetKey, 0x0048F6C0);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::GetNumKeys, 0x0048F740);

	ZENGIN_REGISTER_CLASS(oCEmitterKey);
	ZENGIN_REGISTER_METHOD(oCEmitterKey, &oCEmitterKey::oCEmitterKey_OnInit, 0x00487650);
	ZENGIN_REGISTER_METHOD(oCEmitterKey, &oCEmitterKey::SetByScript, 0x00487B40);
	ZENGIN_REGISTER_METHOD(oCEmitterKey, &oCEmitterKey::ParseStrings, 0x00487D10);
	ZENGIN_REGISTER_METHOD(oCEmitterKey, &oCEmitterKey::Edit, 0x00498E50);
	ZENGIN_REGISTER_METHOD(oCEmitterKey, &oCEmitterKey::SetDefaultByFX, 0x0049C2A0);

	ZENGIN_REGISTER_CLASS(oCVisualFX);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::oCVisualFX_OnInit, 0x004882E0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::CreateHierachy, 0x004895B0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::DisposeHierachy, 0x00489850);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::InitValues, 0x00489EB0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::ParseStrings, 0x0048A4E0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::UpdateFXByEmitterKey, 0x0048C430);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::CreateBackup, 0x0048CC30);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::FindKey, 0x0048CC40);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCVisualFX, &oCVisualFX::CreateAndCastFX, oCVisualFX*(oCVisualFX::*)(zSTRING const&, zCVob const*, zCVob const*), 0x0048D4C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCVisualFX, &oCVisualFX::CreateAndCastFX, oCVisualFX*(oCVisualFX::*)(zSTRING const&, zMAT4 const&), 0x0048D810);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::CreateInvestFX, 0x0048FB80);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::InitInvestFX, 0x0048FD00);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::StopInvestFX, 0x0048FE60);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::InitEffect, 0x00492950);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::EndEffect, 0x004930A0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetShowVisual, 0x00493140);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::ProcessQueuedCollisions, 0x00493C50);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::ProcessCollision, 0x00493CF0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::CheckDeletion, 0x00495120);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::UpdateActKey, 0x00495730);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::DoMovements, 0x00495980);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::CheckDelayedTrigger, 0x00496EC0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::AdjustShapeToOrigin, 0x00497230);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::UpdateEffects, 0x00497840);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::Edit, 0x00498680);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetupEmitterKeysByVisual, 0x0049C720);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetName, 0x0078B010);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::_GetClassDef, 0x00488850);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::Archive, 0x00497EA0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::Unarchive, 0x00497EB0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::OnTick, 0x00497DC0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::CanThisCollideWith, 0x00494EF0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::Open, 0x0048FF10);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetOrigin, 0x0048F770);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCVisualFX, &oCVisualFX::SetTarget, void(oCVisualFX::*)(zCVob*), 0x0048F950);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCVisualFX, &oCVisualFX::SetTarget, void(oCVisualFX::*)(zVEC3&), 0x0048FAC0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetInflictor, 0x0048F890);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetOrigin, 0x00488860);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetTarget, 0x00488870);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetInflictor, 0x00488880);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCVisualFX, &oCVisualFX::Init, void(oCVisualFX::*)(zCVob const*, zVEC3 const&), 0x00490430);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCVisualFX, &oCVisualFX::Init, void(oCVisualFX::*)(zCVob const*, zCVob const*, zCVob const*), 0x00490540);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCVisualFX, &oCVisualFX::Init, void(oCVisualFX::*)(zCArray<zCVob*> const&), 0x00490C90);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::InvestNext, 0x00490E20);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetLevel, 0x004912A0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetLevel, 0x00491720);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::Cast, 0x00491730);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::Stop, 0x004921B0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::Kill, 0x00492540);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::Play, 0x00488890);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::CanBeDeleted, 0x00492820);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::IsFinished, 0x00492860);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::IsLooping, 0x004928E0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetByScript, 0x0048BB20);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetDuration, 0x004888A0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::Reset, 0x00490250);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::ReportCollision, 0x004932A0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetCollisionEnabled, 0x0048B9C0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetCollisionCandidates, 0x00494D10);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetCollisionCandidates, 0x004888B0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetNumCollisionCandidates, 0x00488950);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetCollidedCandidates, 0x00494E30);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetDamage, 0x00488960);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetDamageType, 0x00488970);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetDamage, 0x00488980);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetDamageType, 0x00488990);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::IsASpell, 0x004889A0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetSpellType, 0x004889B0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetSpellType, 0x004889C0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetSpellTargetTypes, 0x004889D0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetSpellTargetTypes, 0x004889E0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetSendsAssessMagic, 0x00489AF0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetSendsAssessMagic, 0x00489A60);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetIsProjectile, 0x004889F0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetIsProjectile, 0x00488A00);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetVisualByString, 0x0048A8B0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::CalcTrajectory, 0x0048DC20);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::Collide, 0x00491FD0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::CollisionResponse, 0x004947C0);

	ZENGIN_REGISTER_CLASS(oCVisualFXAI);
	ZENGIN_REGISTER_METHOD(oCVisualFXAI, &oCVisualFXAI::DoAI, 0x00497EC0);
	ZENGIN_REGISTER_METHOD(oCVisualFXAI, &oCVisualFXAI::ReportCollisionToAI, 0x0048A410);
	ZENGIN_REGISTER_METHOD(oCVisualFXAI, &oCVisualFXAI::HostVobAddedToWorld, 0x0048A430);

} // namespace Gothic_II_Classic
