namespace Gothic_II_Classic {

	ZENGIN_REGISTER_CLASS(oCVob);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::oCVob_OnInit, 0x0071BC60);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::GetShowDebug, 0x0071BD60);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::ToggleShowDebug, 0x0071BD90);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::SetShowDebug, 0x0071BE10);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::HasNpcEnoughSpace, 0x0071C980);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::HasEnoughSpace, 0x0071CC70);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::SearchNpcPosition, 0x0071CE20);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::SearchFreePosition, 0x0071D270);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::SetOnFloor, 0x0071D6A0);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::GetFloorPosition, 0x0071D6F0);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::GetFloorPositionWithVob, 0x0071D7C0);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::StartParticleEffects, 0x0071D960);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::_GetClassDef, 0x0071BC80);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::Archive, 0x0071D940);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::Unarchive, 0x0071D950);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::Render, 0x0071D970);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::GetCSStateFlags, 0x006B3740);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::Init, 0x0071BCE0);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::ShowDebugInfo, 0x0071BE90);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::GetInstance, 0x0071D8A0);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::GetInstanceName, 0x0071D8B0);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::IsOwnedByGuild, 0x006D00D0);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::IsOwnedByNpc, 0x006D00E0);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::DoFocusCheckBBox, 0x006B3720);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::GetAIVobMove, 0x0071DBB0);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::GetSoundMaterial_AM, 0x0071BC90);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::SetSoundMaterial, 0x006B3730);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::GetSoundMaterial, 0x006D00F0);

	ZENGIN_REGISTER_CLASS(oCTouchDamage);
	ZENGIN_REGISTER_METHOD(oCTouchDamage, &oCTouchDamage::_GetClassDef, 0x0071E130);
	ZENGIN_REGISTER_METHOD(oCTouchDamage, &oCTouchDamage::GetDamageTypeArcEnum, 0x0071DC60);

} // namespace Gothic_II_Classic
