namespace Gothic_II_Classic {

	ZENGIN_REGISTER_CLASS(zTEngineStats);
	ZENGIN_REGISTER_METHOD(zTEngineStats, &zTEngineStats::PrintScreen, 0x00507F40);

	ZENGIN_REGISTER_CLASS(zCLineCache);
	ZENGIN_REGISTER_METHOD(zCLineCache, &zCLineCache::Line, 0x00508570);
	ZENGIN_REGISTER_METHOD(zCLineCache, &zCLineCache::Flush, 0x00508600);
	ZENGIN_REGISTER_METHOD(zCLineCache, &zCLineCache::Line3D, 0x005086A0);
	ZENGIN_REGISTER_METHOD(zCLineCache, &zCLineCache::LineCS3D, 0x00508AA0);

	ZENGIN_REGISTER_CLASS(zCCamera);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::zCCamera_OnInit, 0x00544C40);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::Project, void(zCCamera::*)(zVEC3 const* const, float&, float&) const, 0x0052D0E0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::PushTransform, 0x00545150);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::PopTransform, 0x005451E0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::SetTransform, 0x00545320);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::GetTransform, 0x00545480);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::Activate, 0x005454E0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::CreateProjectionMatrix, 0x005455F0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::UpdateProjectionMatrix, 0x00545670);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::GetFOV, float(zCCamera::*)() const, 0x005456C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::GetFOV, void(zCCamera::*)(float&, float&) const, 0x005456D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::SetFOV, void(zCCamera::*)(float), 0x00545700);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::SetFOV, void(zCCamera::*)(float, float), 0x00545740);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::UpdateViewport, 0x00545870);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::SetRenderTarget, 0x005459B0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::SetRenderScreenFadeTex, 0x005459D0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::SetUpFrustum, 0x00545B00);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::SetFarClipZ, 0x00545FE0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::BBox3DInFrustum, zTCam_ClipType(zCCamera::*)(zTBBox3D const&), 0x00546190);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::BBox3DInFrustum, zTCam_ClipType(zCCamera::*)(zTBBox3D const&, int&), 0x005461F0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::StopTremor, 0x00546430);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::AddTremor, 0x00546440);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::PreRenderProcessing, 0x005465B0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::PostRenderProcessing, 0x00546700);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::GetCamPos, 0x00546740);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::InitDrawPolySimple, 0x00546770);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::CleanupDrawPolySimple, 0x00546830);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::DrawPolySimple, 0x00546890);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::SetRenderScreenFade, 0x005469A0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::SetRenderScreenFadeTexAniFPS, 0x005469C0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::SetRenderScreenFadeTexBlendFunc, 0x005469F0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::SetRenderCinemaScope, 0x00546A00);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::RenderScreenFade, 0x00546A20);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::RenderCinemaScope, 0x00546B10);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::ScreenProjectionTouchesPortalRough, 0x00546C60);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::ScreenProjectionTouchesPortal, 0x00546EE0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::ProjectClamp, 0x00566AB0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::Project, void(zCCamera::*)(zVEC3 const* const, int&, int&), 0x00574F20);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::Project, void(zCCamera::*)(zVEC3 const* const, float, float&, float&) const, 0x005FE050);

	ZENGIN_REGISTER_CLASS(zCVertex);
	ZENGIN_REGISTER_METHOD(zCVertex, &zCVertex::zCVertex_OnInit, 0x0056C410);
	ZENGIN_REGISTER_METHOD(zCVertex, &zCVertex::Draw, 0x00508D60);
	ZENGIN_REGISTER_METHOD(zCVertex, &zCVertex::CreateVertexTransform, 0x00508E50);
	ZENGIN_REGISTER_METHOD(zCVertex, &zCVertex::ResetVertexTransform, 0x005BEF20);

	ZENGIN_REGISTER_CLASS(zCVertFeature);
	ZENGIN_REGISTER_METHOD(zCVertFeature, &zCVertFeature::zCVertFeature_OnInit, 0x00568510);

	ZENGIN_REGISTER_CLASS(zCPolygon);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::zCPolygon_OnInit, 0x005B1430);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::RenderPoly, 0x00526FE0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::ApplyMorphing, 0x00527620);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::LightClippedPoly, 0x00527F40);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TransformProjectLight, 0x005287F0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TransformProject, 0x005289C0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::SetMaterial, 0x005345B0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::ClipToPlane, 0x005B1780);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::ClipToPlane_Occluder, 0x005B1C20);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::Unclip, 0x005B1EA0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::Unclip_Occluder, 0x005B1F20);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CopyClipFeaturesForTexAniMapping, 0x005B1F40);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::ClipToFrustum, 0x005B1FB0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::ClipToFrustum_Occluder, 0x005B22F0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::ClassifyPlane, 0x005B24D0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::ClassifyPlaneBSPBuild, 0x005B2580);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CalcNormal, 0x005B2610);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CalcNormalApprox, 0x005B2A30);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::GetScreenBBox2D, 0x005B2E60);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::DrawWire, 0x005B2F00);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::LightDynCamSpace, 0x005B36E0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::GetLightStatAtPos, 0x005B38A0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CheckRayPolyIntersection, 0x005B3FB0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CheckRayPolyIntersection2Sided, 0x005B4340);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::GetBBox3D, 0x005B46B0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::GetCenter, 0x005B4780);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPolygon, &zCPolygon::SetMapping, void(zCPolygon::*)(zVEC2 const&, zVEC2 const&, zVEC2 const&), 0x005B4800);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPolygon, &zCPolygon::SetMapping, void(zCPolygon::*)(int, zVEC2 const&), 0x005B4850);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::Flip, 0x005B4870);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::VertPartOfPoly, 0x005B48B0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::EdgePartOfPoly, 0x005B48E0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::EdgePositionsPartOfPoly, 0x005B4930);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TexTranslate, 0x005B4980);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TexSetTranslation, 0x005B49C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPolygon, &zCPolygon::TexScale, void(zCPolygon::*)(float, float), 0x005B4A00);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPolygon, &zCPolygon::TexScale, void(zCPolygon::*)(zVEC2&, float, float), 0x005B4A40);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TexRotate, 0x005B4B00);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TexMirrorU, 0x005B4CD0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TexMirrorV, 0x005B4D00);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TexShearU, 0x005B4D30);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TexShearV, 0x005B4DF0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPolygon, &zCPolygon::TexApplyPlanarMapping, void(zCPolygon::*)(zVEC3 const&, zVEC3 const&, zVEC3 const&, int), 0x005B4EB0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPolygon, &zCPolygon::TexApplyPlanarMapping, void(zCPolygon::*)(float, float, int), 0x005B5060);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TexCorrectUV, 0x005B5650);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::AllocVerts, 0x005B57A0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::AddVertex, 0x005B5910);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::AddVertexAndFeature, 0x005B5930);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPolygon, &zCPolygon::SetVertices, void(zCPolygon::*)(zCVertex*, zCVertex*, zCVertex*), 0x005B5970);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPolygon, &zCPolygon::SetVertices, void(zCPolygon::*)(zCVertex*, zCVertex*, zCVertex*, zCVertex*, int), 0x005B59D0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::SetVertex, 0x005B5A40);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::SetFeature, 0x005B5A80);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CopyValuesInto, 0x005B5AC0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CopyPolyInto, 0x005B5B70);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::RemoveVerticesAndFeatures, 0x005B5BD0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::GetArea, 0x005B5C60);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::GetLongestEdgeLen, 0x005B5D00);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::ResetStaticLight, 0x005B5D70);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::SetStaticLight, 0x005B5DB0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::SetLightDyn, 0x005B5DE0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::SetLightStatAlpha, 0x005B5E10);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::ResetLightDynToLightStat, 0x005B5E40);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::AddToLightDyn, 0x005B5E70);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CheckBBoxPolyIntersection, 0x005B5F00);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CheckBSpherePolyIntersection, 0x005B6380);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::SplitPoly, 0x005B64F0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::IsIntersectingProjection, 0x005B6A40);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::IsIntersecting, 0x005B71B0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::IsNeighbourOf, 0x005B7280);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::GetStaticLODPossible, 0x005B7350);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::LightStatic, 0x00621720);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::SmoothSectorBorder, 0x00622080);

	ZENGIN_REGISTER_CLASS(zCPortal);
	ZENGIN_REGISTER_METHOD(zCPortal, &zCPortal::zCPortal_OnInit, 0x005265C0);
	ZENGIN_REGISTER_METHOD(zCPortal, &zCPortal::RemoveFromBsp, 0x005265A0);
	ZENGIN_REGISTER_METHOD(zCPortal, &zCPortal::Init, 0x00539C50);

} // namespace Gothic_II_Classic
