namespace Gothic_II_Classic {

	ZENGIN_REGISTER_CLASS(zCArchiverGeneric);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::zCArchiverGeneric_OnInit, 0x0051F060);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::DebugMessage, 0x0051F520);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::CheckObjectListSize, 0x00522C80);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::_GetClassDef, 0x0051F180);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteInt, 0x00520060);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteByte, 0x00520200);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteWord, 0x005203A0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteFloat, 0x00520540);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteBool, 0x00520700);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteString, 0x005208A0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteVec3, 0x00520900);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteColor, 0x00520C40);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteRaw, 0x00520FB0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteRawFloat, 0x00521180);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteEnum, 0x00521450);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::WriteObject, void(__fastcall zCArchiverGeneric::*)(zCObject*), 0x005220F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::WriteObject, void(__fastcall zCArchiverGeneric::*)(char const*, zCObject*), 0x00522050);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::WriteObject, void(__fastcall zCArchiverGeneric::*)(char const*, zCObject&), 0x00521E40);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::WriteChunkStart, void(__fastcall zCArchiverGeneric::*)(char const*, unsigned short), 0x00521B80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::WriteChunkStart, void(__fastcall zCArchiverGeneric::*)(char const*, char const*, unsigned short, unsigned long), 0x005216C0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteChunkEnd, 0x00521BA0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteGroupBegin, 0x00522100);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteGroupEnd, 0x005221E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadInt, void(__fastcall zCArchiverGeneric::*)(char const*, int&), 0x00524DB0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadInt, int(__fastcall zCArchiverGeneric::*)(char const*), 0x005246F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadByte, void(__fastcall zCArchiverGeneric::*)(char const*, unsigned char&), 0x00524E00);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadByte, unsigned char(__fastcall zCArchiverGeneric::*)(char const*), 0x00524710);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadWord, void(__fastcall zCArchiverGeneric::*)(char const*, unsigned short&), 0x00524E50);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadWord, unsigned short(__fastcall zCArchiverGeneric::*)(char const*), 0x00524730);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadFloat, void(__fastcall zCArchiverGeneric::*)(char const*, float&), 0x00524D00);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadFloat, float(__fastcall zCArchiverGeneric::*)(char const*), 0x00524690);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadBool, void(__fastcall zCArchiverGeneric::*)(char const*, int&), 0x00524EA0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadBool, int(__fastcall zCArchiverGeneric::*)(char const*), 0x00524750);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadString, void(__fastcall zCArchiverGeneric::*)(char const*, zSTRING&), 0x00524F00);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadString, zSTRING(__fastcall zCArchiverGeneric::*)(char const*), 0x00524770);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadVec3, void(__fastcall zCArchiverGeneric::*)(char const*, zVEC3&), 0x00524D50);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadVec3, zVEC3(__fastcall zCArchiverGeneric::*)(char const*), 0x005246B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadColor, void(__fastcall zCArchiverGeneric::*)(char const*, zCOLOR&), 0x00524F30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadColor, zCOLOR(__fastcall zCArchiverGeneric::*)(char const*), 0x00524830);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadEnum, void(__fastcall zCArchiverGeneric::*)(char const*, int&), 0x00524FC0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadEnum, int(__fastcall zCArchiverGeneric::*)(char const*), 0x00524850);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::ReadRaw, 0x00524870);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::ReadRawFloat, 0x00524B00);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadObject, zCObject*(__fastcall zCArchiverGeneric::*)(zCObject*), 0x00524020);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadObject, zCObject*(__fastcall zCArchiverGeneric::*)(char const*, zCObject*), 0x00523790);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadChunkStart, int(__fastcall zCArchiverGeneric::*)(zSTRING&, unsigned short&), 0x00523610);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadChunkStart, int(__fastcall zCArchiverGeneric::*)(char const*), 0x005231E0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::ReadChunkStartNamed, 0x00523730);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::SkipOpenChunk, 0x0051F190);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::GetCurrentChunkVersion, 0x00523760);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::GetFile, 0x0051F1A0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::GetBufferString, 0x0051F910);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::GetBuffer, 0x0051FA80);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::EndOfArchive, 0x0051F880);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::Close, 0x0051F6A0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::SetStringEOL, 0x0051F1B0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::GetStringEOL, 0x0051F330);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::IsStringValid, 0x0051FE30);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::GetChecksumEnabled, 0x0051F370);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::SetChecksumEnabled, 0x0051F380);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::SetNoReadSearchCycles, 0x0051F390);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::InProperties, 0x0051F3A0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::InSaveGame, 0x0051F3B0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::InBinaryMode, 0x0051F3C0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::GetParentObject, 0x00525A30);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::OpenWriteBuffer, 0x0051FA90);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::OpenWriteFile, 0x0051FC60);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteHeader, 0x0051FDC0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteHeaderNumObj, 0x0051F540);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteASCIILine, 0x0051FE70);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::StoreBuffer, 0x0051FCD0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::StoreString, 0x0051FD00);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::StoreStringEOL, 0x0051FD90);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::StoreGetPos, 0x0051FD40);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::StoreSeek, 0x0051FD60);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::OpenReadBuffer, 0x005222C0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::OpenReadFile, 0x00522490);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::GetClassDefByString, 0x00522DF0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::CreateObject, 0x00522D20);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::SkipChunk, 0x00524030);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::ReadChunkStartASCII, 0x00522F90);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::ReadChunkEnd, 0x00523780);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::ReadEntryASCII, 0x00524230);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::ReadHeader, 0x00522980);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::RestoreBuffer, 0x00522500);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::RestoreStringEOL, 0x00522530);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::RestoreString0, 0x00522910);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::RestoreGetPos, 0x00522920);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::RestoreSeek, 0x00522940);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::DeleteBuffer, 0x0051F8F0);

} // namespace Gothic_II_Classic
