namespace Gothic_II_Classic {

	ZENGIN_REGISTER_CLASS(zCArchiverBinSafe);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::zCArchiverBinSafe_OnInit, 0x00519100);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::RestoreString, 0x00518570);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteType, 0x00518580);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ReadType, 0x005185F0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ClearChunkList, 0x00518E20);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::InsertChunkInList, 0x00518FA0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ResolveAndPosEntry, 0x00519030);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::DebugMessage, 0x005195F0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::CheckObjectListSize, 0x0051C0F0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::_GetClassDef, 0x00519270);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteInt, 0x0051A250);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteByte, 0x0051A330);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteWord, 0x0051A410);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteFloat, 0x0051A4F0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteBool, 0x0051A5D0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteString, 0x0051A6B0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteVec3, 0x0051A7E0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteColor, 0x0051AB10);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteRaw, 0x0051ABF0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteRawFloat, 0x0051ACD0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteEnum, 0x0051AEF0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::WriteObject, void(__fastcall zCArchiverBinSafe::*)(zCObject*), 0x0051BA60);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::WriteObject, void(__fastcall zCArchiverBinSafe::*)(char const*, zCObject*), 0x0051B9D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::WriteObject, void(__fastcall zCArchiverBinSafe::*)(char const*, zCObject&), 0x0051B790);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::WriteChunkStart, void(__fastcall zCArchiverBinSafe::*)(char const*, unsigned short), 0x0051B530);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::WriteChunkStart, void(__fastcall zCArchiverBinSafe::*)(char const*, char const*, unsigned short, unsigned long), 0x0051B110);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteChunkEnd, 0x0051B550);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteGroupBegin, 0x0051B0F0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteGroupEnd, 0x0051B100);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadInt, void(__fastcall zCArchiverBinSafe::*)(char const*, int&), 0x0051DEC0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadInt, int(__fastcall zCArchiverBinSafe::*)(char const*), 0x0051DC80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadByte, void(__fastcall zCArchiverBinSafe::*)(char const*, unsigned char&), 0x0051DEF0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadByte, unsigned char(__fastcall zCArchiverBinSafe::*)(char const*), 0x0051DCA0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadWord, void(__fastcall zCArchiverBinSafe::*)(char const*, unsigned short&), 0x0051DF20);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadWord, unsigned short(__fastcall zCArchiverBinSafe::*)(char const*), 0x0051DCC0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadFloat, void(__fastcall zCArchiverBinSafe::*)(char const*, float&), 0x0051DE60);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadFloat, float(__fastcall zCArchiverBinSafe::*)(char const*), 0x0051DC20);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadBool, void(__fastcall zCArchiverBinSafe::*)(char const*, int&), 0x0051DF50);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadBool, int(__fastcall zCArchiverBinSafe::*)(char const*), 0x0051DCE0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadString, void(__fastcall zCArchiverBinSafe::*)(char const*, zSTRING&), 0x0051DF80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadString, zSTRING(__fastcall zCArchiverBinSafe::*)(char const*), 0x0051DD00);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadVec3, void(__fastcall zCArchiverBinSafe::*)(char const*, zVEC3&), 0x0051DE90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadVec3, zVEC3(__fastcall zCArchiverBinSafe::*)(char const*), 0x0051DC40);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadColor, void(__fastcall zCArchiverBinSafe::*)(char const*, zCOLOR&), 0x0051DFB0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadColor, zCOLOR(__fastcall zCArchiverBinSafe::*)(char const*), 0x0051DDC0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadEnum, void(__fastcall zCArchiverBinSafe::*)(char const*, int&), 0x0051DFE0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadEnum, int(__fastcall zCArchiverBinSafe::*)(char const*), 0x0051DDE0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ReadRaw, 0x0051DE00);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ReadRawFloat, 0x0051DE30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadObject, zCObject*(__fastcall zCArchiverBinSafe::*)(zCObject*), 0x0051D400);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadObject, zCObject*(__fastcall zCArchiverBinSafe::*)(char const*, zCObject*), 0x0051CD80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadChunkStart, int(__fastcall zCArchiverBinSafe::*)(zSTRING&, unsigned short&), 0x0051CC00);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadChunkStart, int(__fastcall zCArchiverBinSafe::*)(char const*), 0x0051C660);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ReadChunkStartNamed, 0x0051CD20);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::SkipOpenChunk, 0x00519280);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::GetCurrentChunkVersion, 0x0051CD50);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::GetFile, 0x00519290);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::GetBufferString, 0x00519B50);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::GetBuffer, 0x00519CC0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::EndOfArchive, 0x00519AC0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::Close, 0x00519670);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::SetStringEOL, 0x005192A0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::GetStringEOL, 0x00519420);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::IsStringValid, 0x0051A030);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::GetChecksumEnabled, 0x00519460);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::SetChecksumEnabled, 0x00519470);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::SetNoReadSearchCycles, 0x00519480);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::InProperties, 0x00519490);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::InSaveGame, 0x005194A0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::InBinaryMode, 0x005194B0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::GetParentObject, 0x0051E010);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::OpenWriteBuffer, 0x00519CD0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::OpenWriteFile, 0x00519E90);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteHeader, 0x00519FB0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteHeaderNumObj, 0x00519610);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteASCIILine, 0x0051A070);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::StoreBuffer, 0x00519EF0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::StoreString, 0x00519F20);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::StoreStringEOL, 0x00519FA0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::StoreGetPos, 0x00519F50);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::StoreSeek, 0x00519F70);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::OpenReadBuffer, 0x0051BA70);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::OpenReadFile, 0x0051BC40);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::GetClassDefByString, 0x0051C260);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::CreateObject, 0x0051C190);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::SkipChunk, 0x0051D410);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ReadChunkStartASCII, 0x0051C400);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ReadChunkEnd, 0x0051CD70);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ReadEntryASCII, 0x0051D5E0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ReadHeader, 0x0051BD50);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::RestoreBuffer, 0x0051BCA0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::RestoreStringEOL, 0x0051BCD0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::RestoreString0, 0x0051BCE0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::RestoreGetPos, 0x0051BCF0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::RestoreSeek, 0x0051BD10);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::DeleteBuffer, 0x00519B30);

} // namespace Gothic_II_Classic
