namespace Gothic_II_Classic {

	ZENGIN_REGISTER_CLASS(zCBspBase);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::DescribeTree, 0x00526C20);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CountNodes, 0x00529C70);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::AddVobsToRenderListSubtree, 0x0052BAF0);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::GetScreenBBox2D, 0x0052BBC0);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CollectNodeLights, 0x0052BE30);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::RenderTrivInIndoor, 0x0052C150);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::RenderIndoor, 0x0052C190);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::RenderNodeOutdoor, 0x0052C230);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::AddVobToLeafs, 0x0052DBA0);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::AddVobLightToLeafs, 0x0052DCE0);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::RemoveVobFromLeafs, 0x0052DFF0);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CollectVobsSubtree, 0x0052E190);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CollectVobsInBBox3D, 0x0052E1A0);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CollectVobsSubtree_I, 0x0052E1B0);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CollectLightVobsSubtree, 0x0052E390);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CollectLightVobsSubtree_I, 0x0052E3A0);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CollectVobsInBBox3D_I, 0x0052E580);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::FindLeaf, 0x0052E9C0);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CheckRayAgainstPolys, 0x0052EB30);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CheckRayAgainstPolysNearestHit, 0x0052EC60);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CheckRayAgainstPolysCache, 0x0052EE10);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::RayIntersection, 0x0052EFC0);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CollectPolysInBBox3DRec, 0x0052F920);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CollectPolysInBBox3D, 0x0052FB50);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::SortNodePolys, 0x00531160);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::SaveBINRec, 0x00534A40);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::LoadBINRec, 0x00534B30);

	ZENGIN_REGISTER_CLASS(zCBspNode);
	ZENGIN_REGISTER_METHOD(zCBspNode, &zCBspNode::zCBspNode_OnInit, 0x00529750);
	ZENGIN_REGISTER_METHOD(zCBspNode, &zCBspNode::CalcPlaneSignbits, 0x0052DB60);

	ZENGIN_REGISTER_CLASS(zCBspLeaf);
	ZENGIN_REGISTER_METHOD(zCBspLeaf, &zCBspLeaf::zCBspLeaf_OnInit, 0x00528DE0);
	ZENGIN_REGISTER_METHOD(zCBspLeaf, &zCBspLeaf::PolyPlueckerAddRef, 0x0052B060);
	ZENGIN_REGISTER_METHOD(zCBspLeaf, &zCBspLeaf::PolyPlueckerRelease, 0x0052B350);
	ZENGIN_REGISTER_METHOD(zCBspLeaf, &zCBspLeaf::AddVobsToRenderList, 0x0052B380);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCBspLeaf, &zCBspLeaf::AddVobsToRenderListOutdoor, void(zCBspLeaf::*)(), 0x0052B580);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCBspLeaf, &zCBspLeaf::AddVobsToRenderListOutdoor, void(__fastcall zCBspLeaf::*)(zCBspSector*, zTBBox2D const&), 0x0052B8F0);
	ZENGIN_REGISTER_METHOD(zCBspLeaf, &zCBspLeaf::RenderLeafIndoor, 0x0052C0A0);
	ZENGIN_REGISTER_METHOD(zCBspLeaf, &zCBspLeaf::TraceRayCollectVobs, 0x0052E7B0);

	ZENGIN_REGISTER_CLASS(zCBspTree);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::zCBspTree_OnInit, 0x00528B80);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::InitTree, 0x00528D10);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::DisposeTree, 0x00528E60);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::BuildRecursive, 0x00529060);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::Build, 0x00529340);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::OptimizeLight, 0x00529770);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::UpdateVertexDependencies, 0x00529CB0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::CollectPolysInBBox3DAngle, 0x00529EC0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::RenderLightList, 0x0052A030);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::RenderVobList, 0x0052A150);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::Render, 0x0052D130);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::RemoveVob, 0x0052E0C0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::AddVob, 0x0052E0D0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::AdjustVob, 0x0052E130);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::CalcLeafRealBBox3D, 0x0052EA20);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::TraceRay, 0x0052F230);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::FindLeaks, 0x0052FD80);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::MarkOccluderPolys, 0x005300D0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::GetOccluderAreaRec, 0x00530EB0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::GetSectorNameVobIsIn, 0x00531E20);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::GetBspSectorByName, 0x00534600);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::CreateBspSectors2, 0x005346B0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::SaveBIN, 0x00534CB0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::ConnectMaterialsToSectors, 0x00535740);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::LoadBIN, 0x00535AB0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::CalcStaticLeafLightData, 0x005369C0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::PreprocessIndoorPortals, 0x0053CCE0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::GetPolyNeighbours, 0x0053D090);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::PostprocessIndoorPortals, 0x0053D140);

	ZENGIN_REGISTER_CLASS(zCCBspNode);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::zCCBspNode_OnInit, 0x0053BD50);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CheckRayAgainstPolysNearestHit, 0x0052F480);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::RayIntersectionOctree, 0x0052F5A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCBspNode, &zCCBspNode::TraceRay, int(zCCBspNode::*)(zVEC3 const&, zVEC3 const&, zCPolygon*&, zVEC3&), 0x0052F8B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCBspNode, &zCCBspNode::TraceRay, int(zCCBspNode::*)(zVEC3 const&, zVEC3 const&, zCPolygon*&), 0x0052F8E0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CollectPolysInBBox3DRec, 0x0052FBA0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CollectPolysInBBox3D, 0x0052FD30);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::RemovePoly, 0x00538E40);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::DoesNodeContainPoly, 0x00538F20);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CheckPortalConsistency, 0x00538FF0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::SplitPortals, 0x00539760);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::SplitPortalByAllPortals, 0x00539C70);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::EnumeratePortals, 0x00539F00);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::ClassifyPortals, 0x0053A030);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::Portalize, 0x0053A0C0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::SelectPlane, 0x0053A4B0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::SelectPlaneOctree, 0x0053A700);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::ClassifyRayToNode, 0x0053A920);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::ClassifyPolyToNode2, 0x0053ABE0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::OutdoorKillRedundantLeafs, 0x0053AE50);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::AddPoly, 0x0053B0A0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::BuildTree, 0x0053B0E0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::PushPolyFront, 0x0053BD70);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CalcBBox3D, 0x0053BE00);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CalcSubtreeBBox3D, 0x0053BF00);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CalcSubtreeBBox3DCell, 0x0053C0F0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CountNodes, 0x0053C1E0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CountLeafs, 0x0053C210);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CountPolys, 0x0053C250);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CountDepthRec, 0x0053C280);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CountDepth, 0x0053C2F0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::DescribeTree, 0x0053C3A0);

	ZENGIN_REGISTER_CLASS(zCCBspTree);
	ZENGIN_REGISTER_METHOD(zCCBspTree, &zCCBspTree::zCCBspTree_OnInit, 0x00537DE0);
	ZENGIN_REGISTER_METHOD(zCCBspTree, &zCCBspTree::GetBspSectorByName, 0x00531D70);
	ZENGIN_REGISTER_METHOD(zCCBspTree, &zCCBspTree::GetPolyNeighbours, 0x00531E40);
	ZENGIN_REGISTER_METHOD(zCCBspTree, &zCCBspTree::MarkGhostOccluder, 0x00531F20);
	ZENGIN_REGISTER_METHOD(zCCBspTree, &zCCBspTree::CreateBspSectors, 0x00532150);
	ZENGIN_REGISTER_METHOD(zCCBspTree, &zCCBspTree::SetBspTreeMode, 0x00537F00);
	ZENGIN_REGISTER_METHOD(zCCBspTree, &zCCBspTree::DeleteTree, 0x00538060);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCBspTree, &zCCBspTree::AddMesh, void(zCCBspTree::*)(zCMesh*), 0x005381B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCBspTree, &zCCBspTree::AddMesh, void(zCCBspTree::*)(zCMesh*, zMAT4 const&), 0x005381E0);
	ZENGIN_REGISTER_METHOD(zCCBspTree, &zCCBspTree::BuildTree, 0x005384E0);

	ZENGIN_REGISTER_CLASS(zCBspSector);
	ZENGIN_REGISTER_METHOD(zCBspSector, &zCBspSector::CalcCenterByPortals, 0x005264C0);
	ZENGIN_REGISTER_METHOD(zCBspSector, &zCBspSector::HasManyBigPortals, 0x00526560);
	ZENGIN_REGISTER_METHOD(zCBspSector, &zCBspSector::RenderSector, 0x005311B0);
	ZENGIN_REGISTER_METHOD(zCBspSector, &zCBspSector::ActivateSectorRec, 0x00531280);
	ZENGIN_REGISTER_METHOD(zCBspSector, &zCBspSector::ActivateSectorRecIndoor, 0x00531810);

	ZENGIN_REGISTER_CLASS(zCBuildPortal);
	ZENGIN_REGISTER_METHOD(zCBuildPortal, &zCBuildPortal::zCBuildPortal_OnInit, 0x0053CBD0);

} // namespace Gothic_II_Classic
