namespace Gothic_II_Classic {

	ZENGIN_REGISTER_CLASS(zCEvMsgCutscene);
	ZENGIN_REGISTER_METHOD(zCEvMsgCutscene, &zCEvMsgCutscene::zCEvMsgCutscene_OnInit, 0x0040C4F0);
	ZENGIN_REGISTER_METHOD(zCEvMsgCutscene, &zCEvMsgCutscene::SetCutsceneName, 0x00413CC0);
	ZENGIN_REGISTER_METHOD(zCEvMsgCutscene, &zCEvMsgCutscene::GetCutsceneName, 0x006EDEA0);
	ZENGIN_REGISTER_METHOD(zCEvMsgCutscene, &zCEvMsgCutscene::_GetClassDef, 0x0040B870);
	ZENGIN_REGISTER_METHOD(zCEvMsgCutscene, &zCEvMsgCutscene::IsHighPriority, 0x0040B880);
	ZENGIN_REGISTER_METHOD(zCEvMsgCutscene, &zCEvMsgCutscene::Delete, 0x0040B890);
	ZENGIN_REGISTER_METHOD(zCEvMsgCutscene, &zCEvMsgCutscene::IsDeleted, 0x0040B8A0);
	ZENGIN_REGISTER_METHOD(zCEvMsgCutscene, &zCEvMsgCutscene::MD_GetNumOfSubTypes, 0x0040C6A0);
	ZENGIN_REGISTER_METHOD(zCEvMsgCutscene, &zCEvMsgCutscene::MD_GetSubTypeString, 0x0040C6B0);

	ZENGIN_REGISTER_CLASS(zCCSRole);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSRole, &zCCSRole::zCCSRole_OnInit, void(zCCSRole::*)(), 0x0040B940);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSRole, &zCCSRole::zCCSRole_OnInit, void(zCCSRole::*)(zSTRING&), 0x0040BA90);
	ZENGIN_REGISTER_METHOD(zCCSRole, &zCCSRole::SetRoleVob, 0x0040BE80);
	ZENGIN_REGISTER_METHOD(zCCSRole, &zCCSRole::GetRoleVob, 0x0040C330);
	ZENGIN_REGISTER_METHOD(zCCSRole, &zCCSRole::_GetClassDef, 0x0040B550);
	ZENGIN_REGISTER_METHOD(zCCSRole, &zCCSRole::Archive, 0x0040C340);
	ZENGIN_REGISTER_METHOD(zCCSRole, &zCCSRole::Unarchive, 0x0040C3A0);

	ZENGIN_REGISTER_CLASS(zCCSBlockBase);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::zCCSBlockBase_OnInit, 0x0040C860);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::_GetClassDef, 0x0040AF40);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::Archive, 0x00416C00);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::Unarchive, 0x00416C10);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::GetChild, 0x0040CA00);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::GetRoleName, 0x0040CA60);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::SetRoleName, 0x0040CAF0);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::GetCommand, 0x00404F70);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::NewBlock, 0x0040CA10);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::InsertBlock, 0x0040A950);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::DeleteChild, 0x0040CB00);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::GetNumOfChilds, 0x0040CA20);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::GetRoleNumOfChild, 0x0040CA30);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::BlockCorrection, 0x0040CA40);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::BlockAsFocus, 0x0040CA50);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::GetChildPos, 0x0040CB10);

	ZENGIN_REGISTER_CLASS(zCCSAtomicBlock);
	ZENGIN_REGISTER_METHOD(zCCSAtomicBlock, &zCCSAtomicBlock::zCCSAtomicBlock_OnInit, 0x0040CB20);
	ZENGIN_REGISTER_METHOD(zCCSAtomicBlock, &zCCSAtomicBlock::_GetClassDef, 0x0040A980);
	ZENGIN_REGISTER_METHOD(zCCSAtomicBlock, &zCCSAtomicBlock::Archive, 0x00416C20);
	ZENGIN_REGISTER_METHOD(zCCSAtomicBlock, &zCCSAtomicBlock::Unarchive, 0x00416C40);
	ZENGIN_REGISTER_METHOD(zCCSAtomicBlock, &zCCSAtomicBlock::OrganizeRoles, 0x0040CD20);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSAtomicBlock, &zCCSAtomicBlock::Play, void(zCCSAtomicBlock::*)(zCArray<zCEventManager*> const&), 0x0040CF80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSAtomicBlock, &zCCSAtomicBlock::Play, void(zCCSAtomicBlock::*)(zCArray<zCEventManager*> const&, float, float), 0x0040CFA0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSAtomicBlock, &zCCSAtomicBlock::Play, void(zCCSAtomicBlock::*)(zCEventManager*), 0x0040CFC0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSAtomicBlock, &zCCSAtomicBlock::Play, void(zCCSAtomicBlock::*)(zCEventManager*, float, float), 0x0040D040);
	ZENGIN_REGISTER_METHOD(zCCSAtomicBlock, &zCCSAtomicBlock::GetMinTime, 0x0040D050);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSAtomicBlock, &zCCSAtomicBlock::IsFinished, int(zCCSAtomicBlock::*)(zCArray<zCEventManager*> const&), 0x0040A990);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSAtomicBlock, &zCCSAtomicBlock::IsFinished, int(zCCSAtomicBlock::*)(zCEventManager*), 0x0040D070);
	ZENGIN_REGISTER_METHOD(zCCSAtomicBlock, &zCCSAtomicBlock::GetCommand, 0x0040A9A0);

	ZENGIN_REGISTER_CLASS(zCCSBlockPosition);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSBlockPosition, &zCCSBlockPosition::zCCSBlockPosition_OnInit, void(zCCSBlockPosition::*)(), 0x00416B70);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSBlockPosition, &zCCSBlockPosition::zCCSBlockPosition_OnInit, void(zCCSBlockPosition::*)(zCCSBlockBase*), 0x00416B90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSBlockPosition, &zCCSBlockPosition::zCCSBlockPosition_OnInit, void(zCCSBlockPosition::*)(float, zCCSBlockBase*), 0x00416BB0);

	ZENGIN_REGISTER_CLASS(zCCSBlock);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::zCCSBlock_OnInit, 0x0040D260);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::_GetClassDef, 0x0040AC80);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::Archive, 0x00416C70);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::Unarchive, 0x00416E50);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::GetChild, 0x0040D410);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::OrganizeRoles, 0x0040D940);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::GetRoleName, 0x0040D990);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::SetRoleName, 0x0040D9E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSBlock, &zCCSBlock::Play, void(zCCSBlock::*)(zCArray<zCEventManager*> const&), 0x0040D600);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSBlock, &zCCSBlock::Play, void(zCCSBlock::*)(zCArray<zCEventManager*> const&, float, float), 0x0040D6D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSBlock, &zCCSBlock::Play, void(zCCSBlock::*)(zCEventManager*), 0x0040D4F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSBlock, &zCCSBlock::Play, void(zCCSBlock::*)(zCEventManager*, float, float), 0x0040D540);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::GetMinTime, 0x0040D7A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSBlock, &zCCSBlock::IsFinished, int(zCCSBlock::*)(zCArray<zCEventManager*> const&), 0x0040D880);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSBlock, &zCCSBlock::IsFinished, int(zCCSBlock::*)(zCEventManager*), 0x0040D830);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::NewBlock, 0x0040DBC0);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::InsertBlock, 0x0040DB20);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::DeleteChild, 0x0040D460);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::GetNumOfChilds, 0x0040D450);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::BlockCorrection, 0x0040DCA0);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::BlockAsFocus, 0x0040DC60);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::GetChildPos, 0x0040D430);

	ZENGIN_REGISTER_CLASS(zCCSSyncBlock);
	ZENGIN_REGISTER_METHOD(zCCSSyncBlock, &zCCSSyncBlock::zCCSSyncBlock_OnInit, 0x0040DDA0);
	ZENGIN_REGISTER_METHOD(zCCSSyncBlock, &zCCSSyncBlock::AssignerCorrection, 0x0040E3B0);
	ZENGIN_REGISTER_METHOD(zCCSSyncBlock, &zCCSSyncBlock::_GetClassDef, 0x0040AF70);
	ZENGIN_REGISTER_METHOD(zCCSSyncBlock, &zCCSSyncBlock::Archive, 0x00417090);
	ZENGIN_REGISTER_METHOD(zCCSSyncBlock, &zCCSSyncBlock::Unarchive, 0x004172C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSSyncBlock, &zCCSSyncBlock::Play, void(zCCSSyncBlock::*)(zCArray<zCEventManager*> const&), 0x0040DF80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSSyncBlock, &zCCSSyncBlock::Play, void(zCCSSyncBlock::*)(zCArray<zCEventManager*> const&, float, float), 0x0040E030);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSSyncBlock, &zCCSSyncBlock::Play, void(zCCSSyncBlock::*)(zCEventManager*), 0x0040DF30);
	ZENGIN_REGISTER_METHOD(zCCSSyncBlock, &zCCSSyncBlock::IsFinished, 0x0040DEE0);
	ZENGIN_REGISTER_METHOD(zCCSSyncBlock, &zCCSSyncBlock::NewBlock, 0x0040E1D0);
	ZENGIN_REGISTER_METHOD(zCCSSyncBlock, &zCCSSyncBlock::InsertBlock, 0x0040E100);
	ZENGIN_REGISTER_METHOD(zCCSSyncBlock, &zCCSSyncBlock::DeleteChild, 0x0040E2F0);
	ZENGIN_REGISTER_METHOD(zCCSSyncBlock, &zCCSSyncBlock::GetRoleNumOfChild, 0x0040E0E0);
	ZENGIN_REGISTER_METHOD(zCCSSyncBlock, &zCCSSyncBlock::BlockAsFocus, 0x0040E2A0);

	ZENGIN_REGISTER_CLASS(zCCutscene);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::zCCutscene_OnInit, 0x0040E3E0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::IsMember, 0x0040E7C0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::SetRoleListForDebugging, 0x0040E7F0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::SaveRolesVobs, 0x0040E9B0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::RestoreRoleVobs, 0x0040EC40);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::CheckMainRole, 0x0040EEB0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::CheckPlayState, 0x0040FD00);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::SolveEventManager, 0x00414280);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::GetActualBlockNum, 0x00415D30);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::ResumeAtBlock, 0x004160F0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::NewRole, 0x00416600);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::DeleteRole, 0x004167B0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::RegisterAdditionalVob, 0x004168A0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::FirstRoleUsed, 0x00417840);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::GetLastCheckResult, 0x00417910);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::TryToCancel, 0x00417C10);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::GetFirstBlockPosition, 0x00417C40);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::GetNextMessage, 0x00417DD0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::GetNextBlock, 0x00417E20);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::SerializeCutscene, 0x00417E50);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::SerializeBlock, 0x00417FC0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::GetProperties, 0x0041CF00);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::_GetClassDef, 0x0040E5C0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::Archive, 0x00417500);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::Unarchive, 0x00417590);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::NewBlock, 0x00416170);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::AddMainRole, 0x00410670);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::AddRoleOU, 0x0040FE40);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::RemoveRole, 0x00410EC0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::SetOwnerPlayer, 0x0040E780);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::Reset, 0x00413E30);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::ClearCutscene, 0x00413F30);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::StartPlaying, 0x004130C0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::Stop, 0x004142C0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::StopRole, 0x00414120);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::Interrupt, 0x00415390);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::ResumeActBlock, 0x00415D40);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::PlaySub, 0x00416100);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::NewCS, 0x00416350);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::IsCutscene, 0x0040E5D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCutscene, &zCCutscene::IsFinished, int(zCCutscene::*)(zCArray<zCEventManager*> const&), 0x0040D880);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCutscene, &zCCutscene::IsFinished, int(zCCutscene::*)(zCEventManager*), 0x0040D830);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCutscene, &zCCutscene::IsFinished, int(zCCutscene::*)(), 0x00416160);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::PrintDebugInfo, 0x00417900);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::CheckRoles, 0x00417870);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::CSCheck, 0x00410F40);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::GetStage, 0x0040FCF0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::LoadStage, 0x00416910);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::CatchPlayer, 0x00416B30);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::PrepareBlock, 0x0040FDC0);

} // namespace Gothic_II_Classic
