namespace Gothic_II_Classic {

	ZENGIN_REGISTER_CLASS(zFILE_VDFS);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::zFILE_VDFS_OnInit, void(zFILE_VDFS::*)(), 0x004485B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::zFILE_VDFS_OnInit, void(zFILE_VDFS::*)(zSTRING const&), 0x004487D0);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::Init, 0x00448580);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::HandleError, 0x00448AB0);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::GetFullPath, 0x004496C0);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::SetCurrentDir, 0x00449470);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::ChangeDir, 0x00449810);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::SearchFile, 0x00449820);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::FindFirst, 0x00449CA0);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::FindNext, 0x00449F50);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::IsOpened, 0x00448990);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::Open, int(zFILE_VDFS::*)(bool), 0x00448AC0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::Open, int(zFILE_VDFS::*)(zSTRING const&, bool), 0x004486E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::Exists, bool(zFILE_VDFS::*)(), 0x004489C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::Exists, bool(zFILE_VDFS::*)(zSTRING const&), 0x00448750);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::Close, 0x00448D40);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::Reset, 0x00448DA0);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::Append, 0x00449450);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::Size, 0x00448DB0);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::Pos, 0x004493F0);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::Seek, 0x00448E30);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::Eof, 0x00448E10);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::GetStats, 0x00449C90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::Read, long(zFILE_VDFS::*)(void*, long), 0x0044A590);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::Read, int(zFILE_VDFS::*)(char*), 0x0044A270);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::Read, int(zFILE_VDFS::*)(zSTRING&), 0x0044A420);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::SeekText, 0x00449210);

} // namespace Gothic_II_Classic
