namespace Gothic_II_Classic {

	ZENGIN_REGISTER_CLASS(zERROR);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::zERROR_OnInit, 0x0044B5F0);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::Init, 0x0044B850);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::SendToSpy, 0x0044C100);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zERROR, &zERROR::Report, int(zERROR::*)(zERROR_LEVEL, int, zSTRING const&, signed char, unsigned int, int, char*, char*), 0x0044C170);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zERROR, &zERROR::Report, int(zERROR::*)(zERROR_TYPE, int, zSTRING const&, signed char, unsigned int, int, char*, char*), 0x0044C180);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::BlockBegin, 0x0044C910);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::BlockEnd, 0x0044CB40);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::Separator, 0x0044CF60);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::ShowSpy, 0x0044D170);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::Message, 0x0044D2C0);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::Warning, 0x0044D300);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::Fatal, 0x0044D330);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::Fault, 0x0044D360);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::SetFilterFlags, 0x0044D390);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::SetFilterAuthors, 0x0044D4B0);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::SetFilterLevel, 0x0044D650);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::SetTarget, 0x0044D800);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::GetTargetDescription, 0x0044DA80);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::GetFilterFlagDescription, 0x0044DCA0);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::GetFilterAuthors, 0x0044DEA0);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::SearchForSpy, 0x0044DEF0);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::GetFilterLevel, 0x00597BD0);

} // namespace Gothic_II_Classic
