namespace Gothic_II_Classic {

	ZENGIN_REGISTER_CLASS(zCFile3DS);
	ZENGIN_REGISTER_METHOD(zCFile3DS, &zCFile3DS::Load3DS, 0x00558440);
	ZENGIN_REGISTER_METHOD(zCFile3DS, &zCFile3DS::Save3DS, 0x00559DF0);

	ZENGIN_REGISTER_CLASS(zCFileQuakeBSP);
	ZENGIN_REGISTER_METHOD(zCFileQuakeBSP, &zCFileQuakeBSP::zCFileQuakeBSP_OnInit, 0x0055B9C0);
	ZENGIN_REGISTER_METHOD(zCFileQuakeBSP, &zCFileQuakeBSP::LoadQuakeBSP, 0x0055B9F0);

	ZENGIN_REGISTER_CLASS(zCFileBIN);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::zCFileBIN_OnInit, 0x00562D00);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinCreate, 0x00562DA0);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinClose, 0x00562DD0);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinStartChunk, 0x0056AD50);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinEndChunk, 0x0056ADF0);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinWriteSrcFileStats, 0x00582040);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinWriteString, 0x00582F60);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinReadCompareSrcFileStats, 0x00585410);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinWriteFloat, 0x00597C20);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinWriteInt, 0x00597C40);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinSkipChunk, 0x00598840);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinSetFile, 0x0061F920);

} // namespace Gothic_II_Classic
