namespace Gothic_II_Classic {

	ZENGIN_REGISTER_CLASS(zCFileCSV);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCFileCSV, &zCFileCSV::zCFileCSV_OnInit, void(zCFileCSV::*)(zSTRING const&), 0x0044E1E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCFileCSV, &zCFileCSV::zCFileCSV_OnInit, void(zCFileCSV::*)(), 0x0044E3A0);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::InitCSV, 0x0044E6A0);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::SetFormat, 0x0044E7C0);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::AddNextField, 0x0044E900);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::AddNextHeader, 0x0044EA90);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::WriteSet, 0x0044EC40);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::GetNextField, 0x0044EE00);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::ReadSet, 0x0044F230);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::ReadHeader, 0x0044F280);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::WriteHeader, 0x0044F460);

} // namespace Gothic_II_Classic
