namespace Gothic_II_Classic {

	ZENGIN_REGISTER_CLASS(zCGfx);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCGfx, &zCGfx::zCGfx_OnInit, void(zCGfx::*)(zSTRING const&), 0x0072AA70);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCGfx, &zCGfx::zCGfx_OnInit, void(zCGfx::*)(int, int), 0x0072AC30);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::LoadRaw, 0x0072B510);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::Readbyte, 0x0072B5B0);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::LoadPcx, 0x0072B620);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::LoadTga, 0x0072BAD0);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::SaveRaw, 0x0072CDB0);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::Save, 0x0072CE10);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::LoadGfx, 0x0072CFB0);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::GetSizex, 0x0072D330);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::GetSizey, 0x0072D340);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::GetDataPtr, 0x0072D350);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::GetPixel, 0x0072D360);

} // namespace Gothic_II_Classic
