namespace Gothic_II_Classic {

	ZENGIN_REGISTER_CLASS(zCMenuItem);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenuItem, &zCMenuItem::zCMenuItem_OnInit, void(zCMenuItem::*)(zSTRING const&), 0x004DC470);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenuItem, &zCMenuItem::zCMenuItem_OnInit, void(zCMenuItem::*)(), 0x004DC680);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Release, 0x0047C150);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetSelItem, 0x004DBDD0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Init, 0x004DCA60);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::SetByScript, 0x004DCDE0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetDimX, 0x004DD6E0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetDimY, 0x004DD7E0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::InitView, 0x004DD8D0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Close, 0x004DDA60);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetType, 0x004DDAB0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenuItem, &zCMenuItem::SetName, void(zCMenuItem::*)(zSTRING const&), 0x004DDB90);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetName, 0x004DDCD0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetCoords, 0x004DDCE0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetSelActionType, 0x004DDCF0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetSelActionString, 0x004DDD00);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenuItem, &zCMenuItem::SetName, void(zCMenuItem::*)(zSTRING&), 0x004DDD20);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Register, 0x004DDE80);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Unregister, 0x004DE030);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::IsRegistered, 0x004DE160);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::UpdateSize, 0x004DE850);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetEventFunc, 0x004DF240);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::SetIsActive, 0x004DF250);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::SetIsSelectable, 0x004DF360);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetIsSelectable, 0x004DF3B0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::SetIsDisabled, 0x004DF430);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetIsDisabled, 0x004DF440);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::SetIsVisible, 0x004DF480);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetIsVisible, 0x004DF490);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::DrawItems, 0x004DF070);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::InitMenuItem, 0x004DD840);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::ToggleValue, 0x004DDA80);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Run, 0x004DEB40);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetText, 0x004DDAC0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenuItem, &zCMenuItem::SetText, void(zCMenuItem::*)(zSTRING const&, int, int), 0x004DE200);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenuItem, &zCMenuItem::SetText, void(zCMenuItem::*)(zCArray<zSTRING>, int), 0x004DE920);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::SetMinValue, 0x004DC3D0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::SetMaxValue, 0x004DC3E0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Enter, 0x004DEAE0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Leave, 0x004DEAF0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Draw, 0x004DEF10);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::DrawFront, 0x004DEF30);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Show, 0x004DD9B0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Hide, 0x004DD9F0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::HasBeenCanceled, 0x004DC3F0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Open, 0x004DDA30);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Input, 0x004DEBA0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::InsertInWin, 0x004DD0E0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::RemoveFromWin, 0x004DD680);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::UpdateContent, 0x004DF0A0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::UpdateFX, 0x004DF0B0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::HandleEvent, 0x004DEB00);

	ZENGIN_REGISTER_CLASS(zCMenuItemInput);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::zCMenuItemInput_OnInit, 0x004DF4D0);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::SetValue, 0x004DF730);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::GetValue, 0x004DF7B0);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::InitMenuItem, 0x004DF7D0);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::Run, 0x004DF9B0);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::Enter, 0x004DC400);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::Leave, 0x004DC410);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::HasBeenCanceled, 0x004DC430);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::InsertInWin, 0x004DF980);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::HandleEvent, 0x004DC420);

	ZENGIN_REGISTER_CLASS(zCMenuItemText);
	ZENGIN_REGISTER_METHOD(zCMenuItemText, &zCMenuItemText::zCMenuItemText_OnInit, 0x004DFD20);
	ZENGIN_REGISTER_METHOD(zCMenuItemText, &zCMenuItemText::FormatMultiline, 0x004DFEB0);
	ZENGIN_REGISTER_METHOD(zCMenuItemText, &zCMenuItemText::DrawMultiline, 0x004E0230);
	ZENGIN_REGISTER_METHOD(zCMenuItemText, &zCMenuItemText::InitMenuItem, 0x004E0650);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenuItemText, &zCMenuItemText::SetText, void(zCMenuItemText::*)(zSTRING const&, int, int), 0x004E0B40);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenuItemText, &zCMenuItemText::SetText, void(zCMenuItemText::*)(zCArray<zSTRING>, int), 0x004E0E00);
	ZENGIN_REGISTER_METHOD(zCMenuItemText, &zCMenuItemText::DrawFront, 0x004DFE60);
	ZENGIN_REGISTER_METHOD(zCMenuItemText, &zCMenuItemText::SetEnum, 0x004E0810);
	ZENGIN_REGISTER_METHOD(zCMenuItemText, &zCMenuItemText::HandleEvent, 0x004E0990);

	ZENGIN_REGISTER_CLASS(zCMenuItemSlider);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::zCMenuItemSlider_OnInit, 0x004E0E60);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::SetValue, 0x004E15C0);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::GetValue, 0x004E1640);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::InitMenuItem, 0x004E12A0);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::ToggleValue, 0x004E0F20);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::InsertInWin, 0x004E1360);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::RemoveFromWin, 0x004E1530);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::SetIsActive, 0x004DC440);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::HandleEvent, 0x004DC460);

	ZENGIN_REGISTER_CLASS(zCMenuItemButton);
	ZENGIN_REGISTER_METHOD(zCMenuItemButton, &zCMenuItemButton::zCMenuItemButton_OnInit, 0x004E2920);
	ZENGIN_REGISTER_METHOD(zCMenuItemButton, &zCMenuItemButton::Toggle, 0x004E2D50);
	ZENGIN_REGISTER_METHOD(zCMenuItemButton, &zCMenuItemButton::InitMenuItem, 0x004E2B80);
	ZENGIN_REGISTER_METHOD(zCMenuItemButton, &zCMenuItemButton::Run, 0x004E2F50);
	ZENGIN_REGISTER_METHOD(zCMenuItemButton, &zCMenuItemButton::InsertInWin, 0x004E31C0);
	ZENGIN_REGISTER_METHOD(zCMenuItemButton, &zCMenuItemButton::RemoveFromWin, 0x004E3200);

	ZENGIN_REGISTER_CLASS(zCMenuItemChoice);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::zCMenuItemChoice_OnInit, 0x004E1650);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::SetOptionByString, 0x004E1960);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::GetStringByOption, 0x004E1DA0);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::Resize, 0x004E2180);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::GetNumOptions, 0x004E24A0);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::InitMenuItem, 0x004E2800);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::ToggleValue, 0x004E16D0);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::GetText, 0x004E2680);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::Draw, 0x004E2250);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::DrawFront, 0x004E2270);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::InsertInWin, 0x004E1F30);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::RemoveFromWin, 0x004E20F0);

	ZENGIN_REGISTER_CLASS(zTMenuItemListElement);
	ZENGIN_REGISTER_METHOD(zTMenuItemListElement, &zTMenuItemListElement::zTMenuItemListElement_OnInit, 0x004E4810);

	ZENGIN_REGISTER_CLASS(zCMenuItemList);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::zCMenuItemList_OnInit, 0x004E32C0);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::DeleteContent, 0x004E3510);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::InsertEnd, 0x004E3560);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::InsertFront, 0x004E3770);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::ShowContent, 0x004E4100);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::JumpToNextEntry, 0x004E42B0);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::JumpToPrevEntry, 0x004E42D0);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::JumpToTopEntry, 0x004E42F0);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::JumpToLastEntry, 0x004E4310);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::InitMenuItem, 0x004E3470);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::Run, 0x004E33E0);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::Enter, 0x004E3B70);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::Leave, 0x004E3B80);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::DrawFront, 0x004E3BA0);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::Show, 0x004E3480);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::Hide, 0x004E34D0);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::InsertInWin, 0x004E3960);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::RemoveFromWin, 0x004E3AC0);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::UpdateContent, 0x004E3B90);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::HandleEvent, 0x004E3EB0);

} // namespace Gothic_II_Classic
