namespace Gothic_II_Classic {

	ZENGIN_REGISTER_CLASS(zCMenu);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenu, &zCMenu::zCMenu_OnInit, void(zCMenu::*)(), 0x004D7DD0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenu, &zCMenu::zCMenu_OnInit, void(zCMenu::*)(zSTRING const&), 0x004D7F70);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::InitValues, 0x004D82B0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::Release, 0x004D84E0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::Register, 0x004D8760);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::Unregister, 0x004D8980);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::IsRegistered, 0x004D8A20);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::ClearAllEvents, 0x004D8F00);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::PreviousOption, 0x004D8F20);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::NextOption, 0x004D8FF0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::RestartMusicTheme, 0x004D90C0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::ForceSelAction, 0x004D9780);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::UpdateWindowGeometry, 0x004D99D0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::PrintInformation, 0x004DA660);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::GetBackWorld, 0x004DB360);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::GetBackDatFile, 0x004DB3A0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::GetActiveItem, 0x004DB3D0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::GetNumberOfActiveItem, 0x004DB3E0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::SetActiveItem, 0x004DB450);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::GetName, 0x004DB5B0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::SetName, 0x004DB5C0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::HandleEvent, 0x004D94D0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::HandleEnterItem, 0x004DB720);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::HandleLeaveItem, 0x004DB730);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::HandleActivateItem, 0x004DB740);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::Run, 0x004D9300);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::Enter, 0x004D90E0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::Leave, 0x004D9270);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::Render, 0x004DB270);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::RedrawItems, 0x004DA630);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::HandleFrame, 0x004D9B20);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::Activate, 0x004D9930);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::ScreenInit, 0x004DA740);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::ScreenDone, 0x004DB030);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::HandleAction, 0x004D9BB0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::HandleSelAction, 0x004D9D90);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::SetByScript, 0x004D8C80);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::ExecCommand, 0x004DA420);

} // namespace Gothic_II_Classic
