namespace Gothic_II_Classic {

	ZENGIN_REGISTER_CLASS(zCModelMeshLib);
	ZENGIN_REGISTER_METHOD(zCModelMeshLib, &zCModelMeshLib::zCModelMeshLib_OnInit, 0x0058E5D0);
	ZENGIN_REGISTER_METHOD(zCModelMeshLib, &zCModelMeshLib::ReleaseData, 0x00599B30);
	ZENGIN_REGISTER_METHOD(zCModelMeshLib, &zCModelMeshLib::AllocNumNodeVisuals, 0x00599BA0);
	ZENGIN_REGISTER_METHOD(zCModelMeshLib, &zCModelMeshLib::AddMeshSoftSkin, 0x00599C10);
	ZENGIN_REGISTER_METHOD(zCModelMeshLib, &zCModelMeshLib::AddNodeVisual, 0x00599CF0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelMeshLib, &zCModelMeshLib::ApplyToModel, void(zCModelMeshLib::*)(zCModel*), 0x00599DF0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelMeshLib, &zCModelMeshLib::ApplyToModel, void(zCModelMeshLib::*)(zCModelPrototype*), 0x00599F60);
	ZENGIN_REGISTER_METHOD(zCModelMeshLib, &zCModelMeshLib::RemoveFromModel, 0x0059A0C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelMeshLib, &zCModelMeshLib::BuildFromModel, void(zCModelMeshLib::*)(zCModelPrototype*), 0x0059A1B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelMeshLib, &zCModelMeshLib::BuildFromModel, void(zCModelMeshLib::*)(zCModel*), 0x0059A3A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelMeshLib, &zCModelMeshLib::SaveMDM, void(zCModelMeshLib::*)(zCModelPrototype*), 0x0059A5D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelMeshLib, &zCModelMeshLib::SaveMDM, void(zCModelMeshLib::*)(zCFileBIN&, zCModelPrototype*), 0x0059A7E0);
	ZENGIN_REGISTER_METHOD(zCModelMeshLib, &zCModelMeshLib::_GetClassDef, 0x00579510);

	ZENGIN_REGISTER_CLASS(zCModelAniEvent);
	ZENGIN_REGISTER_METHOD(zCModelAniEvent, &zCModelAniEvent::zCModelAniEvent_OnInit, 0x00582D20);
	ZENGIN_REGISTER_METHOD(zCModelAniEvent, &zCModelAniEvent::Save, 0x00582EA0);
	ZENGIN_REGISTER_METHOD(zCModelAniEvent, &zCModelAniEvent::Load, 0x00583000);

	ZENGIN_REGISTER_CLASS(zCModelNode);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelNode, &zCModelNode::zCModelNode_OnInit, void(zCModelNode::*)(), 0x0057F460);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelNode, &zCModelNode::zCModelNode_OnInit, void(zCModelNode::*)(zCModelNode const&), 0x0057F5A0);
	ZENGIN_REGISTER_METHOD(zCModelNode, &zCModelNode::SetNodeVisualS, 0x0057F7D0);

	ZENGIN_REGISTER_CLASS(zCModelAni);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::zCModelAni_OnInit, 0x0057FBC0);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::PrecacheAniEventData, 0x0057FFD0);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::GetAniVelocity, 0x005800A0);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::GetAniTranslation, 0x00580220);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::AddTrafoMatrix, 0x00580360);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::GetQuat, 0x00580800);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::GetTrans, 0x00580860);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::SetTrans, 0x00580900);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::SetQuat, 0x00580980);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::AddNodeList, 0x00580A20);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::SetFlags, 0x00580A90);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::SetBlendingSec, 0x00580B40);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::GetBlendingSec, 0x00580BA0);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::CorrectRootNodeIdleMovement, 0x00580C00);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::CalcInPlaceFlag, 0x00580D60);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::ResolveAlias, 0x00580F40);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::ResolveComb, 0x00581220);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::SaveMAN, 0x00581920);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::LoadMAN, 0x005821E0);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::GetAniName, 0x00597C00);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::GetAniType, 0x00597C10);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::GetAniID, 0x0064CF80);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::_GetClassDef, 0x0057FD60);

	ZENGIN_REGISTER_CLASS(zCModelPrototype);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::zCModelPrototype_OnInit, 0x005830B0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::Init, 0x005832F0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::Clear, 0x005836F0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReleaseMeshSoftSkinList, 0x00583890);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReleaseMeshes, 0x005838F0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::Release, 0x00583980);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::GetModelProtoFileName, 0x005839D0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::SetModelProtoName, 0x005839E0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::SetFileSourceType, 0x00583B70);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::PrepareAsModelProtoOverlay, 0x00583F40);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::CalcNodeListChecksum, 0x00584310);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::CollectNodeMeshes, 0x00584370);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::SearchNode, 0x00584590);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::FindMeshTreeNode, 0x00584640);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::FindMeshTreeNodeIndex, 0x005846F0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::FindNodeListIndex, 0x005847B0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::AddAni, 0x00584850);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::SearchAniIndex, 0x00584A60);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::SearchAni, 0x00584B30);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::DescribeTree, 0x00584B50);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelPrototype, &zCModelPrototype::LoadMDH, int(zCModelPrototype::*)(zSTRING const&), 0x00584DA0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelPrototype, &zCModelPrototype::LoadMDH, int(zCModelPrototype::*)(zCFileBIN&), 0x00585000);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelPrototype, &zCModelPrototype::SaveMDH, void(zCModelPrototype::*)(), 0x00585660);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelPrototype, &zCModelPrototype::SaveMDH, void(zCModelPrototype::*)(zCFileBIN&), 0x00585860);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ConvertVec3, 0x00585D80);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ConvertAngle, 0x00585DA0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::SkipBlock, 0x00585DB0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::SkipBlockCmt, 0x00585E30);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadComment, 0x00585F00);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadScene, 0x00585F10);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadTriple, 0x005862B0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadNodeTM, 0x005864A0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadVertexList, 0x00586940);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadFaceList, 0x00586B70);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadTVertexList, 0x00587070);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadTFaceList, 0x00587270);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadSoftSkinVertList, 0x005874E0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadMesh, 0x005886A0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadMeshAnimation, 0x00588A80);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadPosTrack, 0x00588C00);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadRotTrack, 0x00588DE0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadTMAnimation, 0x00589090);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::LocalizeTrafos, 0x005896D0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadMapDiffuse, 0x00589800);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadMaterial, 0x00589C70);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadWireframeColor, 0x0058A2E0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::AssignMeshNodeMaterials, 0x0058A580);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::TransformNodeVisual, 0x0058A670);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ProcessMeshNode, 0x0058A6D0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadGeomobject, 0x0058AAE0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadMaterialList, 0x0058C060);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::Load3DSMAXAsc, 0x0058C2F0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::CalcAniBBox, 0x0058D370);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ResolveReferences, 0x0058D8A0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::SkipBlockMDS, 0x0058DBA0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadMeshAndTreeMSB, 0x0058DC20);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadMeshAndTree, 0x0058E060);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::RegisterMesh, 0x0058E6E0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadAniEnumMSB, 0x0058E970);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadAniEnum, 0x005916A0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadModelMSB, 0x00597CF0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadModel, 0x00597F60);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::LoadModelScriptMSB, 0x00598250);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::LoadModelScript, 0x00598870);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::LoadModelASC, 0x00599200);

	ZENGIN_REGISTER_CLASS(zCModelAniActive);
	ZENGIN_REGISTER_METHOD(zCModelAniActive, &zCModelAniActive::zCModelAniActive_OnInit, 0x00571850);
	ZENGIN_REGISTER_METHOD(zCModelAniActive, &zCModelAniActive::SetDirection, 0x00571960);
	ZENGIN_REGISTER_METHOD(zCModelAniActive, &zCModelAniActive::GetProgressPercent, 0x005719B0);
	ZENGIN_REGISTER_METHOD(zCModelAniActive, &zCModelAniActive::SetProgressPercent, 0x005719F0);
	ZENGIN_REGISTER_METHOD(zCModelAniActive, &zCModelAniActive::SetActFrame, 0x00571A40);
	ZENGIN_REGISTER_METHOD(zCModelAniActive, &zCModelAniActive::DoCombineAni, 0x0057A890);

	ZENGIN_REGISTER_CLASS(zCModelTexAniState);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::zCModelTexAniState_OnInit, 0x00571A90);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::DeleteTexList, 0x00571AD0);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::UpdateTexList, 0x00571AF0);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::SetChannelVariation, 0x00571B30);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::BuildTexListFromMeshLib, 0x00571BA0);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::BuildTexListFromMesh, 0x00571C20);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::BuildTexListFromProgMesh, 0x00571DB0);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::AddTexListFromMeshLib, 0x00571F20);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::AddTexListFromMesh, 0x00572180);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::AddTexListFromProgMesh, 0x005722E0);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::FinishTexList, 0x00572430);

	ZENGIN_REGISTER_CLASS(zCModelNodeInst);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelNodeInst, &zCModelNodeInst::zCModelNodeInst_OnInit, void(zCModelNodeInst::*)(), 0x005725C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelNodeInst, &zCModelNodeInst::zCModelNodeInst_OnInit, void(zCModelNodeInst::*)(zCModelNode*), 0x00572690);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::Init, 0x00572800);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::InitByModelProtoNode, 0x00572890);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::SetNodeVisualS, 0x00572940);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::AddNodeAni, 0x005795D0);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::RemoveAllNodeAnis, 0x00579800);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::RemoveNodeAni, 0x00579810);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::FindMasterAni, 0x00579900);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::FadeOutNodeAni, 0x00579970);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::CalcWeights, 0x00579F50);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::AddToNodeAniWeight, 0x0057A190);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::CalcBlending, 0x0057A200);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::GetNodeAniListIndex, 0x0057A390);

	ZENGIN_REGISTER_CLASS(zTAniAttachment);
	ZENGIN_REGISTER_METHOD(zTAniAttachment, &zTAniAttachment::zTAniAttachment_OnInit, 0x0057DE00);

	ZENGIN_REGISTER_CLASS(zCModel);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::zCModel_OnInit, 0x00572F90);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetAniFromAniID, 0x00471E30);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::IsAniActive, 0x00471E70);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::Init, 0x00572D20);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CopyProtoNodeList, 0x00573150);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::ApplyModelProtoOverlay, int(zCModel::*)(zSTRING const&), 0x00573540);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::ApplyModelProtoOverlay, int(zCModel::*)(zCModelPrototype*), 0x00573590);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::HasAppliedModelProtoOverlay, int(zCModel::*)(zCModelPrototype*) const, 0x005737E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::HasAppliedModelProtoOverlay, int(zCModel::*)(zSTRING const&) const, 0x00573810);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::RemoveModelProtoOverlay, void(zCModel::*)(zSTRING const&), 0x00573990);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::RemoveModelProtoOverlay, void(zCModel::*)(zCModelPrototype*), 0x00573B90);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CalcNodeListBBoxWorld, 0x00573D10);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetBBox3DNodeWorld, 0x00573E40);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetNodePositionWorld, 0x00573E90);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CalcModelBBox3DWorld, 0x00573EC0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetNodeVisual, 0x00573FF0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetDynLightMode, 0x00574020);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RenderNodeList, 0x00574040);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CheckNodeCollisionList, 0x005752B0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CheckNodeCollision, 0x00575350);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetTrafoNodeToModel, 0x005754A0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetRandAnisEnabled, 0x005755D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::GetActiveAni, zCModelAniActive*(zCModel::*)(int) const, 0x00575640);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::GetActiveAni, zCModelAniActive*(zCModel::*)(zCModelAni*) const, 0x00575680);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::StopAni, void(zCModel::*)(int), 0x005756C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::StopAni, void(zCModel::*)(zCModelAni*), 0x00575740);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::StopAni, void(zCModel::*)(zCModelAniActive*), 0x00575790);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetAniTransLerp, 0x00575950);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::StartAni, void(zCModel::*)(zSTRING const&, int), 0x00575A50);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::StartAni, void(zCModel::*)(int, int), 0x00575B50);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::StartAni, void(zCModel::*)(zCModelAni*, int), 0x00575BA0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::AssertActiveAniListAlloced, 0x00576250);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::DoAniEvents, 0x00576370);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::AdvanceAni, 0x005772B0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::AdvanceAnis, 0x00577570);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetModelScale, 0x00578710);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::IsStateActive, 0x00578880);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SearchNode, 0x00578AD0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetNodeMeshTexture, 0x00578B80);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetMeshLibTexture, 0x00578CB0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RemoveMeshLibAll, 0x00578EB0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RemoveMeshLib, 0x00578EE0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::ApplyMeshLib, 0x005790F0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::UpdateMeshLibTexAniState, 0x00579550);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::FadeOutAni, void(zCModel::*)(int), 0x00579A30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::FadeOutAni, void(zCModel::*)(zCModelAni*), 0x00579AC0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::FadeOutAni, void(zCModel::*)(zCModelAniActive*), 0x00579B00);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::FadeOutAnisLayerRange, 0x00579CD0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::StopAnisLayerRange, 0x00579D20);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::GetProgressPercent, float(zCModel::*)(zSTRING const&) const, 0x00579D70);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::GetProgressPercent, float(zCModel::*)(int) const, 0x00579E20);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetCombineAniXY, 0x00579E90);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetCombineAniXY, 0x00579EE0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CalcNodeListAniBlending, 0x0057A360);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CalcTransBlending, 0x0057A3C0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::AttachChildVobToNode, 0x0057B180);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RemoveChildVobFromNode, 0x0057B2D0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RemoveAllChildVobsFromNode, 0x0057B350);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::UpdateAttachedVobs, 0x0057B3A0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RemoveStartedVobFX, 0x0057B4F0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetVelocityRing, 0x0057B5A0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::ResetVelocity, 0x0057B600);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetAniMinMaxWeight, 0x0057B690);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::PrintStatus, 0x0057B930);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CorrectAniFreezer, 0x0057C080);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::psb_WriteAniBlock, 0x0057C2F0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::psb_ReadAniBlock, 0x0057C480);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::PackStateBinary, 0x0057C6D0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::UnpackStateBinary, 0x0057CA20);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::ShowAniListAdd, 0x0057D1A0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::ShowAniList, 0x0057D210);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SearchAniAttachList, 0x0057DE40);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RemoveAniAttachment, 0x0057DEC0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RemoveAllAniAttachments, 0x0057E010);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RemoveAllVobFX, 0x0057E060);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetCreateAniAttachment, 0x0057E0F0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::DeleteRandAniList, 0x0057E340);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::InsertRandAni, 0x0057E3D0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetRandAniFreq, 0x0057E4D0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetRandAniFreq, 0x0057E560);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RecalcRootPosLocal, 0x0057E580);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetAniIDFromAniName, 0x0060A9B0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::_GetClassDef, 0x00571300);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::Render, 0x00574FC0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::IsBBox3DLocal, 0x00571310);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetBBox3D, 0x00578A00);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetVisualName, 0x00578A40);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetVisualUsedBy, 0x00573410);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetRenderSortKey, 0x0057D280);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CanTraceRay, 0x00571320);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::TraceRay, 0x0057D2A0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::HostVobRemovedFromWorld, 0x005762C0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetFileExtension, 0x00573490);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::LoadVisualVirtual, 0x005734B0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::StartAnimation, 0x00571330);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::StopAnimation, 0x00571340);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::IsAnimationActive, 0x005713E0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetAnyAnimation, 0x00575900);

	ZENGIN_REGISTER_CLASS(zCModelConvertFileHandler);
	ZENGIN_REGISTER_METHOD(zCModelConvertFileHandler, &zCModelConvertFileHandler::zCModelConvertFileHandler_OnInit, 0x0059C0B0);
	ZENGIN_REGISTER_METHOD(zCModelConvertFileHandler, &zCModelConvertFileHandler::HandleFile, 0x0059C1E0);

} // namespace Gothic_II_Classic
