namespace Gothic_II_Classic {

	ZENGIN_REGISTER_CLASS(zCPar_TreeNode);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPar_TreeNode, &zCPar_TreeNode::zCPar_TreeNode_OnInit, void(zCPar_TreeNode::*)(), 0x00737F40);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPar_TreeNode, &zCPar_TreeNode::zCPar_TreeNode_OnInit, void(zCPar_TreeNode::*)(int, int), 0x00737F80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPar_TreeNode, &zCPar_TreeNode::zCPar_TreeNode_OnInit, void(zCPar_TreeNode::*)(int, zSTRING&, int), 0x00737FD0);
	ZENGIN_REGISTER_METHOD(zCPar_TreeNode, &zCPar_TreeNode::SetLeft, 0x00738220);
	ZENGIN_REGISTER_METHOD(zCPar_TreeNode, &zCPar_TreeNode::SetRight, 0x00738230);
	ZENGIN_REGISTER_METHOD(zCPar_TreeNode, &zCPar_TreeNode::SetNext, 0x00738240);

	ZENGIN_REGISTER_CLASS(zCPar_File);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::zCPar_File_OnInit, 0x0072D5E0);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::IsNewerDate, 0x0072D6B0);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::IsExactDate, 0x0072D730);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::SetFileNumber, 0x0072D7B0);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::GetFileNumber, 0x0072D7C0);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::GetName, 0x0072D7D0);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::EnableTreeLoad, 0x0072D820);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::Load, 0x0072D830);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::GetStartAddress, 0x0072DAB0);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::GetEndAddress, 0x0072DAC0);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::Dispose, 0x0072DAD0);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::SetTree, 0x0072DAF0);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::GetTree, 0x0072DB30);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::SetLabelCount, 0x0072DB40);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::GetLabelCount, 0x0072DB50);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::SaveTree, 0x0072DB60);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::SaveTreeNode, 0x0072DDE0);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::LoadTreeNode, 0x0072DF50);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::LoadTree, 0x0072E080);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::DeleteTree, 0x0072E450);

	ZENGIN_REGISTER_CLASS(zCParser);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::zCParser_OnInit, 0x0072E490);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SetMessageFunc, 0x0072E810);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SetStopOnError, 0x0072E820);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::Error, void(zCParser::*)(zSTRING&, int), 0x0072E830);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::Message, 0x0072EBB0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::Error, int(zCParser::*)(), 0x0072ECF0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SaveDat, 0x0072ED00);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::LoadDat, 0x0072EEC0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::Parse, 0x0072F160);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ParseSource, 0x0072F3E0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ParseFile, 0x0072FC20);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ParseBlock, 0x007303F0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::CreatePCode, 0x007306A0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ShowSymbols, 0x00730DD0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::PushTree, 0x00730DE0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::PushOnStack, 0x00730E00);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SolveLabels, 0x00731BB0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::MergeFile, 0x00731C10);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::PopDataValue, 0x00731E70);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::PopFloatValue, 0x00731EA0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::PopVarAddress, 0x00731ED0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::PopString, 0x00731F00);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DoStack, 0x00731F20);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::CallFunc, void*(zCParser::*)(zSTRING const&), 0x00732F90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::CallFunc, void*(__cdecl zCParser::*)(int, ...), 0x00732FB0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetCurrentFunc, 0x007334D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::CreateInstance, int(zCParser::*)(zSTRING&, void*), 0x007334E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::CreateInstance, int(zCParser::*)(int, void*), 0x00733560);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::CreatePrototype, int(zCParser::*)(zSTRING&, void*), 0x007335D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::CreatePrototype, int(zCParser::*)(int, void*), 0x00733650);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::Reset, 0x007336C0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SetPercentDone, 0x00733830);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::CreateHelpers, 0x00733890);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::EnableTreeSave, 0x00733A00);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::EnableDatSave, 0x00733A10);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::EnableTreeLoad, 0x00733A20);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetIndex, 0x00733A30);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::MatchClass, 0x00733AF0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetBaseClass, int(zCParser::*)(zCPar_Symbol*), 0x00733B70);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetBaseClass, int(zCParser::*)(int), 0x00733BD0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetBase, 0x00733C30);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetPrototype, 0x00733C80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetInstance, int(zCParser::*)(int, int), 0x00733CF0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetSymbolInfo, zSTRING(zCParser::*)(int, int&, int&), 0x00733DB0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetSymbolInfo, zCPar_Symbol*(zCParser::*)(int), 0x00733E70);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetSymbol, zCPar_Symbol*(zCParser::*)(int), 0x00733E80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetSymbol, zCPar_Symbol*(zCParser::*)(zSTRING const&), 0x00733E90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetClassVarInfo, zSTRING(zCParser::*)(int, int, int&, int&), 0x00733F50);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetClassVarInfo, void(zCParser::*)(int, zSTRING&, int&, int&), 0x00734170);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetText, zSTRING(zCParser::*)(zSTRING&, int), 0x00734330);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetText, zSTRING(zCParser::*)(int, int), 0x00734370);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetInt, 0x00734450);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetInstanceValue, zSTRING(zCParser::*)(zSTRING&, int, void*, int), 0x007344A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetInstanceValue, zSTRING(zCParser::*)(int, int, void*, int), 0x00734590);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::IsValid, 0x007348A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::CheckClassSize, int(zCParser::*)(zSTRING&, int), 0x00734A10);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::CheckClassSize, int(zCParser::*)(int, int), 0x00734A30);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::AddClassOffset, 0x00734CF0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::SetInstance, int(zCParser::*)(zSTRING const&, void*), 0x00734E30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::SetInstance, int(zCParser::*)(int, void*), 0x00734ED0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::AutoCompletion, 0x00734F10);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetNumFiles, 0x00735120);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetFileName, 0x00735130);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::IsStackFull, 0x007351D0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetLastErrorLine, 0x007351E0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::Reparse, 0x007351F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::SaveInstance, int(zCParser::*)(zSTRING&, void*), 0x00735300);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::SaveInstance, int(zCParser::*)(int, void*), 0x00735330);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::CloseViews, 0x00735FF0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ShowCode, 0x00736020);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SaveInfoFile, 0x00736170);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SetInfoFile, 0x007367C0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::IsInAdditionalInfo, 0x00736950);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::WriteAdditionalInfo, 0x00736B00);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ClearAllInstanceRefs, 0x00736E90);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ClearInstanceRefs, 0x00736F00);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ResetGlobalVars, 0x00736F80);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::CreateVarReferenceList, 0x00737000);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ResetWithVarReferenceList, 0x00737180);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SaveGlobalVars, 0x00737200);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::LoadGlobalVars, 0x00737730);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetOperatorString, 0x00738340);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::FindNext, 0x007388D0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::PrevWord, 0x00738A40);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ReadWord, 0x00738A70);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::Match, 0x00738CE0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ReadVarType, 0x00738E70);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ReadFuncType, 0x007390A0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ReadInt, 0x007392C0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ReadFloat, 0x00739560);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ReadString, 0x007398A0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ReadArray, 0x00739B80);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::CreateLeaf, 0x00739D80);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::CreateStringLeaf, 0x00739DE0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::CreateFloatLeaf, 0x0073A030);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetNextToken, 0x0073A1D0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::Parse_Expression_Primary, 0x0073A950);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::Parse_Expression, 0x0073AF00);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ParseExpressionEx, 0x0073B110);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ParseExpression, 0x0073B180);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::EvalLeaf, 0x0073B1A0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareVar, 0x0073B660);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareClass, 0x0073C990);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareInstance, 0x0073CB60);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclarePrototype, 0x0073D340);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareIf, 0x0073D830);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareAssign, 0x0073DC90);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareAssignFunc, 0x0073E410);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareFunc, 0x0073E700);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareReturn, 0x0073EB90);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareFuncCall, 0x0073ED70);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SearchFuncWithStartAddress, 0x0073F740);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetNextCommand, 0x0073F7B0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ShowPCodeSpy, 0x007403D0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ShowPCode, 0x00740500);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DefineExternal, 0x00740750);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DefineExternalVar, 0x00740B10);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetParameter, void(zCParser::*)(int&), 0x00740D20);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetParameter, void(zCParser::*)(float&), 0x00740D30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetParameter, void(zCParser::*)(zSTRING&), 0x00740D70);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetInstance, void*(zCParser::*)(), 0x00740EB0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetInstanceAndIndex, 0x00740EE0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::SetReturn, void(zCParser::*)(int), 0x00740F20);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::SetReturn, void(zCParser::*)(float), 0x00740F40);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::SetReturn, void(zCParser::*)(void*), 0x00740F60);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::SetReturn, void(zCParser::*)(zSTRING&), 0x00740F90);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::FindInstanceVar, 0x00740FB0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetLastInstance, 0x00741190);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::FindIndex, 0x007411A0);

} // namespace Gothic_II_Classic
