namespace Gothic_II_Classic {

	ZENGIN_REGISTER_CLASS(zCPar_StringTable);
	ZENGIN_REGISTER_METHOD(zCPar_StringTable, &zCPar_StringTable::zCPar_StringTable_OnInit, 0x00741470);
	ZENGIN_REGISTER_METHOD(zCPar_StringTable, &zCPar_StringTable::Clear, 0x00741590);
	ZENGIN_REGISTER_METHOD(zCPar_StringTable, &zCPar_StringTable::Insert, 0x007415C0);
	ZENGIN_REGISTER_METHOD(zCPar_StringTable, &zCPar_StringTable::GetLastEntry, 0x00741710);
	ZENGIN_REGISTER_METHOD(zCPar_StringTable, &zCPar_StringTable::GetString, 0x00741720);
	ZENGIN_REGISTER_METHOD(zCPar_StringTable, &zCPar_StringTable::Save, 0x00741740);
	ZENGIN_REGISTER_METHOD(zCPar_StringTable, &zCPar_StringTable::Load, 0x00741860);
	ZENGIN_REGISTER_METHOD(zCPar_StringTable, &zCPar_StringTable::ShrinkToFit, 0x00741A40);
	ZENGIN_REGISTER_METHOD(zCPar_StringTable, &zCPar_StringTable::Show, 0x00741AC0);

	ZENGIN_REGISTER_CLASS(zCPar_Symbol);
	ZENGIN_REGISTER_METHOD(zCPar_Symbol, &zCPar_Symbol::zCPar_Symbol_OnInit, 0x00741C50);
	ZENGIN_REGISTER_METHOD(zCPar_Symbol, &zCPar_Symbol::AllocSpace, 0x00741D80);
	ZENGIN_REGISTER_METHOD(zCPar_Symbol, &zCPar_Symbol::GetDataAdr, 0x00742000);
	ZENGIN_REGISTER_METHOD(zCPar_Symbol, &zCPar_Symbol::SetDataAdr, 0x00742300);
	ZENGIN_REGISTER_METHOD(zCPar_Symbol, &zCPar_Symbol::SetFlag, 0x00742310);
	ZENGIN_REGISTER_METHOD(zCPar_Symbol, &zCPar_Symbol::HasFlag, 0x00742340);
	ZENGIN_REGISTER_METHOD(zCPar_Symbol, &zCPar_Symbol::SetParent, 0x00742360);
	ZENGIN_REGISTER_METHOD(zCPar_Symbol, &zCPar_Symbol::GetParent, 0x00742370);
	ZENGIN_REGISTER_METHOD(zCPar_Symbol, &zCPar_Symbol::GetInstanceAdr, 0x00742380);
	ZENGIN_REGISTER_METHOD(zCPar_Symbol, &zCPar_Symbol::GetNext, 0x00742390);
	ZENGIN_REGISTER_METHOD(zCPar_Symbol, &zCPar_Symbol::ArrayCheck, 0x007423A0);
	ZENGIN_REGISTER_METHOD(zCPar_Symbol, &zCPar_Symbol::GetStackPos, 0x007423D0);
	ZENGIN_REGISTER_METHOD(zCPar_Symbol, &zCPar_Symbol::SetStackPos, 0x007423E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPar_Symbol, &zCPar_Symbol::SetValue, void(zCPar_Symbol::*)(int, int), 0x007423F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPar_Symbol, &zCPar_Symbol::SetValue, void(zCPar_Symbol::*)(float, int), 0x00742420);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPar_Symbol, &zCPar_Symbol::SetValue, void(zCPar_Symbol::*)(zSTRING&, int), 0x00742450);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPar_Symbol, &zCPar_Symbol::GetValue, void(zCPar_Symbol::*)(int&, int), 0x007425A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPar_Symbol, &zCPar_Symbol::GetValue, void(zCPar_Symbol::*)(float&, int), 0x007425D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPar_Symbol, &zCPar_Symbol::GetValue, void(zCPar_Symbol::*)(zSTRING&, int), 0x00742600);
	ZENGIN_REGISTER_METHOD(zCPar_Symbol, &zCPar_Symbol::SetLineData, 0x00742750);
	ZENGIN_REGISTER_METHOD(zCPar_Symbol, &zCPar_Symbol::GetLineData, 0x00742B10);
	ZENGIN_REGISTER_METHOD(zCPar_Symbol, &zCPar_Symbol::SetFileNr, 0x00742B50);
	ZENGIN_REGISTER_METHOD(zCPar_Symbol, &zCPar_Symbol::Save, 0x00742CE0);
	ZENGIN_REGISTER_METHOD(zCPar_Symbol, &zCPar_Symbol::SaveFull, 0x00742F00);
	ZENGIN_REGISTER_METHOD(zCPar_Symbol, &zCPar_Symbol::LoadFull, 0x00743160);
	ZENGIN_REGISTER_METHOD(zCPar_Symbol, &zCPar_Symbol::Load, 0x00743330);
	ZENGIN_REGISTER_METHOD(zCPar_Symbol, &zCPar_Symbol::SetOffset, 0x007434E0);
	ZENGIN_REGISTER_METHOD(zCPar_Symbol, &zCPar_Symbol::GetOffset, 0x007434F0);
	ZENGIN_REGISTER_METHOD(zCPar_Symbol, &zCPar_Symbol::SetClassOffset, 0x00743500);
	ZENGIN_REGISTER_METHOD(zCPar_Symbol, &zCPar_Symbol::GetClassOffset, 0x00743510);

	ZENGIN_REGISTER_CLASS(zCPar_SymbolTable);
	ZENGIN_REGISTER_METHOD(zCPar_SymbolTable, &zCPar_SymbolTable::zCPar_SymbolTable_OnInit, 0x00743520);
	ZENGIN_REGISTER_METHOD(zCPar_SymbolTable, &zCPar_SymbolTable::Clear, 0x007436C0);
	ZENGIN_REGISTER_METHOD(zCPar_SymbolTable, &zCPar_SymbolTable::PreAlloc, 0x007437B0);
	ZENGIN_REGISTER_METHOD(zCPar_SymbolTable, &zCPar_SymbolTable::Save, 0x007438A0);
	ZENGIN_REGISTER_METHOD(zCPar_SymbolTable, &zCPar_SymbolTable::Load, 0x00743A20);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPar_SymbolTable, &zCPar_SymbolTable::IsIn, int(zCPar_SymbolTable::*)(zCPar_Symbol*), 0x00743E10);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPar_SymbolTable, &zCPar_SymbolTable::IsIn, int(zCPar_SymbolTable::*)(zSTRING const&), 0x00743F20);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPar_SymbolTable, &zCPar_SymbolTable::GetIndex, int(zCPar_SymbolTable::*)(zCPar_Symbol*), 0x00744030);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPar_SymbolTable, &zCPar_SymbolTable::GetIndex, int(zCPar_SymbolTable::*)(zSTRING const&), 0x00744120);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPar_SymbolTable, &zCPar_SymbolTable::GetIndex, int(zCPar_SymbolTable::*)(zSTRING const&, int), 0x00744210);
	ZENGIN_REGISTER_METHOD(zCPar_SymbolTable, &zCPar_SymbolTable::Search, 0x00744320);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPar_SymbolTable, &zCPar_SymbolTable::GetSymbol, zCPar_Symbol*(zCPar_SymbolTable::*)(zSTRING const&), 0x00744400);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPar_SymbolTable, &zCPar_SymbolTable::GetSymbol, zCPar_Symbol*(zCPar_SymbolTable::*)(int), 0x007444A0);
	ZENGIN_REGISTER_METHOD(zCPar_SymbolTable, &zCPar_SymbolTable::Insert, 0x007444C0);
	ZENGIN_REGISTER_METHOD(zCPar_SymbolTable, &zCPar_SymbolTable::InsertEnd, 0x00744700);
	ZENGIN_REGISTER_METHOD(zCPar_SymbolTable, &zCPar_SymbolTable::ShrinkToFit, 0x00744910);
	ZENGIN_REGISTER_METHOD(zCPar_SymbolTable, &zCPar_SymbolTable::SetSize, 0x007449F0);
	ZENGIN_REGISTER_METHOD(zCPar_SymbolTable, &zCPar_SymbolTable::GetNumInList, 0x00744AA0);
	ZENGIN_REGISTER_METHOD(zCPar_SymbolTable, &zCPar_SymbolTable::GetLastSymbol, 0x00744AB0);
	ZENGIN_REGISTER_METHOD(zCPar_SymbolTable, &zCPar_SymbolTable::GetFirstSymbol, 0x00744AC0);
	ZENGIN_REGISTER_METHOD(zCPar_SymbolTable, &zCPar_SymbolTable::Show, 0x00744AD0);

	ZENGIN_REGISTER_CLASS(zCPar_Stack);
	ZENGIN_REGISTER_METHOD(zCPar_Stack, &zCPar_Stack::zCPar_Stack_OnInit, 0x00745080);
	ZENGIN_REGISTER_METHOD(zCPar_Stack, &zCPar_Stack::GetPopPos, 0x007450D0);
	ZENGIN_REGISTER_METHOD(zCPar_Stack, &zCPar_Stack::SetPopPos, 0x007450E0);
	ZENGIN_REGISTER_METHOD(zCPar_Stack, &zCPar_Stack::GetDynSize, 0x007450F0);
	ZENGIN_REGISTER_METHOD(zCPar_Stack, &zCPar_Stack::GetStatSize, 0x00745100);
	ZENGIN_REGISTER_METHOD(zCPar_Stack, &zCPar_Stack::PushByte, 0x00745110);
	ZENGIN_REGISTER_METHOD(zCPar_Stack, &zCPar_Stack::PushWord, 0x00745130);
	ZENGIN_REGISTER_METHOD(zCPar_Stack, &zCPar_Stack::PushInt, 0x00745150);
	ZENGIN_REGISTER_METHOD(zCPar_Stack, &zCPar_Stack::PushString, 0x00745170);
	ZENGIN_REGISTER_METHOD(zCPar_Stack, &zCPar_Stack::PopByte, 0x007451E0);
	ZENGIN_REGISTER_METHOD(zCPar_Stack, &zCPar_Stack::PopWord, 0x007451F0);
	ZENGIN_REGISTER_METHOD(zCPar_Stack, &zCPar_Stack::PopInt, 0x00745200);
	ZENGIN_REGISTER_METHOD(zCPar_Stack, &zCPar_Stack::PopString, 0x00745210);
	ZENGIN_REGISTER_METHOD(zCPar_Stack, &zCPar_Stack::CheckOverflow, 0x007453D0);
	ZENGIN_REGISTER_METHOD(zCPar_Stack, &zCPar_Stack::Set, 0x00745440);
	ZENGIN_REGISTER_METHOD(zCPar_Stack, &zCPar_Stack::ReachedEnd, 0x00745450);
	ZENGIN_REGISTER_METHOD(zCPar_Stack, &zCPar_Stack::Clear, 0x00745460);
	ZENGIN_REGISTER_METHOD(zCPar_Stack, &zCPar_Stack::Save, 0x00745470);
	ZENGIN_REGISTER_METHOD(zCPar_Stack, &zCPar_Stack::Load, 0x007454B0);

	ZENGIN_REGISTER_CLASS(zCPar_DataStack);
	ZENGIN_REGISTER_METHOD(zCPar_DataStack, &zCPar_DataStack::zCPar_DataStack_OnInit, 0x00745510);
	ZENGIN_REGISTER_METHOD(zCPar_DataStack, &zCPar_DataStack::Push, 0x00745540);
	ZENGIN_REGISTER_METHOD(zCPar_DataStack, &zCPar_DataStack::Pop, 0x00745630);
	ZENGIN_REGISTER_METHOD(zCPar_DataStack, &zCPar_DataStack::PopFloat, 0x00745650);
	ZENGIN_REGISTER_METHOD(zCPar_DataStack, &zCPar_DataStack::IsEmpty, 0x00745670);
	ZENGIN_REGISTER_METHOD(zCPar_DataStack, &zCPar_DataStack::Clear, 0x00745680);

} // namespace Gothic_II_Classic
