namespace Gothic_II_Classic {

	ZENGIN_REGISTER_CLASS(zSTRING);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(char const*), 0x004010C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(), 0x00402AF0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(zSTRING const&), 0x00416500);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(int), 0x00435370);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(float, int), 0x00435470);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(double, int), 0x00453F30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(unsigned long), 0x00461680);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(char), 0x00517EB0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(long), 0x00673000);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(zSTRING const*), 0x00732E90);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::ToChar, 0x004631C0);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Clear, 0x00597AB0);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::IsEmpty, 0x0078AF30);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Lower, 0x00469DC0);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Upper, 0x00469ED0);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::UpperFirstLowerRest, 0x00469FE0);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Align, 0x0046A130);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::PickWord, 0x0046A350);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::PickWordPos, 0x0046A5A0);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::PickWord_Old, 0x0046A710);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Insert, 0x0046A7D0);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Inserted, 0x0046A8F0);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Overwrite, 0x0046AA70);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Overwritten, 0x0046AC60);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::DeleteRight, 0x0046AD60);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Delete, int(zSTRING::*)(unsigned int, unsigned long), 0x0046AE70);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Deleted, zSTRING(zSTRING::*)(unsigned int, unsigned long) const, 0x0046AF80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Delete, int(zSTRING::*)(zSTRING const&, zTSTR_KIND), 0x0046B0C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Deleted, zSTRING(zSTRING::*)(zSTRING const&, zTSTR_KIND) const, 0x0046B2B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Copied, zSTRING(zSTRING::*)(unsigned int, unsigned long) const, 0x0046B540);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Copy, int(zSTRING::*)(zSTRING const&, zTSTR_KIND const&), 0x0046B6A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Copy, int(zSTRING::*)(unsigned int, unsigned long), 0x0046B390);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Copied, zSTRING(zSTRING::*)(zSTRING const&, zTSTR_KIND const&) const, 0x0046B920);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::TrimLeft, 0x0046BA00);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::TrimRight, 0x0046BB40);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Search, int(zSTRING::*)(int, char const*, unsigned int) const, 0x0046BCF0);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::SearchRev, 0x0046BDF0);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Sprintf, 0x0046C030);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Search, int(zSTRING::*)(zSTRING const&, unsigned int) const, 0x00490C70);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::ToFloat, 0x00491C90);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::ToInt, 0x00597B90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Search, int(zSTRING::*)(char const*, unsigned int) const, 0x00597BB0);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Init, 0x0067CC70);

} // namespace Gothic_II_Classic
