namespace Gothic_II_Classic {

	ZENGIN_REGISTER_CLASS(zCOLOR);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCOLOR, &zCOLOR::zCOLOR_OnInit, void(zCOLOR::*)(int), 0x00401F20);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCOLOR, &zCOLOR::zCOLOR_OnInit, void(zCOLOR::*)(unsigned char, unsigned char, unsigned char, unsigned char), 0x0072B4B0);
	ZENGIN_REGISTER_METHOD(zCOLOR, &zCOLOR::Reset, 0x0056D650);
	ZENGIN_REGISTER_METHOD(zCOLOR, &zCOLOR::GetDescription, 0x005F3DB0);
	ZENGIN_REGISTER_METHOD(zCOLOR, &zCOLOR::SetByDescription, 0x005F4120);
	ZENGIN_REGISTER_METHOD(zCOLOR, &zCOLOR::GetDescriptionRGB, 0x005F43A0);
	ZENGIN_REGISTER_METHOD(zCOLOR, &zCOLOR::SetRGB, 0x00622FC0);

	ZENGIN_REGISTER_CLASS(zTPlane);
	ZENGIN_REGISTER_METHOD(zTPlane, &zTPlane::CalcSignbits, 0x00545F80);
	ZENGIN_REGISTER_METHOD(zTPlane, &zTPlane::ClassifyPointBSPBuild, 0x005F4650);
	ZENGIN_REGISTER_METHOD(zTPlane, &zTPlane::Print, 0x005F46A0);
	ZENGIN_REGISTER_METHOD(zTPlane, &zTPlane::Calc, 0x005F4A80);
	ZENGIN_REGISTER_METHOD(zTPlane, &zTPlane::GetOriginUpRight, 0x005F4B60);

} // namespace Gothic_II_Classic
