namespace Gothic_II_Classic {

	ZENGIN_REGISTER_CLASS(zCViewFX);
	ZENGIN_REGISTER_METHOD(zCViewFX, &zCViewFX::zCViewFX_OnInit, 0x007A0CB0);
	ZENGIN_REGISTER_METHOD(zCViewFX, &zCViewFX::Init, 0x007A0DB0);
	ZENGIN_REGISTER_METHOD(zCViewFX, &zCViewFX::Open, 0x007A0E30);
	ZENGIN_REGISTER_METHOD(zCViewFX, &zCViewFX::OpenSafe, 0x007A0E60);
	ZENGIN_REGISTER_METHOD(zCViewFX, &zCViewFX::OpenImmediately, 0x007A0EE0);
	ZENGIN_REGISTER_METHOD(zCViewFX, &zCViewFX::Close, 0x007A0F00);
	ZENGIN_REGISTER_METHOD(zCViewFX, &zCViewFX::CloseSafe, 0x007A0F50);
	ZENGIN_REGISTER_METHOD(zCViewFX, &zCViewFX::CloseImmediately, 0x007A0FE0);
	ZENGIN_REGISTER_METHOD(zCViewFX, &zCViewFX::ApplyOpenCloseFX, 0x007A1000);
	ZENGIN_REGISTER_METHOD(zCViewFX, &zCViewFX::ApplyOpenFX, 0x007A12B0);
	ZENGIN_REGISTER_METHOD(zCViewFX, &zCViewFX::ApplyCloseFX, 0x007A13F0);
	ZENGIN_REGISTER_METHOD(zCViewFX, &zCViewFX::ApplyOpenFade, 0x007A1530);
	ZENGIN_REGISTER_METHOD(zCViewFX, &zCViewFX::ApplyOpenZoom, 0x007A1580);
	ZENGIN_REGISTER_METHOD(zCViewFX, &zCViewFX::ApplyCloseFade, 0x007A1610);
	ZENGIN_REGISTER_METHOD(zCViewFX, &zCViewFX::ApplyCloseZoom, 0x007A1670);
	ZENGIN_REGISTER_METHOD(zCViewFX, &zCViewFX::_GetClassDef, 0x007A0CA0);
	ZENGIN_REGISTER_METHOD(zCViewFX, &zCViewFX::EvaluateTexturePosition, 0x007A1830);
	ZENGIN_REGISTER_METHOD(zCViewFX, &zCViewFX::Blit, 0x007A1700);

} // namespace Gothic_II_Classic
