namespace Gothic_II_Classic {

	ZENGIN_REGISTER_CLASS(zCVisual);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::zCVisual_OnInit, 0x005FF7D0);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::AddNextLODVisual, 0x005FF990);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::AddEndLODVisual, 0x005FF9C0);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::_GetClassDef, 0x004C7AD0);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::IsBBox3DLocal, 0x00561DD0);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::GetOBBox3D, 0x004C7AE0);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::GetVisualDied, 0x004C7AF0);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::SetVisualUsedBy, 0x00561DE0);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::DynLightVisual, 0x004C7B00);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::GetRenderSortKey, 0x004C7B10);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::CanTraceRay, 0x004C7B20);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::TraceRay, 0x005FFA50);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::HostVobRemovedFromWorld, 0x004C7B30);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::HostVobAddedToWorld, 0x004C7B40);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::GetFileExtension, 0x004C7B50);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::GetLODVisualAndAlpha, 0x005FF9F0);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::GetAlphaTestingEnabled, 0x004C7B60);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::SetAlphaTestingEnabled, 0x004C7B70);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::LoadVisualVirtual, 0x004C7B80);

	ZENGIN_REGISTER_CLASS(zCVisualAnimate);
	ZENGIN_REGISTER_METHOD(zCVisualAnimate, &zCVisualAnimate::_GetClassDef, 0x005712D0);

	ZENGIN_REGISTER_CLASS(zCDecal);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::zCDecal_OnInit, 0x00551350);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCDecal, &zCDecal::SetTexture, void(zCDecal::*)(zSTRING&), 0x00551730);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCDecal, &zCDecal::SetTexture, void(zCDecal::*)(zCTexture*), 0x00551740);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::SetDecalDim, 0x00551750);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::_GetClassDef, 0x00551330);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::Archive, 0x00551B50);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::Unarchive, 0x00551C40);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::Render, 0x00551770);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::IsBBox3DLocal, 0x00551340);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::GetBBox3D, 0x00551910);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::GetVisualName, 0x00551960);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::SetVisualUsedBy, 0x005518F0);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::DynLightVisual, 0x00551A40);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::GetRenderSortKey, 0x00551720);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::GetFileExtension, 0x00551580);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::GetAlphaTestingEnabled, 0x005519C0);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::LoadVisualVirtual, 0x005515E0);

	ZENGIN_REGISTER_CLASS(zCMesh);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::zCMesh_OnInit, 0x00561B70);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::DeleteAll, 0x00562070);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::VertexInMesh, 0x00563100);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::AllocVerts, 0x005632B0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::AllocPolys, 0x005633A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::AddVertex, zCVertex*(zCMesh::*)(zCVertex*), 0x00563460);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::AddVertex, zCVertex*(zCMesh::*)(zVEC3&), 0x005636A0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::AddVertexSmart, 0x00563930);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::AddPoly, zCPolygon*(zCMesh::*)(zVEC3&, zVEC3&, zVEC3&, zVEC2&, zVEC2&, zVEC2&), 0x005639C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::AddPoly, zCPolygon*(zCMesh::*)(zCVertex*, zCVertex*, zCVertex*), 0x00563C50);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::AddPoly, zCPolygon*(zCMesh::*)(zCVertex*, zCVertex*, zCVertex*, zCVertex*), 0x00563D60);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::AddPoly, zCPolygon*(zCMesh::*)(zCPolygon*), 0x00563E70);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::AddPoly, zCPolygon*(zCMesh::*)(), 0x00563F20);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::DeletePoly, 0x00564000);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::DynLightScalePrelit, 0x005640F0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::PrelightMesh, 0x00564100);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SharePoly, 0x00564510);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::CheckRayPolyIntersection, zCPolygon*(zCMesh::*)(zVEC3 const&, zVEC3 const&, zVEC3&), 0x00564530);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::CheckRayPolyIntersection, zCPolygon*(zCMesh::*)(zCCamera&, int, int, zVEC3&), 0x00564590);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::PickPolygon, zCPolygon*(zCMesh::*)(zVEC3 const&, zVEC3 const&, zVEC3&), 0x00564740);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::PickPolygon, zCPolygon*(zCMesh::*)(zCCamera&, int, int, zVEC3&), 0x00564810);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::CalcVertexNormals, 0x00564B90);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::UnSmoothMesh, 0x00565290);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SetDefaultPlanarMapping, 0x00565330);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::CalcBBox3D, 0x005653C0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::Center, 0x00565550);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::TransformAllVerts, 0x005656A0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::MergeMesh, 0x00565760);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::CalcNormals, 0x00565C40);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SetMaterial, 0x00565C70);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::ScaleXZ, 0x00565CD0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::Scale, 0x00565D40);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::CheckForMaterials, 0x00565E00);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::Render_novt, 0x00565FC0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::RenderHorizon, 0x005662A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::RenderDecal, void(zCMesh::*)(float, float, float, int), 0x00566550);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::RenderDecalHorizon, 0x00566730);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::RenderDecal, void(zCMesh::*)(zTRenderContext&, int), 0x00566B50);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::ResetStaticLight, 0x00566DB0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SetStaticLight, 0x00566DF0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SetLightDyn, 0x00566E30);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SetLightStatAlpha, 0x00566E70);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::ResetLightDynToLightStat, 0x00566EB0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::AddToLightDyn, 0x00566EF0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::SaveMSH, void(zCMesh::*)(zCFileBIN&), 0x00568540);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::SaveMSH, void(zCMesh::*)(zSTRING const&), 0x00568560);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::LoadMSH, int(zCMesh::*)(zCFileBIN&, int), 0x0056AE50);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::LoadMSH, int(zCMesh::*)(zSTRING const&, int), 0x0056C420);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::CreateListsFromArrays, 0x0056C6D0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::ClearLists, 0x0056C7A0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::ArraysToLists, 0x0056C800);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::ShareFeatures, 0x0056C8E0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::UnshareFeatures, 0x0056D6C0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::FlipPolys, 0x0056D7E0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SortPolysByMaterial, 0x0056DA60);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SortPolysByList, 0x0056DB10);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::DeletePolyAndVerts, void(zCMesh::*)(zCPolygon*), 0x0056E3A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::DeletePolyAndVerts, void(zCMesh::*)(unsigned long), 0x0056E430);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::RemoveDegeneratePolys, 0x0056E5B0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::CombineLightmaps, 0x0056E7E0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::LightMesh, 0x006222D0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::_GetClassDef, 0x00561DF0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::Render, 0x00565F40);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::GetBBox3D, 0x00561E50);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::GetOBBox3D, 0x00561E80);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::GetVisualName, 0x00561E00);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::DynLightVisual, 0x005640E0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::CanTraceRay, 0x00561E90);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::TraceRay, 0x00564A10);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::GetFileExtension, 0x00562030);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::GetAlphaTestingEnabled, 0x00561EA0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SetAlphaTestingEnabled, 0x00561EB0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::LoadVisualVirtual, 0x00562050);

} // namespace Gothic_II_Classic
