namespace Gothic_II_Classic {

	ZENGIN_REGISTER_CLASS(zCEventMessage);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCEventMessage, &zCEventMessage::zCEventMessage_OnInit, void(zCEventMessage::*)(), 0x00413B60);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCEventMessage, &zCEventMessage::zCEventMessage_OnInit, void(zCEventMessage::*)(unsigned short), 0x005FE6D0);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::GetMessageID, 0x005FE840);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::PackToBuffer, 0x005FE8A0);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::GetSubType, 0x0078AFB0);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::_GetClassDef, 0x00401F30);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::Archive, 0x005FE930);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::Unarchive, 0x005FEB30);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::IsOverlay, 0x00401F40);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::IsNetRelevant, 0x00401F50);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::IsHighPriority, 0x00401F60);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::IsJob, 0x00401F70);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::GetIgnoreCutsceneMode, 0x00401F80);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::Delete, 0x00401F90);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::IsDeleteable, 0x00401FA0);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::IsDeleted, 0x00401FB0);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::SetCutsceneMode, 0x00401FC0);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::GetCutsceneMode, 0x00401FD0);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::MD_GetNumOfSubTypes, 0x00401FE0);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::MD_GetSubTypeString, 0x00401FF0);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::MD_GetVobRefName, 0x00402030);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::MD_SetVobRefName, 0x00402070);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::MD_SetVobParam, 0x00402080);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::MD_GetTimeBehavior, 0x00402090);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::MD_GetMinTime, 0x004020A0);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::Pack, 0x004020B0);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::Unpack, 0x004020C0);

	ZENGIN_REGISTER_CLASS(zCEventCore);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::Clear, 0x005FF230);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::_GetClassDef, 0x00402130);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::Archive, 0x005FF660);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::Unarchive, 0x005FF6D0);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::IsNetRelevant, 0x00402150);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::MD_GetNumOfSubTypes, 0x00402140);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::MD_GetSubTypeString, 0x005FF460);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::Pack, 0x005FF290);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::Unpack, 0x005FF340);

	ZENGIN_REGISTER_CLASS(zCVob);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::zCVob_OnInit, 0x005F73F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::GetPositionWorld, zVEC3(zCVob::*)() const, 0x0052AD40);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetAtVectorWorld, 0x0052AD60);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetUpVectorWorld, 0x0052AD80);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetRightVectorWorld, 0x0052ADA0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetVobID, 0x005F7AF0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetAI, 0x005F7B00);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetVobPresetName, 0x005F7B50);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetVobPresetName, 0x005F7B60);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetRigidBody, 0x005F7B70);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ArchivePacked, 0x005F7BE0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ArchiveVerbose, 0x005F7FC0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::UnarchivePacked, 0x005F8410);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::UnarchiveVerbose, 0x005F8930);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetVobName, 0x005F8FD0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetEM, 0x005F9010);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CalcLightSampleAtOrigin, 0x005F9330);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetLightColorStat, 0x005F93B0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetLightColorStatGroundPoly, 0x005F9640);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetLightColorDyn, 0x005F9670);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CalcStaticLight, 0x005F9850);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetSectorNameVobIsIn, 0x005F9CE0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetGroundShadowSize, 0x005F9E30);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetGroundShadowSize, 0x005F9E80);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RenderGroundShadow, 0x005F9ED0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetClassHelperVisual, 0x005FA3C0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CalcRenderAlpha, 0x005FA5C0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetLightColorAtCenter, 0x005FAC90);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RemoveVobFromWorld, 0x005FAE10);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RemoveVobSubtreeFromWorld, 0x005FAE30);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::AddRefVobSubtree, 0x005FAE90);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ReleaseVobSubtree, 0x005FAF10);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RemoveWorldDependencies, 0x005FAF70);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RemoveVobFromGlobalVobTree, 0x005FB1C0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RemoveVobFromBspTree, 0x005FB2B0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetVobInfo, 0x005FB2D0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetSleeping, 0x005FBB00);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::UpdateVisualDependencies, 0x005FBCF0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::AddVobToWorld_CorrectParentDependencies, 0x005FBD80);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ResetOnTimer, 0x005FBDA0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetOnTimer, 0x005FBDB0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::IsOnTimer, 0x005FBDE0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ProcessOnTimer, 0x005FBE00);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::DoFrameActivity, 0x005FBE30);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CheckModelLimbCollision, 0x005FC050);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CheckModelLimbCollisionLevel, 0x005FCC00);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CheckModelLimbCollisionPolys, 0x005FD890);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::GetTrafoModelNodeToWorld, zMAT4(zCVob::*)(zSTRING const&), 0x005FDAE0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::GetTrafoModelNodeToWorld, zMAT4(zCVob::*)(zCModelNodeInst*), 0x005FDBD0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetScreenBBox2D, 0x005FDC60);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::PackStateBinary, 0x005FE290);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::UnpackStateBinary, 0x005FE340);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetVisual, 0x0060F460);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CalcGroundPoly, 0x00613610);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CalcWaterVob, 0x00613760);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetCollTypeDefaultFromVisual, 0x00613830);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::TouchMovement, 0x006139A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::GetNewTrafoObjToWorld, zMAT4 const&(zCVob::*)() const, 0x006139C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::GetNewTrafoObjToWorld, zMAT4&(zCVob::*)(), 0x006139E0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetNewTrafoObjToWorld, 0x00613A00);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetBBox3DWorld, 0x00613A20);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetBBox3DLocal, 0x00613A80);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetBBox3DLocal, 0x00613B30);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::Move, 0x00613C20);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::MoveWorld, 0x00613C90);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::MoveLocal, 0x00613D00);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetRotationWorld, 0x00613DF0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RotateWorld, 0x00613E50);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RotateLocal, 0x00613F40);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RotateLocalX, 0x00613FE0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RotateLocalY, 0x00614050);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RotateLocalZ, 0x006140C0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RotateWorldX, 0x00614130);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RotateWorldY, 0x00614160);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RotateWorldZ, 0x00614190);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::GetPositionWorld, void(zCVob::*)(float&, float&, float&) const, 0x006141C0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetPositionLocal, 0x006141F0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetDistanceToVob, 0x00614240);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetDistanceToVobApprox, 0x006142A0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetDistanceToVob2, 0x00614370);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetPositionLocal, 0x006143D0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetPositionWorld, 0x00614490);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetTrafo, 0x006144F0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetTrafoObjToWorld, 0x006145A0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ResetRotationsLocal, 0x00614600);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ResetXZRotationsLocal, 0x00614720);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ResetRotationsWorld, 0x006148F0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ResetXZRotationsWorld, 0x00614980);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetHeadingYLocal, 0x00614AA0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::SetHeadingYWorld, void(zCVob::*)(zVEC3 const&), 0x00614B70);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::SetHeadingYWorld, void(zCVob::*)(zCVob*), 0x00614D40);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetHeadingLocal, 0x00614ED0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::SetHeadingWorld, void(zCVob::*)(zVEC3 const&), 0x00614F90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::SetHeadingWorld, void(zCVob::*)(zCVob*), 0x00615050);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetHeadingAtLocal, 0x00615130);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::HasParentVob, 0x00615460);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetHeadingAtWorld, 0x00615480);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetCollDetStat, 0x00615710);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetCollDetDyn, 0x00615800);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CorrectTrafo, 0x00615900);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::DoneWithTrafoLocal, 0x00615970);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CreateTrafoLocal, 0x006159C0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetPhysicsEnabled, 0x00615A50);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetVelocity, 0x00615A80);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::UpdatePhysics, 0x00615B90);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::DetectCollision, 0x00616150);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetInMovement, 0x00616290);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetInMovementMode, 0x006162F0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::BeginMovement, 0x00616340);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ResetToOldMovementState, 0x006164C0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::UpdateTouchList, 0x006164F0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CalcDestinationBBox3DWorld, 0x006167A0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::AdoptCollObjResults, 0x006168E0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetCollisionObject, 0x00616E90);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetCollisionClass, 0x00616EC0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetCollisionObject, 0x00616F00);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CreateCollisionObject, 0x00616F10);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ResetCollisionObjectState, 0x00616F40);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::DestroyCollisionObject, 0x00616F80);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CheckEmergencyPutToSleep, 0x00616FC0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CollectCollisionContext_Vobs, 0x00617120);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CollectCollisionContext_Static, 0x00617380);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CollectCollisionContext, 0x00617670);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CleanupCollisionContext, 0x006176F0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::NotifyCollisionPair, 0x00617760);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ExecuteCollisionResponse, 0x00617830);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CheckAndResolveCollisions, 0x00617910);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::IsColliding, 0x00617DA0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetStaticVob, 0x00673230);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetVobType, 0x00673250);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetDrawBBox3D, 0x00673260);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetCollDet, 0x00673280);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetHomeWorld, 0x0078AFC0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::_GetClassDef, 0x0043C680);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::Archive, 0x005F8350);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::Unarchive, 0x005F8E80);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnTrigger, 0x005F7380);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnUntrigger, 0x005F7390);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnTouch, 0x005F73A0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnUntouch, 0x005F73B0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnTouchLevel, 0x005F73C0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnDamage, 0x005F73D0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnMessage, 0x005F73E0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnTick, 0x00404270);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnTimer, 0x0043C690);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::PostLoad, 0x00404280);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetCharacterClass, 0x00404290);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetSleepingMode, 0x005FBB30);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::EndMovement, 0x00616990);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CanThisCollideWith, 0x004042A0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::Render, 0x005FA7A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::SetVisual, void(zCVob::*)(zCVisual*), 0x005FB6C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::SetVisual, void(zCVob::*)(zSTRING const&), 0x005FB850);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetScriptInstance, 0x004042B0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetByScriptInstance, 0x004042D0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetCSStateFlags, 0x004042E0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::TraceRay, 0x005F9040);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetTriggerTarget, 0x0043C6A0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ThisVobAddedToWorld, 0x005FAE50);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ThisVobRemovedFromWorld, 0x005FAE70);

	ZENGIN_REGISTER_CLASS(zCVob::zTModelLimbColl);
	ZENGIN_REGISTER_METHOD(zCVob::zTModelLimbColl, &zCVob::zTModelLimbColl::zTModelLimbColl_OnInit, 0x005FCBA0);

	ZENGIN_REGISTER_CLASS(zCVobLightData);
	ZENGIN_REGISTER_METHOD(zCVobLightData, &zCVobLightData::zCVobLightData_OnInit, 0x006036B0);
	ZENGIN_REGISTER_METHOD(zCVobLightData, &zCVobLightData::SetLensFlareFXByName, 0x006026B0);
	ZENGIN_REGISTER_METHOD(zCVobLightData, &zCVobLightData::GetLensFlareFXName, 0x006027B0);
	ZENGIN_REGISTER_METHOD(zCVobLightData, &zCVobLightData::Archive, 0x006027D0);
	ZENGIN_REGISTER_METHOD(zCVobLightData, &zCVobLightData::Unarchive, 0x00602CE0);
	ZENGIN_REGISTER_METHOD(zCVobLightData, &zCVobLightData::SetRange, 0x006037A0);

	ZENGIN_REGISTER_CLASS(zCVobLightPreset);
	ZENGIN_REGISTER_METHOD(zCVobLightPreset, &zCVobLightPreset::_GetClassDef, 0x005F68A0);
	ZENGIN_REGISTER_METHOD(zCVobLightPreset, &zCVobLightPreset::Archive, 0x006024D0);
	ZENGIN_REGISTER_METHOD(zCVobLightPreset, &zCVobLightPreset::Unarchive, 0x00602500);

	ZENGIN_REGISTER_CLASS(zCVobLight);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::zCVobLight_OnInit, 0x00600EF0);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::DoAnimation, 0x00601270);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::SetRange, 0x00601540);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::AddThisToPresetList, 0x00601B30);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::SetByPreset, 0x00601E00);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::SetByPresetInUse, 0x00602080);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::_GetClassDef, 0x00600E90);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::Archive, 0x006022D0);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::Unarchive, 0x00602320);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::OnTrigger, 0x00601100);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::OnUntrigger, 0x006011D0);

	ZENGIN_REGISTER_CLASS(zCVobLevelCompo);
	ZENGIN_REGISTER_METHOD(zCVobLevelCompo, &zCVobLevelCompo::zCVobLevelCompo_OnInit, 0x005FE3F0);
	ZENGIN_REGISTER_METHOD(zCVobLevelCompo, &zCVobLevelCompo::HasIdentityTrafo, 0x005FE450);
	ZENGIN_REGISTER_METHOD(zCVobLevelCompo, &zCVobLevelCompo::_GetClassDef, 0x005F6E40);
	ZENGIN_REGISTER_METHOD(zCVobLevelCompo, &zCVobLevelCompo::Archive, 0x005FE4D0);
	ZENGIN_REGISTER_METHOD(zCVobLevelCompo, &zCVobLevelCompo::Unarchive, 0x005FE580);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVobLevelCompo, &zCVobLevelCompo::SetVisual, void(zCVobLevelCompo::*)(zCVisual*), 0x005FE650);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVobLevelCompo, &zCVobLevelCompo::SetVisual, void(zCVobLevelCompo::*)(zSTRING const&), 0x005FE690);

} // namespace Gothic_II_Classic
