namespace Gothic_II_Classic {

	ZENGIN_REGISTER_CLASS(zCVobWaypoint);
	ZENGIN_REGISTER_METHOD(zCVobWaypoint, &zCVobWaypoint::zCVobWaypoint_OnInit, 0x0074D0C0);
	ZENGIN_REGISTER_METHOD(zCVobWaypoint, &zCVobWaypoint::_GetClassDef, 0x0074D0E0);

	ZENGIN_REGISTER_CLASS(zCWaypoint);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::zCWaypoint_OnInit, 0x0074FC70);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWaypoint, &zCWaypoint::Init, void(zCWaypoint::*)(zVEC3&), 0x0074FDA0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWaypoint, &zCWaypoint::Init, void(zCWaypoint::*)(float, float, float), 0x0074FE00);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWaypoint, &zCWaypoint::Init, void(zCWaypoint::*)(zCVobWaypoint*), 0x0074FE70);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::Free, 0x0074FF10);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::GetPositionWorld, 0x00750030);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::UpdatePositionWorld, 0x00750040);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::SetName, 0x007500B0);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::GetName, 0x00750210);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::GetVob, 0x00750370);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::CalcProperties, 0x00750380);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::CorrectHeight, 0x007505A0);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::InsertWay, 0x00750640);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::RemoveWay, 0x00750650);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::HasWay, 0x007506B0);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::GetNumberOfWays, 0x007506E0);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::GetWayList, 0x00750700);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::SetWaypointVob, 0x00750710);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::Draw, 0x00750750);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::_GetClassDef, 0x0071E4D0);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::Archive, 0x00750760);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::Unarchive, 0x007507C0);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::CanBeUsed, 0x0074FD60);

	ZENGIN_REGISTER_CLASS(zCWay);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWay, &zCWay::zCWay_OnInit, void(zCWay::*)(), 0x0074ED30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWay, &zCWay::zCWay_OnInit, void(zCWay::*)(zCWaypoint*, zCWaypoint*), 0x0074ED90);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::Free, 0x0074EEE0);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::GetGoalWaypoint, 0x0074EF90);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::EstimateCost, 0x0074EFA0);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::GetLength, 0x0074F010);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::GetJumpDistance, 0x0074F0C0);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::GetDistancePos, 0x0074F180);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::Draw, 0x0074F290);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::GetFloor, 0x0074F770);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::Init, 0x0074EE40);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::CalcProperties, 0x0074F810);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::GetChasm, 0x0074FB00);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::CanJump, 0x0074FB10);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::CanBeUsed, 0x0074F280);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::IsObjectOnWay, 0x0074ED50);

	ZENGIN_REGISTER_CLASS(zCWayNet);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::zCWayNet_OnInit, void(zCWayNet::*)(), 0x0074D130);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::zCWayNet_OnInit, void(zCWayNet::*)(zCWorld*), 0x0074D210);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::HasWaypoint, zCWaypoint*(zCWayNet::*)(float, float, float), 0x0074D400);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::HasWaypoint, int(zCWayNet::*)(zCWaypoint*), 0x0074D470);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::HasWaypoint, zCWaypoint*(zCWayNet::*)(zVEC3&), 0x0074D4A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::InsertWaypoint, zCWaypoint*(zCWayNet::*)(float, float, float), 0x0074D4F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::InsertWaypoint, void(zCWayNet::*)(zCWaypoint*), 0x0074D600);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::InsertWaypoint, void(zCWayNet::*)(zCWaypoint*, zCWaypoint*, zCWaypoint*), 0x0074D630);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::DeleteWaypoint, 0x0074D7B0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::CreateWay, 0x0074D920);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::DeleteWay, 0x0074D9F0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::GetNearestWaypoint, 0x0074DB60);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::GetSecNearestWaypoint, 0x0074DBF0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::CorrectHeight, 0x0074DCB0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::Draw, 0x0074DD70);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::UpdateVobDependencies, 0x0074DDA0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::ClearVobDependencies, 0x0074DFF0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::CreateVobDependencies, 0x0074E1F0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::MergeWaypoints, 0x0074E470);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::CheckConsistency, 0x0074E730);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::AddWays, 0x0074EC30);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::GetWaypoint, 0x00750830);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::SearchWaypoint, 0x007509A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::FindRoute, zCRoute*(zCWayNet::*)(zVEC3 const&, zVEC3 const&, zCVob const*), 0x007509D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::FindRoute, zCRoute*(zCWayNet::*)(zVEC3 const&, zCWaypoint*, zCVob const*), 0x00750A60);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::FindRoute, zCRoute*(zCWayNet::*)(zVEC3 const&, zSTRING const&, zCVob const*), 0x00750AD0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::FindRoute, zCRoute*(zCWayNet::*)(zCWaypoint*, zCWaypoint*, zCVob const*), 0x00750B40);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::FindRoute, zCRoute*(zCWayNet::*)(zSTRING const&, zSTRING const&, zCVob const*), 0x00750B80);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::InsertInOpen, 0x00750C00);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::IsInOpen, 0x00750C30);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::InsertInClosed, 0x00750C50);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::RemoveFromClosed, 0x00750C70);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::IsInClosed, 0x00750C80);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::IsInAnyList, 0x00750CA0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::EstimateCost, 0x00750CD0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::CreateRoute, 0x00750D30);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::AStar, 0x00750DD0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::GetWPList, 0x00751050);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::CreateWPVobList, 0x007511B0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::RemoveUnusedWPVobs, 0x007511F0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::ArchiveOldFormat, 0x00751340);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::UnarchiveOldFormat, 0x00751BF0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::CalcProperties, 0x00752D20);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::_GetClassDef, 0x0074D1D0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::Archive, 0x007516D0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::Unarchive, 0x00752700);

	ZENGIN_REGISTER_CLASS(zCRoute);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::zCRoute_OnInit, 0x00752D60);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::SetStart, 0x00752DE0);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::GetNextWP, 0x00752DF0);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::GetTargetWP, 0x00752E60);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::GetCurrentWay, 0x00752E70);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::GetDesc, 0x00752E80);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::GetRemainingDesc, 0x00753060);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::GetNumberOfWaypoints, 0x00753240);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::IsEmpty, 0x00753260);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::IsLastTarget, 0x00753280);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::GetInterpolatedPosition, 0x007532A0);

	ZENGIN_REGISTER_CLASS(zCVobSpot);
	ZENGIN_REGISTER_METHOD(zCVobSpot, &zCVobSpot::zCVobSpot_OnInit, 0x007534A0);
	ZENGIN_REGISTER_METHOD(zCVobSpot, &zCVobSpot::IsAvailable, 0x00753520);
	ZENGIN_REGISTER_METHOD(zCVobSpot, &zCVobSpot::MarkAsUsed, 0x007536A0);
	ZENGIN_REGISTER_METHOD(zCVobSpot, &zCVobSpot::_GetClassDef, 0x007534C0);

	ZENGIN_REGISTER_CLASS(zCVobStartpoint);
	ZENGIN_REGISTER_METHOD(zCVobStartpoint, &zCVobStartpoint::_GetClassDef, 0x00753E40);

} // namespace Gothic_II_Classic
