namespace Gothic_II_Classic {

	ZENGIN_REGISTER_CLASS(zCPatch);
	ZENGIN_REGISTER_METHOD(zCPatch, &zCPatch::zCPatch_OnInit, 0x00624940);
	ZENGIN_REGISTER_METHOD(zCPatch, &zCPatch::DoTransfers, 0x00627880);

	ZENGIN_REGISTER_CLASS(zCPatchMap);
	ZENGIN_REGISTER_METHOD(zCPatchMap, &zCPatchMap::CheckRaySurfaceIntersection, 0x00624990);

	ZENGIN_REGISTER_CLASS(zCWorld);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::zCWorld_OnInit, 0x006182F0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GetActiveSkyControler, 0x00618C50);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SetSkyControlerIndoor, 0x00618C80);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SetSkyControlerOutdoor, 0x00618CC0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::AddZone, 0x00618D70);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveZone, 0x00618EE0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveAllZones, 0x00619020);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::UpdateZone, 0x00619090);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::ProcessZones, 0x006190A0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::ShowZonesDebugInfo, 0x00619710);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::ShowTextureStats, 0x00619B30);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::Render, 0x00619FB0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::TraceRayFirstHit, int(__fastcall zCWorld::*)(zVEC3 const&, zVEC3 const&, zCArray<zCVob*> const*, int), 0x0061A210);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::TraceRayNearestHit, int(__fastcall zCWorld::*)(zVEC3 const&, zVEC3 const&, zCArray<zCVob*> const*, int), 0x0061A410);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::TraceRayFirstHit, int(__fastcall zCWorld::*)(zVEC3 const&, zVEC3 const&, zCVob*, int), 0x0061A6E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::TraceRayNearestHit, int(__fastcall zCWorld::*)(zVEC3 const&, zVEC3 const&, zCVob*, int), 0x0061A810);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::TraceRayFirstHitCache, int(__fastcall zCWorld::*)(zVEC3 const&, zVEC3 const&, zCArray<zCVob*> const*, int, zCRayCache*), 0x0061A940);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::TraceRayFirstHitCache, int(__fastcall zCWorld::*)(zVEC3 const&, zVEC3 const&, zCVob*, int, zCRayCache*), 0x0061AAA0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::TraceRayNearestHitCache, int(__fastcall zCWorld::*)(zVEC3 const&, zVEC3 const&, zCArray<zCVob*> const*, int, zCRayCache*), 0x0061AC60);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::TraceRayNearestHitCache, int(__fastcall zCWorld::*)(zVEC3 const&, zVEC3 const&, zCVob*, int, zCRayCache*), 0x0061ADC0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::PickScene, 0x0061AF80);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::TraverseBsp, 0x0061B1F0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::TraverseBspAddVobsToMesh, 0x0061B2F0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SaveBspTreeMesh3DS, 0x0061B700);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::CompileWorld, 0x0061B730);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchZoneListByClass, 0x0061CC70);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchZoneDefaultByClass, 0x0061CDA0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::ShouldAddThisVobToBsp, 0x0061D020);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::AddVobAsChild_novt, 0x0061D060);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::AddVob, 0x0061D080);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveVob_novt, 0x0061D410);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveVobSubtree_r, 0x0061D430);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveVobSubtree_novt, 0x0061D600);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::MoveVobSubtreeTo_novt, 0x0061D6E0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::MoveVobSubtreeToWorldSpace, 0x0061D700);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveVobFromLists, 0x0061D720);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::PrintStatus, 0x0061D8F0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::PrintGlobalVobTree, 0x0061E350);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::PrintActiveVobs, 0x0061E610);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::UpdateVobTreeBspDependencies, 0x0061E850);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::MoveVobs, 0x0061E8C0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::AdvanceClock, 0x0061E950);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SaveBspTree, 0x0061E990);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::LoadBspTree, 0x0061EB10);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::DebugMarkOccluderPolys, 0x0061EC40);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::UnarcTraverseVobs, 0x0061EDE0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GetProgressBar, 0x0061F230);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::ArcTraverseVobs, 0x0061FD20);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::TraverseVobTree, 0x00620790);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::GetVobHashIndex, unsigned long(zCWorld::*)(zSTRING const&), 0x006207F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::GetVobHashIndex, unsigned long(zCWorld::*)(zCVob*), 0x00620820);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::InsertVobHashTable, 0x00620860);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveVobHashTable, 0x00620980);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchVobHashTable, 0x00620A10);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchVobListHashTable, 0x00620AF0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SetOwnerSession, 0x00620CB0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GetOwnerSession, 0x00620D00);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::ResetCutscenePlayer, 0x00620D10);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RegisterPerFrameCallback, 0x00620D60);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::UnregisterPerFrameCallback, 0x00620E90);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::LightWorldStaticUncompiled, 0x006223B0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::LightWorldStaticCompiled, 0x006227F0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GenerateStaticVertexLighting, 0x00622FE0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::LightingTestRay, 0x006232F0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GetSurfaceLightmapBBox2D, 0x006233B0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GetPhongNormal, 0x00623810);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GeneratePatchMapFromSurface, 0x00623BD0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GenerateLightmapFromPatchMap, 0x00624A30);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::LightPatchMap, 0x00625D40);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GenerateSurfaces, 0x006261F0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::MakeTransfers, 0x00627080);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GenerateLightmapsRadiosity, 0x006279D0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GenerateLightmaps, 0x00627C20);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GenerateStaticWorldLighting, 0x006283F0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::MakeVobLightingDirty, 0x006286E0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GetShowTextureStats, 0x0062FA10);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SetShowTextureStats, 0x0062FA20);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SetVobFarClipZScalability, 0x0062FA30);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GetBspTree, 0x006732A0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::_GetClassDef, 0x006188F0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::Archive, 0x00620110);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::Unarchive, 0x0061F240);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::LoadWorld, 0x0061F940);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SaveWorld, 0x00620430);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::MergeVobSubtree, 0x0061FC60);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SaveVobSubtree, 0x006206D0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::DisposeWorld, 0x0061C5A0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::DisposeVobs, 0x0061C1D0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::DisposeVobsDbg, 0x0061C360);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::DisposeStaticWorld, 0x0061C4F0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::AddVobAsChild, 0x0061CE10);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveVob, 0x0061D3E0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveVobSubtree, 0x0061D5D0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::MoveVobSubtreeTo, 0x0061D620);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GetPlayerGroup, 0x00618900);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchVob, 0x0061C780);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchVobByID, 0x0061C7D0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchVobByName, 0x0061C820);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchVobListByName, 0x0061C900);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchVobListByClass, 0x0061CAC0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchVobListByBaseClass, 0x0061CB90);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::VobAddedToWorld, 0x0061D0A0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::VobRemovedFromWorld, 0x0061D1E0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RenderWaynet, 0x00618D00);

} // namespace Gothic_II_Classic
