namespace Gothic_I_Addon {

	ZENGIN_REGISTER_CLASS(oCAISound);
	ZENGIN_REGISTER_METHOD(oCAISound, &oCAISound::RemoveSlideSound, 0x0063A7C0);
	ZENGIN_REGISTER_METHOD(oCAISound, &oCAISound::CheckSlideSound, 0x0063A7E0);
	ZENGIN_REGISTER_METHOD(oCAISound, &oCAISound::GetSoundMaterial, 0x0063A870);
	ZENGIN_REGISTER_METHOD(oCAISound, &oCAISound::StartCollisionSound, 0x0063A940);
	ZENGIN_REGISTER_METHOD(oCAISound, &oCAISound::_GetClassDef, 0x0063ABD0);

	ZENGIN_REGISTER_CLASS(oCAIArrowBase);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::oCAIArrowBase_OnInit, 0x0063B8E0);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::AddIgnoreCDVob, 0x0063BB40);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::ClearIgnoreCDVob, 0x0063BB60);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::CreateTrail, 0x0063BBD0);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::_GetClassDef, 0x0063B9C0);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::Archive, 0x0063C1E0);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::Unarchive, 0x0063C260);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::DoAI, 0x0063BE70);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::ReportCollisionToAI, 0x0063C160);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::HasAIDetectedCollision, 0x0063B9D0);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::AICollisionResponseSelfDetected, 0x0063B9E0);

	ZENGIN_REGISTER_CLASS(oCAIArrow);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::oCAIArrow_OnInit, 0x0063C330);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::SetTarget, 0x0063C520);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::ClearUsedVobs, 0x0063C560);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::SetupAIVob, 0x0063C620);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::_GetClassDef, 0x0063C3E0);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::Archive, 0x0063CDA0);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::Unarchive, 0x0063CE70);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::DoAI, 0x0063C9E0);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::CanThisCollideWith, 0x0063CA10);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::ReportCollisionToAI, 0x0063CAA0);

	ZENGIN_REGISTER_CLASS(oCAIDrop);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::oCAIDrop_OnInit, 0x0063CF90);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::AddIgnoreCDVob, 0x0063D230);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::ClearIgnoreCDVob, 0x0063D250);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::SetupAIVob, 0x0063D2C0);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::SetVelocity, 0x0063D620);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::SetStartPosition, 0x0063D710);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::_GetClassDef, 0x0063D070);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::Archive, 0x0063D890);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::Unarchive, 0x0063D8A0);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::DoAI, 0x0063D560);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::CanThisCollideWith, 0x0063D090);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::ReportCollisionToAI, 0x0063D5D0);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::HasAIDetectedCollision, 0x0063D080);

	ZENGIN_REGISTER_CLASS(oCAIVobMove);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::oCAIVobMove_OnInit, 0x0063A950);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::AddIgnoreCDVob, 0x0063B320);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::ClearIgnoreCDVob, 0x0063B340);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::_GetClassDef, 0x0063AA20);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::Archive, 0x0063B1C0);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::Unarchive, 0x0063B220);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::DoAI, 0x0063B000);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::CanThisCollideWith, 0x0063AA30);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::ReportCollisionToAI, 0x0063B170);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::Init, 0x0063AC80);

	ZENGIN_REGISTER_CLASS(oCAIVobMoveTorch);
	ZENGIN_REGISTER_METHOD(oCAIVobMoveTorch, &oCAIVobMoveTorch::oCAIVobMoveTorch_OnInit, 0x0063B3B0);
	ZENGIN_REGISTER_METHOD(oCAIVobMoveTorch, &oCAIVobMoveTorch::CheckWater, 0x0063B600);
	ZENGIN_REGISTER_METHOD(oCAIVobMoveTorch, &oCAIVobMoveTorch::BurnedOut, 0x0063B6E0);
	ZENGIN_REGISTER_METHOD(oCAIVobMoveTorch, &oCAIVobMoveTorch::_GetClassDef, 0x0063B440);
	ZENGIN_REGISTER_METHOD(oCAIVobMoveTorch, &oCAIVobMoveTorch::DoAI, 0x0063B5D0);
	ZENGIN_REGISTER_METHOD(oCAIVobMoveTorch, &oCAIVobMoveTorch::Init, 0x0063B5A0);

} // namespace Gothic_I_Addon
