namespace Gothic_I_Addon {

	ZENGIN_REGISTER_CLASS(oCItemContainer);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::oCItemContainer_OnInit, 0x00693B90);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetNextContainerLeft, 0x00693A70);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetNextContainerRight, 0x00693B00);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::JumpOffset, 0x00694710);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetCategoryText, 0x006947C0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::ActivateNextContainer, 0x006974E0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::HandleEvent, 0x00697960);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Open, 0x00695A10);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::OpenPassive, 0x00695BB0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Close, 0x00696770);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Activate, 0x00696AE0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Deactivate, 0x00696CF0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::IsOpen, 0x00696AC0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::IsActive, 0x00693D90);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::IsEmpty, 0x006972A0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::SetContents, 0x006959C0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetContents, 0x00695A00);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Insert, 0x00696DC0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCItemContainer, &oCItemContainer::Remove, void(oCItemContainer::*)(oCItem*), 0x00696E80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCItemContainer, &oCItemContainer::Remove, oCItem*(oCItemContainer::*)(oCItem*, int), 0x00696F30);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::RemoveByPtr, 0x00696F10);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetSelectedItem, 0x00696D20);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetSelectedItemCount, 0x00696D50);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetSize, 0x006946D0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::DisableManipulateItems, 0x00693DA0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::CanManipulateItems, 0x00693DB0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::DisableTransferMoreThanOneItem, 0x00693DC0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::CanTransferMoreThanOneItem, 0x00693DE0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::IsPassive, 0x00696760);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetTransferCount, 0x00693DF0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::SetTransferCount, 0x00693E00);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::IncTransferCount, 0x00693E10);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Archive, 0x006975F0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Unarchive, 0x00697790);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCItemContainer, &oCItemContainer::Init, void(oCItemContainer::*)(int, int), 0x00694550);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCItemContainer, &oCItemContainer::Init, void(oCItemContainer::*)(int, int, oCItemContainer::oTItemListMode), 0x00694570);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetPosition, 0x006946F0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::LoadGrafix, 0x00693FA0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::DeleteContents, 0x00696FF0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::NextItem, 0x00697100);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::PrevItem, 0x006971E0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::CheckSelectedItem, 0x006970C0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::TransferItem, 0x006972D0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::SetCategoryOnRightContainer, 0x00696B40);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Draw, 0x00695040);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::DrawCategory, 0x00694970);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::DrawItemInfo, 0x00694AD0);

	ZENGIN_REGISTER_CLASS(oCStealContainer);
	ZENGIN_REGISTER_METHOD(oCStealContainer, &oCStealContainer::oCStealContainer_OnInit, 0x00697DA0);
	ZENGIN_REGISTER_METHOD(oCStealContainer, &oCStealContainer::HandleEvent, 0x00698100);
	ZENGIN_REGISTER_METHOD(oCStealContainer, &oCStealContainer::SetOwner, 0x00697F70);
	ZENGIN_REGISTER_METHOD(oCStealContainer, &oCStealContainer::GetOwner, 0x00697F90);
	ZENGIN_REGISTER_METHOD(oCStealContainer, &oCStealContainer::CreateList, 0x00697FA0);

	ZENGIN_REGISTER_CLASS(oCNpcContainer);
	ZENGIN_REGISTER_METHOD(oCNpcContainer, &oCNpcContainer::oCNpcContainer_OnInit, 0x006983B0);
	ZENGIN_REGISTER_METHOD(oCNpcContainer, &oCNpcContainer::HandleEvent, 0x00698730);
	ZENGIN_REGISTER_METHOD(oCNpcContainer, &oCNpcContainer::Insert, 0x006989A0);
	ZENGIN_REGISTER_METHOD(oCNpcContainer, &oCNpcContainer::Remove, 0x006989E0);
	ZENGIN_REGISTER_METHOD(oCNpcContainer, &oCNpcContainer::CreateList, 0x00698570);

	ZENGIN_REGISTER_CLASS(oCNpcInventory);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::oCNpcInventory_OnInit, 0x00812FBB);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::ClearInventory, 0x00699370);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::Open, 0x00699500);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::SetOwner, 0x00699A20);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetOwner, 0x00699A30);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::SetFirstCategory, 0x00699A40);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetCategory, 0x00699BB0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetNumItemsInCategory, 0x00699C40);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetItem, 0x00699D70);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetAmount, 0x0069A240);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::IsCatEmpty, 0x0069AE60);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetNextCategory, 0x0069B640);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetPrevCategory, 0x0069B660);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::SwitchToCategory, 0x0069B670);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::SwitchNextCategory, 0x0069B710);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::SwitchPrevCategory, 0x0069B740);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::FindNextCategory, 0x0069B760);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::HandleTrade, 0x0069B970);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::CheckForEquippedItems, 0x0069CEA0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::CanCarry, 0x0069D000);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::SetPackAbility, 0x0069D200);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::UnpackCategory, 0x0069D240);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetNumItemsInPackString, 0x0069D270);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetPackedItemBySlot, 0x0069D370);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::CreateFromPackString, 0x0069D4D0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetPackedItemInfo, 0x0069D560);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::PackSingleItem, 0x0069D7F0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::PackAllItems, 0x0069DBE0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::UnpackAllItems, 0x0069DC00);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::PackItemsInCategory, 0x0069DC20);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::UnpackItemsInCategory, 0x0069DF90);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::HandleEvent, 0x0069BBC0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::Close, 0x00699960);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::Insert, 0x00699F50);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::Remove, oCItem*(oCNpcInventory::*)(int, int), 0x0069ABA0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::Remove, oCItem*(oCNpcInventory::*)(zSTRING const&, int), 0x0069ACB0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::RemoveByPtr, 0x0069A680);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::Archive, 0x0069AFB0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::Unarchive, 0x0069B2D0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::Draw, 0x00699970);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::DrawCategory, 0x0069B770);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::Remove, void(oCNpcInventory::*)(oCItem*), 0x0069A580);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::Remove, oCItem*(oCNpcInventory::*)(oCItem*, int), 0x0069A8D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::IsIn, oCItem*(oCNpcInventory::*)(oCItem*, int), 0x0069A370);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::IsIn, oCItem*(oCNpcInventory::*)(int, int), 0x0069A460);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::IsIn, oCItem*(oCNpcInventory::*)(zSTRING const&, int), 0x0069A430);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::IsEmpty, int(oCNpcInventory::*)(), 0x006972A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::IsEmpty, int(oCNpcInventory::*)(int), 0x0069ACE0);

} // namespace Gothic_I_Addon
