namespace Gothic_I_Addon {

	ZENGIN_REGISTER_CLASS(oCMOB);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::oCMOB_OnInit, 0x006A8D90);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::SetMoveable, 0x006A9430);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::IsMoveable, 0x006A9460);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCMOB, &oCMOB::SetOwner, void(oCMOB::*)(zSTRING const&, zSTRING const&), 0x006A94D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCMOB, &oCMOB::SetOwner, void(oCMOB::*)(int, int), 0x006A96C0);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::IsOwner, 0x006A9720);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::Hit, 0x006A9770);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::InsertInIgnoreList, 0x006A9A20);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::RemoveFromIgnoreList, 0x006A9A50);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::_GetClassDef, 0x006A8EC0);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::Archive, 0x006A9B00);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::Unarchive, 0x006A9C40);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::OnDamage, 0x006A93F0);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::OnMessage, 0x006A9400);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::CanThisCollideWith, 0x006A9AC0);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::SetVisual, 0x006A90A0);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::IsOwnedByGuild, 0x006A96E0);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::IsOwnedByNpc, 0x006A9700);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::GetSoundMaterial_AM, 0x006A94B0);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::SetSoundMaterial, 0x006A9470);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::GetSoundMaterial, 0x006A94A0);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::SetName, 0x006A90C0);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::GetName, 0x006A90E0);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::GetModel, 0x006A9410);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::GetScemeName, 0x006A91E0);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::Destroy, 0x006A9780);
	ZENGIN_REGISTER_METHOD(oCMOB, &oCMOB::AllowDiscardingOfSubtree, 0x006AA2D0);

	ZENGIN_REGISTER_CLASS(oCMobInter);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::oCMobInter_OnInit, 0x006AA630);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::SetTempState, 0x006AABB0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::IsTempStateChanged, 0x006AABF0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::SetStateToTempState, 0x006AAC00);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::SetMobBodyState, 0x006AAC90);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::HasUseWithItem, 0x006AB1C0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::ScanIdealPositions, 0x006AB290);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::GetFreePosition, 0x006AB640);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::SetHeading, 0x006AB990);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::SetIdealPosition, 0x006AB9E0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::SendStateChange, 0x006AC5B0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::SendEndInteraction, 0x006AC8C0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::StartTransitionAniNpc, 0x006AD920);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::IsMultiMob, 0x006AE690);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::IsAvailable, 0x006AE6B0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::MarkAsUsed, 0x006AE710);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::_GetClassDef, 0x006AA7B0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::Archive, 0x006AFC20);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::Unarchive, 0x006AFCC0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::OnTrigger, 0x006ABF70);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::OnUntrigger, 0x006AC2A0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::OnDamage, 0x006AAFA0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::OnMessage, 0x006AAFB0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::OnTick, 0x006ABEE0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::SetVisual, 0x006AAA10);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::GetTriggerTarget, 0x006A6060);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::GetScemeName, 0x006AB240);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::GetState, 0x006A5FF0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::GetStateNum, 0x006A6000);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::GetDirection, 0x006A6010);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::SetDirection, 0x006A6020);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::SetUseWithItem, 0x006AB060);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::GetUseWithItem, 0x006AB1A0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::Reset, 0x006ABC70);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::Interact, 0x006ACA60);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::EndInteraction, 0x006AF1D0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::InterruptInteraction, 0x006AE470);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::StopInteraction, 0x006AF4B0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::CanInteractWith, 0x006AE730);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::IsInteractingWith, 0x006AEDB0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::IsOccupied, 0x006A6030);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::AI_UseMobToState, 0x006AF7D0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::IsIn, 0x006A6050);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::IsInState, 0x006AD2F0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::StartInteraction, 0x006AEDE0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::StartStateChange, 0x006AD670);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::CheckStateChange, 0x006ADC50);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::CanChangeState, 0x006AD420);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::GetTransitionNames, 0x006ACDE0);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::OnBeginStateChange, 0x006AE400);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::OnEndStateChange, 0x006AE410);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::CallOnStateFunc, 0x006AE040);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::SendCallOnStateFunc, 0x006AE250);
	ZENGIN_REGISTER_METHOD(oCMobInter, &oCMobInter::SearchFreePosition, 0x006AB6C0);

	ZENGIN_REGISTER_CLASS(oCMobBed);
	ZENGIN_REGISTER_METHOD(oCMobBed, &oCMobBed::oCMobBed_OnInit, 0x006B07B0);
	ZENGIN_REGISTER_METHOD(oCMobBed, &oCMobBed::_GetClassDef, 0x006A60A0);
	ZENGIN_REGISTER_METHOD(oCMobBed, &oCMobBed::GetScemeName, 0x006B0C40);
	ZENGIN_REGISTER_METHOD(oCMobBed, &oCMobBed::StartInteraction, 0x006B0BC0);
	ZENGIN_REGISTER_METHOD(oCMobBed, &oCMobBed::OnBeginStateChange, 0x006B0BD0);
	ZENGIN_REGISTER_METHOD(oCMobBed, &oCMobBed::OnEndStateChange, 0x006B0BE0);
	ZENGIN_REGISTER_METHOD(oCMobBed, &oCMobBed::SearchFreePosition, 0x006B0CF0);

	ZENGIN_REGISTER_CLASS(oCMobSwitch);
	ZENGIN_REGISTER_METHOD(oCMobSwitch, &oCMobSwitch::oCMobSwitch_OnInit, 0x006B0E80);
	ZENGIN_REGISTER_METHOD(oCMobSwitch, &oCMobSwitch::_GetClassDef, 0x006A6400);
	ZENGIN_REGISTER_METHOD(oCMobSwitch, &oCMobSwitch::Archive, 0x006B11B0);
	ZENGIN_REGISTER_METHOD(oCMobSwitch, &oCMobSwitch::Unarchive, 0x006B1250);

	ZENGIN_REGISTER_CLASS(oCMobItemSlot);
	ZENGIN_REGISTER_METHOD(oCMobItemSlot, &oCMobItemSlot::oCMobItemSlot_OnInit, 0x006B5B00);
	ZENGIN_REGISTER_METHOD(oCMobItemSlot, &oCMobItemSlot::_GetClassDef, 0x006A7FA0);
	ZENGIN_REGISTER_METHOD(oCMobItemSlot, &oCMobItemSlot::Archive, 0x006B6140);
	ZENGIN_REGISTER_METHOD(oCMobItemSlot, &oCMobItemSlot::Unarchive, 0x006B6210);
	ZENGIN_REGISTER_METHOD(oCMobItemSlot, &oCMobItemSlot::GetUseWithItem, 0x006B5D60);
	ZENGIN_REGISTER_METHOD(oCMobItemSlot, &oCMobItemSlot::CanInteractWith, 0x006B5DA0);
	ZENGIN_REGISTER_METHOD(oCMobItemSlot, &oCMobItemSlot::IsIn, 0x006B6110);
	ZENGIN_REGISTER_METHOD(oCMobItemSlot, &oCMobItemSlot::GetInsertedItem, 0x006B5DC0);
	ZENGIN_REGISTER_METHOD(oCMobItemSlot, &oCMobItemSlot::PlaceItem, 0x006B5DD0);
	ZENGIN_REGISTER_METHOD(oCMobItemSlot, &oCMobItemSlot::RemoveItem, 0x006B60D0);

	ZENGIN_REGISTER_CLASS(oCMobLockable);
	ZENGIN_REGISTER_METHOD(oCMobLockable, &oCMobLockable::oCMobLockable_OnInit, 0x006B1300);
	ZENGIN_REGISTER_METHOD(oCMobLockable, &oCMobLockable::CanOpen, 0x006B1F20);
	ZENGIN_REGISTER_METHOD(oCMobLockable, &oCMobLockable::_GetClassDef, 0x006A6A00);
	ZENGIN_REGISTER_METHOD(oCMobLockable, &oCMobLockable::Archive, 0x006B2FE0);
	ZENGIN_REGISTER_METHOD(oCMobLockable, &oCMobLockable::Unarchive, 0x006B30D0);
	ZENGIN_REGISTER_METHOD(oCMobLockable, &oCMobLockable::OnMessage, 0x006A6CB0);
	ZENGIN_REGISTER_METHOD(oCMobLockable, &oCMobLockable::Interact, 0x006B16F0);
	ZENGIN_REGISTER_METHOD(oCMobLockable, &oCMobLockable::CanInteractWith, 0x006B16C0);
	ZENGIN_REGISTER_METHOD(oCMobLockable, &oCMobLockable::CanChangeState, 0x006B1D00);
	ZENGIN_REGISTER_METHOD(oCMobLockable, &oCMobLockable::OnEndStateChange, 0x006B1D50);
	ZENGIN_REGISTER_METHOD(oCMobLockable, &oCMobLockable::SetLocked, 0x006A6A10);
	ZENGIN_REGISTER_METHOD(oCMobLockable, &oCMobLockable::SetKeyInstance, 0x006A6A30);
	ZENGIN_REGISTER_METHOD(oCMobLockable, &oCMobLockable::SetPickLockStr, 0x006A6B70);
	ZENGIN_REGISTER_METHOD(oCMobLockable, &oCMobLockable::Lock, 0x006B2DB0);
	ZENGIN_REGISTER_METHOD(oCMobLockable, &oCMobLockable::Unlock, 0x006B25E0);
	ZENGIN_REGISTER_METHOD(oCMobLockable, &oCMobLockable::PickLock, 0x006B2260);

	ZENGIN_REGISTER_CLASS(oCMobContainer);
	ZENGIN_REGISTER_METHOD(oCMobContainer, &oCMobContainer::oCMobContainer_OnInit, 0x006B31E0);
	ZENGIN_REGISTER_METHOD(oCMobContainer, &oCMobContainer::_GetClassDef, 0x006A6D80);
	ZENGIN_REGISTER_METHOD(oCMobContainer, &oCMobContainer::Archive, 0x006B40C0);
	ZENGIN_REGISTER_METHOD(oCMobContainer, &oCMobContainer::Unarchive, 0x006B4260);
	ZENGIN_REGISTER_METHOD(oCMobContainer, &oCMobContainer::OnMessage, 0x006B35E0);
	ZENGIN_REGISTER_METHOD(oCMobContainer, &oCMobContainer::Destroy, 0x006B36E0);
	ZENGIN_REGISTER_METHOD(oCMobContainer, &oCMobContainer::Reset, 0x006B38A0);
	ZENGIN_REGISTER_METHOD(oCMobContainer, &oCMobContainer::IsIn, 0x006B3F60);
	ZENGIN_REGISTER_METHOD(oCMobContainer, &oCMobContainer::Open, 0x006B3FA0);
	ZENGIN_REGISTER_METHOD(oCMobContainer, &oCMobContainer::Close, 0x006B4080);
	ZENGIN_REGISTER_METHOD(oCMobContainer, &oCMobContainer::Insert, 0x006B3A00);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCMobContainer, &oCMobContainer::Remove, void(oCMobContainer::*)(oCItem*), 0x006B3A30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCMobContainer, &oCMobContainer::Remove, oCItem*(oCMobContainer::*)(oCItem*, int), 0x006B3AB0);
	ZENGIN_REGISTER_METHOD(oCMobContainer, &oCMobContainer::CreateContents, 0x006B3BC0);

	ZENGIN_REGISTER_CLASS(oCMobDoor);
	ZENGIN_REGISTER_METHOD(oCMobDoor, &oCMobDoor::oCMobDoor_OnInit, 0x006B44E0);
	ZENGIN_REGISTER_METHOD(oCMobDoor, &oCMobDoor::_GetClassDef, 0x006A7880);
	ZENGIN_REGISTER_METHOD(oCMobDoor, &oCMobDoor::GetScemeName, 0x006B48B0);
	ZENGIN_REGISTER_METHOD(oCMobDoor, &oCMobDoor::SearchFreePosition, 0x006B4960);
	ZENGIN_REGISTER_METHOD(oCMobDoor, &oCMobDoor::Open, 0x006A7890);
	ZENGIN_REGISTER_METHOD(oCMobDoor, &oCMobDoor::Close, 0x006A78A0);

	ZENGIN_REGISTER_CLASS(oCMobFire);
	ZENGIN_REGISTER_METHOD(oCMobFire, &oCMobFire::oCMobFire_OnInit, 0x006AFD70);
	ZENGIN_REGISTER_METHOD(oCMobFire, &oCMobFire::DeleteEffects, 0x006B0180);
	ZENGIN_REGISTER_METHOD(oCMobFire, &oCMobFire::_GetClassDef, 0x006A7CD0);
	ZENGIN_REGISTER_METHOD(oCMobFire, &oCMobFire::Archive, 0x006B05C0);
	ZENGIN_REGISTER_METHOD(oCMobFire, &oCMobFire::Unarchive, 0x006B06D0);
	ZENGIN_REGISTER_METHOD(oCMobFire, &oCMobFire::OnTrigger, 0x006B02B0);
	ZENGIN_REGISTER_METHOD(oCMobFire, &oCMobFire::OnUntrigger, 0x006B04F0);
	ZENGIN_REGISTER_METHOD(oCMobFire, &oCMobFire::OnDamage, 0x006B01D0);
	ZENGIN_REGISTER_METHOD(oCMobFire, &oCMobFire::OnEndStateChange, 0x006B0220);
	ZENGIN_REGISTER_METHOD(oCMobFire, &oCMobFire::PreSave, 0x006B0560);
	ZENGIN_REGISTER_METHOD(oCMobFire, &oCMobFire::PostSave, 0x006B06A0);

	ZENGIN_REGISTER_CLASS(oCMobWheel);
	ZENGIN_REGISTER_METHOD(oCMobWheel, &oCMobWheel::oCMobWheel_OnInit, 0x006B4AF0);
	ZENGIN_REGISTER_METHOD(oCMobWheel, &oCMobWheel::_GetClassDef, 0x006A70F0);
	ZENGIN_REGISTER_METHOD(oCMobWheel, &oCMobWheel::OnTrigger, 0x006B4C20);
	ZENGIN_REGISTER_METHOD(oCMobWheel, &oCMobWheel::OnUntrigger, 0x006B4D40);
	ZENGIN_REGISTER_METHOD(oCMobWheel, &oCMobWheel::Interact, 0x006B4E50);

	ZENGIN_REGISTER_CLASS(oCMobLadder);
	ZENGIN_REGISTER_METHOD(oCMobLadder, &oCMobLadder::oCMobLadder_OnInit, 0x006B5090);
	ZENGIN_REGISTER_METHOD(oCMobLadder, &oCMobLadder::_GetClassDef, 0x006A7470);
	ZENGIN_REGISTER_METHOD(oCMobLadder, &oCMobLadder::DoFocusCheckBBox, 0x006A7480);
	ZENGIN_REGISTER_METHOD(oCMobLadder, &oCMobLadder::Interact, 0x006B5690);
	ZENGIN_REGISTER_METHOD(oCMobLadder, &oCMobLadder::EndInteraction, 0x006B5AE0);
	ZENGIN_REGISTER_METHOD(oCMobLadder, &oCMobLadder::CanInteractWith, 0x006B5610);
	ZENGIN_REGISTER_METHOD(oCMobLadder, &oCMobLadder::StartInteraction, 0x006B53E0);
	ZENGIN_REGISTER_METHOD(oCMobLadder, &oCMobLadder::CanChangeState, 0x006B55C0);
	ZENGIN_REGISTER_METHOD(oCMobLadder, &oCMobLadder::SearchFreePosition, 0x006B5620);

	ZENGIN_REGISTER_CLASS(oCDummyVobGenerator);
	ZENGIN_REGISTER_METHOD(oCDummyVobGenerator, &oCDummyVobGenerator::oCDummyVobGenerator_OnInit, 0x006B6300);
	ZENGIN_REGISTER_METHOD(oCDummyVobGenerator, &oCDummyVobGenerator::_GetClassDef, 0x006A8290);
	ZENGIN_REGISTER_METHOD(oCDummyVobGenerator, &oCDummyVobGenerator::OnTrigger, 0x006B6370);

	ZENGIN_REGISTER_CLASS(oCMobMsg);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCMobMsg, &oCMobMsg::oCMobMsg_OnInit, void(oCMobMsg::*)(oCMobMsg::TMobMsgSubType, oCNpc*), 0x006A86B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCMobMsg, &oCMobMsg::oCMobMsg_OnInit, void(oCMobMsg::*)(), 0x006A8830);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCMobMsg, &oCMobMsg::oCMobMsg_OnInit, void(oCMobMsg::*)(oCMobMsg::TMobMsgSubType, oCNpc*, int), 0x006A8970);
	ZENGIN_REGISTER_METHOD(oCMobMsg, &oCMobMsg::_GetClassDef, 0x006A8690);
	ZENGIN_REGISTER_METHOD(oCMobMsg, &oCMobMsg::IsNetRelevant, 0x006A86A0);
	ZENGIN_REGISTER_METHOD(oCMobMsg, &oCMobMsg::MD_GetNumOfSubTypes, 0x006A8BE0);
	ZENGIN_REGISTER_METHOD(oCMobMsg, &oCMobMsg::MD_GetSubTypeString, 0x006A8BF0);
	ZENGIN_REGISTER_METHOD(oCMobMsg, &oCMobMsg::Pack, 0x006A8AC0);
	ZENGIN_REGISTER_METHOD(oCMobMsg, &oCMobMsg::Unpack, 0x006A8B40);

} // namespace Gothic_I_Addon
