namespace Gothic_I_Addon {

	ZENGIN_REGISTER_CLASS(oCSVMManager);
	ZENGIN_REGISTER_METHOD(oCSVMManager, &oCSVMManager::oCSVMManager_OnInit, 0x00707DF0);
	ZENGIN_REGISTER_METHOD(oCSVMManager, &oCSVMManager::GetOU, 0x00708100);

	ZENGIN_REGISTER_CLASS(oCSVM);
	ZENGIN_REGISTER_METHOD(oCSVM, &oCSVM::oCSVM_OnInit, 0x00708500);
	ZENGIN_REGISTER_METHOD(oCSVM, &oCSVM::InitByScript, 0x00708530);
	ZENGIN_REGISTER_METHOD(oCSVM, &oCSVM::GetOU, 0x00708800);

} // namespace Gothic_I_Addon
