namespace Gothic_I_Addon {

	ZENGIN_REGISTER_CLASS(oCTrajectory);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::Calc, 0x0048AE10);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::Changed, 0x0048B180);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::Interpolate, 0x0048B190);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::InterpolateN, 0x0048B600);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::Draw, 0x0048B710);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::Clear, 0x0048B990);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::RecalcByColl, 0x0048BA50);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::ApplyGrav, 0x0048BF00);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::SetByList, 0x0048BF80);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::VobCross, 0x0048C120);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::InsertKey, 0x004942C0);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::GetKey, 0x004943F0);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::SetKey, 0x004944E0);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::GetNumKeys, 0x00494510);

	ZENGIN_REGISTER_CLASS(oCEmitterKey);
	ZENGIN_REGISTER_METHOD(oCEmitterKey, &oCEmitterKey::oCEmitterKey_OnInit, 0x0048C1C0);
	ZENGIN_REGISTER_METHOD(oCEmitterKey, &oCEmitterKey::SetByScript, 0x0048C770);
	ZENGIN_REGISTER_METHOD(oCEmitterKey, &oCEmitterKey::ParseStrings, 0x0048C9B0);
	ZENGIN_REGISTER_METHOD(oCEmitterKey, &oCEmitterKey::Edit, 0x0049CD50);
	ZENGIN_REGISTER_METHOD(oCEmitterKey, &oCEmitterKey::SetDefaultByFX, 0x004A09C0);

	ZENGIN_REGISTER_CLASS(oCVisualFX);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::oCVisualFX_OnInit, 0x0048D120);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::CreateHierachy, 0x0048E490);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::DisposeHierachy, 0x0048E760);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::InitValues, 0x0048ECB0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::ParseStrings, 0x0048F320);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::UpdateFXByEmitterKey, 0x00491380);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::CreateBackup, 0x00491BD0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::FindKey, 0x00491BE0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCVisualFX, &oCVisualFX::CreateAndCastFX, oCVisualFX*(oCVisualFX::*)(zSTRING const&, zCVob const*, zCVob const*), 0x00492530);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCVisualFX, &oCVisualFX::CreateAndCastFX, oCVisualFX*(oCVisualFX::*)(zSTRING const&, zMAT4 const&), 0x00492890);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::CreateInvestFX, 0x00494BF0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::InitInvestFX, 0x00494DB0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::StopInvestFX, 0x00494F10);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetShowVisual, 0x00497260);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::InitEffect, 0x00497B80);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::EndEffect, 0x00498050);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::ProcessQueuedCollisions, 0x00498AA0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::ProcessCollision, 0x00498B50);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::CheckDeletion, 0x00499CC0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::UpdateActKey, 0x0049A110);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::DoMovements, 0x0049A390);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::CheckDelayedTrigger, 0x0049AEE0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::AdjustShapeToOrigin, 0x0049B170);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::UpdateEffects, 0x0049B630);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::Edit, 0x0049C480);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetupEmitterKeysByVisual, 0x004A0E40);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetName, 0x0077F620);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::_GetClassDef, 0x0048D640);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::Archive, 0x0049BAA0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::Unarchive, 0x0049BAB0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::OnTick, 0x0049B9C0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::CanThisCollideWith, 0x00499A80);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::Open, 0x00494FC0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetOrigin, 0x00494950);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCVisualFX, &oCVisualFX::SetTarget, void(oCVisualFX::*)(zCVob*), 0x00494A20);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCVisualFX, &oCVisualFX::SetTarget, void(oCVisualFX::*)(zVEC3&), 0x00494B80);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetInflictor, 0x004949C0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetOrigin, 0x0048D650);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetTarget, 0x0048D660);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetInflictor, 0x0048D670);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCVisualFX, &oCVisualFX::Init, void(oCVisualFX::*)(zCVob const*, zVEC3 const&), 0x00495520);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCVisualFX, &oCVisualFX::Init, void(oCVisualFX::*)(zCVob const*, zCVob const*, zCVob const*), 0x00495640);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCVisualFX, &oCVisualFX::Init, void(oCVisualFX::*)(zCArray<zCVob*> const&), 0x00495DA0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::InvestNext, 0x00495F30);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetLevel, 0x00496310);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetLevel, 0x00496710);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::Cast, 0x00496720);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::Stop, 0x004973B0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::Kill, 0x004977A0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::Play, 0x0048D680);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::CanBeDeleted, 0x00497A40);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::IsFinished, 0x00497A80);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::IsLooping, 0x00497B10);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetByScript, 0x00490910);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetDuration, 0x0048D690);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::Reset, 0x00495330);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::ReportCollision, 0x004980A0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetCollisionEnabled, 0x004907F0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetCollisionCandidates, 0x004998A0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetCollisionCandidates, 0x0048D6A0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetNumCollisionCandidates, 0x0048D750);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetCollidedCandidates, 0x004999B0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetDamage, 0x0048D760);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetDamageType, 0x0048D770);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetDamage, 0x0048D780);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetDamageType, 0x0048D790);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::IsASpell, 0x0048D7A0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetSpellType, 0x0048D7B0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetSpellType, 0x0048D7C0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetSpellTargetTypes, 0x0048D7D0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetSpellTargetTypes, 0x0048D7E0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetIsProjectile, 0x0048D7F0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetIsProjectile, 0x0048D800);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetVisualByString, 0x0048F6A0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::CalcTrajectory, 0x00492CF0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::Collide, 0x00496FC0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::CollisionResponse, 0x00499300);

	ZENGIN_REGISTER_CLASS(oCVisualFXAI);
	ZENGIN_REGISTER_METHOD(oCVisualFXAI, &oCVisualFXAI::DoAI, 0x0049BAC0);
	ZENGIN_REGISTER_METHOD(oCVisualFXAI, &oCVisualFXAI::ReportCollisionToAI, 0x0048F250);
	ZENGIN_REGISTER_METHOD(oCVisualFXAI, &oCVisualFXAI::HostVobAddedToWorld, 0x0048F270);

} // namespace Gothic_I_Addon
