namespace Gothic_I_Addon {

	ZENGIN_REGISTER_CLASS(zTEngineStats);
	ZENGIN_REGISTER_METHOD(zTEngineStats, &zTEngineStats::PrintScreen, 0x0050E510);

	ZENGIN_REGISTER_CLASS(zCLineCache);
	ZENGIN_REGISTER_METHOD(zCLineCache, &zCLineCache::Line, 0x0050EA20);
	ZENGIN_REGISTER_METHOD(zCLineCache, &zCLineCache::Flush, 0x0050EAC0);
	ZENGIN_REGISTER_METHOD(zCLineCache, &zCLineCache::Line3D, 0x0050EB50);
	ZENGIN_REGISTER_METHOD(zCLineCache, &zCLineCache::LineCS3D, 0x0050EF00);

	ZENGIN_REGISTER_CLASS(zCCamera);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::zCCamera_OnInit, 0x0054CDB0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::Project, void(zCCamera::*)(zVEC3 const* const, float&, float&) const, 0x00533550);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::PushTransform, 0x0054D110);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::PopTransform, 0x0054D1A0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::SetTransform, 0x0054D2E0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::GetTransform, 0x0054D440);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::Activate, 0x0054D4A0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::CreateProjectionMatrix, 0x0054D5B0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::UpdateProjectionMatrix, 0x0054D630);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::GetFOV, float(zCCamera::*)() const, 0x0054D680);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::GetFOV, void(zCCamera::*)(float&, float&) const, 0x0054D690);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::SetFOV, void(zCCamera::*)(float), 0x0054D6C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::SetFOV, void(zCCamera::*)(float, float), 0x0054D700);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::UpdateViewport, 0x0054D830);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::SetRenderTarget, 0x0054D970);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::SetUpFrustum, 0x0054D990);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::SetNearClipZ, 0x0054DC90);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::SetFarClipZ, 0x0054DD00);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::BBox3DInFrustum, zTCam_ClipType(zCCamera::*)(zTBBox3D const&), 0x0054DE40);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::BBox3DInFrustum, zTCam_ClipType(zCCamera::*)(zTBBox3D const&, int&), 0x0054DEA0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::StopTremor, 0x0054E140);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::AddTremor, 0x0054E150);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::PreRenderProcessing, 0x0054E370);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::PostRenderProcessing, 0x0054E520);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::GetCamPos, 0x0054E560);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::InitDrawPolySimple, 0x0054E590);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::CleanupDrawPolySimple, 0x0054E660);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::DrawPolySimple, 0x0054E6C0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::SetRenderScreenFade, 0x0054E7D0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::SetRenderCinemaScope, 0x0054E7F0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::RenderScreenFade, 0x0054E810);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::RenderCinemaScope, 0x0054E8E0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::ScreenProjectionTouchesPortalRough, 0x0054EA40);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::ScreenProjectionTouchesPortal, 0x0054ED10);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::Project, void(zCCamera::*)(zVEC3 const* const, int&, int&), 0x00578B50);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::BackProject, 0x00658690);

	ZENGIN_REGISTER_CLASS(zCVertex);
	ZENGIN_REGISTER_METHOD(zCVertex, &zCVertex::zCVertex_OnInit, 0x00570850);
	ZENGIN_REGISTER_METHOD(zCVertex, &zCVertex::Draw, 0x0050F170);
	ZENGIN_REGISTER_METHOD(zCVertex, &zCVertex::CreateVertexTransform, 0x0050F290);
	ZENGIN_REGISTER_METHOD(zCVertex, &zCVertex::ResetVertexTransform, 0x005BF270);

	ZENGIN_REGISTER_CLASS(zCVertFeature);
	ZENGIN_REGISTER_METHOD(zCVertFeature, &zCVertFeature::zCVertFeature_OnInit, 0x0056DDC0);

	ZENGIN_REGISTER_CLASS(zCPolygon);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::zCPolygon_OnInit, 0x005B19F0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::RenderPoly, 0x0052EB30);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TransformProjectLight, 0x0052EFA0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::SetMaterial, 0x0053A0A0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::ClipToPlane, 0x005B1B00);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::Unclip, 0x005B2080);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CopyClipFeaturesForTexAniMapping, 0x005B2100);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::ClipToFrustum, 0x005B2170);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::ClassifyPlane, 0x005B23B0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::ClassifyPlaneBSPBuild, 0x005B2440);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CalcNormal, 0x005B24D0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::GetScreenBBox2D, 0x005B28D0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::DrawWire, 0x005B2970);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::LightDynCamSpace, 0x005B31B0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::LightClippedPoly, 0x005B3370);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::GetLightStatAtPos, 0x005B3950);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CheckRayPolyIntersection, 0x005B40A0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CheckRayPolyIntersection2Sided, 0x005B4460);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CalcNormalMainAxis, 0x005B47E0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::GetBBox3D, 0x005B4840);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::GetCenter, 0x005B48F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPolygon, &zCPolygon::SetMapping, void(zCPolygon::*)(zVEC2 const&, zVEC2 const&, zVEC2 const&), 0x005B4980);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPolygon, &zCPolygon::SetMapping, void(zCPolygon::*)(int, zVEC2 const&), 0x005B49D0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::Flip, 0x005B49F0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::VertPartOfPoly, 0x005B4A30);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::EdgePartOfPoly, 0x005B4A60);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TexTranslate, 0x005B4AB0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TexSetTranslation, 0x005B4AF0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPolygon, &zCPolygon::TexScale, void(zCPolygon::*)(float, float), 0x005B4B30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPolygon, &zCPolygon::TexScale, void(zCPolygon::*)(zVEC2&, float, float), 0x005B4B70);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TexRotate, 0x005B4C30);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TexMirrorU, 0x005B4E10);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TexMirrorV, 0x005B4E40);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TexShearU, 0x005B4E70);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TexShearV, 0x005B4F30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPolygon, &zCPolygon::TexApplyPlanarMapping, void(zCPolygon::*)(zVEC3 const&, zVEC3 const&, zVEC3 const&, int), 0x005B4FF0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPolygon, &zCPolygon::TexApplyPlanarMapping, void(zCPolygon::*)(float, float, int), 0x005B51C0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TexCorrectUV, 0x005B5840);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::AllocVerts, 0x005B59A0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::AddVertex, 0x005B5B30);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::AddVertexAndFeature, 0x005B5B50);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPolygon, &zCPolygon::SetVertices, void(zCPolygon::*)(zCVertex*, zCVertex*, zCVertex*), 0x005B5B90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPolygon, &zCPolygon::SetVertices, void(zCPolygon::*)(zCVertex*, zCVertex*, zCVertex*, zCVertex*, int), 0x005B5BF0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::SetVertex, 0x005B5C60);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::SetFeature, 0x005B5CA0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CopyValuesInto, 0x005B5CE0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CopyPolyInto, 0x005B5DA0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::RemoveVerticesAndFeatures, 0x005B5E00);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::GetArea, 0x005B5E90);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::GetLongestEdgeLen, 0x005B5F30);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::ResetStaticLight, 0x005B5FB0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::SetStaticLight, 0x005B5FF0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::SetLightDyn, 0x005B6020);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::SetLightStatAlpha, 0x005B6050);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::ResetLightDynToLightStat, 0x005B6080);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::AddToLightDyn, 0x005B60B0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CheckBBoxPolyIntersection, 0x005B6150);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CheckBSpherePolyIntersection, 0x005B6630);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::SplitPoly, 0x005B6800);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::IsIntersectingProjection, 0x005B6DC0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::IsIntersecting, 0x005B75F0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::LightStatic, 0x0061BD10);

	ZENGIN_REGISTER_CLASS(zCPortal);
	ZENGIN_REGISTER_METHOD(zCPortal, &zCPortal::zCPortal_OnInit, 0x0052DFE0);
	ZENGIN_REGISTER_METHOD(zCPortal, &zCPortal::RemoveFromBsp, 0x0052DFC0);
	ZENGIN_REGISTER_METHOD(zCPortal, &zCPortal::Init, 0x005419B0);

} // namespace Gothic_I_Addon
