namespace Gothic_I_Addon {

	ZENGIN_REGISTER_CLASS(zCArchiverBinSafe);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::zCArchiverBinSafe_OnInit, 0x00520B00);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::RestoreString, 0x00520170);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteType, 0x00520180);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ReadType, 0x005201F0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ClearChunkList, 0x00520820);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::InsertChunkInList, 0x00520980);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ResolveAndPosEntry, 0x00520A10);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::DebugMessage, 0x00521020);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::CheckObjectListSize, 0x00523B30);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::_GetClassDef, 0x00520C80);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteInt, 0x00521CC0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteByte, 0x00521DB0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteWord, 0x00521EA0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteFloat, 0x00521F90);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteBool, 0x00522080);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteString, 0x00522170);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteVec3, 0x005222B0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteColor, 0x00522550);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteRaw, 0x00522640);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteRawFloat, 0x00522730);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteEnum, 0x00522930);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::WriteObject, void(__fastcall zCArchiverBinSafe::*)(zCObject*), 0x005234F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::WriteObject, void(__fastcall zCArchiverBinSafe::*)(char const*, zCObject*), 0x00523460);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::WriteObject, void(__fastcall zCArchiverBinSafe::*)(char const*, zCObject&), 0x00523250);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::WriteChunkStart, void(__fastcall zCArchiverBinSafe::*)(char const*, unsigned short), 0x00522FB0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::WriteChunkStart, void(__fastcall zCArchiverBinSafe::*)(char const*, char const*, unsigned short, unsigned long), 0x00522B60);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteChunkEnd, 0x00522FD0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteGroupBegin, 0x00522B40);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteGroupEnd, 0x00522B50);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadInt, void(__fastcall zCArchiverBinSafe::*)(char const*, int&), 0x00525AB0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadInt, int(__fastcall zCArchiverBinSafe::*)(char const*), 0x00525850);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadByte, void(__fastcall zCArchiverBinSafe::*)(char const*, unsigned char&), 0x00525AE0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadByte, unsigned char(__fastcall zCArchiverBinSafe::*)(char const*), 0x00525870);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadWord, void(__fastcall zCArchiverBinSafe::*)(char const*, unsigned short&), 0x00525B10);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadWord, unsigned short(__fastcall zCArchiverBinSafe::*)(char const*), 0x00525890);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadFloat, void(__fastcall zCArchiverBinSafe::*)(char const*, float&), 0x00525A50);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadFloat, float(__fastcall zCArchiverBinSafe::*)(char const*), 0x005257F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadBool, void(__fastcall zCArchiverBinSafe::*)(char const*, int&), 0x00525B40);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadBool, int(__fastcall zCArchiverBinSafe::*)(char const*), 0x005258B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadString, void(__fastcall zCArchiverBinSafe::*)(char const*, zSTRING&), 0x00525B70);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadString, zSTRING(__fastcall zCArchiverBinSafe::*)(char const*), 0x005258D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadVec3, void(__fastcall zCArchiverBinSafe::*)(char const*, zVEC3&), 0x00525A80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadVec3, zVEC3(__fastcall zCArchiverBinSafe::*)(char const*), 0x00525810);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadColor, void(__fastcall zCArchiverBinSafe::*)(char const*, zCOLOR&), 0x00525BA0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadColor, zCOLOR(__fastcall zCArchiverBinSafe::*)(char const*), 0x005259B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadEnum, void(__fastcall zCArchiverBinSafe::*)(char const*, int&), 0x00525BD0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadEnum, int(__fastcall zCArchiverBinSafe::*)(char const*), 0x005259D0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ReadRaw, 0x005259F0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ReadRawFloat, 0x00525A20);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadObject, zCObject*(__fastcall zCArchiverBinSafe::*)(zCObject*), 0x00524F30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadObject, zCObject*(__fastcall zCArchiverBinSafe::*)(char const*, zCObject*), 0x00524900);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadChunkStart, int(__fastcall zCArchiverBinSafe::*)(zSTRING&, unsigned short&), 0x00524760);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadChunkStart, int(__fastcall zCArchiverBinSafe::*)(char const*), 0x00524160);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ReadChunkStartNamed, 0x005248A0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::SkipOpenChunk, 0x00520C90);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::GetCurrentChunkVersion, 0x005248D0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::GetFile, 0x00520CA0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::GetBufferString, 0x00521560);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::GetBuffer, 0x005216E0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::EndOfArchive, 0x005214D0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::Close, 0x005210A0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::SetStringEOL, 0x00520CB0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::GetStringEOL, 0x00520E30);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::IsStringValid, 0x00521A70);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::GetChecksumEnabled, 0x00520E80);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::SetChecksumEnabled, 0x00520E90);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::SetNoReadSearchCycles, 0x00520EA0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::InProperties, 0x00520EB0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::InSaveGame, 0x00520EC0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::InBinaryMode, 0x00520ED0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::GetParentObject, 0x00525C00);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::OpenWriteBuffer, 0x005216F0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::OpenWriteFile, 0x005218D0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteHeader, 0x005219F0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteHeaderNumObj, 0x00521040);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteASCIILine, 0x00521AB0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::StoreBuffer, 0x00521930);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::StoreString, 0x00521960);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::StoreStringEOL, 0x005219E0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::StoreGetPos, 0x00521990);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::StoreSeek, 0x005219B0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::OpenReadBuffer, 0x00523500);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::OpenReadFile, 0x00523700);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::GetClassDefByString, 0x00523CC0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::CreateObject, 0x00523BE0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::SkipChunk, 0x00524F40);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ReadChunkStartASCII, 0x00523E90);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ReadChunkEnd, 0x005248F0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ReadEntryASCII, 0x00525150);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ReadHeader, 0x00523810);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::RestoreBuffer, 0x00523760);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::RestoreStringEOL, 0x00523790);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::RestoreString0, 0x005237A0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::RestoreGetPos, 0x005237B0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::RestoreSeek, 0x005237D0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::DeleteBuffer, 0x00521540);

} // namespace Gothic_I_Addon
