namespace Gothic_I_Addon {

	ZENGIN_REGISTER_CLASS(zCArchiverGeneric);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::zCArchiverGeneric_OnInit, 0x00526DD0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::DebugMessage, 0x005272C0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::CheckObjectListSize, 0x0052A5E0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::_GetClassDef, 0x00526F00);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteInt, 0x00527DC0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteByte, 0x00527E90);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteWord, 0x00527F60);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteFloat, 0x00528030);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteBool, 0x00528100);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteString, 0x005281D0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteVec3, 0x00528230);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteColor, 0x005284C0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteRaw, 0x005287E0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteRawFloat, 0x005289B0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteEnum, 0x00528C90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::WriteObject, void(__fastcall zCArchiverGeneric::*)(zCObject*), 0x00529920);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::WriteObject, void(__fastcall zCArchiverGeneric::*)(char const*, zCObject*), 0x00529880);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::WriteObject, void(__fastcall zCArchiverGeneric::*)(char const*, zCObject&), 0x00529650);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::WriteChunkStart, void(__fastcall zCArchiverGeneric::*)(char const*, unsigned short), 0x00529350);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::WriteChunkStart, void(__fastcall zCArchiverGeneric::*)(char const*, char const*, unsigned short, unsigned long), 0x00528E50);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteChunkEnd, 0x00529370);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteGroupBegin, 0x00529930);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteGroupEnd, 0x00529A10);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadInt, void(__fastcall zCArchiverGeneric::*)(char const*, int&), 0x0052C8F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadInt, int(__fastcall zCArchiverGeneric::*)(char const*), 0x0052C1F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadByte, void(__fastcall zCArchiverGeneric::*)(char const*, unsigned char&), 0x0052C940);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadByte, unsigned char(__fastcall zCArchiverGeneric::*)(char const*), 0x0052C210);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadWord, void(__fastcall zCArchiverGeneric::*)(char const*, unsigned short&), 0x0052C990);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadWord, unsigned short(__fastcall zCArchiverGeneric::*)(char const*), 0x0052C230);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadFloat, void(__fastcall zCArchiverGeneric::*)(char const*, float&), 0x0052C840);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadFloat, float(__fastcall zCArchiverGeneric::*)(char const*), 0x0052C190);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadBool, void(__fastcall zCArchiverGeneric::*)(char const*, int&), 0x0052C9E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadBool, int(__fastcall zCArchiverGeneric::*)(char const*), 0x0052C250);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadString, void(__fastcall zCArchiverGeneric::*)(char const*, zSTRING&), 0x0052CA50);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadString, zSTRING(__fastcall zCArchiverGeneric::*)(char const*), 0x0052C270);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadVec3, void(__fastcall zCArchiverGeneric::*)(char const*, zVEC3&), 0x0052C890);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadVec3, zVEC3(__fastcall zCArchiverGeneric::*)(char const*), 0x0052C1B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadColor, void(__fastcall zCArchiverGeneric::*)(char const*, zCOLOR&), 0x0052CA80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadColor, zCOLOR(__fastcall zCArchiverGeneric::*)(char const*), 0x0052C350);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadEnum, void(__fastcall zCArchiverGeneric::*)(char const*, int&), 0x0052CB10);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadEnum, int(__fastcall zCArchiverGeneric::*)(char const*), 0x0052C370);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::ReadRaw, 0x0052C390);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::ReadRawFloat, 0x0052C610);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadObject, zCObject*(__fastcall zCArchiverGeneric::*)(zCObject*), 0x0052BA50);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadObject, zCObject*(__fastcall zCArchiverGeneric::*)(char const*, zCObject*), 0x0052B240);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadChunkStart, int(__fastcall zCArchiverGeneric::*)(zSTRING&, unsigned short&), 0x0052B0A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadChunkStart, int(__fastcall zCArchiverGeneric::*)(char const*), 0x0052ABF0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::ReadChunkStartNamed, 0x0052B1E0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::SkipOpenChunk, 0x00526F10);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::GetCurrentChunkVersion, 0x0052B210);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::GetFile, 0x00526F20);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::GetBufferString, 0x00527600);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::GetBuffer, 0x00527780);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::EndOfArchive, 0x00527570);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::Close, 0x005273D0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::SetStringEOL, 0x00526F30);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::GetStringEOL, 0x005270B0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::IsStringValid, 0x00527B50);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::GetChecksumEnabled, 0x00527100);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::SetChecksumEnabled, 0x00527110);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::SetNoReadSearchCycles, 0x00527120);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::InProperties, 0x00527130);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::InSaveGame, 0x00527140);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::InBinaryMode, 0x00527150);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::GetParentObject, 0x0052D3E0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::OpenWriteBuffer, 0x00527790);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::OpenWriteFile, 0x00527980);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteHeader, 0x00527AE0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteHeaderNumObj, 0x005272E0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteASCIILine, 0x00527B90);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::StoreBuffer, 0x005279F0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::StoreString, 0x00527A20);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::StoreStringEOL, 0x00527AB0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::StoreGetPos, 0x00527A60);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::StoreSeek, 0x00527A80);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::OpenReadBuffer, 0x00529AF0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::OpenReadFile, 0x00529CF0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::GetClassDefByString, 0x0052A770);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::CreateObject, 0x0052A690);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::SkipChunk, 0x0052BA60);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::ReadChunkStartASCII, 0x0052A940);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::ReadChunkEnd, 0x0052B230);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::ReadEntryASCII, 0x0052BC80);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::ReadHeader, 0x0052A270);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::RestoreBuffer, 0x00529D60);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::RestoreStringEOL, 0x00529D90);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::RestoreString0, 0x0052A200);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::RestoreGetPos, 0x0052A210);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::RestoreSeek, 0x0052A230);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::DeleteBuffer, 0x005275E0);

} // namespace Gothic_I_Addon
