namespace Gothic_I_Addon {

	ZENGIN_REGISTER_CLASS(zCBspBase);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::zCBspBase_OnInit, 0x0053C570);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::DescribeTree, 0x0052E7B0);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CountNodes, 0x0052FFC0);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::AddVobsToRenderListSubtree, 0x00531D90);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::GetScreenBBox2D, 0x00531E70);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CollectNodeLights, 0x00532130);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::RenderTrivInIndoor, 0x00532480);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::RenderIndoor, 0x005324C0);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::RenderNodeOutdoor, 0x00532560);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::AddVobToLeafs, 0x00533F00);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::AddVobLightToLeafs, 0x00534040);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::RemoveVobFromLeafs, 0x005343E0);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CollectVobsSubtree, 0x00534590);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CollectVobsInBBox3D, 0x005345A0);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CollectVobsSubtree_I, 0x005345C0);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CollectLightVobsSubtree, 0x005347B0);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CollectLightVobsSubtree_I, 0x005347C0);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CollectVobsInBBox3D_I, 0x005349B0);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::FindLeaf, 0x00534E00);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CheckRayAgainstPolys, 0x00534F30);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CheckRayAgainstPolysNearestHit, 0x00535090);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CheckRayAgainstPolysCache, 0x00535270);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::RayIntersection, 0x00535450);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CollectPolysInBBox3DRec, 0x00535CD0);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CollectPolysInBBox3D, 0x00535F20);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::SortNodePolys, 0x00536B20);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::SaveBINRec, 0x0053A550);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::LoadBINRec, 0x0053A650);

	ZENGIN_REGISTER_CLASS(zCBspNode);
	ZENGIN_REGISTER_METHOD(zCBspNode, &zCBspNode::zCBspNode_OnInit, 0x0052FFA0);
	ZENGIN_REGISTER_METHOD(zCBspNode, &zCBspNode::CalcPlaneSignbits, 0x00533EC0);

	ZENGIN_REGISTER_CLASS(zCBspLeaf);
	ZENGIN_REGISTER_METHOD(zCBspLeaf, &zCBspLeaf::zCBspLeaf_OnInit, 0x0052F530);
	ZENGIN_REGISTER_METHOD(zCBspLeaf, &zCBspLeaf::PolyPlueckerAddRef, 0x00531340);
	ZENGIN_REGISTER_METHOD(zCBspLeaf, &zCBspLeaf::PolyPlueckerRelease, 0x00531610);
	ZENGIN_REGISTER_METHOD(zCBspLeaf, &zCBspLeaf::AddVobsToRenderList, 0x00531640);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCBspLeaf, &zCBspLeaf::AddVobsToRenderListOutdoor, void(zCBspLeaf::*)(), 0x00531860);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCBspLeaf, &zCBspLeaf::AddVobsToRenderListOutdoor, void(__fastcall zCBspLeaf::*)(zCBspSector*, zTBBox2D const&), 0x00531BA0);
	ZENGIN_REGISTER_METHOD(zCBspLeaf, &zCBspLeaf::RenderLeafIndoor, 0x005322C0);
	ZENGIN_REGISTER_METHOD(zCBspLeaf, &zCBspLeaf::TraceRayCollectVobs, 0x00534BF0);

	ZENGIN_REGISTER_CLASS(zCBspTree);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::zCBspTree_OnInit, 0x0052F190);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::InitTree, 0x0052F450);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::DisposeTree, 0x0052F5B0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::BuildRecursive, 0x0052F830);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::Build, 0x0052FB30);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::UpdateVertexDependencies, 0x00530000);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::CollectPolysInBBox3DAngle, 0x005301F0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::RenderLightList, 0x00530360);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::RenderVobList, 0x005304A0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::Render, 0x005335A0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::RemoveVob, 0x005344A0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::AddVob, 0x005344B0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::AdjustVob, 0x00534520);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::CalcLeafRealBBox3D, 0x00534E40);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::TraceRay, 0x005356E0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::FindLeaks, 0x00536160);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::MarkOccluderPolys, 0x005364F0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::GetSectorNameVobIsIn, 0x005377A0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::GetBspSectorByName, 0x0053A100);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::CreateBspSectors2, 0x0053A1B0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::SaveBIN, 0x0053A7E0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::ConnectMaterialsToSectors, 0x0053B170);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::LoadBIN, 0x0053B550);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::CalcStaticLeafLightData, 0x0053C5A0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::PreprocessIndoorPortals, 0x00544DA0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::GetPolyNeighbours, 0x00545120);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::PostprocessIndoorPortals, 0x00545200);

	ZENGIN_REGISTER_CLASS(zCCBspNode);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::zCCBspNode_OnInit, 0x00543BB0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CheckRayAgainstPolysNearestHit, 0x005358F0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::RayIntersectionOctree, 0x00535A20);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCBspNode, &zCCBspNode::TraceRay, int(zCCBspNode::*)(zVEC3 const&, zVEC3 const&, zCPolygon*&, zVEC3&), 0x00535C60);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCBspNode, &zCCBspNode::TraceRay, int(zCCBspNode::*)(zVEC3 const&, zVEC3 const&, zCPolygon*&), 0x00535C90);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CollectPolysInBBox3DRec, 0x00535F70);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CollectPolysInBBox3D, 0x00536110);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::RemovePoly, 0x0053E850);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::LODGenerate, 0x0053E920);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::LODTriangulatePortal, 0x0053EF80);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::LODCollectLeafPolys, 0x0053F340);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::DoesNodeContainPoly, 0x00540CA0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CheckPortalConsistency, 0x00540D20);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::SplitPortals, 0x00541420);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::SplitPortalByAllPortals, 0x005419D0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::EnumeratePortals, 0x00541C90);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::ClassifyPortals, 0x00541DD0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::Portalize, 0x00541E60);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::SelectPlane, 0x005421C0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::SelectPlaneOctree, 0x00542440);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::ClassifyRayToNode, 0x00542680);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::ClassifyPolyToNode2, 0x005428A0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::OutdoorKillRedundantLeafs, 0x00542BF0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::AddPoly, 0x00542E40);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::BuildTree, 0x00542E90);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::PushPolyFront, 0x00543BD0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CalcBBox3D, 0x00543C70);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CalcSubtreeBBox3D, 0x00543D50);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CalcSubtreeBBox3DCell, 0x00543F00);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CountNodes, 0x00543FF0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CountLeafs, 0x00544020);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CountPolys, 0x00544060);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CountDepthRec, 0x00544090);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CountDepth, 0x00544100);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::DescribeTree, 0x005441B0);

	ZENGIN_REGISTER_CLASS(zCCBspTree);
	ZENGIN_REGISTER_METHOD(zCCBspTree, &zCCBspTree::zCCBspTree_OnInit, 0x0053D820);
	ZENGIN_REGISTER_METHOD(zCCBspTree, &zCCBspTree::GetBspSectorByName, 0x005376F0);
	ZENGIN_REGISTER_METHOD(zCCBspTree, &zCCBspTree::GetPolyNeighbours, 0x005377C0);
	ZENGIN_REGISTER_METHOD(zCCBspTree, &zCCBspTree::MarkGhostOccluder, 0x005378C0);
	ZENGIN_REGISTER_METHOD(zCCBspTree, &zCCBspTree::CreateBspSectors, 0x00537A80);
	ZENGIN_REGISTER_METHOD(zCCBspTree, &zCCBspTree::SetBspTreeMode, 0x0053D950);
	ZENGIN_REGISTER_METHOD(zCCBspTree, &zCCBspTree::DeleteTree, 0x0053DAB0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCBspTree, &zCCBspTree::AddMesh, void(zCCBspTree::*)(zCMesh*), 0x0053DC00);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCBspTree, &zCCBspTree::AddMesh, void(zCCBspTree::*)(zCMesh*, zMAT4 const&), 0x0053DC30);
	ZENGIN_REGISTER_METHOD(zCCBspTree, &zCCBspTree::BuildTree, 0x0053DF60);

	ZENGIN_REGISTER_CLASS(zCBspSector);
	ZENGIN_REGISTER_METHOD(zCBspSector, &zCBspSector::CalcCenterByPortals, 0x0052DDB0);
	ZENGIN_REGISTER_METHOD(zCBspSector, &zCBspSector::IsRendered, 0x0052DE50);
	ZENGIN_REGISTER_METHOD(zCBspSector, &zCBspSector::Rendered, 0x0052DE70);
	ZENGIN_REGISTER_METHOD(zCBspSector, &zCBspSector::IsActivated, 0x0052DE80);
	ZENGIN_REGISTER_METHOD(zCBspSector, &zCBspSector::Activate, 0x0052DEA0);
	ZENGIN_REGISTER_METHOD(zCBspSector, &zCBspSector::HasManyBigPortals, 0x0052DF80);
	ZENGIN_REGISTER_METHOD(zCBspSector, &zCBspSector::RenderSector, 0x00536B70);
	ZENGIN_REGISTER_METHOD(zCBspSector, &zCBspSector::ActivateSectorRec, 0x00536CB0);
	ZENGIN_REGISTER_METHOD(zCBspSector, &zCBspSector::ActivateSectorRecIndoor, 0x005371D0);

	ZENGIN_REGISTER_CLASS(zCBuildPortal);
	ZENGIN_REGISTER_METHOD(zCBuildPortal, &zCBuildPortal::zCBuildPortal_OnInit, 0x00544C90);

} // namespace Gothic_I_Addon
