namespace Gothic_I_Addon {

	ZENGIN_REGISTER_CLASS(zCEvMsgCutscene);
	ZENGIN_REGISTER_METHOD(zCEvMsgCutscene, &zCEvMsgCutscene::zCEvMsgCutscene_OnInit, 0x0040D330);
	ZENGIN_REGISTER_METHOD(zCEvMsgCutscene, &zCEvMsgCutscene::SetCutsceneName, 0x00415170);
	ZENGIN_REGISTER_METHOD(zCEvMsgCutscene, &zCEvMsgCutscene::GetCutsceneName, 0x006DB160);
	ZENGIN_REGISTER_METHOD(zCEvMsgCutscene, &zCEvMsgCutscene::_GetClassDef, 0x0040C680);
	ZENGIN_REGISTER_METHOD(zCEvMsgCutscene, &zCEvMsgCutscene::IsHighPriority, 0x0040C690);
	ZENGIN_REGISTER_METHOD(zCEvMsgCutscene, &zCEvMsgCutscene::Delete, 0x0040C6A0);
	ZENGIN_REGISTER_METHOD(zCEvMsgCutscene, &zCEvMsgCutscene::IsDeleted, 0x0040C6B0);
	ZENGIN_REGISTER_METHOD(zCEvMsgCutscene, &zCEvMsgCutscene::MD_GetNumOfSubTypes, 0x0040D500);
	ZENGIN_REGISTER_METHOD(zCEvMsgCutscene, &zCEvMsgCutscene::MD_GetSubTypeString, 0x0040D510);

	ZENGIN_REGISTER_CLASS(zCCSRole);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSRole, &zCCSRole::zCCSRole_OnInit, void(zCCSRole::*)(), 0x0040C750);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSRole, &zCCSRole::zCCSRole_OnInit, void(zCCSRole::*)(zSTRING&), 0x0040C8A0);
	ZENGIN_REGISTER_METHOD(zCCSRole, &zCCSRole::SetRoleVob, 0x0040CCB0);
	ZENGIN_REGISTER_METHOD(zCCSRole, &zCCSRole::GetRoleVob, 0x0040D150);
	ZENGIN_REGISTER_METHOD(zCCSRole, &zCCSRole::_GetClassDef, 0x0040C330);
	ZENGIN_REGISTER_METHOD(zCCSRole, &zCCSRole::Archive, 0x0040D160);
	ZENGIN_REGISTER_METHOD(zCCSRole, &zCCSRole::Unarchive, 0x0040D1D0);

	ZENGIN_REGISTER_CLASS(zCCSBlockBase);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::zCCSBlockBase_OnInit, 0x0040D6C0);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::_GetClassDef, 0x0040BD10);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::Archive, 0x00418410);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::Unarchive, 0x00418420);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::GetChild, 0x0040D860);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::GetRoleName, 0x0040D8C0);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::SetRoleName, 0x0040D950);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::GetCommand, 0x00405690);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::NewBlock, 0x0040D870);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::InsertBlock, 0x0040B6B0);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::DeleteChild, 0x0040D960);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::GetNumOfChilds, 0x0040D880);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::GetRoleNumOfChild, 0x0040D890);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::BlockCorrection, 0x0040D8A0);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::BlockAsFocus, 0x0040D8B0);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::GetChildPos, 0x0040D970);

	ZENGIN_REGISTER_CLASS(zCCSAtomicBlock);
	ZENGIN_REGISTER_METHOD(zCCSAtomicBlock, &zCCSAtomicBlock::zCCSAtomicBlock_OnInit, 0x0040D980);
	ZENGIN_REGISTER_METHOD(zCCSAtomicBlock, &zCCSAtomicBlock::_GetClassDef, 0x0040B6E0);
	ZENGIN_REGISTER_METHOD(zCCSAtomicBlock, &zCCSAtomicBlock::Archive, 0x00418430);
	ZENGIN_REGISTER_METHOD(zCCSAtomicBlock, &zCCSAtomicBlock::Unarchive, 0x00418450);
	ZENGIN_REGISTER_METHOD(zCCSAtomicBlock, &zCCSAtomicBlock::OrganizeRoles, 0x0040DB90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSAtomicBlock, &zCCSAtomicBlock::Play, void(zCCSAtomicBlock::*)(zCArray<zCEventManager*> const&), 0x0040DE10);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSAtomicBlock, &zCCSAtomicBlock::Play, void(zCCSAtomicBlock::*)(zCArray<zCEventManager*> const&, float, float), 0x0040DE30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSAtomicBlock, &zCCSAtomicBlock::Play, void(zCCSAtomicBlock::*)(zCEventManager*), 0x0040DE50);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSAtomicBlock, &zCCSAtomicBlock::Play, void(zCCSAtomicBlock::*)(zCEventManager*, float, float), 0x0040DEE0);
	ZENGIN_REGISTER_METHOD(zCCSAtomicBlock, &zCCSAtomicBlock::GetMinTime, 0x0040DEF0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSAtomicBlock, &zCCSAtomicBlock::IsFinished, int(zCCSAtomicBlock::*)(zCArray<zCEventManager*> const&), 0x0040B6F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSAtomicBlock, &zCCSAtomicBlock::IsFinished, int(zCCSAtomicBlock::*)(zCEventManager*), 0x0040DF10);
	ZENGIN_REGISTER_METHOD(zCCSAtomicBlock, &zCCSAtomicBlock::GetCommand, 0x0040B700);

	ZENGIN_REGISTER_CLASS(zCCSBlockPosition);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSBlockPosition, &zCCSBlockPosition::zCCSBlockPosition_OnInit, void(zCCSBlockPosition::*)(), 0x00418380);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSBlockPosition, &zCCSBlockPosition::zCCSBlockPosition_OnInit, void(zCCSBlockPosition::*)(zCCSBlockBase*), 0x004183A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSBlockPosition, &zCCSBlockPosition::zCCSBlockPosition_OnInit, void(zCCSBlockPosition::*)(float, zCCSBlockBase*), 0x004183C0);

	ZENGIN_REGISTER_CLASS(zCCSBlock);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::zCCSBlock_OnInit, 0x0040E130);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::_GetClassDef, 0x0040BA10);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::Archive, 0x00418480);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::Unarchive, 0x00418610);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::GetChild, 0x0040E2F0);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::OrganizeRoles, 0x0040E810);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::GetRoleName, 0x0040E850);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::SetRoleName, 0x0040E8A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSBlock, &zCCSBlock::Play, void(zCCSBlock::*)(zCArray<zCEventManager*> const&), 0x0040E4B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSBlock, &zCCSBlock::Play, void(zCCSBlock::*)(zCArray<zCEventManager*> const&, float, float), 0x0040E580);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSBlock, &zCCSBlock::Play, void(zCCSBlock::*)(zCEventManager*), 0x0040E3D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSBlock, &zCCSBlock::Play, void(zCCSBlock::*)(zCEventManager*, float, float), 0x0040E420);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::GetMinTime, 0x0040E650);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSBlock, &zCCSBlock::IsFinished, int(zCCSBlock::*)(zCArray<zCEventManager*> const&), 0x0040E730);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSBlock, &zCCSBlock::IsFinished, int(zCCSBlock::*)(zCEventManager*), 0x0040E6E0);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::NewBlock, 0x0040EA80);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::InsertBlock, 0x0040E9E0);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::DeleteChild, 0x0040E340);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::GetNumOfChilds, 0x0040E330);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::BlockCorrection, 0x0040EB60);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::BlockAsFocus, 0x0040EB20);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::GetChildPos, 0x0040E310);

	ZENGIN_REGISTER_CLASS(zCCSSyncBlock);
	ZENGIN_REGISTER_METHOD(zCCSSyncBlock, &zCCSSyncBlock::zCCSSyncBlock_OnInit, 0x0040EC50);
	ZENGIN_REGISTER_METHOD(zCCSSyncBlock, &zCCSSyncBlock::AssignerCorrection, 0x0040F240);
	ZENGIN_REGISTER_METHOD(zCCSSyncBlock, &zCCSSyncBlock::_GetClassDef, 0x0040BD40);
	ZENGIN_REGISTER_METHOD(zCCSSyncBlock, &zCCSSyncBlock::Archive, 0x00418800);
	ZENGIN_REGISTER_METHOD(zCCSSyncBlock, &zCCSSyncBlock::Unarchive, 0x004189F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSSyncBlock, &zCCSSyncBlock::Play, void(zCCSSyncBlock::*)(zCArray<zCEventManager*> const&), 0x0040EE30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSSyncBlock, &zCCSSyncBlock::Play, void(zCCSSyncBlock::*)(zCArray<zCEventManager*> const&, float, float), 0x0040EED0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSSyncBlock, &zCCSSyncBlock::Play, void(zCCSSyncBlock::*)(zCEventManager*), 0x0040EDE0);
	ZENGIN_REGISTER_METHOD(zCCSSyncBlock, &zCCSSyncBlock::IsFinished, 0x0040ED90);
	ZENGIN_REGISTER_METHOD(zCCSSyncBlock, &zCCSSyncBlock::NewBlock, 0x0040F070);
	ZENGIN_REGISTER_METHOD(zCCSSyncBlock, &zCCSSyncBlock::InsertBlock, 0x0040EFA0);
	ZENGIN_REGISTER_METHOD(zCCSSyncBlock, &zCCSSyncBlock::DeleteChild, 0x0040F190);
	ZENGIN_REGISTER_METHOD(zCCSSyncBlock, &zCCSSyncBlock::GetRoleNumOfChild, 0x0040EF80);
	ZENGIN_REGISTER_METHOD(zCCSSyncBlock, &zCCSSyncBlock::BlockAsFocus, 0x0040F140);

	ZENGIN_REGISTER_CLASS(zCCutscene);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::zCCutscene_OnInit, 0x0040F270);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::IsMember, 0x0040F670);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::SetRoleListForDebugging, 0x0040F6A0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::SaveRolesVobs, 0x0040F850);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::RestoreRoleVobs, 0x0040FA90);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::CheckMainRole, 0x0040FD10);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::CheckPlayState, 0x00410D60);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::SolveEventManager, 0x00415780);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::GetActualBlockNum, 0x004174A0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::ResumeAtBlock, 0x00417860);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::NewRole, 0x00417DA0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::DeleteRole, 0x00417F90);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::RegisterAdditionalVob, 0x00418080);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::FirstRoleUsed, 0x00418FD0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::GetLastCheckResult, 0x00419090);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::TryToCancel, 0x00419390);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::GetFirstBlockPosition, 0x004193C0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::GetNextMessage, 0x00419560);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::GetNextBlock, 0x004195B0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::SerializeCutscene, 0x004195E0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::SerializeBlock, 0x00419760);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::GetProperties, 0x0041EBF0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::_GetClassDef, 0x0040F460);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::Archive, 0x00418C70);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::Unarchive, 0x00418D00);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::NewBlock, 0x004178E0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::AddMainRole, 0x00411730);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::AddRoleOU, 0x00410EA0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::RemoveRole, 0x00411FE0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::SetOwnerPlayer, 0x0040F630);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::Reset, 0x00415300);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::ClearCutscene, 0x00415400);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::StartPlaying, 0x00414430);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::Stop, 0x004157C0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::StopRole, 0x00415600);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::Interrupt, 0x00416A30);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::ResumeActBlock, 0x004174B0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::PlaySub, 0x00417870);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::NewCS, 0x00417AF0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::IsCutscene, 0x0040F470);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCutscene, &zCCutscene::IsFinished, int(zCCutscene::*)(zCArray<zCEventManager*> const&), 0x0040E730);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCutscene, &zCCutscene::IsFinished, int(zCCutscene::*)(zCEventManager*), 0x0040E6E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCutscene, &zCCutscene::IsFinished, int(zCCutscene::*)(), 0x004178D0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::PrintDebugInfo, 0x00419080);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::CheckRoles, 0x00419000);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::CSCheck, 0x00412060);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::GetStage, 0x00410D50);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::LoadStage, 0x004180F0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::CatchPlayer, 0x00418340);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::PrepareBlock, 0x00410E20);

} // namespace Gothic_I_Addon
