namespace Gothic_I_Addon {

	ZENGIN_REGISTER_CLASS(zFILE_VDFS);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::zFILE_VDFS_OnInit, void(zFILE_VDFS::*)(), 0x0044A7A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::zFILE_VDFS_OnInit, void(zFILE_VDFS::*)(zSTRING const&), 0x0044A9E0);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::Init, 0x0044A770);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::HandleError, 0x0044ACD0);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::GetFullPath, 0x0044B740);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::SetCurrentDir, 0x0044B4B0);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::ChangeDir, 0x0044B8D0);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::SearchFile, 0x0044B8E0);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::FindFirst, 0x0044BDE0);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::FindNext, 0x0044C0D0);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::IsOpened, 0x0044ABA0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::Open, int(zFILE_VDFS::*)(bool), 0x0044ACE0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::Open, int(zFILE_VDFS::*)(zSTRING const&, bool), 0x0044A8E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::Exists, bool(zFILE_VDFS::*)(), 0x0044ABD0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::Exists, bool(zFILE_VDFS::*)(zSTRING const&), 0x0044A950);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::Close, 0x0044AFA0);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::Reset, 0x0044B000);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::Append, 0x0044B490);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::Size, 0x0044B010);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::Pos, 0x0044B430);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::Seek, 0x0044B090);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::Eof, 0x0044B070);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::GetStats, 0x0044BDD0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::Read, long(zFILE_VDFS::*)(void*, long), 0x0044C780);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::Read, int(zFILE_VDFS::*)(char*), 0x0044C430);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::Read, int(zFILE_VDFS::*)(zSTRING&), 0x0044C600);

} // namespace Gothic_I_Addon
