namespace Gothic_I_Addon {

	ZENGIN_REGISTER_CLASS(zERROR);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::zERROR_OnInit, 0x0044D6D0);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::Init, 0x0044D950);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::SendToSpy, 0x0044E210);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zERROR, &zERROR::Report, int(zERROR::*)(zERROR_LEVEL, int, zSTRING const&, signed char, unsigned int, int, char*, char*), 0x0044E280);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zERROR, &zERROR::Report, int(zERROR::*)(zERROR_TYPE, int, zSTRING const&, signed char, unsigned int, int, char*, char*), 0x0044E2B0);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::BlockBegin, 0x0044EB20);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::BlockEnd, 0x0044ED70);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::Separator, 0x0044F160);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::ShowSpy, 0x0044F3B0);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::Message, 0x0044F510);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::Warning, 0x0044F550);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::Fatal, 0x0044F580);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::Fault, 0x0044F5B0);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::SetFilterFlags, 0x0044F5E0);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::SetFilterAuthors, 0x0044F710);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::SetFilterLevel, 0x0044F8F0);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::SetTarget, 0x0044FA20);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::GetTargetDescription, 0x0044FCE0);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::GetFilterFlagDescription, 0x0044FF30);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::GetFilterAuthors, 0x00450160);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::SearchForSpy, 0x004501B0);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::GetFilterLevel, 0x00598B80);

} // namespace Gothic_I_Addon
