namespace Gothic_I_Addon {

	ZENGIN_REGISTER_CLASS(zCFile3DS);
	ZENGIN_REGISTER_METHOD(zCFile3DS, &zCFile3DS::Load3DS, 0x0055EAB0);
	ZENGIN_REGISTER_METHOD(zCFile3DS, &zCFile3DS::Save3DS, 0x005602F0);

	ZENGIN_REGISTER_CLASS(zCFileQuakeBSP);
	ZENGIN_REGISTER_METHOD(zCFileQuakeBSP, &zCFileQuakeBSP::zCFileQuakeBSP_OnInit, 0x00561F40);
	ZENGIN_REGISTER_METHOD(zCFileQuakeBSP, &zCFileQuakeBSP::LoadQuakeBSP, 0x00561F70);

	ZENGIN_REGISTER_CLASS(zCFileBIN);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::zCFileBIN_OnInit, 0x00569180);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinCreate, 0x00569220);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinClose, 0x00569250);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinStartChunk, 0x00585E70);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinWriteSrcFileStats, 0x00585F10);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinEndChunk, 0x00586D50);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinWriteString, 0x00587000);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinReadCompareSrcFileStats, 0x005896D0);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinSkipChunk, 0x0059C330);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinSetFile, 0x00619EA0);

} // namespace Gothic_I_Addon
