namespace Gothic_I_Addon {

	ZENGIN_REGISTER_CLASS(zCFileCSV);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCFileCSV, &zCFileCSV::zCFileCSV_OnInit, void(zCFileCSV::*)(zSTRING const&), 0x004504C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCFileCSV, &zCFileCSV::zCFileCSV_OnInit, void(zCFileCSV::*)(), 0x004506D0);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::InitCSV, 0x00450A20);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::SetFormat, 0x00450B80);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::AddNextField, 0x00450CD0);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::AddNextHeader, 0x00450EA0);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::WriteSet, 0x00451080);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::GetNextField, 0x00451250);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::ReadSet, 0x00451700);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::ReadHeader, 0x00451750);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::WriteHeader, 0x00451960);

} // namespace Gothic_I_Addon
