namespace Gothic_I_Addon {

	ZENGIN_REGISTER_CLASS(zCGfx);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCGfx, &zCGfx::zCGfx_OnInit, void(zCGfx::*)(zSTRING const&), 0x00719800);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCGfx, &zCGfx::zCGfx_OnInit, void(zCGfx::*)(int, int), 0x00719A20);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::LoadRaw, 0x0071A2E0);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::Readbyte, 0x0071A3A0);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::LoadPcx, 0x0071A410);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::LoadTga, 0x0071A950);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::SaveRaw, 0x0071BDE0);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::Save, 0x0071BE40);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::LoadGfx, 0x0071C000);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::GetSizex, 0x0071C3D0);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::GetSizey, 0x0071C3E0);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::GetDataPtr, 0x0071C3F0);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::GetPixel, 0x0071C400);

} // namespace Gothic_I_Addon
