namespace Gothic_I_Addon {

	ZENGIN_REGISTER_CLASS(zCMenu);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenu, &zCMenu::zCMenu_OnInit, void(zCMenu::*)(), 0x004DDF60);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenu, &zCMenu::zCMenu_OnInit, void(zCMenu::*)(zSTRING const&), 0x004DE130);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::InitValues, 0x004DE4B0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::Release, 0x004DE700);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::Register, 0x004DE9E0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::Unregister, 0x004DEC30);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::IsRegistered, 0x004DECF0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::ClearAllEvents, 0x004DF240);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::PreviousOption, 0x004DF260);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::NextOption, 0x004DF330);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::RestartMusicTheme, 0x004DF400);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::ForceSelAction, 0x004DF9F0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::UpdateWindowGeometry, 0x004DFBB0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::PrintInformation, 0x004E07A0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::GetBackWorld, 0x004E15C0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::GetBackDatFile, 0x004E1600);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::GetActiveItem, 0x004E1630);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::GetNumberOfActiveItem, 0x004E1640);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::SetActiveItem, 0x004E16B0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::GetName, 0x004E1810);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::SetName, 0x004E1820);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::HandleEvent, 0x004DF6A0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::HandleEnterItem, 0x004E1980);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::HandleLeaveItem, 0x004E1990);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::HandleActivateItem, 0x004E19A0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::Run, 0x004DF4C0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::Enter, 0x004DF420);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::Leave, 0x004DF480);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::Render, 0x004E14E0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::RedrawItems, 0x004E0770);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::HandleFrame, 0x004DFD00);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::Activate, 0x004DFB90);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::ScreenInit, 0x004E08E0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::ScreenDone, 0x004E1280);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::HandleAction, 0x004DFD90);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::HandleSelAction, 0x004DFF70);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::SetByScript, 0x004DEFC0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::ExecCommand, 0x004E0510);

} // namespace Gothic_I_Addon
