namespace Gothic_I_Addon {

	ZENGIN_REGISTER_CLASS(zCMenuItem);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenuItem, &zCMenuItem::zCMenuItem_OnInit, void(zCMenuItem::*)(zSTRING const&), 0x004E27F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenuItem, &zCMenuItem::zCMenuItem_OnInit, void(zCMenuItem::*)(), 0x004E29C0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetSelItem, 0x004E2120);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Init, 0x004E2D90);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::SetByScript, 0x004E30E0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetDimX, 0x004E3A70);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetDimY, 0x004E3B90);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::InitView, 0x004E3C80);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Close, 0x004E3E20);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetType, 0x004E3E70);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenuItem, &zCMenuItem::SetName, void(zCMenuItem::*)(zSTRING const&), 0x004E3F50);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetName, 0x004E4090);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetCoords, 0x004E40A0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetSelActionType, 0x004E40C0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetSelActionString, 0x004E40D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenuItem, &zCMenuItem::SetName, void(zCMenuItem::*)(zSTRING&), 0x004E40F0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Register, 0x004E4250);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Unregister, 0x004E4430);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::IsRegistered, 0x004E45A0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::UpdateSize, 0x004E4D30);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetEventFunc, 0x004E5780);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::SetIsActive, 0x004E5790);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::SetIsSelectable, 0x004E58B0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetIsSelectable, 0x004E5900);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::SetIsDisabled, 0x004E5970);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetIsDisabled, 0x004E5980);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::SetIsVisible, 0x004E59C0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetIsVisible, 0x004E59D0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::DrawItems, 0x004E55C0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::InitMenuItem, 0x004E3BF0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::ToggleValue, 0x004E3E40);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Run, 0x004E5030);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetText, 0x004E3E80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenuItem, &zCMenuItem::SetText, void(zCMenuItem::*)(zSTRING const&, int, int), 0x004E4660);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenuItem, &zCMenuItem::SetText, void(zCMenuItem::*)(zCArray<zSTRING>, int), 0x004E4E00);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::SetMinValue, 0x004E2750);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::SetMaxValue, 0x004E2760);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Enter, 0x004E4FD0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Leave, 0x004E4FE0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Draw, 0x004E5440);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::DrawFront, 0x004E5460);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Show, 0x004E3D70);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Hide, 0x004E3DB0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::HasBeenCanceled, 0x004E2770);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Open, 0x004E3DF0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Input, 0x004E5090);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::InsertInWin, 0x004E3410);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::RemoveFromWin, 0x004E3A10);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::UpdateContent, 0x004E55E0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::UpdateFX, 0x004E55F0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::HandleEvent, 0x004E4FF0);

	ZENGIN_REGISTER_CLASS(zCMenuItemInput);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::zCMenuItemInput_OnInit, 0x004E5A10);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::SetValue, 0x004E5C70);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::GetValue, 0x004E5CF0);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::InitMenuItem, 0x004E5D10);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::Run, 0x004E5F20);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::Enter, 0x004E2780);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::Leave, 0x004E2790);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::HasBeenCanceled, 0x004E27B0);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::InsertInWin, 0x004E5EF0);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::HandleEvent, 0x004E27A0);

	ZENGIN_REGISTER_CLASS(zCMenuItemText);
	ZENGIN_REGISTER_METHOD(zCMenuItemText, &zCMenuItemText::zCMenuItemText_OnInit, 0x004E62D0);
	ZENGIN_REGISTER_METHOD(zCMenuItemText, &zCMenuItemText::FormatMultiline, 0x004E6450);
	ZENGIN_REGISTER_METHOD(zCMenuItemText, &zCMenuItemText::DrawMultiline, 0x004E6850);
	ZENGIN_REGISTER_METHOD(zCMenuItemText, &zCMenuItemText::InitMenuItem, 0x004E6C20);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenuItemText, &zCMenuItemText::SetText, void(zCMenuItemText::*)(zSTRING const&, int, int), 0x004E7170);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenuItemText, &zCMenuItemText::SetText, void(zCMenuItemText::*)(zCArray<zSTRING>, int), 0x004E7470);
	ZENGIN_REGISTER_METHOD(zCMenuItemText, &zCMenuItemText::DrawFront, 0x004E6410);
	ZENGIN_REGISTER_METHOD(zCMenuItemText, &zCMenuItemText::SetEnum, 0x004E6E10);
	ZENGIN_REGISTER_METHOD(zCMenuItemText, &zCMenuItemText::HandleEvent, 0x004E6FB0);

	ZENGIN_REGISTER_CLASS(zCMenuItemSlider);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::zCMenuItemSlider_OnInit, 0x004E74D0);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::SetValue, 0x004E7C10);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::GetValue, 0x004E7CF0);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::InitMenuItem, 0x004E78A0);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::ToggleValue, 0x004E7590);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::InsertInWin, 0x004E7950);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::RemoveFromWin, 0x004E7B80);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::SetIsActive, 0x004E27C0);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::HandleEvent, 0x004E27E0);

	ZENGIN_REGISTER_CLASS(zCMenuItemButton);
	ZENGIN_REGISTER_METHOD(zCMenuItemButton, &zCMenuItemButton::zCMenuItemButton_OnInit, 0x004E9080);
	ZENGIN_REGISTER_METHOD(zCMenuItemButton, &zCMenuItemButton::Toggle, 0x004E9540);
	ZENGIN_REGISTER_METHOD(zCMenuItemButton, &zCMenuItemButton::InitMenuItem, 0x004E92E0);
	ZENGIN_REGISTER_METHOD(zCMenuItemButton, &zCMenuItemButton::Run, 0x004E97C0);
	ZENGIN_REGISTER_METHOD(zCMenuItemButton, &zCMenuItemButton::InsertInWin, 0x004E9A30);
	ZENGIN_REGISTER_METHOD(zCMenuItemButton, &zCMenuItemButton::RemoveFromWin, 0x004E9A70);

	ZENGIN_REGISTER_CLASS(zCMenuItemChoice);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::zCMenuItemChoice_OnInit, 0x004E7D00);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::SetOptionByString, 0x004E7FA0);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::GetStringByOption, 0x004E8400);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::Resize, 0x004E8830);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::GetNumOptions, 0x004E8B90);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::InitMenuItem, 0x004E8F60);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::ToggleValue, 0x004E7D80);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::GetText, 0x004E8DA0);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::Draw, 0x004E8900);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::DrawFront, 0x004E8920);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::InsertInWin, 0x004E85D0);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::RemoveFromWin, 0x004E87A0);

	ZENGIN_REGISTER_CLASS(zTMenuItemListElement);
	ZENGIN_REGISTER_METHOD(zTMenuItemListElement, &zTMenuItemListElement::zTMenuItemListElement_OnInit, 0x004EB190);

	ZENGIN_REGISTER_CLASS(zCMenuItemList);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::zCMenuItemList_OnInit, 0x004E9B30);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::DeleteContent, 0x004E9D90);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::InsertEnd, 0x004E9DE0);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::InsertFront, 0x004EA000);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::ShowContent, 0x004EA9F0);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::JumpToNextEntry, 0x004EABD0);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::JumpToPrevEntry, 0x004EABF0);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::JumpToTopEntry, 0x004EAC10);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::JumpToLastEntry, 0x004EAC30);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::InitMenuItem, 0x004E9CF0);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::Run, 0x004E9C50);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::Enter, 0x004EA420);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::Leave, 0x004EA430);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::DrawFront, 0x004EA450);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::Show, 0x004E9D00);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::Hide, 0x004E9D50);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::InsertInWin, 0x004EA1F0);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::RemoveFromWin, 0x004EA370);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::UpdateContent, 0x004EA440);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::HandleEvent, 0x004EA7A0);

} // namespace Gothic_I_Addon
