namespace Gothic_I_Addon {

	ZENGIN_REGISTER_CLASS(zCModelMeshLib);
	ZENGIN_REGISTER_METHOD(zCModelMeshLib, &zCModelMeshLib::zCModelMeshLib_OnInit, 0x00599D60);
	ZENGIN_REGISTER_METHOD(zCModelMeshLib, &zCModelMeshLib::ReleaseData, 0x00599F10);
	ZENGIN_REGISTER_METHOD(zCModelMeshLib, &zCModelMeshLib::AllocNumNodeVisuals, 0x00599F80);
	ZENGIN_REGISTER_METHOD(zCModelMeshLib, &zCModelMeshLib::AddMeshSoftSkin, 0x0059A000);
	ZENGIN_REGISTER_METHOD(zCModelMeshLib, &zCModelMeshLib::AddNodeVisual, 0x0059A100);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelMeshLib, &zCModelMeshLib::ApplyToModel, void(zCModelMeshLib::*)(zCModel*), 0x0059A220);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelMeshLib, &zCModelMeshLib::ApplyToModel, void(zCModelMeshLib::*)(zCModelPrototype*), 0x0059A380);
	ZENGIN_REGISTER_METHOD(zCModelMeshLib, &zCModelMeshLib::RemoveFromModel, 0x0059A500);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelMeshLib, &zCModelMeshLib::BuildFromModel, void(zCModelMeshLib::*)(zCModelPrototype*), 0x0059A5F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelMeshLib, &zCModelMeshLib::BuildFromModel, void(zCModelMeshLib::*)(zCModel*), 0x0059A800);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelMeshLib, &zCModelMeshLib::SaveMDM, void(zCModelMeshLib::*)(zCModelPrototype*), 0x0059AA50);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelMeshLib, &zCModelMeshLib::SaveMDM, void(zCModelMeshLib::*)(zCFileBIN&, zCModelPrototype*), 0x0059AC90);
	ZENGIN_REGISTER_METHOD(zCModelMeshLib, &zCModelMeshLib::_GetClassDef, 0x0057D310);

	ZENGIN_REGISTER_CLASS(zCModelAniEvent);
	ZENGIN_REGISTER_METHOD(zCModelAniEvent, &zCModelAniEvent::zCModelAniEvent_OnInit, 0x00586DB0);
	ZENGIN_REGISTER_METHOD(zCModelAniEvent, &zCModelAniEvent::Save, 0x00586F40);
	ZENGIN_REGISTER_METHOD(zCModelAniEvent, &zCModelAniEvent::Load, 0x005870A0);

	ZENGIN_REGISTER_CLASS(zCModelNode);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelNode, &zCModelNode::zCModelNode_OnInit, void(zCModelNode::*)(), 0x00582FD0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelNode, &zCModelNode::zCModelNode_OnInit, void(zCModelNode::*)(zCModelNode const&), 0x00583110);
	ZENGIN_REGISTER_METHOD(zCModelNode, &zCModelNode::SetNodeVisualS, 0x00583350);

	ZENGIN_REGISTER_CLASS(zCModelAni);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::zCModelAni_OnInit, 0x00583750);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::PrecacheAniEventData, 0x00583B90);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::GetAniVelocity, 0x00583C60);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::GetAniTranslation, 0x00583DF0);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::AddTrafoMatrix, 0x00583F60);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::GetQuat, 0x005844A0);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::GetTrans, 0x00584500);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::SetTrans, 0x005845B0);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::SetQuat, 0x00584630);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::AddNodeList, 0x005846D0);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::SetFlags, 0x00584750);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::SetBlendingSec, 0x00584800);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::GetBlendingSec, 0x00584860);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::CorrectRootNodeIdleMovement, 0x005848C0);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::CalcInPlaceFlag, 0x00584A30);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::ResolveAlias, 0x00584C10);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::ResolveComb, 0x00584F50);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::SaveMAN, 0x00585720);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::LoadMAN, 0x005860D0);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::GetAniName, 0x00598B90);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::GetAniType, 0x00598BA0);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::_GetClassDef, 0x005838F0);

	ZENGIN_REGISTER_CLASS(zCModelPrototype);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::zCModelPrototype_OnInit, 0x00587150);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::Init, 0x005873A0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::Clear, 0x00587800);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReleaseMeshSoftSkinList, 0x005879A0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReleaseMeshes, 0x00587A00);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::Release, 0x00587A90);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::GetModelProtoFileName, 0x00587AE0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::SetModelProtoName, 0x00587AF0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::SetFileSourceType, 0x00587C90);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::PrepareAsModelProtoOverlay, 0x00588070);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::CalcNodeListChecksum, 0x005884B0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::CollectNodeMeshes, 0x00588510);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::SearchNode, 0x00588770);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::FindMeshTreeNode, 0x00588820);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::FindMeshTreeNodeIndex, 0x005888C0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::FindNodeListIndex, 0x00588980);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::AddAni, 0x00588A20);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::SearchAniIndex, 0x00588C60);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::SearchAni, 0x00588D30);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::DescribeTree, 0x00588D50);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelPrototype, &zCModelPrototype::LoadMDH, int(zCModelPrototype::*)(zSTRING const&), 0x00588FD0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelPrototype, &zCModelPrototype::LoadMDH, int(zCModelPrototype::*)(zCFileBIN&), 0x00589250);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelPrototype, &zCModelPrototype::SaveMDH, void(zCModelPrototype::*)(), 0x005899A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelPrototype, &zCModelPrototype::SaveMDH, void(zCModelPrototype::*)(zCFileBIN&), 0x00589BD0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ConvertVec3, 0x0058A0F0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ConvertAngle, 0x0058A110);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::SkipBlock, 0x0058A120);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::SkipBlockCmt, 0x0058A1A0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadComment, 0x0058A2A0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadScene, 0x0058A2B0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadTriple, 0x0058A680);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadNodeTM, 0x0058A8B0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadVertexList, 0x0058AD80);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadFaceList, 0x0058B000);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadTVertexList, 0x0058B5A0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadTFaceList, 0x0058B7F0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadSoftSkinVertList, 0x0058BA90);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadMesh, 0x0058CDA0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadMeshAnimation, 0x0058D1C0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadPosTrack, 0x0058D340);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadRotTrack, 0x0058D550);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadTMAnimation, 0x0058D850);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::LocalizeTrafos, 0x0058DF50);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadMapDiffuse, 0x0058E0B0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadMaterial, 0x0058E530);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadWireframeColor, 0x0058EC00);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::AssignMeshNodeMaterials, 0x0058EEE0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::TransformNodeVisual, 0x0058EFF0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ProcessMeshNode, 0x0058F040);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadGeomobject, 0x0058F470);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadMaterialList, 0x00590B50);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::Load3DSMAXAsc, 0x00590DF0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::CalcAniBBox, 0x00591E80);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ResolveReferences, 0x00592450);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::SkipBlockMDS, 0x00592760);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadMeshAndTree, 0x005927E0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::RegisterMesh, 0x00592CF0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadStartMesh, 0x00592F60);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadAniEventTag, 0x00593110);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadAniEnum, 0x005933E0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadModel, 0x00598C60);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::LoadModelScript, 0x00598DC0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::LoadModelASC, 0x005993E0);

	ZENGIN_REGISTER_CLASS(zCModelAniActive);
	ZENGIN_REGISTER_METHOD(zCModelAniActive, &zCModelAniActive::zCModelAniActive_OnInit, 0x00575710);
	ZENGIN_REGISTER_METHOD(zCModelAniActive, &zCModelAniActive::SetDirection, 0x00575820);
	ZENGIN_REGISTER_METHOD(zCModelAniActive, &zCModelAniActive::GetProgressPercent, 0x00575870);
	ZENGIN_REGISTER_METHOD(zCModelAniActive, &zCModelAniActive::SetProgressPercent, 0x005758B0);
	ZENGIN_REGISTER_METHOD(zCModelAniActive, &zCModelAniActive::SetActFrame, 0x00575900);
	ZENGIN_REGISTER_METHOD(zCModelAniActive, &zCModelAniActive::DoCombineAni, 0x0057E780);

	ZENGIN_REGISTER_CLASS(zCModelTexAniState);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::zCModelTexAniState_OnInit, 0x00575950);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::DeleteTexList, 0x00575990);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::UpdateTexList, 0x005759B0);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::SetChannelVariation, 0x005759F0);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::BuildTexListFromMeshLib, 0x00575A60);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::BuildTexListFromMesh, 0x00575AE0);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::BuildTexListFromProgMesh, 0x00575C00);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::AddTexListFromMeshLib, 0x00575D70);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::AddTexListFromMesh, 0x00575FF0);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::AddTexListFromProgMesh, 0x00576170);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::FinishTexList, 0x005762E0);

	ZENGIN_REGISTER_CLASS(zCModelNodeInst);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelNodeInst, &zCModelNodeInst::zCModelNodeInst_OnInit, void(zCModelNodeInst::*)(), 0x00576430);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelNodeInst, &zCModelNodeInst::zCModelNodeInst_OnInit, void(zCModelNodeInst::*)(zCModelNode*), 0x00576500);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::Init, 0x00576670);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::InitByModelProtoNode, 0x00576700);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::SetNodeVisualS, 0x005767B0);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::AddNodeAni, 0x0057D3D0);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::RemoveAllNodeAnis, 0x0057D620);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::RemoveNodeAni, 0x0057D630);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::FindMasterAni, 0x0057D720);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::FadeOutNodeAni, 0x0057D790);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::CalcWeights, 0x0057DD70);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::AddToNodeAniWeight, 0x0057DFC0);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::CalcBlending, 0x0057E030);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::GetNodeAniListIndex, 0x0057E1B0);

	ZENGIN_REGISTER_CLASS(zTAniAttachment);
	ZENGIN_REGISTER_METHOD(zTAniAttachment, &zTAniAttachment::zTAniAttachment_OnInit, 0x00581870);

	ZENGIN_REGISTER_CLASS(zCModel);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::zCModel_OnInit, 0x00576D90);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetAniFromAniID, 0x00475680);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::IsAniActive, 0x004756D0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetAniIDFromAniName, 0x00489660);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::Init, 0x00576B60);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CopyProtoNodeList, 0x00576F30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::ApplyModelProtoOverlay, int(zCModel::*)(zSTRING const&), 0x00577340);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::ApplyModelProtoOverlay, int(zCModel::*)(zCModelPrototype*), 0x00577390);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::HasAppliedModelProtoOverlay, int(zCModel::*)(zCModelPrototype*) const, 0x005775A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::HasAppliedModelProtoOverlay, int(zCModel::*)(zSTRING const&) const, 0x005775D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::RemoveModelProtoOverlay, void(zCModel::*)(zSTRING const&), 0x00577780);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::RemoveModelProtoOverlay, void(zCModel::*)(zCModelPrototype*), 0x005779A0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CalcNodeListBBoxWorld, 0x00577B20);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetBBox3DNodeWorld, 0x00577C60);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetNodePositionWorld, 0x00577CD0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CalcModelBBox3DWorld, 0x00577D10);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetNodeVisual, 0x00577E20);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetDynLightMode, 0x00577E50);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RenderNodeList, 0x00577E70);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CheckNodeCollisionList, 0x00578E70);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CheckNodeCollision, 0x00578F10);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetTrafoNodeToModel, 0x00579080);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetRandAnisEnabled, 0x005791B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::GetActiveAni, zCModelAniActive*(zCModel::*)(int) const, 0x00579220);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::GetActiveAni, zCModelAniActive*(zCModel::*)(zCModelAni*) const, 0x00579260);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::StopAni, void(zCModel::*)(int), 0x005792A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::StopAni, void(zCModel::*)(zCModelAni*), 0x00579320);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::StopAni, void(zCModel::*)(zCModelAniActive*), 0x00579370);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetAniTransLerp, 0x00579550);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::StartAni, void(zCModel::*)(zSTRING const&, int), 0x005796F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::StartAni, void(zCModel::*)(int, int), 0x00579960);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::StartAni, void(zCModel::*)(zCModelAni*, int), 0x005799D0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::AssertActiveAniListAlloced, 0x0057A0C0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::DoAniEvents, 0x0057A1F0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::AdvanceAni, 0x0057B150);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::AdvanceAnis, 0x0057B430);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetModelScale, 0x0057C430);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::IsStateActive, 0x0057C5B0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SearchNode, 0x0057C810);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetNodeMeshTexture, 0x0057C8C0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetMeshLibTexture, 0x0057C9E0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RemoveMeshLibAll, 0x0057CC20);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RemoveMeshLib, 0x0057CC50);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::ApplyMeshLib, 0x0057CEA0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::UpdateMeshLibTexAniState, 0x0057D350);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::FadeOutAni, void(zCModel::*)(int), 0x0057D850);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::FadeOutAni, void(zCModel::*)(zCModelAni*), 0x0057D8D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::FadeOutAni, void(zCModel::*)(zCModelAniActive*), 0x0057D910);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::FadeOutAnisLayerRange, 0x0057DAE0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::StopAnisLayerRange, 0x0057DB30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::GetProgressPercent, float(zCModel::*)(zSTRING const&) const, 0x0057DB80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::GetProgressPercent, float(zCModel::*)(int) const, 0x0057DC40);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetCombineAniXY, 0x0057DCB0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetCombineAniXY, 0x0057DD00);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CalcNodeListAniBlending, 0x0057E180);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CalcTransBlending, 0x0057E1E0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::AttachChildVobToNode, 0x0057F0D0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RemoveChildVobFromNode, 0x0057F260);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RemoveAllChildVobsFromNode, 0x0057F2E0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::UpdateAttachedVobs, 0x0057F330);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RemoveStartedVobFX, 0x0057F480);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RemoveAllVobFX, 0x0057F530);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetVelocityRing, 0x0057F5C0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::ResetVelocity, 0x0057F630);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetAniMinMaxWeight, 0x0057F6C0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::PrintStatus, 0x0057F910);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::psb_WriteAniBlock, 0x00580010);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::psb_ReadAniBlock, 0x005801A0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::PackStateBinary, 0x00580410);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::UnpackStateBinary, 0x00580770);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::ShowAniListAdd, 0x00580F60);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::ShowAniList, 0x00580FD0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SearchAniAttachList, 0x005818B0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RemoveAniAttachment, 0x00581950);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RemoveAllAniAttachments, 0x00581AD0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetCreateAniAttachment, 0x00581B30);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::DeleteRandAniList, 0x00581D10);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::InsertRandAni, 0x00581DB0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetRandAniFreq, 0x00581EE0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetRandAniFreq, 0x00581F80);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RecalcRootPosLocal, 0x00581FA0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::_GetClassDef, 0x005751A0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::Render, 0x00578BD0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::IsBBox3DLocal, 0x005751B0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetBBox3D, 0x0057C730);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetVisualName, 0x0057C770);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetVisualUsedBy, 0x00577210);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetRenderSortKey, 0x00581040);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CanTraceRay, 0x005751C0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::TraceRay, 0x00581060);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::HostVobRemovedFromWorld, 0x0057A140);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetFileExtension, 0x00577280);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::LoadVisualVirtual, 0x005772A0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::StartAnimation, 0x005751D0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::StopAnimation, 0x005751E0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::IsAnimationActive, 0x00575280);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetAnyAnimation, 0x005794F0);

	ZENGIN_REGISTER_CLASS(zCModelConvertFileHandler);
	ZENGIN_REGISTER_METHOD(zCModelConvertFileHandler, &zCModelConvertFileHandler::zCModelConvertFileHandler_OnInit, 0x0059C6C0);
	ZENGIN_REGISTER_METHOD(zCModelConvertFileHandler, &zCModelConvertFileHandler::HandleFile, 0x0059C7F0);

} // namespace Gothic_I_Addon
