namespace Gothic_I_Addon {

	ZENGIN_REGISTER_CLASS(zCPar_TreeNode);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPar_TreeNode, &zCPar_TreeNode::zCPar_TreeNode_OnInit, void(zCPar_TreeNode::*)(), 0x00727490);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPar_TreeNode, &zCPar_TreeNode::zCPar_TreeNode_OnInit, void(zCPar_TreeNode::*)(int, int), 0x007274D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPar_TreeNode, &zCPar_TreeNode::zCPar_TreeNode_OnInit, void(zCPar_TreeNode::*)(int, zSTRING&, int), 0x00727520);
	ZENGIN_REGISTER_METHOD(zCPar_TreeNode, &zCPar_TreeNode::SetLeft, 0x00727770);
	ZENGIN_REGISTER_METHOD(zCPar_TreeNode, &zCPar_TreeNode::SetRight, 0x00727780);
	ZENGIN_REGISTER_METHOD(zCPar_TreeNode, &zCPar_TreeNode::SetNext, 0x00727790);

	ZENGIN_REGISTER_CLASS(zCPar_File);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::zCPar_File_OnInit, 0x0071C6A0);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::IsNewerDate, 0x0071C780);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::IsExactDate, 0x0071C820);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::SetFileNumber, 0x0071C8B0);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::GetFileNumber, 0x0071C8C0);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::GetName, 0x0071C8D0);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::EnableTreeLoad, 0x0071C920);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::Load, 0x0071C930);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::GetStartAddress, 0x0071CBB0);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::GetEndAddress, 0x0071CBC0);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::Dispose, 0x0071CBD0);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::SetTree, 0x0071CBF0);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::GetTree, 0x0071CC30);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::SetLabelCount, 0x0071CC40);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::GetLabelCount, 0x0071CC50);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::SaveTree, 0x0071CC60);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::SaveTreeNode, 0x0071CF10);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::LoadTreeNode, 0x0071D080);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::LoadTree, 0x0071D1C0);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::DeleteTree, 0x0071D630);

	ZENGIN_REGISTER_CLASS(zCParser);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::zCParser_OnInit, 0x0071D670);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SetMessageFunc, 0x0071DA00);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SetStopOnError, 0x0071DA10);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::Error, void(zCParser::*)(zSTRING&, int), 0x0071DA20);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::Message, 0x0071DDD0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::Error, int(zCParser::*)(), 0x0071DF40);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SaveDat, 0x0071DF50);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::LoadDat, 0x0071E130);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::Parse, 0x0071E400);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ParseSource, 0x0071E6D0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ParseFile, 0x0071F050);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ParseBlock, 0x0071F8E0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::CreatePCode, 0x0071FBA0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ShowSymbols, 0x007202C0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::PushTree, 0x007202D0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::PushOnStack, 0x007202F0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SolveLabels, 0x00721210);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::MergeFile, 0x00721270);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::PopDataValue, 0x007214F0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::PopFloatValue, 0x00721520);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::PopVarAddress, 0x00721560);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::PopString, 0x00721590);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DoStack, 0x007215B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::CallFunc, void*(zCParser::*)(zSTRING const&), 0x00722640);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::CallFunc, void*(__cdecl zCParser::*)(int, ...), 0x00722660);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetCurrentFunc, 0x00722B80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::CreateInstance, int(zCParser::*)(zSTRING&, void*), 0x00722B90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::CreateInstance, int(zCParser::*)(int, void*), 0x00722C10);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::CreatePrototype, int(zCParser::*)(zSTRING&, void*), 0x00722C80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::CreatePrototype, int(zCParser::*)(int, void*), 0x00722D00);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::Reset, 0x00722D70);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SetPercentDone, 0x00722EE0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::CreateHelpers, 0x00722F50);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::EnableTreeSave, 0x007230F0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::EnableDatSave, 0x00723100);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::EnableTreeLoad, 0x00723110);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetIndex, 0x00723120);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::MatchClass, 0x007231F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetBaseClass, int(zCParser::*)(zCPar_Symbol*), 0x00723270);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetBaseClass, int(zCParser::*)(int), 0x007232D0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetBase, 0x00723330);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetPrototype, 0x00723380);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetInstance, int(zCParser::*)(int, int), 0x007233F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetSymbolInfo, zSTRING(zCParser::*)(int, int&, int&), 0x007234A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetSymbolInfo, zCPar_Symbol*(zCParser::*)(int), 0x00723560);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetSymbol, zCPar_Symbol*(zCParser::*)(int), 0x00723570);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetSymbol, zCPar_Symbol*(zCParser::*)(zSTRING const&), 0x00723580);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetClassVarInfo, zSTRING(zCParser::*)(int, int, int&, int&), 0x00723650);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetClassVarInfo, void(zCParser::*)(int, zSTRING&, int&, int&), 0x007238C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetText, zSTRING(zCParser::*)(zSTRING&, int), 0x00723AE0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetText, zSTRING(zCParser::*)(int, int), 0x00723B20);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetInt, 0x00723C30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetInstanceValue, zSTRING(zCParser::*)(zSTRING&, int, void*, int), 0x00723C80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetInstanceValue, zSTRING(zCParser::*)(int, int, void*, int), 0x00723D80);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::IsValid, 0x00724070);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::CheckClassSize, int(zCParser::*)(zSTRING&, int), 0x007241F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::CheckClassSize, int(zCParser::*)(int, int), 0x00724210);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::AddClassOffset, 0x007244E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::SetInstance, int(zCParser::*)(zSTRING const&, void*), 0x00724640);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::SetInstance, int(zCParser::*)(int, void*), 0x00724680);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::AutoCompletion, 0x007246C0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetNumFiles, 0x00724910);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetFileName, 0x00724920);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::IsStackFull, 0x007249C0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetLastErrorLine, 0x007249D0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::Reparse, 0x007249E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::SaveInstance, int(zCParser::*)(zSTRING&, void*), 0x00724B10);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::SaveInstance, int(zCParser::*)(int, void*), 0x00724B40);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::CloseViews, 0x007258D0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ShowCode, 0x00725900);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SaveInfoFile, 0x00725A60);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SetInfoFile, 0x00726100);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::IsInAdditionalInfo, 0x00726270);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::WriteAdditionalInfo, 0x00726440);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ClearAllInstanceRefs, 0x007267D0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ClearInstanceRefs, 0x00726840);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ResetGlobalVars, 0x007268D0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::CreateVarReferenceList, 0x00726930);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ResetWithVarReferenceList, 0x00726AD0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SaveGlobalVars, 0x00726B50);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::LoadGlobalVars, 0x00726EA0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetOperatorString, 0x007278B0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::FindNext, 0x00727E60);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::PrevWord, 0x00727FE0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ReadWord, 0x00728010);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::Match, 0x00728290);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ReadVarType, 0x00728460);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ReadFuncType, 0x007286B0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ReadInt, 0x007288F0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ReadFloat, 0x00728BC0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ReadString, 0x00728F10);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ReadArray, 0x00729230);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::CreateLeaf, 0x00729470);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::CreateStringLeaf, 0x007294E0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::CreateFloatLeaf, 0x00729770);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetNextToken, 0x00729920);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::Parse_Expression_Primary, 0x0072A210);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::Parse_Expression, 0x0072A880);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ParseExpressionEx, 0x0072AAB0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ParseExpression, 0x0072AB20);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::EvalLeaf, 0x0072AB40);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareVar, 0x0072B060);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareClass, 0x0072C4D0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareInstance, 0x0072C6E0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclarePrototype, 0x0072CFD0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareIf, 0x0072D570);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareAssign, 0x0072DA10);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareAssignFunc, 0x0072E260);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareFunc, 0x0072E570);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareReturn, 0x0072EAA0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareFuncCall, 0x0072ECA0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SearchFuncWithStartAddress, 0x0072F700);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetNextCommand, 0x0072F780);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ShowPCodeSpy, 0x00730450);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ShowPCode, 0x00730590);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DefineExternal, 0x00730820);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DefineExternalVar, 0x00730C00);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetParameter, void(zCParser::*)(int&), 0x00730E40);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetParameter, void(zCParser::*)(float&), 0x00730E50);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetParameter, void(zCParser::*)(zSTRING&), 0x00730E90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetInstance, void*(zCParser::*)(), 0x00730FD0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::SetReturn, void(zCParser::*)(int), 0x00731000);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::SetReturn, void(zCParser::*)(float), 0x00731020);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::SetReturn, void(zCParser::*)(void*), 0x00731040);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::SetReturn, void(zCParser::*)(zSTRING&), 0x00731080);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::FindInstanceVar, 0x007310A0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetLastInstance, 0x007312F0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::FindIndex, 0x00731300);

} // namespace Gothic_I_Addon
