namespace Gothic_I_Addon {

	ZENGIN_REGISTER_CLASS(zSTRING);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(char const*), 0x004010C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(), 0x00402F90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(zSTRING const&), 0x00417CA0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(int), 0x0046D520);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(long), 0x0046D620);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(unsigned long), 0x0046D720);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(float, int), 0x0046D820);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(double, int), 0x0046D970);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(char), 0x0051FA10);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(zSTRING const*), 0x00722540);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::ToChar, 0x00465C00);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Clear, 0x00598A50);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::IsEmpty, 0x0077F500);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Lower, 0x0046CF70);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Upper, 0x0046D090);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::UpperFirstLowerRest, 0x0046D1B0);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Align, 0x0046D300);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::PickWord, 0x0046DAC0);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::PickWordPos, 0x0046DDB0);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::PickWord_Old, 0x0046DF30);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Insert, 0x0046E010);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Inserted, 0x0046E140);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Overwrite, 0x0046E2E0);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Overwritten, 0x0046E4E0);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::DeleteRight, 0x0046E600);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Delete, int(zSTRING::*)(unsigned int, unsigned long), 0x0046E710);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Deleted, zSTRING(zSTRING::*)(unsigned int, unsigned long) const, 0x0046E820);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Delete, int(zSTRING::*)(zSTRING const&, zTSTR_KIND), 0x0046E980);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Deleted, zSTRING(zSTRING::*)(zSTRING const&, zTSTR_KIND) const, 0x0046EB60);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Copied, zSTRING(zSTRING::*)(unsigned int, unsigned long) const, 0x0046EE10);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Copy, int(zSTRING::*)(zSTRING const&, zTSTR_KIND const&), 0x0046EFA0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Copy, int(zSTRING::*)(unsigned int, unsigned long), 0x0046EC60);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Copied, zSTRING(zSTRING::*)(zSTRING const&, zTSTR_KIND const&) const, 0x0046F260);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::TrimLeft, 0x0046F360);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::TrimRight, 0x0046F4A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Search, int(zSTRING::*)(int, char const*, unsigned int) const, 0x0046F650);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::SearchRev, 0x0046F760);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Sprintf, 0x0046F9F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Search, int(zSTRING::*)(zSTRING const&, unsigned int) const, 0x00495310);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::ToInt, 0x00598B20);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::ToFloat, 0x00598B40);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Search, int(zSTRING::*)(char const*, unsigned int) const, 0x00598B60);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Init, 0x00629900);

} // namespace Gothic_I_Addon
