namespace Gothic_I_Addon {

	ZENGIN_REGISTER_CLASS(zCOLOR);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCOLOR, &zCOLOR::zCOLOR_OnInit, void(zCOLOR::*)(int), 0x004021F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCOLOR, &zCOLOR::zCOLOR_OnInit, void(zCOLOR::*)(unsigned char, unsigned char, unsigned char, unsigned char), 0x0071A280);
	ZENGIN_REGISTER_METHOD(zCOLOR, &zCOLOR::Reset, 0x00571AA0);
	ZENGIN_REGISTER_METHOD(zCOLOR, &zCOLOR::GetVEC3, 0x005B4050);
	ZENGIN_REGISTER_METHOD(zCOLOR, &zCOLOR::GetDescription, 0x005EE8C0);
	ZENGIN_REGISTER_METHOD(zCOLOR, &zCOLOR::SetByDescription, 0x005EEBC0);
	ZENGIN_REGISTER_METHOD(zCOLOR, &zCOLOR::GetDescriptionRGB, 0x005EEE90);
	ZENGIN_REGISTER_METHOD(zCOLOR, &zCOLOR::SetRGB, 0x0061D320);

	ZENGIN_REGISTER_CLASS(zTPlane);
	ZENGIN_REGISTER_METHOD(zTPlane, &zTPlane::EqualTo, 0x005EF0F0);
	ZENGIN_REGISTER_METHOD(zTPlane, &zTPlane::Opposite, 0x005EF1A0);
	ZENGIN_REGISTER_METHOD(zTPlane, &zTPlane::ClassifyPoint, 0x005EF1E0);
	ZENGIN_REGISTER_METHOD(zTPlane, &zTPlane::ClassifyPointBSPBuild, 0x005EF230);
	ZENGIN_REGISTER_METHOD(zTPlane, &zTPlane::CalcSignbits, 0x005EF280);
	ZENGIN_REGISTER_METHOD(zTPlane, &zTPlane::Print, 0x005EF2E0);
	ZENGIN_REGISTER_METHOD(zTPlane, &zTPlane::Intersection, 0x005EF650);
	ZENGIN_REGISTER_METHOD(zTPlane, &zTPlane::IntersectionFront, 0x005EF740);
	ZENGIN_REGISTER_METHOD(zTPlane, &zTPlane::Calc, 0x005EF830);
	ZENGIN_REGISTER_METHOD(zTPlane, &zTPlane::GetOriginUpRight, 0x005EF920);

} // namespace Gothic_I_Addon
