namespace Gothic_I_Addon {

	ZENGIN_REGISTER_CLASS(zCVisual);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::zCVisual_OnInit, 0x005F96C0);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::AddNextLODVisual, 0x005F9890);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::AddEndLODVisual, 0x005F98C0);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::_GetClassDef, 0x004D0650);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::IsBBox3DLocal, 0x00568100);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::GetOBBox3D, 0x004D0660);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::GetVisualDied, 0x004D0670);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::SetVisualUsedBy, 0x00568110);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::DynLightVisual, 0x004D0680);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::GetRenderSortKey, 0x004D0690);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::CanTraceRay, 0x004D06A0);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::TraceRay, 0x005F9960);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::HostVobRemovedFromWorld, 0x004D06B0);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::HostVobAddedToWorld, 0x004D06C0);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::GetFileExtension, 0x004D06D0);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::GetLODVisualAndAlpha, 0x005F98F0);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::LoadVisualVirtual, 0x004D06E0);

	ZENGIN_REGISTER_CLASS(zCVisualAnimate);
	ZENGIN_REGISTER_METHOD(zCVisualAnimate, &zCVisualAnimate::_GetClassDef, 0x00575170);

	ZENGIN_REGISTER_CLASS(zCDecal);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::zCDecal_OnInit, 0x005597A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCDecal, &zCDecal::SetTexture, void(zCDecal::*)(zSTRING&), 0x00559BE0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCDecal, &zCDecal::SetTexture, void(zCDecal::*)(zCTexture*), 0x00559BF0);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::SetDecalDim, 0x00559C00);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::_GetClassDef, 0x00559780);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::Archive, 0x00559F30);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::Unarchive, 0x0055A000);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::Render, 0x00559C20);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::IsBBox3DLocal, 0x00559790);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::GetBBox3D, 0x00559D70);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::GetVisualName, 0x00559DC0);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::SetVisualUsedBy, 0x00559D60);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::DynLightVisual, 0x00559E10);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::GetRenderSortKey, 0x00559BD0);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::GetFileExtension, 0x005599F0);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::LoadVisualVirtual, 0x00559A50);

	ZENGIN_REGISTER_CLASS(zCMesh);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::zCMesh_OnInit, 0x00567EC0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::LODRecalcEdge, 0x0053F620);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::LODGenerate, 0x0053FE30);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::DeleteAll, 0x00568370);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::VertexInMesh, 0x005692D0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::AllocVerts, 0x005693A0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::AllocPolys, 0x005694A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::AddVertex, zCVertex*(zCMesh::*)(zCVertex*), 0x00569570);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::AddVertex, zCVertex*(zCMesh::*)(zVEC3&), 0x005696F0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::AddVertexSmart, 0x00569850);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::AddPoly, zCPolygon*(zCMesh::*)(zVEC3&, zVEC3&, zVEC3&, zVEC2&, zVEC2&, zVEC2&), 0x00569980);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::AddPoly, zCPolygon*(zCMesh::*)(zCVertex*, zCVertex*, zCVertex*), 0x00569C30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::AddPoly, zCPolygon*(zCMesh::*)(zCVertex*, zCVertex*, zCVertex*, zCVertex*), 0x00569D50);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::AddPoly, zCPolygon*(zCMesh::*)(zCPolygon*), 0x00569E80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::AddPoly, zCPolygon*(zCMesh::*)(), 0x00569F30);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::DeletePoly, 0x0056A030);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::DynLightScalePrelit, 0x0056A120);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::PrelightMesh, 0x0056A130);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SharePoly, 0x0056A5B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::CheckRayPolyIntersection, zCPolygon*(zCMesh::*)(zVEC3 const&, zVEC3 const&, zVEC3&), 0x0056A5E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::CheckRayPolyIntersection, zCPolygon*(zCMesh::*)(zCCamera&, int, int, zVEC3&), 0x0056A640);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::PickPolygon, zCPolygon*(zCMesh::*)(zVEC3 const&, zVEC3 const&, zVEC3&), 0x0056A7C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::PickPolygon, zCPolygon*(zCMesh::*)(zCCamera&, int, int, zVEC3&), 0x0056A890);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::CalcVertexNormals, 0x0056ABE0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::UnSmoothMesh, 0x0056B2A0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SetDefaultPlanarMapping, 0x0056B340);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::CalcBBox3D, 0x0056B3D0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::Center, 0x0056B540);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::TransformAllVerts, 0x0056B6B0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::MergeMesh, 0x0056B790);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::CalcNormals, 0x0056BB80);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SetMaterial, 0x0056BBB0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::ScaleXZ, 0x0056BC10);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::Scale, 0x0056BC70);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::CheckForMaterials, 0x0056BD20);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::Render_novt, 0x0056BEF0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::RenderDecal, void(zCMesh::*)(float, float, float, int), 0x0056C1E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::RenderDecal, void(zCMesh::*)(zTRenderContext&, int), 0x0056C3B0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::ResetStaticLight, 0x0056C620);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SetStaticLight, 0x0056C660);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SetLightDyn, 0x0056C6A0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SetLightStatAlpha, 0x0056C6E0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::ResetLightDynToLightStat, 0x0056C720);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::AddToLightDyn, 0x0056C760);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::SaveMSH, void(zCMesh::*)(zCFileBIN&), 0x0056DDF0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::SaveMSH, void(zCMesh::*)(zSTRING const&), 0x0056DE10);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::LoadMSH, int(zCMesh::*)(zCFileBIN&, int), 0x0056F2E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::LoadMSH, int(zCMesh::*)(zSTRING const&, int), 0x00570860);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::CreateListsFromArrays, 0x00570B30);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::ClearLists, 0x00570C30);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::ArraysToLists, 0x00570C90);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::ShareFeatures, 0x00570D70);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::UnshareFeatures, 0x00571B10);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::FlipPolys, 0x00571C30);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SortPolysByMaterial, 0x00571C80);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SortPolysByList, 0x00571D30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::DeletePolyAndVerts, void(zCMesh::*)(zCPolygon*), 0x00572630);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::DeletePolyAndVerts, void(zCMesh::*)(unsigned long), 0x005726C0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::RemoveDegeneratePolys, 0x00572850);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::CombineLightmaps, 0x00572A10);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::LightMesh, 0x0061C6F0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::_GetClassDef, 0x00568120);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::Render, 0x0056BE70);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::GetBBox3D, 0x00568180);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::GetOBBox3D, 0x005681B0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::GetVisualName, 0x00568130);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::DynLightVisual, 0x0056A110);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::CanTraceRay, 0x005681C0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::TraceRay, 0x0056AA60);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::GetFileExtension, 0x00568340);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::LoadVisualVirtual, 0x00568360);

} // namespace Gothic_I_Addon
