namespace Gothic_I_Addon {

	ZENGIN_REGISTER_CLASS(zCEventMessage);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCEventMessage, &zCEventMessage::zCEventMessage_OnInit, void(zCEventMessage::*)(), 0x00415000);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCEventMessage, &zCEventMessage::zCEventMessage_OnInit, void(zCEventMessage::*)(unsigned short), 0x005F8530);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::GetMessageID, 0x005F86A0);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::PackToBuffer, 0x005F8700);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::GetSubType, 0x0077F580);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::_GetClassDef, 0x00402200);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::Archive, 0x005F8790);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::Unarchive, 0x005F89E0);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::IsOverlay, 0x00402210);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::IsNetRelevant, 0x00402220);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::IsHighPriority, 0x00402230);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::IsJob, 0x00402240);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::Delete, 0x00402250);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::IsDeleteable, 0x00402260);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::IsDeleted, 0x00402270);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::SetCutsceneMode, 0x00402280);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::GetCutsceneMode, 0x00402290);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::MD_GetNumOfSubTypes, 0x004022A0);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::MD_GetSubTypeString, 0x004022B0);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::MD_GetVobRefName, 0x00402300);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::MD_SetVobRefName, 0x00402350);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::MD_SetVobParam, 0x00402360);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::MD_GetTimeBehavior, 0x00402370);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::MD_GetMinTime, 0x00402380);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::Pack, 0x00402390);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::Unpack, 0x004023A0);

	ZENGIN_REGISTER_CLASS(zCEventCore);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::Clear, 0x005F9100);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::_GetClassDef, 0x00402410);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::Archive, 0x005F9550);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::Unarchive, 0x005F95C0);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::IsNetRelevant, 0x00402430);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::MD_GetNumOfSubTypes, 0x00402420);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::MD_GetSubTypeString, 0x005F9340);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::Pack, 0x005F9160);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::Unpack, 0x005F9210);

	ZENGIN_REGISTER_CLASS(zCVob);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::zCVob_OnInit, 0x005F2220);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::GetPositionWorld, zVEC3(zCVob::*)() const, 0x00489680);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetUpVectorWorld, 0x00494290);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetAtVectorWorld, 0x00514C80);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetRightVectorWorld, 0x00531060);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetVobID, 0x005F2900);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetAI, 0x005F2910);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetVobPresetName, 0x005F2960);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetVobPresetName, 0x005F2970);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetRigidBody, 0x005F2980);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ArchivePacked, 0x005F2A00);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ArchiveVerbose, 0x005F2E60);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::UnarchivePacked, 0x005F3270);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::UnarchiveVerbose, 0x005F3740);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetVobName, 0x005F3D40);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetEM, 0x005F3D80);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CalcLightSampleAtOrigin, 0x005F40A0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetLightColorStat, 0x005F4120);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetLightColorDyn, 0x005F43C0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CalcStaticLight, 0x005F45E0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetSectorNameVobIsIn, 0x005F4B10);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetGroundShadowSize, 0x005F4C80);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetGroundShadowSize, 0x005F4CC0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RenderGroundShadow, 0x005F4D10);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetClassHelperVisual, 0x005F51D0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CalcRenderAlpha, 0x005F53E0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetLightColorAtCenter, 0x005F59F0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RemoveVobFromWorld, 0x005F5BB0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RemoveVobSubtreeFromWorld, 0x005F5BD0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::AddRefVobSubtree, 0x005F5C30);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ReleaseVobSubtree, 0x005F5C70);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RemoveWorldDependencies, 0x005F5CD0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RemoveVobFromGlobalVobTree, 0x005F5F20);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RemoveVobFromBspTree, 0x005F6000);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetVobInfo, 0x005F6020);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetSleeping, 0x005F68A0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::UpdateVisualDependencies, 0x005F6AA0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::AddVobToWorld_CorrectParentDependencies, 0x005F6B30);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ResetOnTimer, 0x005F6B50);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetOnTimer, 0x005F6B60);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::IsOnTimer, 0x005F6B90);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ProcessOnTimer, 0x005F6BB0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::DoFrameActivity, 0x005F6BE0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CheckModelLimbCollision, 0x005F6E60);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::GetTrafoModelNodeToWorld, zMAT4(zCVob::*)(zSTRING const&), 0x005F7AD0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::GetTrafoModelNodeToWorld, zMAT4(zCVob::*)(zCModelNodeInst*), 0x005F7C20);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetScreenBBox2D, 0x005F7CF0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::PackStateBinary, 0x005F80C0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::UnpackStateBinary, 0x005F81A0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetVisual, 0x0060A0A0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CalcGroundPoly, 0x0060DFE0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetCollTypeDefaultFromVisual, 0x0060E170);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::TouchMovement, 0x0060E2E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::GetNewTrafoObjToWorld, zMAT4 const&(zCVob::*)() const, 0x0060E300);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::GetNewTrafoObjToWorld, zMAT4&(zCVob::*)(), 0x0060E320);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetNewTrafoObjToWorld, 0x0060E340);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetBBox3DWorld, 0x0060E360);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetBBox3DLocal, 0x0060E3C0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetBBox3DLocal, 0x0060E470);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::Move, void(zCVob::*)(float, float, float), 0x0060E5A0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::MoveWorld, 0x0060E610);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::MoveLocal, 0x0060E680);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetRotationWorld, 0x0060E770);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RotateWorld, 0x0060E7D0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RotateLocal, 0x0060E8E0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RotateLocalX, 0x0060E980);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RotateLocalY, 0x0060E9F0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RotateLocalZ, 0x0060EA60);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RotateWorldX, 0x0060EAD0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RotateWorldY, 0x0060EB00);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RotateWorldZ, 0x0060EB30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::GetPositionWorld, void(zCVob::*)(float&, float&, float&) const, 0x0060EB60);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetPositionLocal, 0x0060EBA0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetDistanceToVob, 0x0060EBF0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetDistanceToVobApprox, 0x0060EC90);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetDistanceToVob2, 0x0060EDA0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetPositionLocal, 0x0060EE40);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetPositionWorld, 0x0060EF20);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetTrafo, 0x0060EF80);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetTrafoObjToWorld, 0x0060F030);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ResetRotationsLocal, 0x0060F090);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ResetXZRotationsLocal, 0x0060F1E0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ResetRotationsWorld, 0x0060F430);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ResetXZRotationsWorld, 0x0060F4D0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetHeadingYLocal, 0x0060F680);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::SetHeadingYWorld, void(zCVob::*)(zVEC3 const&), 0x0060F770);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::SetHeadingYWorld, void(zCVob::*)(zCVob*), 0x0060F860);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetHeadingLocal, 0x0060F9A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::SetHeadingWorld, void(zCVob::*)(zVEC3 const&), 0x0060FA80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::SetHeadingWorld, void(zCVob::*)(zCVob*), 0x0060FB60);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetHeadingAtLocal, 0x0060FC90);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::HasParentVob, 0x00610090);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetHeadingAtWorld, 0x006100B0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetCollDetStat, 0x006103D0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetCollDetDyn, 0x006104E0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CorrectTrafo, 0x006105F0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::DoneWithTrafoLocal, 0x00610660);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CreateTrafoLocal, 0x006106B0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetPhysicsEnabled, 0x00610750);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetVelocity, 0x00610780);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::UpdatePhysics, 0x006108C0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::DetectCollision, 0x00610F40);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetInMovement, 0x00611080);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetInMovementMode, 0x006110E0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::BeginMovement, 0x00611130);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ResetToOldMovementState, 0x006112E0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::UpdateTouchList, 0x00611310);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CalcDestinationBBox3DWorld, 0x006115A0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::AdoptCollObjResults, 0x00611790);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetCollisionObject, 0x00611D40);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetCollisionClass, 0x00611D70);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetCollisionObject, 0x00611DB0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CreateCollisionObject, 0x00611DC0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ResetCollisionObjectState, 0x00611DF0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::DestroyCollisionObject, 0x00611E30);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CheckEmergencyPutToSleep, 0x00611E70);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CollectCollisionContext_Vobs, 0x00612030);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CollectCollisionContext_Static, 0x006122A0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CollectCollisionContext, 0x006125A0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CleanupCollisionContext, 0x00612620);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::NotifyCollisionPair, 0x00612690);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ExecuteCollisionResponse, 0x00612760);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CheckAndResolveCollisions, 0x00612850);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::IsColliding, 0x00612CE0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::Move, void(zCVob::*)(zVEC3 const&), 0x0064FA60);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetStaticVob, 0x0066C900);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetVobType, 0x0066C920);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetDrawBBox3D, 0x0066C930);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetCollDet, 0x0066C950);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetHomeWorld, 0x0077F590);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::_GetClassDef, 0x0043DCA0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::Archive, 0x005F31B0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::Unarchive, 0x005F3BE0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnTrigger, 0x005F21B0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnUntrigger, 0x005F21C0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnTouch, 0x005F21D0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnUntouch, 0x005F21E0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnTouchLevel, 0x005F21F0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnDamage, 0x005F2200);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnMessage, 0x005F2210);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnTick, 0x004048C0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnTimer, 0x0043DCB0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::PostLoad, 0x004048D0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetCharacterClass, 0x004048E0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetSleepingMode, 0x005F68C0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::EndMovement, 0x00611840);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CanThisCollideWith, 0x004048F0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::Render, 0x005F5510);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::SetVisual, void(zCVob::*)(zCVisual*), 0x005F63E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::SetVisual, void(zCVob::*)(zSTRING const&), 0x005F6570);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetScriptInstance, 0x00404900);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetByScriptInstance, 0x00404920);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetCSStateFlags, 0x00404930);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::TraceRay, 0x005F3DB0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetTriggerTarget, 0x0043DCC0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ThisVobAddedToWorld, 0x005F5BF0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ThisVobRemovedFromWorld, 0x005F5C10);

	ZENGIN_REGISTER_CLASS(zCVob::zTModelLimbColl);
	ZENGIN_REGISTER_METHOD(zCVob::zTModelLimbColl, &zCVob::zTModelLimbColl::zTModelLimbColl_OnInit, 0x005F7A70);

	ZENGIN_REGISTER_CLASS(zCVobLightData);
	ZENGIN_REGISTER_METHOD(zCVobLightData, &zCVobLightData::zCVobLightData_OnInit, 0x005FD8C0);
	ZENGIN_REGISTER_METHOD(zCVobLightData, &zCVobLightData::SetLensFlareFXByName, 0x005FC7E0);
	ZENGIN_REGISTER_METHOD(zCVobLightData, &zCVobLightData::GetLensFlareFXName, 0x005FC900);
	ZENGIN_REGISTER_METHOD(zCVobLightData, &zCVobLightData::Archive, 0x005FC920);
	ZENGIN_REGISTER_METHOD(zCVobLightData, &zCVobLightData::Unarchive, 0x005FCE10);
	ZENGIN_REGISTER_METHOD(zCVobLightData, &zCVobLightData::SetRange, 0x005FD9A0);

	ZENGIN_REGISTER_CLASS(zCVobLightPreset);
	ZENGIN_REGISTER_METHOD(zCVobLightPreset, &zCVobLightPreset::_GetClassDef, 0x005F16B0);
	ZENGIN_REGISTER_METHOD(zCVobLightPreset, &zCVobLightPreset::Archive, 0x005FC600);
	ZENGIN_REGISTER_METHOD(zCVobLightPreset, &zCVobLightPreset::Unarchive, 0x005FC630);

	ZENGIN_REGISTER_CLASS(zCVobLight);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::zCVobLight_OnInit, 0x005FAFC0);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::DoAnimation, 0x005FB340);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::SetRange, 0x005FB5F0);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::AddThisToPresetList, 0x005FBC00);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::SetByPreset, 0x005FBF00);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::SetByPresetInUse, 0x005FC1A0);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::_GetClassDef, 0x005FAF60);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::Archive, 0x005FC3F0);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::Unarchive, 0x005FC440);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::OnTrigger, 0x005FB1D0);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::OnUntrigger, 0x005FB2A0);

	ZENGIN_REGISTER_CLASS(zCVobLevelCompo);
	ZENGIN_REGISTER_METHOD(zCVobLevelCompo, &zCVobLevelCompo::zCVobLevelCompo_OnInit, 0x005F8250);
	ZENGIN_REGISTER_METHOD(zCVobLevelCompo, &zCVobLevelCompo::HasIdentityTrafo, 0x005F82B0);
	ZENGIN_REGISTER_METHOD(zCVobLevelCompo, &zCVobLevelCompo::_GetClassDef, 0x005F1CB0);
	ZENGIN_REGISTER_METHOD(zCVobLevelCompo, &zCVobLevelCompo::Archive, 0x005F8330);
	ZENGIN_REGISTER_METHOD(zCVobLevelCompo, &zCVobLevelCompo::Unarchive, 0x005F83E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVobLevelCompo, &zCVobLevelCompo::SetVisual, void(zCVobLevelCompo::*)(zCVisual*), 0x005F84B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVobLevelCompo, &zCVobLevelCompo::SetVisual, void(zCVobLevelCompo::*)(zSTRING const&), 0x005F84F0);

} // namespace Gothic_I_Addon
