namespace Gothic_I_Addon {

	ZENGIN_REGISTER_CLASS(zCVobWaypoint);
	ZENGIN_REGISTER_METHOD(zCVobWaypoint, &zCVobWaypoint::zCVobWaypoint_OnInit, 0x0073D7B0);
	ZENGIN_REGISTER_METHOD(zCVobWaypoint, &zCVobWaypoint::_GetClassDef, 0x0073D7D0);

	ZENGIN_REGISTER_CLASS(zCWaypoint);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::zCWaypoint_OnInit, 0x007405E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWaypoint, &zCWaypoint::Init, void(zCWaypoint::*)(zVEC3&), 0x00740720);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWaypoint, &zCWaypoint::Init, void(zCWaypoint::*)(float, float, float), 0x00740780);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWaypoint, &zCWaypoint::Init, void(zCWaypoint::*)(zCVobWaypoint*), 0x007407F0);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::Free, 0x007408D0);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::GetPositionWorld, 0x00740A00);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::UpdatePositionWorld, 0x00740A10);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::SetName, 0x00740AA0);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::GetName, 0x00740C00);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::GetVob, 0x00740D60);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::CalcProperties, 0x00740D70);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::CorrectHeight, 0x00740FA0);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::InsertWay, 0x00741050);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::RemoveWay, 0x00741060);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::HasWay, 0x007410C0);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::GetNumberOfWays, 0x007410F0);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::GetWayList, 0x00741110);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::SetWaypointVob, 0x00741120);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::Draw, 0x00741160);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::_GetClassDef, 0x0070C590);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::Archive, 0x00741170);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::Unarchive, 0x007411D0);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::CanBeUsed, 0x007406E0);

	ZENGIN_REGISTER_CLASS(zCWay);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWay, &zCWay::zCWay_OnInit, void(zCWay::*)(), 0x0073F540);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWay, &zCWay::zCWay_OnInit, void(zCWay::*)(zCWaypoint*, zCWaypoint*), 0x0073F5A0);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::Free, 0x0073F6F0);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::GetGoalWaypoint, 0x0073F7B0);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::EstimateCost, 0x0073F7C0);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::GetLength, 0x0073F830);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::GetJumpDistance, 0x0073F8E0);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::GetDistancePos, 0x0073F9A0);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::Draw, 0x0073FB40);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::GetFloor, 0x00740090);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::Init, 0x0073F650);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::CalcProperties, 0x00740130);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::GetChasm, 0x00740460);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::CanJump, 0x00740470);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::CanBeUsed, 0x0073FB30);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::IsObjectOnWay, 0x0073F560);

	ZENGIN_REGISTER_CLASS(zCWayNet);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::zCWayNet_OnInit, void(zCWayNet::*)(), 0x0073D820);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::zCWayNet_OnInit, void(zCWayNet::*)(zCWorld*), 0x0073D900);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::HasWaypoint, zCWaypoint*(zCWayNet::*)(float, float, float), 0x0073DB00);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::HasWaypoint, int(zCWayNet::*)(zCWaypoint*), 0x0073DB60);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::HasWaypoint, zCWaypoint*(zCWayNet::*)(zVEC3&), 0x0073DB90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::InsertWaypoint, zCWaypoint*(zCWayNet::*)(float, float, float), 0x0073DBE0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::InsertWaypoint, void(zCWayNet::*)(zCWaypoint*), 0x0073DCE0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::InsertWaypoint, void(zCWayNet::*)(zCWaypoint*, zCWaypoint*, zCWaypoint*), 0x0073DD10);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::DeleteWaypoint, 0x0073DE90);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::CreateWay, 0x0073E000);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::DeleteWay, 0x0073E0C0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::GetNearestWaypoint, 0x0073E240);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::GetSecNearestWaypoint, 0x0073E2D0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::CorrectHeight, 0x0073E390);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::Draw, 0x0073E460);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::UpdateVobDependencies, 0x0073E490);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::ClearVobDependencies, 0x0073E6D0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::CreateVobDependencies, 0x0073E8E0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::MergeWaypoints, 0x0073EBB0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::CheckConsistency, 0x0073EEB0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::AddWays, 0x0073F440);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::GetWaypoint, 0x00741240);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::SearchWaypoint, 0x007413C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::FindRoute, zCRoute*(zCWayNet::*)(zVEC3 const&, zVEC3 const&, zCVob const*), 0x007413E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::FindRoute, zCRoute*(zCWayNet::*)(zVEC3 const&, zCWaypoint*, zCVob const*), 0x00741470);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::FindRoute, zCRoute*(zCWayNet::*)(zVEC3 const&, zSTRING const&, zCVob const*), 0x007414E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::FindRoute, zCRoute*(zCWayNet::*)(zCWaypoint*, zCWaypoint*, zCVob const*), 0x00741550);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::FindRoute, zCRoute*(zCWayNet::*)(zSTRING const&, zSTRING const&, zCVob const*), 0x00741590);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::InsertInOpen, 0x00741610);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::IsInOpen, 0x00741640);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::InsertInClosed, 0x00741660);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::RemoveFromClosed, 0x00741680);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::IsInClosed, 0x00741690);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::IsInAnyList, 0x007416B0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::EstimateCost, 0x007416E0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::CreateRoute, 0x00741740);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::AStar, 0x007417F0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::GetWPList, 0x00741A70);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::CreateWPVobList, 0x00741C00);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::RemoveUnusedWPVobs, 0x00741C40);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::ArchiveOldFormat, 0x00741DA0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::UnarchiveOldFormat, 0x00742600);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::CalcProperties, 0x00743840);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::_GetClassDef, 0x0073D8C0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::Archive, 0x00742100);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::Unarchive, 0x007431E0);

	ZENGIN_REGISTER_CLASS(zCRoute);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::zCRoute_OnInit, 0x00743880);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::SetStart, 0x00743900);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::GetNextWP, 0x00743910);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::GetTargetWP, 0x00743980);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::GetCurrentWay, 0x00743990);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::GetDesc, 0x007439A0);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::GetRemainingDesc, 0x00743BE0);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::GetNumberOfWaypoints, 0x00743E20);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::IsEmpty, 0x00743E40);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::IsLastTarget, 0x00743E60);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::GetInterpolatedPosition, 0x00743E80);

	ZENGIN_REGISTER_CLASS(zCVobSpot);
	ZENGIN_REGISTER_METHOD(zCVobSpot, &zCVobSpot::zCVobSpot_OnInit, 0x007440A0);
	ZENGIN_REGISTER_METHOD(zCVobSpot, &zCVobSpot::IsAvailable, 0x00744120);
	ZENGIN_REGISTER_METHOD(zCVobSpot, &zCVobSpot::MarkAsUsed, 0x007442B0);
	ZENGIN_REGISTER_METHOD(zCVobSpot, &zCVobSpot::_GetClassDef, 0x007440C0);

	ZENGIN_REGISTER_CLASS(zCVobStartpoint);
	ZENGIN_REGISTER_METHOD(zCVobStartpoint, &zCVobStartpoint::_GetClassDef, 0x00744AD0);

} // namespace Gothic_I_Addon
