namespace Gothic_I_Addon {

	ZENGIN_REGISTER_CLASS(zCPatch);
	ZENGIN_REGISTER_METHOD(zCPatch, &zCPatch::zCPatch_OnInit, 0x0061EE90);
	ZENGIN_REGISTER_METHOD(zCPatch, &zCPatch::DoTransfers, 0x00621CF0);

	ZENGIN_REGISTER_CLASS(zCPatchMap);
	ZENGIN_REGISTER_METHOD(zCPatchMap, &zCPatchMap::CheckRaySurfaceIntersection, 0x0061EEE0);

	ZENGIN_REGISTER_CLASS(zCWorld);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::zCWorld_OnInit, 0x006131C0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GetActiveSkyControler, 0x00613A60);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SetSkyControlerIndoor, 0x00613A90);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SetSkyControlerOutdoor, 0x00613AD0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::AddZone, 0x00613B80);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveZone, 0x00613D10);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveAllZones, 0x00613E40);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::UpdateZone, 0x00613EB0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::ProcessZones, 0x00613ED0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::ShowZonesDebugInfo, 0x006144D0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::ShowTextureStats, 0x00614920);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::Render, 0x00614D70);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::TraceRayFirstHit, int(__fastcall zCWorld::*)(zVEC3 const&, zVEC3 const&, zCArray<zCVob*> const*, int), 0x00614F70);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::TraceRayNearestHit, int(__fastcall zCWorld::*)(zVEC3 const&, zVEC3 const&, zCArray<zCVob*> const*, int), 0x006151A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::TraceRayFirstHit, int(__fastcall zCWorld::*)(zVEC3 const&, zVEC3 const&, zCVob*, int), 0x006154C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::TraceRayNearestHit, int(__fastcall zCWorld::*)(zVEC3 const&, zVEC3 const&, zCVob*, int), 0x00615600);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::TraceRayFirstHitCache, int(__fastcall zCWorld::*)(zVEC3 const&, zVEC3 const&, zCArray<zCVob*> const*, int, zCRayCache*), 0x00615740);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::TraceRayFirstHitCache, int(__fastcall zCWorld::*)(zVEC3 const&, zVEC3 const&, zCVob*, int, zCRayCache*), 0x00615810);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::TraceRayNearestHitCache, int(__fastcall zCWorld::*)(zVEC3 const&, zVEC3 const&, zCArray<zCVob*> const*, int, zCRayCache*), 0x00615940);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::TraceRayNearestHitCache, int(__fastcall zCWorld::*)(zVEC3 const&, zVEC3 const&, zCVob*, int, zCRayCache*), 0x00615A10);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::PickScene, 0x00615B40);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::TraverseBsp, 0x00615DA0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SaveBspTreeMesh3DS, 0x00615EA0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::CompileWorld, 0x00615ED0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchZoneListByClass, 0x00616EE0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchZoneDefaultByClass, 0x00617020);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::ShouldAddThisVobToBsp, 0x006172A0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::AddVobAsChild_novt, 0x006172F0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::AddVob, 0x00617320);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveVob_novt, 0x006176C0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveVobSubtree_r, 0x006176E0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveVobSubtree_novt, 0x006178C0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::MoveVobSubtreeTo_novt, 0x006179A0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::MoveVobSubtreeToWorldSpace, 0x006179C0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveVobFromLists, 0x006179E0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::PrintStatus, 0x00617BD0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::PrintGlobalVobTree, 0x006185F0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::PrintActiveVobs, 0x00618900);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::UpdateVobTreeBspDependencies, 0x00618B40);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::MoveVobs, 0x00618BA0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::AdvanceClock, 0x00618C30);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SaveBspTree, 0x00618C70);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::LoadBspTree, 0x00618E10);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::DebugMarkOccluderPolys, 0x00618F40);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::UnarcTraverseVobs, 0x00619390);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GetProgressBar, 0x00619760);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::ArcTraverseVobs, 0x0061A1F0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::TraverseVobTree, 0x0061ABD0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::GetVobHashIndex, unsigned long(zCWorld::*)(zSTRING const&), 0x0061AC30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::GetVobHashIndex, unsigned long(zCWorld::*)(zCVob*), 0x0061AC60);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::InsertVobHashTable, 0x0061ACA0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveVobHashTable, 0x0061ADE0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchVobHashTable, 0x0061AE70);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchVobListHashTable, 0x0061AF60);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SetOwnerSession, 0x0061B150);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GetOwnerSession, 0x0061B1A0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::ResetCutscenePlayer, 0x0061B1B0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RegisterPerFrameCallback, 0x0061B200);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::UnregisterPerFrameCallback, 0x0061B350);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::LightWorldStaticUncompiled, 0x0061C840);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::LightWorldStaticCompiled, 0x0061CCE0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GenerateStaticVertexLighting, 0x0061D340);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::LightingTestRay, 0x0061D630);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GetSurfaceLightmapBBox2D, 0x0061D700);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GetPhongNormal, 0x0061DB90);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GeneratePatchMapFromSurface, 0x0061DFA0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GenerateLightmapFromPatchMap, 0x0061EF80);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::LightPatchMap, 0x00620320);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GenerateSurfaces, 0x00620830);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::MakeTransfers, 0x00621570);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GenerateLightmapsRadiosity, 0x00621E80);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GenerateLightmaps, 0x006220E0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GenerateStaticWorldLighting, 0x00622880);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::MakeVobLightingDirty, 0x006228C0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GetBspTree, 0x006299A0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SetVobFarClipZScalability, 0x006299B0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::_GetClassDef, 0x00613730);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::Archive, 0x0061A510);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::Unarchive, 0x00619770);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::LoadWorld, 0x00619EC0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SaveWorld, 0x0061A850);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::MergeVobSubtree, 0x0061A130);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SaveVobSubtree, 0x0061AB10);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::DisposeWorld, 0x00616780);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::DisposeVobs, 0x00616570);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::DisposeStaticWorld, 0x00616710);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::AddVobAsChild, 0x00617090);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveVob, 0x00617690);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveVobSubtree, 0x00617890);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::MoveVobSubtreeTo, 0x006178E0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GetPlayerGroup, 0x00613740);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchVob, 0x00616980);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchVobByID, 0x006169D0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchVobByName, 0x00616A20);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchVobListByName, 0x00616B10);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchVobListByClass, 0x00616D00);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchVobListByBaseClass, 0x00616DE0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::VobAddedToWorld, 0x00617340);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::VobRemovedFromWorld, 0x006174A0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RenderWaynet, 0x00613B10);

} // namespace Gothic_I_Addon
