namespace Gothic_I_Classic {

	ZENGIN_REGISTER_CLASS(oCAISound);
	ZENGIN_REGISTER_METHOD(oCAISound, &oCAISound::RemoveSlideSound, 0x00617530);
	ZENGIN_REGISTER_METHOD(oCAISound, &oCAISound::CheckSlideSound, 0x00617550);
	ZENGIN_REGISTER_METHOD(oCAISound, &oCAISound::GetSoundMaterial, 0x006175E0);
	ZENGIN_REGISTER_METHOD(oCAISound, &oCAISound::StartCollisionSound, 0x006176B0);
	ZENGIN_REGISTER_METHOD(oCAISound, &oCAISound::_GetClassDef, 0x00617930);

	ZENGIN_REGISTER_CLASS(oCAIArrowBase);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::oCAIArrowBase_OnInit, 0x00618550);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::AddIgnoreCDVob, 0x006187A0);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::ClearIgnoreCDVob, 0x006187C0);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::CreateTrail, 0x00618830);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::_GetClassDef, 0x00618630);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::Archive, 0x00618DC0);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::Unarchive, 0x00618E40);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::DoAI, 0x00618A80);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::ReportCollisionToAI, 0x00618D50);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::HasAIDetectedCollision, 0x00618640);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::AICollisionResponseSelfDetected, 0x00618650);

	ZENGIN_REGISTER_CLASS(oCAIArrow);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::oCAIArrow_OnInit, 0x00618F00);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::SetTarget, 0x006190E0);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::ClearUsedVobs, 0x00619120);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::SetupAIVob, 0x006191D0);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::_GetClassDef, 0x00618FB0);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::Archive, 0x00619890);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::Unarchive, 0x00619960);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::DoAI, 0x00619520);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::CanThisCollideWith, 0x00619550);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::ReportCollisionToAI, 0x006195E0);

	ZENGIN_REGISTER_CLASS(oCAIDrop);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::oCAIDrop_OnInit, 0x00619A70);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::AddIgnoreCDVob, 0x00619D00);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::ClearIgnoreCDVob, 0x00619D20);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::SetupAIVob, 0x00619D90);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::SetVelocity, 0x0061A080);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::SetStartPosition, 0x0061A130);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::_GetClassDef, 0x00619B50);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::Archive, 0x0061A2A0);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::Unarchive, 0x0061A2B0);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::DoAI, 0x00619FD0);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::CanThisCollideWith, 0x00619B70);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::ReportCollisionToAI, 0x0061A040);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::HasAIDetectedCollision, 0x00619B60);

	ZENGIN_REGISTER_CLASS(oCAIVobMove);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::oCAIVobMove_OnInit, 0x006176C0);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::AddIgnoreCDVob, 0x00618010);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::ClearIgnoreCDVob, 0x00618030);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::_GetClassDef, 0x00617790);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::Archive, 0x00617EC0);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::Unarchive, 0x00617F20);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::DoAI, 0x00617D10);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::CanThisCollideWith, 0x006177A0);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::ReportCollisionToAI, 0x00617E80);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::Init, 0x006179E0);

	ZENGIN_REGISTER_CLASS(oCAIVobMoveTorch);
	ZENGIN_REGISTER_METHOD(oCAIVobMoveTorch, &oCAIVobMoveTorch::oCAIVobMoveTorch_OnInit, 0x006180A0);
	ZENGIN_REGISTER_METHOD(oCAIVobMoveTorch, &oCAIVobMoveTorch::CheckWater, 0x006182D0);
	ZENGIN_REGISTER_METHOD(oCAIVobMoveTorch, &oCAIVobMoveTorch::BurnedOut, 0x00618380);
	ZENGIN_REGISTER_METHOD(oCAIVobMoveTorch, &oCAIVobMoveTorch::_GetClassDef, 0x00618130);
	ZENGIN_REGISTER_METHOD(oCAIVobMoveTorch, &oCAIVobMoveTorch::DoAI, 0x006182A0);
	ZENGIN_REGISTER_METHOD(oCAIVobMoveTorch, &oCAIVobMoveTorch::Init, 0x00618280);

} // namespace Gothic_I_Classic
