namespace Gothic_I_Classic {

	ZENGIN_REGISTER_CLASS(oCItemContainer);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::oCItemContainer_OnInit, 0x006663A0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetNextContainerLeft, 0x00666280);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetNextContainerRight, 0x00666310);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::JumpOffset, 0x00666E90);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetCategoryText, 0x00666F40);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::ActivateNextContainer, 0x00669980);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::HandleEvent, 0x00669DD0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Open, 0x00667EB0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::OpenPassive, 0x00668050);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Close, 0x00668C10);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Activate, 0x00668F60);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Deactivate, 0x00669180);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::IsOpen, 0x00668F30);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::IsActive, 0x006665A0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::IsEmpty, 0x00669750);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::SetContents, 0x00667E60);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetContents, 0x00667EA0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Insert, 0x00669250);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCItemContainer, &oCItemContainer::Remove, void(oCItemContainer::*)(oCItem*), 0x00669320);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCItemContainer, &oCItemContainer::Remove, oCItem*(oCItemContainer::*)(oCItem*, int), 0x006693D0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::RemoveByPtr, 0x006693C0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetSelectedItem, 0x006691B0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetSelectedItemCount, 0x006691E0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetSize, 0x00666E50);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::DisableManipulateItems, 0x006665B0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::CanManipulateItems, 0x006665C0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::DisableTransferMoreThanOneItem, 0x006665D0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::CanTransferMoreThanOneItem, 0x006665F0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::IsPassive, 0x00668C00);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Archive, 0x00669AA0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Unarchive, 0x00669C20);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCItemContainer, &oCItemContainer::Init, void(oCItemContainer::*)(int, int), 0x00666CD0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCItemContainer, &oCItemContainer::Init, void(oCItemContainer::*)(int, int, oCItemContainer::oTItemListMode), 0x00666CF0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetPosition, 0x00666E70);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::LoadGrafix, 0x00666770);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::DeleteContents, 0x00669490);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::NextItem, 0x006695A0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::PrevItem, 0x00669680);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::CheckSelectedItem, 0x00669560);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::TransferItem, 0x00669780);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::SetCategoryOnRightContainer, 0x00668FC0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Draw, 0x00667660);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::DrawCategory, 0x006670D0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::DrawItemInfo, 0x00667220);

	ZENGIN_REGISTER_CLASS(oCStealContainer);
	ZENGIN_REGISTER_METHOD(oCStealContainer, &oCStealContainer::oCStealContainer_OnInit, 0x0066A3D0);
	ZENGIN_REGISTER_METHOD(oCStealContainer, &oCStealContainer::HandleEvent, 0x0066A730);
	ZENGIN_REGISTER_METHOD(oCStealContainer, &oCStealContainer::SetOwner, 0x0066A590);
	ZENGIN_REGISTER_METHOD(oCStealContainer, &oCStealContainer::GetOwner, 0x0066A5B0);
	ZENGIN_REGISTER_METHOD(oCStealContainer, &oCStealContainer::CreateList, 0x0066A5C0);

	ZENGIN_REGISTER_CLASS(oCNpcContainer);
	ZENGIN_REGISTER_METHOD(oCNpcContainer, &oCNpcContainer::oCNpcContainer_OnInit, 0x0066A960);
	ZENGIN_REGISTER_METHOD(oCNpcContainer, &oCNpcContainer::HandleEvent, 0x0066ACD0);
	ZENGIN_REGISTER_METHOD(oCNpcContainer, &oCNpcContainer::Insert, 0x0066B2D0);
	ZENGIN_REGISTER_METHOD(oCNpcContainer, &oCNpcContainer::Remove, 0x0066B310);
	ZENGIN_REGISTER_METHOD(oCNpcContainer, &oCNpcContainer::CreateList, 0x0066AB10);

	ZENGIN_REGISTER_CLASS(oCNpcInventory);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::oCNpcInventory_OnInit, 0x007CFFA3);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::ClearInventory, 0x0066BC50);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::Open, 0x0066BDE0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::SetOwner, 0x0066C290);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetOwner, 0x0066C2A0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::SetFirstCategory, 0x0066C2B0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetCategory, 0x0066C430);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetNumItemsInCategory, 0x0066C4C0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetItem, 0x0066C610);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetAmount, 0x0066CAC0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::IsCatEmpty, 0x0066D6C0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetNextCategory, 0x0066DE30);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetPrevCategory, 0x0066DE50);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::SwitchToCategory, 0x0066DE60);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::SwitchNextCategory, 0x0066DF00);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::SwitchPrevCategory, 0x0066DF30);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::FindNextCategory, 0x0066DF50);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::HandleTrade, 0x0066E150);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::CheckForEquippedItems, 0x0066F740);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::CanCarry, 0x0066F8B0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::SetPackAbility, 0x0066FAA0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::UnpackCategory, 0x0066FAD0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetNumItemsInPackString, 0x0066FB00);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetPackedItemBySlot, 0x0066FC10);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::CreateFromPackString, 0x0066FD60);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetPackedItemInfo, 0x0066FDF0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::PackSingleItem, 0x00670030);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::PackAllItems, 0x006703D0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::UnpackAllItems, 0x00670400);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::PackItemsInCategory, 0x00670420);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::UnpackItemsInCategory, 0x00670740);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::HandleEvent, 0x0066E390);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::Close, 0x0066C1E0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::IsEmpty, 0x0066D550);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::Insert, 0x0066C7D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::Remove, oCItem*(oCNpcInventory::*)(int, int), 0x0066D410);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::Remove, oCItem*(oCNpcInventory::*)(zSTRING const&, int), 0x0066D520);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::RemoveByPtr, 0x0066CF10);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::Archive, 0x0066D830);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::Unarchive, 0x0066DB10);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::Draw, 0x0066C1F0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::DrawCategory, 0x0066DF60);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::Remove, void(oCNpcInventory::*)(oCItem*), 0x0066CE00);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::Remove, oCItem*(oCNpcInventory::*)(oCItem*, int), 0x0066D140);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::IsIn, oCItem*(oCNpcInventory::*)(oCItem*, int), 0x0066CBF0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::IsIn, oCItem*(oCNpcInventory::*)(int, int), 0x0066CCE0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::IsIn, oCItem*(oCNpcInventory::*)(zSTRING const&, int), 0x0066CCB0);

} // namespace Gothic_I_Classic
