namespace Gothic_I_Classic {

	ZENGIN_REGISTER_CLASS(oCSVMManager);
	ZENGIN_REGISTER_METHOD(oCSVMManager, &oCSVMManager::oCSVMManager_OnInit, 0x006D1240);
	ZENGIN_REGISTER_METHOD(oCSVMManager, &oCSVMManager::GetOU, 0x006D1520);

	ZENGIN_REGISTER_CLASS(oCSVM);
	ZENGIN_REGISTER_METHOD(oCSVM, &oCSVM::oCSVM_OnInit, 0x006D18B0);
	ZENGIN_REGISTER_METHOD(oCSVM, &oCSVM::InitByScript, 0x006D18E0);
	ZENGIN_REGISTER_METHOD(oCSVM, &oCSVM::GetOU, 0x006D1B70);

} // namespace Gothic_I_Classic
