namespace Gothic_I_Classic {

	ZENGIN_REGISTER_CLASS(oCTrajectory);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::Calc, 0x0047FF60);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::Changed, 0x00480320);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::Interpolate, 0x00480330);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::InterpolateN, 0x00480740);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::Draw, 0x00480850);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::Clear, 0x00480B10);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::RecalcByColl, 0x00480BE0);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::ApplyGrav, 0x00481060);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::SetByList, 0x004810D0);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::VobCross, 0x00481260);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::InsertKey, 0x00489110);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::GetKey, 0x00489240);
	ZENGIN_REGISTER_METHOD(oCTrajectory, &oCTrajectory::GetNumKeys, 0x004892C0);

	ZENGIN_REGISTER_CLASS(oCEmitterKey);
	ZENGIN_REGISTER_METHOD(oCEmitterKey, &oCEmitterKey::oCEmitterKey_OnInit, 0x004812F0);
	ZENGIN_REGISTER_METHOD(oCEmitterKey, &oCEmitterKey::SetByScript, 0x004817E0);
	ZENGIN_REGISTER_METHOD(oCEmitterKey, &oCEmitterKey::ParseStrings, 0x004819B0);
	ZENGIN_REGISTER_METHOD(oCEmitterKey, &oCEmitterKey::Edit, 0x00490B40);
	ZENGIN_REGISTER_METHOD(oCEmitterKey, &oCEmitterKey::SetDefaultByFX, 0x00493FE0);

	ZENGIN_REGISTER_CLASS(oCVisualFX);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::oCVisualFX_OnInit, 0x004820C0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::CreateHierachy, 0x00483300);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::DisposeHierachy, 0x004835D0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::InitValues, 0x00483B90);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::ParseStrings, 0x00484200);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::UpdateFXByEmitterKey, 0x00486110);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::CreateBackup, 0x00486900);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::FindKey, 0x00486910);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCVisualFX, &oCVisualFX::CreateAndCastFX, oCVisualFX*(oCVisualFX::*)(zSTRING const&, zCVob const*, zCVob const*), 0x00487170);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCVisualFX, &oCVisualFX::CreateAndCastFX, oCVisualFX*(oCVisualFX::*)(zSTRING const&, zMAT4 const&), 0x00487470);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::CreateInvestFX, 0x00489520);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::InitInvestFX, 0x004896E0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::StopInvestFX, 0x00489840);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetShowVisual, 0x0048B9F0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::InitEffect, 0x0048C290);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::EndEffect, 0x0048C6A0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::ProcessQueuedCollisions, 0x0048D070);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::ProcessCollision, 0x0048D110);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::CheckDeletion, 0x0048E0E0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::UpdateActKey, 0x0048E530);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::DoMovements, 0x0048E780);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::CheckDelayedTrigger, 0x0048F110);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::AdjustShapeToOrigin, 0x0048F390);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::UpdateEffects, 0x0048F810);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::Edit, 0x00490340);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetupEmitterKeysByVisual, 0x00494460);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetName, 0x0073F560);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::_GetClassDef, 0x004825E0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::Archive, 0x0048FC40);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::Unarchive, 0x0048FC50);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::OnTick, 0x0048FB60);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::CanThisCollideWith, 0x0048DEC0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::Open, 0x004898F0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetOrigin, 0x004892D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCVisualFX, &oCVisualFX::SetTarget, void(oCVisualFX::*)(zCVob*), 0x00489390);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCVisualFX, &oCVisualFX::SetTarget, void(oCVisualFX::*)(zVEC3&), 0x004894B0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetInflictor, 0x00489340);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetOrigin, 0x004825F0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetTarget, 0x00482600);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetInflictor, 0x00482610);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCVisualFX, &oCVisualFX::Init, void(oCVisualFX::*)(zCVob const*, zVEC3 const&), 0x00489E00);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCVisualFX, &oCVisualFX::Init, void(oCVisualFX::*)(zCVob const*, zCVob const*, zCVob const*), 0x00489F10);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCVisualFX, &oCVisualFX::Init, void(oCVisualFX::*)(zCArray<zCVob*> const&), 0x0048A640);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::InvestNext, 0x0048A7D0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetLevel, 0x0048AB70);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetLevel, 0x0048AF30);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::Cast, 0x0048AF40);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::Stop, 0x0048BB30);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::Kill, 0x0048BEE0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::Play, 0x00482620);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::CanBeDeleted, 0x0048C150);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::IsFinished, 0x0048C190);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::IsLooping, 0x0048C220);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetByScript, 0x00485790);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetDuration, 0x00482630);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::Reset, 0x00489C20);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::ReportCollision, 0x0048C6F0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetCollisionEnabled, 0x00485640);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetCollisionCandidates, 0x0048DCD0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetCollisionCandidates, 0x00482640);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetNumCollisionCandidates, 0x004826F0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetCollidedCandidates, 0x0048DDF0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetDamage, 0x00482700);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetDamageType, 0x00482710);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetDamage, 0x00482720);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetDamageType, 0x00482730);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::IsASpell, 0x00482740);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetSpellType, 0x00482750);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetSpellType, 0x00482760);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetSpellTargetTypes, 0x00482770);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetSpellTargetTypes, 0x00482780);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::GetIsProjectile, 0x00482790);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetIsProjectile, 0x004827A0);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::SetVisualByString, 0x00484580);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::CalcTrajectory, 0x00487870);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::Collide, 0x0048B750);
	ZENGIN_REGISTER_METHOD(oCVisualFX, &oCVisualFX::CollisionResponse, 0x0048D850);

	ZENGIN_REGISTER_CLASS(oCVisualFXAI);
	ZENGIN_REGISTER_METHOD(oCVisualFXAI, &oCVisualFXAI::DoAI, 0x0048FC60);
	ZENGIN_REGISTER_METHOD(oCVisualFXAI, &oCVisualFXAI::ReportCollisionToAI, 0x00484130);
	ZENGIN_REGISTER_METHOD(oCVisualFXAI, &oCVisualFXAI::HostVobAddedToWorld, 0x00484150);

} // namespace Gothic_I_Classic
