namespace Gothic_I_Classic {

	ZENGIN_REGISTER_CLASS(oCVob);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::oCVob_OnInit, 0x006D2AF0);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::GetShowDebug, 0x006D2BF0);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::ToggleShowDebug, 0x006D2C20);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::SetShowDebug, 0x006D2CA0);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::HasNpcEnoughSpace, 0x006D3680);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::HasEnoughSpace, 0x006D3960);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::SearchNpcPosition, 0x006D3B10);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::SearchFreePosition, 0x006D3F90);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::SetOnFloor, 0x006D43C0);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::GetFloorPosition, 0x006D4410);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::GetFloorPositionWithVob, 0x006D44E0);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::StartParticleEffects, 0x006D4680);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::_GetClassDef, 0x006D2B10);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::Archive, 0x006D4660);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::Unarchive, 0x006D4670);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::Render, 0x006D4690);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::GetCSStateFlags, 0x00670F30);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::Init, 0x006D2B70);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::ShowDebugInfo, 0x006D2D20);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::GetInstance, 0x006D45C0);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::GetInstanceName, 0x006D45D0);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::IsOwnedByGuild, 0x0068BDD0);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::IsOwnedByNpc, 0x0068BDE0);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::DoFocusCheckBBox, 0x00670F10);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::GetAIVobMove, 0x006D4850);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::GetSoundMaterial_AM, 0x006D2B20);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::SetSoundMaterial, 0x00670F20);
	ZENGIN_REGISTER_METHOD(oCVob, &oCVob::GetSoundMaterial, 0x0068BDF0);

	ZENGIN_REGISTER_CLASS(oCTouchDamage);
	ZENGIN_REGISTER_METHOD(oCTouchDamage, &oCTouchDamage::_GetClassDef, 0x006D4E10);
	ZENGIN_REGISTER_METHOD(oCTouchDamage, &oCTouchDamage::GetDamageTypeArcEnum, 0x006D4920);

} // namespace Gothic_I_Classic
