namespace Gothic_I_Classic {

	ZENGIN_REGISTER_CLASS(zTEngineStats);
	ZENGIN_REGISTER_METHOD(zTEngineStats, &zTEngineStats::PrintScreen, 0x004FB470);

	ZENGIN_REGISTER_CLASS(zCLineCache);
	ZENGIN_REGISTER_METHOD(zCLineCache, &zCLineCache::Line, 0x004FB8D0);
	ZENGIN_REGISTER_METHOD(zCLineCache, &zCLineCache::Flush, 0x004FB970);
	ZENGIN_REGISTER_METHOD(zCLineCache, &zCLineCache::Line3D, 0x004FBA10);
	ZENGIN_REGISTER_METHOD(zCLineCache, &zCLineCache::LineCS3D, 0x004FBE10);

	ZENGIN_REGISTER_CLASS(zCCamera);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::zCCamera_OnInit, 0x00535DE0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::Project, void(zCCamera::*)(zVEC3 const* const, float&, float&) const, 0x0051D7F0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::PushTransform, 0x00536130);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::PopTransform, 0x005361C0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::SetTransform, 0x00536300);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::GetTransform, 0x00536460);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::Activate, 0x005364C0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::CreateProjectionMatrix, 0x005365D0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::UpdateProjectionMatrix, 0x00536650);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::GetFOV, float(zCCamera::*)() const, 0x005366A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::GetFOV, void(zCCamera::*)(float&, float&) const, 0x005366B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::SetFOV, void(zCCamera::*)(float), 0x005366E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::SetFOV, void(zCCamera::*)(float, float), 0x00536720);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::UpdateViewport, 0x00536850);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::SetRenderTarget, 0x00536990);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::SetUpFrustum, 0x005369B0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::SetNearClipZ, 0x00536CC0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::SetFarClipZ, 0x00536D30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::BBox3DInFrustum, zTCam_ClipType(zCCamera::*)(zTBBox3D const&), 0x00536E90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::BBox3DInFrustum, zTCam_ClipType(zCCamera::*)(zTBBox3D const&, int&), 0x00536EF0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::StopTremor, 0x00537130);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::AddTremor, 0x00537140);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::PreRenderProcessing, 0x005372B0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::PostRenderProcessing, 0x00537400);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::GetCamPos, 0x00537440);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::InitDrawPolySimple, 0x00537470);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::CleanupDrawPolySimple, 0x00537540);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::DrawPolySimple, 0x005375A0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::SetRenderScreenFade, 0x005376B0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::SetRenderCinemaScope, 0x005376D0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::RenderScreenFade, 0x005376F0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::RenderCinemaScope, 0x005377B0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::ScreenProjectionTouchesPortalRough, 0x00537900);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::ScreenProjectionTouchesPortal, 0x00537B80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::Project, void(zCCamera::*)(zVEC3 const* const, int&, int&), 0x005606D0);

	ZENGIN_REGISTER_CLASS(zCVertex);
	ZENGIN_REGISTER_METHOD(zCVertex, &zCVertex::zCVertex_OnInit, 0x005587F0);
	ZENGIN_REGISTER_METHOD(zCVertex, &zCVertex::Draw, 0x004FC0D0);
	ZENGIN_REGISTER_METHOD(zCVertex, &zCVertex::CreateVertexTransform, 0x004FC1C0);
	ZENGIN_REGISTER_METHOD(zCVertex, &zCVertex::ResetVertexTransform, 0x005A2A90);

	ZENGIN_REGISTER_CLASS(zCVertFeature);
	ZENGIN_REGISTER_METHOD(zCVertFeature, &zCVertFeature::zCVertFeature_OnInit, 0x00555640);

	ZENGIN_REGISTER_CLASS(zCPolygon);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::zCPolygon_OnInit, 0x00595B00);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::RenderPoly, 0x00518F30);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TransformProjectLight, 0x00519380);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::ClipToPlane, 0x00595C00);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::Unclip, 0x005960C0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CopyClipFeaturesForTexAniMapping, 0x00596140);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::ClipToFrustum, 0x005961B0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::ClassifyPlane, 0x00596420);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::ClassifyPlaneBSPBuild, 0x005964B0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CalcNormal, 0x00596540);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::GetScreenBBox2D, 0x00596930);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::DrawWire, 0x005969D0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::LightDynCamSpace, 0x005971B0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::LightClippedPoly, 0x00597370);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::GetLightStatAtPos, 0x00597950);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CheckRayPolyIntersection, 0x00598060);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CheckRayPolyIntersection2Sided, 0x005983F0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CalcNormalMainAxis, 0x00598760);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::GetBBox3D, 0x005987C0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::GetCenter, 0x00598870);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPolygon, &zCPolygon::SetMapping, void(zCPolygon::*)(zVEC2 const&, zVEC2 const&, zVEC2 const&), 0x005988F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPolygon, &zCPolygon::SetMapping, void(zCPolygon::*)(int, zVEC2 const&), 0x00598940);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::Flip, 0x00598960);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::VertPartOfPoly, 0x005989A0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::EdgePartOfPoly, 0x005989D0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TexTranslate, 0x00598A20);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TexSetTranslation, 0x00598A60);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPolygon, &zCPolygon::TexScale, void(zCPolygon::*)(float, float), 0x00598AA0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPolygon, &zCPolygon::TexScale, void(zCPolygon::*)(zVEC2&, float, float), 0x00598AE0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TexRotate, 0x00598BA0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TexMirrorU, 0x00598D70);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TexMirrorV, 0x00598DA0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TexShearU, 0x00598DD0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TexShearV, 0x00598E90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPolygon, &zCPolygon::TexApplyPlanarMapping, void(zCPolygon::*)(zVEC3 const&, zVEC3 const&, zVEC3 const&, int), 0x00598F50);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPolygon, &zCPolygon::TexApplyPlanarMapping, void(zCPolygon::*)(float, float, int), 0x00599100);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TexCorrectUV, 0x005996F0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::AllocVerts, 0x00599840);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::AddVertex, 0x005999D0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::AddVertexAndFeature, 0x005999F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPolygon, &zCPolygon::SetVertices, void(zCPolygon::*)(zCVertex*, zCVertex*, zCVertex*), 0x00599A30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPolygon, &zCPolygon::SetVertices, void(zCPolygon::*)(zCVertex*, zCVertex*, zCVertex*, zCVertex*, int), 0x00599A90);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::SetVertex, 0x00599B00);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::SetFeature, 0x00599B40);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CopyValuesInto, 0x00599B80);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CopyPolyInto, 0x00599C30);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::RemoveVerticesAndFeatures, 0x00599C90);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::GetArea, 0x00599D20);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::GetLongestEdgeLen, 0x00599DC0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::ResetStaticLight, 0x00599E30);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::SetStaticLight, 0x00599E70);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::SetLightDyn, 0x00599EA0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::SetLightStatAlpha, 0x00599ED0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::ResetLightDynToLightStat, 0x00599F00);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::AddToLightDyn, 0x00599F30);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CheckBBoxPolyIntersection, 0x00599FC0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CheckBSpherePolyIntersection, 0x0059A440);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::SplitPoly, 0x0059A5B0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::IsIntersectingProjection, 0x0059AB10);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::IsIntersecting, 0x0059B280);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::LightStatic, 0x005FA720);

	ZENGIN_REGISTER_CLASS(zCPortal);
	ZENGIN_REGISTER_METHOD(zCPortal, &zCPortal::zCPortal_OnInit, 0x005185B0);
	ZENGIN_REGISTER_METHOD(zCPortal, &zCPortal::RemoveFromBsp, 0x00518590);
	ZENGIN_REGISTER_METHOD(zCPortal, &zCPortal::Init, 0x0052B330);

} // namespace Gothic_I_Classic
