namespace Gothic_I_Classic {

	ZENGIN_REGISTER_CLASS(zCAIPlayer);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::zCAIPlayer_OnInit, 0x004FCB90);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::RemoveEffects, 0x004FCF50);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::GetJumpUpHeight, 0x004FD040);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::SetJumpUpForceByHeight, 0x004FD080);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::SetVob, 0x004FD0A0);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::DoAutoRoll, 0x004FD200);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::ResetAutoRoll, 0x004FD390);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::CalcModelAnisInPlace, 0x004FD3C0);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::DoSurfaceAlignment, 0x004FD420);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::IsSliding, 0x004FDA40);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::CheckFloorSliding, 0x004FDA70);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::CheckPhysics, 0x004FE140);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::PropagateCollObjectStates, 0x004FE610);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::CalcForceModelHalt, 0x004FE820);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::CalcStateVars, 0x004FE8D0);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::DoProceduralMovement, 0x004FEB50);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::Begin, 0x004FEBE0);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::End, 0x004FED80);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::UpdateEffects, 0x004FEE20);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::GetBloodQuadMark, 0x004FFA40);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::SetBloodDefaultTexture, 0x004FFCE0);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::AddBlood, 0x004FFE20);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::AddWeaponTrailSegment, 0x004FFEB0);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::CreateLedgeInfo, 0x00500140);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::GetLedgeInfo, 0x00500160);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::GetFoundLedge, 0x005001A0);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::ClearFoundLedge, 0x005001C0);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::DetectClimbUpLedge, 0x00500230);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::AlignModelToLedge, 0x00501510);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::GetHandPositionWorld, 0x00501610);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::AlignToFloor, 0x00501760);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::GetModelFloorWorld, 0x005017A0);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::CheckEnoughSpaceMoveDir, 0x005017C0);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::CheckEnoughSpaceMoveForward, 0x00501BA0);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::CheckEnoughSpaceMoveBackward, 0x00501BE0);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::CheckEnoughSpaceMoveRight, 0x00501C30);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::CheckEnoughSpaceMoveLeft, 0x00501C70);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::GetProtoYHeight, 0x00501CC0);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::GetSurfaceAlignScanOrigin, 0x00501CE0);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::DiveRotateX, 0x00501E10);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::SetCDStat, 0x00501F60);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCAIPlayer, &zCAIPlayer::LandAndStartAni, void(zCAIPlayer::*)(zSTRING const&), 0x00501FB0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCAIPlayer, &zCAIPlayer::LandAndStartAni, void(zCAIPlayer::*)(zCModelAni*), 0x00502060);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCAIPlayer, &zCAIPlayer::CheckForceModelHalt, int(zCAIPlayer::*)(zSTRING const&), 0x005020C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCAIPlayer, &zCAIPlayer::CheckForceModelHalt, int(zCAIPlayer::*)(zCModelAni*), 0x00502100);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::ShouldCorrectFloorHeight, 0x00502140);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::BeginStateSwitch, 0x00502160);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::SetPhysicsEnabled, 0x005021E0);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::StartPhysicsWithVel, 0x005021F0);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::Print, 0x00502520);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::Line3D, 0x00502530);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::PrintScreen, 0x00502540);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::GetModel, 0x006211D0);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::_GetClassDef, 0x004FCD00);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::Archive, 0x00502300);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::Unarchive, 0x005023F0);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::DoAI, 0x004FEE10);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::HostVobRemovedFromWorld, 0x004FD030);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::StartStandAni, 0x00502220);
	ZENGIN_REGISTER_METHOD(zCAIPlayer, &zCAIPlayer::StartFallDownAni, 0x00502240);

} // namespace Gothic_I_Classic
