namespace Gothic_I_Classic {

	ZENGIN_REGISTER_CLASS(zCArchiverBinSafe);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::zCArchiverBinSafe_OnInit, 0x0050BDA0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::RestoreString, 0x0050B3B0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteType, 0x0050B3C0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ReadType, 0x0050B430);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ClearChunkList, 0x0050BAC0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::InsertChunkInList, 0x0050BC40);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ResolveAndPosEntry, 0x0050BCD0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::DebugMessage, 0x0050C2A0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::CheckObjectListSize, 0x0050EAE0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::_GetClassDef, 0x0050BF20);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteInt, 0x0050CEB0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteByte, 0x0050CF90);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteWord, 0x0050D070);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteFloat, 0x0050D150);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteBool, 0x0050D230);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteString, 0x0050D310);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteVec3, 0x0050D440);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteColor, 0x0050D680);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteRaw, 0x0050D760);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteRawFloat, 0x0050D840);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteEnum, 0x0050DA10);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::WriteObject, void(__fastcall zCArchiverBinSafe::*)(zCObject*), 0x0050E4E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::WriteObject, void(__fastcall zCArchiverBinSafe::*)(char const*, zCObject*), 0x0050E450);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::WriteObject, void(__fastcall zCArchiverBinSafe::*)(char const*, zCObject&), 0x0050E260);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::WriteChunkStart, void(__fastcall zCArchiverBinSafe::*)(char const*, unsigned short), 0x0050E000);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::WriteChunkStart, void(__fastcall zCArchiverBinSafe::*)(char const*, char const*, unsigned short, unsigned long), 0x0050DC30);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteChunkEnd, 0x0050E020);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteGroupBegin, 0x0050DC10);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteGroupEnd, 0x0050DC20);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadInt, void(__fastcall zCArchiverBinSafe::*)(char const*, int&), 0x00510850);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadInt, int(__fastcall zCArchiverBinSafe::*)(char const*), 0x00510610);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadByte, void(__fastcall zCArchiverBinSafe::*)(char const*, unsigned char&), 0x00510880);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadByte, unsigned char(__fastcall zCArchiverBinSafe::*)(char const*), 0x00510630);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadWord, void(__fastcall zCArchiverBinSafe::*)(char const*, unsigned short&), 0x005108B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadWord, unsigned short(__fastcall zCArchiverBinSafe::*)(char const*), 0x00510650);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadFloat, void(__fastcall zCArchiverBinSafe::*)(char const*, float&), 0x005107F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadFloat, float(__fastcall zCArchiverBinSafe::*)(char const*), 0x005105B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadBool, void(__fastcall zCArchiverBinSafe::*)(char const*, int&), 0x005108E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadBool, int(__fastcall zCArchiverBinSafe::*)(char const*), 0x00510670);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadString, void(__fastcall zCArchiverBinSafe::*)(char const*, zSTRING&), 0x00510910);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadString, zSTRING(__fastcall zCArchiverBinSafe::*)(char const*), 0x00510690);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadVec3, void(__fastcall zCArchiverBinSafe::*)(char const*, zVEC3&), 0x00510820);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadVec3, zVEC3(__fastcall zCArchiverBinSafe::*)(char const*), 0x005105D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadColor, void(__fastcall zCArchiverBinSafe::*)(char const*, zCOLOR&), 0x00510940);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadColor, zCOLOR(__fastcall zCArchiverBinSafe::*)(char const*), 0x00510750);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadEnum, void(__fastcall zCArchiverBinSafe::*)(char const*, int&), 0x00510970);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadEnum, int(__fastcall zCArchiverBinSafe::*)(char const*), 0x00510770);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ReadRaw, 0x00510790);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ReadRawFloat, 0x005107C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadObject, zCObject*(__fastcall zCArchiverBinSafe::*)(zCObject*), 0x0050FDD0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadObject, zCObject*(__fastcall zCArchiverBinSafe::*)(char const*, zCObject*), 0x0050F780);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadChunkStart, int(__fastcall zCArchiverBinSafe::*)(zSTRING&, unsigned short&), 0x0050F600);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadChunkStart, int(__fastcall zCArchiverBinSafe::*)(char const*), 0x0050F060);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ReadChunkStartNamed, 0x0050F720);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::SkipOpenChunk, 0x0050BF30);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::GetCurrentChunkVersion, 0x0050F750);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::GetFile, 0x0050BF40);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::GetBufferString, 0x0050C7B0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::GetBuffer, 0x0050C920);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::EndOfArchive, 0x0050C720);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::Close, 0x0050C320);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::SetStringEOL, 0x0050BF50);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::GetStringEOL, 0x0050C0D0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::IsStringValid, 0x0050CC90);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::GetChecksumEnabled, 0x0050C110);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::SetChecksumEnabled, 0x0050C120);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::SetNoReadSearchCycles, 0x0050C130);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::InProperties, 0x0050C140);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::InSaveGame, 0x0050C150);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::InBinaryMode, 0x0050C160);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::GetParentObject, 0x005109A0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::OpenWriteBuffer, 0x0050C930);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::OpenWriteFile, 0x0050CAF0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteHeader, 0x0050CC10);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteHeaderNumObj, 0x0050C2C0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteASCIILine, 0x0050CCD0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::StoreBuffer, 0x0050CB50);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::StoreString, 0x0050CB80);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::StoreStringEOL, 0x0050CC00);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::StoreGetPos, 0x0050CBB0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::StoreSeek, 0x0050CBD0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::OpenReadBuffer, 0x0050E4F0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::OpenReadFile, 0x0050E6C0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::GetClassDefByString, 0x0050EC60);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::CreateObject, 0x0050EB90);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::SkipChunk, 0x0050FDE0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ReadChunkStartASCII, 0x0050EE00);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ReadChunkEnd, 0x0050F770);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ReadEntryASCII, 0x0050FFB0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ReadHeader, 0x0050E7D0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::RestoreBuffer, 0x0050E720);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::RestoreStringEOL, 0x0050E750);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::RestoreString0, 0x0050E760);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::RestoreGetPos, 0x0050E770);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::RestoreSeek, 0x0050E790);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::DeleteBuffer, 0x0050C790);

} // namespace Gothic_I_Classic
