namespace Gothic_I_Classic {

	ZENGIN_REGISTER_CLASS(zCArchiverGeneric);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::zCArchiverGeneric_OnInit, 0x00511AB0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::DebugMessage, 0x00511F70);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::CheckObjectListSize, 0x00514EA0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::_GetClassDef, 0x00511BD0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteInt, 0x005129E0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteByte, 0x00512AA0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteWord, 0x00512B70);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteFloat, 0x00512C40);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteBool, 0x00512D10);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteString, 0x00512DE0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteVec3, 0x00512E40);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteColor, 0x00513080);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteRaw, 0x00513330);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteRawFloat, 0x00513500);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteEnum, 0x00513790);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::WriteObject, void(__fastcall zCArchiverGeneric::*)(zCObject*), 0x00514310);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::WriteObject, void(__fastcall zCArchiverGeneric::*)(char const*, zCObject*), 0x00514270);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::WriteObject, void(__fastcall zCArchiverGeneric::*)(char const*, zCObject&), 0x00514060);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::WriteChunkStart, void(__fastcall zCArchiverGeneric::*)(char const*, unsigned short), 0x00513DA0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::WriteChunkStart, void(__fastcall zCArchiverGeneric::*)(char const*, char const*, unsigned short, unsigned long), 0x00513940);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteChunkEnd, 0x00513DC0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteGroupBegin, 0x00514320);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteGroupEnd, 0x00514400);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadInt, void(__fastcall zCArchiverGeneric::*)(char const*, int&), 0x00516EE0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadInt, int(__fastcall zCArchiverGeneric::*)(char const*), 0x00516880);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadByte, void(__fastcall zCArchiverGeneric::*)(char const*, unsigned char&), 0x00516F30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadByte, unsigned char(__fastcall zCArchiverGeneric::*)(char const*), 0x005168A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadWord, void(__fastcall zCArchiverGeneric::*)(char const*, unsigned short&), 0x00516F80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadWord, unsigned short(__fastcall zCArchiverGeneric::*)(char const*), 0x005168C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadFloat, void(__fastcall zCArchiverGeneric::*)(char const*, float&), 0x00516E30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadFloat, float(__fastcall zCArchiverGeneric::*)(char const*), 0x00516820);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadBool, void(__fastcall zCArchiverGeneric::*)(char const*, int&), 0x00516FD0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadBool, int(__fastcall zCArchiverGeneric::*)(char const*), 0x005168E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadString, void(__fastcall zCArchiverGeneric::*)(char const*, zSTRING&), 0x00517030);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadString, zSTRING(__fastcall zCArchiverGeneric::*)(char const*), 0x00516900);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadVec3, void(__fastcall zCArchiverGeneric::*)(char const*, zVEC3&), 0x00516E80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadVec3, zVEC3(__fastcall zCArchiverGeneric::*)(char const*), 0x00516840);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadColor, void(__fastcall zCArchiverGeneric::*)(char const*, zCOLOR&), 0x00517060);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadColor, zCOLOR(__fastcall zCArchiverGeneric::*)(char const*), 0x005169C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadEnum, void(__fastcall zCArchiverGeneric::*)(char const*, int&), 0x005170F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadEnum, int(__fastcall zCArchiverGeneric::*)(char const*), 0x005169E0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::ReadRaw, 0x00516A00);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::ReadRawFloat, 0x00516C30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadObject, zCObject*(__fastcall zCArchiverGeneric::*)(zCObject*), 0x005161B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadObject, zCObject*(__fastcall zCArchiverGeneric::*)(char const*, zCObject*), 0x005159C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadChunkStart, int(__fastcall zCArchiverGeneric::*)(zSTRING&, unsigned short&), 0x00515840);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadChunkStart, int(__fastcall zCArchiverGeneric::*)(char const*), 0x00515410);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::ReadChunkStartNamed, 0x00515960);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::SkipOpenChunk, 0x00511BE0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::GetCurrentChunkVersion, 0x00515990);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::GetFile, 0x00511BF0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::GetBufferString, 0x00512290);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::GetBuffer, 0x00512400);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::EndOfArchive, 0x00512200);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::Close, 0x00512080);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::SetStringEOL, 0x00511C00);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::GetStringEOL, 0x00511D80);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::IsStringValid, 0x005127B0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::GetChecksumEnabled, 0x00511DC0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::SetChecksumEnabled, 0x00511DD0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::SetNoReadSearchCycles, 0x00511DE0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::InProperties, 0x00511DF0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::InSaveGame, 0x00511E00);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::InBinaryMode, 0x00511E10);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::GetParentObject, 0x005179E0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::OpenWriteBuffer, 0x00512410);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::OpenWriteFile, 0x005125E0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteHeader, 0x00512740);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteHeaderNumObj, 0x00511F90);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteASCIILine, 0x005127F0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::StoreBuffer, 0x00512650);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::StoreString, 0x00512680);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::StoreStringEOL, 0x00512710);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::StoreGetPos, 0x005126C0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::StoreSeek, 0x005126E0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::OpenReadBuffer, 0x005144E0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::OpenReadFile, 0x005146B0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::GetClassDefByString, 0x00515020);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::CreateObject, 0x00514F50);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::SkipChunk, 0x005161C0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::ReadChunkStartASCII, 0x005151C0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::ReadChunkEnd, 0x005159B0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::ReadEntryASCII, 0x005163C0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::ReadHeader, 0x00514BA0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::RestoreBuffer, 0x00514720);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::RestoreStringEOL, 0x00514750);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::RestoreString0, 0x00514B30);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::RestoreGetPos, 0x00514B40);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::RestoreSeek, 0x00514B60);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::DeleteBuffer, 0x00512270);

} // namespace Gothic_I_Classic
