namespace Gothic_I_Classic {

	ZENGIN_REGISTER_CLASS(zCBspBase);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::zCBspBase_OnInit, 0x00526200);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::DescribeTree, 0x00518C50);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CountNodes, 0x0051A320);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::AddVobsToRenderListSubtree, 0x0051C0F0);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::GetScreenBBox2D, 0x0051C1C0);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CollectNodeLights, 0x0051C430);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::RenderTrivInIndoor, 0x0051C780);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::RenderIndoor, 0x0051C7C0);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::RenderNodeOutdoor, 0x0051C860);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::AddVobToLeafs, 0x0051E1C0);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::AddVobLightToLeafs, 0x0051E300);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::RemoveVobFromLeafs, 0x0051E610);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CollectVobsSubtree, 0x0051E7B0);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CollectVobsInBBox3D, 0x0051E7C0);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CollectVobsSubtree_I, 0x0051E7D0);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CollectLightVobsSubtree, 0x0051E9D0);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CollectLightVobsSubtree_I, 0x0051E9E0);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CollectVobsInBBox3D_I, 0x0051EBE0);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::FindLeaf, 0x0051F050);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CheckRayAgainstPolys, 0x0051F180);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CheckRayAgainstPolysNearestHit, 0x0051F2A0);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CheckRayAgainstPolysCache, 0x0051F440);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::RayIntersection, 0x0051F5E0);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CollectPolysInBBox3DRec, 0x0051FE70);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::CollectPolysInBBox3D, 0x005200C0);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::SortNodePolys, 0x00520C00);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::SaveBINRec, 0x00524230);
	ZENGIN_REGISTER_METHOD(zCBspBase, &zCBspBase::LoadBINRec, 0x00524330);

	ZENGIN_REGISTER_CLASS(zCBspNode);
	ZENGIN_REGISTER_METHOD(zCBspNode, &zCBspNode::zCBspNode_OnInit, 0x0051A300);
	ZENGIN_REGISTER_METHOD(zCBspNode, &zCBspNode::CalcPlaneSignbits, 0x0051E180);

	ZENGIN_REGISTER_CLASS(zCBspLeaf);
	ZENGIN_REGISTER_METHOD(zCBspLeaf, &zCBspLeaf::zCBspLeaf_OnInit, 0x005198F0);
	ZENGIN_REGISTER_METHOD(zCBspLeaf, &zCBspLeaf::PolyPlueckerAddRef, 0x0051B6E0);
	ZENGIN_REGISTER_METHOD(zCBspLeaf, &zCBspLeaf::PolyPlueckerRelease, 0x0051B960);
	ZENGIN_REGISTER_METHOD(zCBspLeaf, &zCBspLeaf::AddVobsToRenderList, 0x0051B990);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCBspLeaf, &zCBspLeaf::AddVobsToRenderListOutdoor, void(zCBspLeaf::*)(), 0x0051BBA0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCBspLeaf, &zCBspLeaf::AddVobsToRenderListOutdoor, void(__fastcall zCBspLeaf::*)(zCBspSector*, zTBBox2D const&), 0x0051BEF0);
	ZENGIN_REGISTER_METHOD(zCBspLeaf, &zCBspLeaf::RenderLeafIndoor, 0x0051C5C0);
	ZENGIN_REGISTER_METHOD(zCBspLeaf, &zCBspLeaf::TraceRayCollectVobs, 0x0051EE30);

	ZENGIN_REGISTER_CLASS(zCBspTree);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::zCBspTree_OnInit, 0x00519560);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::InitTree, 0x00519810);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::DisposeTree, 0x00519970);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::BuildRecursive, 0x00519BD0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::Build, 0x00519EB0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::UpdateVertexDependencies, 0x0051A360);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::CollectPolysInBBox3DAngle, 0x0051A530);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::RenderLightList, 0x0051A6A0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::RenderVobList, 0x0051A7E0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::Render, 0x0051D840);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::RemoveVob, 0x0051E6E0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::AddVob, 0x0051E6F0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::AdjustVob, 0x0051E750);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::CalcLeafRealBBox3D, 0x0051F090);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::TraceRay, 0x0051F850);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::FindLeaks, 0x00520310);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::MarkOccluderPolys, 0x00520640);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::GetSectorNameVobIsIn, 0x00521920);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::GetBspSectorByName, 0x00523DF0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::CreateBspSectors2, 0x00523EA0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::SaveBIN, 0x005244C0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::ConnectMaterialsToSectors, 0x00524FC0);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::LoadBIN, 0x00525330);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::CalcStaticLeafLightData, 0x00526230);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::PreprocessIndoorPortals, 0x0052E430);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::GetPolyNeighbours, 0x0052E790);
	ZENGIN_REGISTER_METHOD(zCBspTree, &zCBspTree::PostprocessIndoorPortals, 0x0052E840);

	ZENGIN_REGISTER_CLASS(zCCBspNode);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::zCCBspNode_OnInit, 0x0052D330);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CheckRayAgainstPolysNearestHit, 0x0051FA60);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::RayIntersectionOctree, 0x0051FB80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCBspNode, &zCCBspNode::TraceRay, int(zCCBspNode::*)(zVEC3 const&, zVEC3 const&, zCPolygon*&, zVEC3&), 0x0051FE00);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCBspNode, &zCCBspNode::TraceRay, int(zCCBspNode::*)(zVEC3 const&, zVEC3 const&, zCPolygon*&), 0x0051FE30);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CollectPolysInBBox3DRec, 0x00520110);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CollectPolysInBBox3D, 0x005202C0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::RemovePoly, 0x005282C0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::LODGenerate, 0x005283A0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::LODTriangulatePortal, 0x00528970);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::LODCollectLeafPolys, 0x00528CF0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::DoesNodeContainPoly, 0x0052A610);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CheckPortalConsistency, 0x0052A690);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::SplitPortals, 0x0052ADC0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::SplitPortalByAllPortals, 0x0052B350);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::EnumeratePortals, 0x0052B600);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::ClassifyPortals, 0x0052B760);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::Portalize, 0x0052B7F0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::SelectPlane, 0x0052BAE0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::SelectPlaneOctree, 0x0052BD40);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::ClassifyRayToNode, 0x0052BF60);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::ClassifyPolyToNode2, 0x0052C1A0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::OutdoorKillRedundantLeafs, 0x0052C410);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::AddPoly, 0x0052C660);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::BuildTree, 0x0052C6B0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::PushPolyFront, 0x0052D350);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CalcBBox3D, 0x0052D3F0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CalcSubtreeBBox3D, 0x0052D4D0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CalcSubtreeBBox3DCell, 0x0052D680);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CountNodes, 0x0052D770);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CountLeafs, 0x0052D7A0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CountPolys, 0x0052D7E0);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CountDepthRec, 0x0052D810);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::CountDepth, 0x0052D880);
	ZENGIN_REGISTER_METHOD(zCCBspNode, &zCCBspNode::DescribeTree, 0x0052D930);

	ZENGIN_REGISTER_CLASS(zCCBspTree);
	ZENGIN_REGISTER_METHOD(zCCBspTree, &zCCBspTree::zCCBspTree_OnInit, 0x00527410);
	ZENGIN_REGISTER_METHOD(zCCBspTree, &zCCBspTree::GetBspSectorByName, 0x00521870);
	ZENGIN_REGISTER_METHOD(zCCBspTree, &zCCBspTree::GetPolyNeighbours, 0x00521940);
	ZENGIN_REGISTER_METHOD(zCCBspTree, &zCCBspTree::MarkGhostOccluder, 0x00521A20);
	ZENGIN_REGISTER_METHOD(zCCBspTree, &zCCBspTree::CreateBspSectors, 0x00521BD0);
	ZENGIN_REGISTER_METHOD(zCCBspTree, &zCCBspTree::SetBspTreeMode, 0x00527540);
	ZENGIN_REGISTER_METHOD(zCCBspTree, &zCCBspTree::DeleteTree, 0x005276A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCBspTree, &zCCBspTree::AddMesh, void(zCCBspTree::*)(zCMesh*), 0x005277F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCBspTree, &zCCBspTree::AddMesh, void(zCCBspTree::*)(zCMesh*, zMAT4 const&), 0x00527820);
	ZENGIN_REGISTER_METHOD(zCCBspTree, &zCCBspTree::BuildTree, 0x00527B00);

	ZENGIN_REGISTER_CLASS(zCBspSector);
	ZENGIN_REGISTER_METHOD(zCBspSector, &zCBspSector::CalcCenterByPortals, 0x00518380);
	ZENGIN_REGISTER_METHOD(zCBspSector, &zCBspSector::IsRendered, 0x00518420);
	ZENGIN_REGISTER_METHOD(zCBspSector, &zCBspSector::Rendered, 0x00518440);
	ZENGIN_REGISTER_METHOD(zCBspSector, &zCBspSector::IsActivated, 0x00518450);
	ZENGIN_REGISTER_METHOD(zCBspSector, &zCBspSector::Activate, 0x00518470);
	ZENGIN_REGISTER_METHOD(zCBspSector, &zCBspSector::HasManyBigPortals, 0x00518550);
	ZENGIN_REGISTER_METHOD(zCBspSector, &zCBspSector::RenderSector, 0x00520C50);
	ZENGIN_REGISTER_METHOD(zCBspSector, &zCBspSector::ActivateSectorRec, 0x00520D90);
	ZENGIN_REGISTER_METHOD(zCBspSector, &zCBspSector::ActivateSectorRecIndoor, 0x00521310);

	ZENGIN_REGISTER_CLASS(zCBuildPortal);
	ZENGIN_REGISTER_METHOD(zCBuildPortal, &zCBuildPortal::zCBuildPortal_OnInit, 0x0052E320);

} // namespace Gothic_I_Classic
