namespace Gothic_I_Classic {

	ZENGIN_REGISTER_CLASS(zCEvMsgCutscene);
	ZENGIN_REGISTER_METHOD(zCEvMsgCutscene, &zCEvMsgCutscene::zCEvMsgCutscene_OnInit, 0x0040C100);
	ZENGIN_REGISTER_METHOD(zCEvMsgCutscene, &zCEvMsgCutscene::SetCutsceneName, 0x004136F0);
	ZENGIN_REGISTER_METHOD(zCEvMsgCutscene, &zCEvMsgCutscene::GetCutsceneName, 0x006A84B0);
	ZENGIN_REGISTER_METHOD(zCEvMsgCutscene, &zCEvMsgCutscene::_GetClassDef, 0x0040B550);
	ZENGIN_REGISTER_METHOD(zCEvMsgCutscene, &zCEvMsgCutscene::IsHighPriority, 0x0040B560);
	ZENGIN_REGISTER_METHOD(zCEvMsgCutscene, &zCEvMsgCutscene::Delete, 0x0040B570);
	ZENGIN_REGISTER_METHOD(zCEvMsgCutscene, &zCEvMsgCutscene::IsDeleted, 0x0040B580);
	ZENGIN_REGISTER_METHOD(zCEvMsgCutscene, &zCEvMsgCutscene::MD_GetNumOfSubTypes, 0x0040C2B0);
	ZENGIN_REGISTER_METHOD(zCEvMsgCutscene, &zCEvMsgCutscene::MD_GetSubTypeString, 0x0040C2C0);

	ZENGIN_REGISTER_CLASS(zCCSRole);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSRole, &zCCSRole::zCCSRole_OnInit, void(zCCSRole::*)(), 0x0040B620);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSRole, &zCCSRole::zCCSRole_OnInit, void(zCCSRole::*)(zSTRING&), 0x0040B770);
	ZENGIN_REGISTER_METHOD(zCCSRole, &zCCSRole::SetRoleVob, 0x0040BB20);
	ZENGIN_REGISTER_METHOD(zCCSRole, &zCCSRole::GetRoleVob, 0x0040BF40);
	ZENGIN_REGISTER_METHOD(zCCSRole, &zCCSRole::_GetClassDef, 0x0040B220);
	ZENGIN_REGISTER_METHOD(zCCSRole, &zCCSRole::Archive, 0x0040BF50);
	ZENGIN_REGISTER_METHOD(zCCSRole, &zCCSRole::Unarchive, 0x0040BFB0);

	ZENGIN_REGISTER_CLASS(zCCSBlockBase);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::zCCSBlockBase_OnInit, 0x0040C470);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::_GetClassDef, 0x0040AC20);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::Archive, 0x00416680);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::Unarchive, 0x00416690);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::GetChild, 0x0040C610);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::GetRoleName, 0x0040C670);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::SetRoleName, 0x0040C700);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::GetCommand, 0x00404E40);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::NewBlock, 0x0040C620);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::InsertBlock, 0x0040A610);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::DeleteChild, 0x0040C710);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::GetNumOfChilds, 0x0040C630);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::GetRoleNumOfChild, 0x0040C640);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::BlockCorrection, 0x0040C650);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::BlockAsFocus, 0x0040C660);
	ZENGIN_REGISTER_METHOD(zCCSBlockBase, &zCCSBlockBase::GetChildPos, 0x0040C720);

	ZENGIN_REGISTER_CLASS(zCCSAtomicBlock);
	ZENGIN_REGISTER_METHOD(zCCSAtomicBlock, &zCCSAtomicBlock::zCCSAtomicBlock_OnInit, 0x0040C730);
	ZENGIN_REGISTER_METHOD(zCCSAtomicBlock, &zCCSAtomicBlock::_GetClassDef, 0x0040A640);
	ZENGIN_REGISTER_METHOD(zCCSAtomicBlock, &zCCSAtomicBlock::Archive, 0x004166A0);
	ZENGIN_REGISTER_METHOD(zCCSAtomicBlock, &zCCSAtomicBlock::Unarchive, 0x004166C0);
	ZENGIN_REGISTER_METHOD(zCCSAtomicBlock, &zCCSAtomicBlock::OrganizeRoles, 0x0040C930);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSAtomicBlock, &zCCSAtomicBlock::Play, void(zCCSAtomicBlock::*)(zCArray<zCEventManager*> const&), 0x0040CB90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSAtomicBlock, &zCCSAtomicBlock::Play, void(zCCSAtomicBlock::*)(zCArray<zCEventManager*> const&, float, float), 0x0040CBB0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSAtomicBlock, &zCCSAtomicBlock::Play, void(zCCSAtomicBlock::*)(zCEventManager*), 0x0040CBD0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSAtomicBlock, &zCCSAtomicBlock::Play, void(zCCSAtomicBlock::*)(zCEventManager*, float, float), 0x0040CC50);
	ZENGIN_REGISTER_METHOD(zCCSAtomicBlock, &zCCSAtomicBlock::GetMinTime, 0x0040CC60);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSAtomicBlock, &zCCSAtomicBlock::IsFinished, int(zCCSAtomicBlock::*)(zCArray<zCEventManager*> const&), 0x0040A650);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSAtomicBlock, &zCCSAtomicBlock::IsFinished, int(zCCSAtomicBlock::*)(zCEventManager*), 0x0040CC80);
	ZENGIN_REGISTER_METHOD(zCCSAtomicBlock, &zCCSAtomicBlock::GetCommand, 0x0040A660);

	ZENGIN_REGISTER_CLASS(zCCSBlockPosition);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSBlockPosition, &zCCSBlockPosition::zCCSBlockPosition_OnInit, void(zCCSBlockPosition::*)(), 0x004165F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSBlockPosition, &zCCSBlockPosition::zCCSBlockPosition_OnInit, void(zCCSBlockPosition::*)(zCCSBlockBase*), 0x00416610);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSBlockPosition, &zCCSBlockPosition::zCCSBlockPosition_OnInit, void(zCCSBlockPosition::*)(float, zCCSBlockBase*), 0x00416630);

	ZENGIN_REGISTER_CLASS(zCCSBlock);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::zCCSBlock_OnInit, 0x0040CE70);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::_GetClassDef, 0x0040A950);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::Archive, 0x004166F0);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::Unarchive, 0x00416860);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::GetChild, 0x0040D020);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::OrganizeRoles, 0x0040D550);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::GetRoleName, 0x0040D5A0);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::SetRoleName, 0x0040D5F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSBlock, &zCCSBlock::Play, void(zCCSBlock::*)(zCArray<zCEventManager*> const&), 0x0040D210);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSBlock, &zCCSBlock::Play, void(zCCSBlock::*)(zCArray<zCEventManager*> const&, float, float), 0x0040D2E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSBlock, &zCCSBlock::Play, void(zCCSBlock::*)(zCEventManager*), 0x0040D100);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSBlock, &zCCSBlock::Play, void(zCCSBlock::*)(zCEventManager*, float, float), 0x0040D150);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::GetMinTime, 0x0040D3B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSBlock, &zCCSBlock::IsFinished, int(zCCSBlock::*)(zCArray<zCEventManager*> const&), 0x0040D490);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSBlock, &zCCSBlock::IsFinished, int(zCCSBlock::*)(zCEventManager*), 0x0040D440);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::NewBlock, 0x0040D7D0);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::InsertBlock, 0x0040D730);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::DeleteChild, 0x0040D070);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::GetNumOfChilds, 0x0040D060);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::BlockCorrection, 0x0040D8B0);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::BlockAsFocus, 0x0040D870);
	ZENGIN_REGISTER_METHOD(zCCSBlock, &zCCSBlock::GetChildPos, 0x0040D040);

	ZENGIN_REGISTER_CLASS(zCCSSyncBlock);
	ZENGIN_REGISTER_METHOD(zCCSSyncBlock, &zCCSSyncBlock::zCCSSyncBlock_OnInit, 0x0040D9B0);
	ZENGIN_REGISTER_METHOD(zCCSSyncBlock, &zCCSSyncBlock::AssignerCorrection, 0x0040DFC0);
	ZENGIN_REGISTER_METHOD(zCCSSyncBlock, &zCCSSyncBlock::_GetClassDef, 0x0040AC50);
	ZENGIN_REGISTER_METHOD(zCCSSyncBlock, &zCCSSyncBlock::Archive, 0x00416A20);
	ZENGIN_REGISTER_METHOD(zCCSSyncBlock, &zCCSSyncBlock::Unarchive, 0x00416BE0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSSyncBlock, &zCCSSyncBlock::Play, void(zCCSSyncBlock::*)(zCArray<zCEventManager*> const&), 0x0040DB90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSSyncBlock, &zCCSSyncBlock::Play, void(zCCSSyncBlock::*)(zCArray<zCEventManager*> const&, float, float), 0x0040DC40);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCSSyncBlock, &zCCSSyncBlock::Play, void(zCCSSyncBlock::*)(zCEventManager*), 0x0040DB40);
	ZENGIN_REGISTER_METHOD(zCCSSyncBlock, &zCCSSyncBlock::IsFinished, 0x0040DAF0);
	ZENGIN_REGISTER_METHOD(zCCSSyncBlock, &zCCSSyncBlock::NewBlock, 0x0040DDE0);
	ZENGIN_REGISTER_METHOD(zCCSSyncBlock, &zCCSSyncBlock::InsertBlock, 0x0040DD10);
	ZENGIN_REGISTER_METHOD(zCCSSyncBlock, &zCCSSyncBlock::DeleteChild, 0x0040DF00);
	ZENGIN_REGISTER_METHOD(zCCSSyncBlock, &zCCSSyncBlock::GetRoleNumOfChild, 0x0040DCF0);
	ZENGIN_REGISTER_METHOD(zCCSSyncBlock, &zCCSSyncBlock::BlockAsFocus, 0x0040DEB0);

	ZENGIN_REGISTER_CLASS(zCCutscene);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::zCCutscene_OnInit, 0x0040DFF0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::IsMember, 0x0040E3E0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::SetRoleListForDebugging, 0x0040E410);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::SaveRolesVobs, 0x0040E5C0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::RestoreRoleVobs, 0x0040E7E0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::CheckMainRole, 0x0040EA20);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::CheckPlayState, 0x0040F870);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::SolveEventManager, 0x00413CD0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::GetActualBlockNum, 0x00415770);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::ResumeAtBlock, 0x00415B20);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::NewRole, 0x00416040);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::DeleteRole, 0x00416230);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::RegisterAdditionalVob, 0x00416320);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::FirstRoleUsed, 0x00417180);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::GetLastCheckResult, 0x00417250);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::TryToCancel, 0x00417550);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::GetFirstBlockPosition, 0x00417580);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::GetNextMessage, 0x00417720);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::GetNextBlock, 0x00417770);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::SerializeCutscene, 0x004177A0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::SerializeBlock, 0x00417930);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::GetProperties, 0x0041CCF0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::_GetClassDef, 0x0040E1E0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::Archive, 0x00416E30);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::Unarchive, 0x00416EC0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::NewBlock, 0x00415BA0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::AddMainRole, 0x00410190);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::AddRoleOU, 0x0040F9B0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::RemoveRole, 0x004109B0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::SetOwnerPlayer, 0x0040E3A0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::Reset, 0x00413860);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::ClearCutscene, 0x00413960);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::StartPlaying, 0x00412AD0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::Stop, 0x00413D10);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::StopRole, 0x00413B50);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::Interrupt, 0x00414DB0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::ResumeActBlock, 0x00415780);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::PlaySub, 0x00415B30);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::NewCS, 0x00415DA0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::IsCutscene, 0x0040E1F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCutscene, &zCCutscene::IsFinished, int(zCCutscene::*)(zCArray<zCEventManager*> const&), 0x0040D490);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCutscene, &zCCutscene::IsFinished, int(zCCutscene::*)(zCEventManager*), 0x0040D440);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCutscene, &zCCutscene::IsFinished, int(zCCutscene::*)(), 0x00415B90);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::PrintDebugInfo, 0x00417240);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::CheckRoles, 0x004171B0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::CSCheck, 0x00410A30);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::GetStage, 0x0040F860);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::LoadStage, 0x00416390);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::CatchPlayer, 0x004165B0);
	ZENGIN_REGISTER_METHOD(zCCutscene, &zCCutscene::PrepareBlock, 0x0040F930);

} // namespace Gothic_I_Classic
