namespace Gothic_I_Classic {

	ZENGIN_REGISTER_CLASS(zCCSProps);
	ZENGIN_REGISTER_METHOD(zCCSProps, &zCCSProps::zCCSProps_OnInit, 0x00421720);
	ZENGIN_REGISTER_METHOD(zCCSProps, &zCCSProps::GetName, 0x00406090);
	ZENGIN_REGISTER_METHOD(zCCSProps, &zCCSProps::GetScriptFuncOnStop, 0x00407400);
	ZENGIN_REGISTER_METHOD(zCCSProps, &zCCSProps::_GetClassDef, 0x004218E0);
	ZENGIN_REGISTER_METHOD(zCCSProps, &zCCSProps::Archive, 0x004219E0);
	ZENGIN_REGISTER_METHOD(zCCSProps, &zCCSProps::Unarchive, 0x00421AC0);
	ZENGIN_REGISTER_METHOD(zCCSProps, &zCCSProps::AcceptRole, 0x004222B0);
	ZENGIN_REGISTER_METHOD(zCCSProps, &zCCSProps::CheckRole, 0x004222C0);
	ZENGIN_REGISTER_METHOD(zCCSProps, &zCCSProps::GetCheckRoleResult, 0x00421C20);
	ZENGIN_REGISTER_METHOD(zCCSProps, &zCCSProps::CheckDistance, 0x00421BB0);
	ZENGIN_REGISTER_METHOD(zCCSProps, &zCCSProps::CheckRange, 0x00421BF0);
	ZENGIN_REGISTER_METHOD(zCCSProps, &zCCSProps::PrintDebugInfo, 0x00421C30);

} // namespace Gothic_I_Classic
