namespace Gothic_I_Classic {

	ZENGIN_REGISTER_CLASS(zFILE_VDFS);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::zFILE_VDFS_OnInit, void(zFILE_VDFS::*)(), 0x00444B60);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::zFILE_VDFS_OnInit, void(zFILE_VDFS::*)(zSTRING const&), 0x00444D90);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::Init, 0x00444B20);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::HandleError, 0x00445080);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::GetFullPath, 0x004459F0);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::SetCurrentDir, 0x004457A0);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::ChangeDir, 0x00445B40);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::SearchFile, 0x00445B50);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::FindFirst, 0x00445FD0);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::FindNext, 0x00446280);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::IsOpened, 0x00444F60);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::Open, int(zFILE_VDFS::*)(bool), 0x00445090);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::Open, int(zFILE_VDFS::*)(zSTRING const&, bool), 0x00444CA0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::Exists, bool(zFILE_VDFS::*)(), 0x00444F90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::Exists, bool(zFILE_VDFS::*)(zSTRING const&), 0x00444D10);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::Close, 0x00445310);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::Reset, 0x00445370);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::Append, 0x00445780);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::Size, 0x00445380);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::Pos, 0x00445720);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::Seek, 0x00445400);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::Eof, 0x004453E0);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::GetStats, 0x00445FC0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::Read, long(zFILE_VDFS::*)(void*, long), 0x004468C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::Read, int(zFILE_VDFS::*)(char*), 0x004465A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::Read, int(zFILE_VDFS::*)(zSTRING&), 0x00446750);

} // namespace Gothic_I_Classic
