namespace Gothic_I_Classic {

	ZENGIN_REGISTER_CLASS(zCFileCSV);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCFileCSV, &zCFileCSV::zCFileCSV_OnInit, void(zCFileCSV::*)(zSTRING const&), 0x0044A1B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCFileCSV, &zCFileCSV::zCFileCSV_OnInit, void(zCFileCSV::*)(), 0x0044A370);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::InitCSV, 0x0044A670);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::SetFormat, 0x0044A790);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::AddNextField, 0x0044A8D0);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::AddNextHeader, 0x0044AA60);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::WriteSet, 0x0044AC10);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::GetNextField, 0x0044ADD0);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::ReadSet, 0x0044B200);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::ReadHeader, 0x0044B250);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::WriteHeader, 0x0044B430);

} // namespace Gothic_I_Classic
