namespace Gothic_I_Classic {

	ZENGIN_REGISTER_CLASS(zCFile3DS);
	ZENGIN_REGISTER_METHOD(zCFile3DS, &zCFile3DS::Load3DS, 0x00546C00);
	ZENGIN_REGISTER_METHOD(zCFile3DS, &zCFile3DS::Save3DS, 0x00548320);

	ZENGIN_REGISTER_CLASS(zCFileQuakeBSP);
	ZENGIN_REGISTER_METHOD(zCFileQuakeBSP, &zCFileQuakeBSP::zCFileQuakeBSP_OnInit, 0x00549F40);
	ZENGIN_REGISTER_METHOD(zCFileQuakeBSP, &zCFileQuakeBSP::LoadQuakeBSP, 0x00549F70);

	ZENGIN_REGISTER_CLASS(zCFileBIN);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::zCFileBIN_OnInit, 0x00550AF0);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinCreate, 0x00550B90);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinClose, 0x00550BC0);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinStartChunk, 0x0056CC80);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinWriteSrcFileStats, 0x0056CD20);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinEndChunk, 0x0056DA20);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinWriteString, 0x0056DCC0);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinReadCompareSrcFileStats, 0x00570240);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinSkipChunk, 0x005818B0);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinSetFile, 0x005F89E0);

} // namespace Gothic_I_Classic
