namespace Gothic_I_Classic {

	ZENGIN_REGISTER_CLASS(zCGfx);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCGfx, &zCGfx::zCGfx_OnInit, void(zCGfx::*)(zSTRING const&), 0x006E11A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCGfx, &zCGfx::zCGfx_OnInit, void(zCGfx::*)(int, int), 0x006E1370);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::LoadRaw, 0x006E1C20);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::Readbyte, 0x006E1CE0);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::LoadPcx, 0x006E1D50);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::LoadTga, 0x006E2240);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::SaveRaw, 0x006E35A0);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::Save, 0x006E3600);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::LoadGfx, 0x006E37A0);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::GetSizex, 0x006E3B00);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::GetSizey, 0x006E3B10);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::GetDataPtr, 0x006E3B20);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::GetPixel, 0x006E3B30);

} // namespace Gothic_I_Classic
