namespace Gothic_I_Classic {

	ZENGIN_REGISTER_CLASS(zCMenuItem);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenuItem, &zCMenuItem::zCMenuItem_OnInit, void(zCMenuItem::*)(zSTRING const&), 0x004D1F90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenuItem, &zCMenuItem::zCMenuItem_OnInit, void(zCMenuItem::*)(), 0x004D2160);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetSelItem, 0x004D1930);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Init, 0x004D2500);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::SetByScript, 0x004D2840);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetDimX, 0x004D3150);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetDimY, 0x004D3250);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::InitView, 0x004D3340);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Close, 0x004D34D0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetType, 0x004D3520);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenuItem, &zCMenuItem::SetName, void(zCMenuItem::*)(zSTRING const&), 0x004D3600);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetName, 0x004D3740);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetCoords, 0x004D3750);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetSelActionType, 0x004D3760);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetSelActionString, 0x004D3770);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenuItem, &zCMenuItem::SetName, void(zCMenuItem::*)(zSTRING&), 0x004D3790);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Register, 0x004D38F0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Unregister, 0x004D3AB0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::IsRegistered, 0x004D3BE0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::UpdateSize, 0x004D42B0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetEventFunc, 0x004D4C40);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::SetIsActive, 0x004D4C50);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::SetIsSelectable, 0x004D4D60);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetIsSelectable, 0x004D4DB0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::SetIsDisabled, 0x004D4E20);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetIsDisabled, 0x004D4E30);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::SetIsVisible, 0x004D4E70);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetIsVisible, 0x004D4E80);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::DrawItems, 0x004D4A80);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::InitMenuItem, 0x004D32B0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::ToggleValue, 0x004D34F0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Run, 0x004D45A0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetText, 0x004D3530);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenuItem, &zCMenuItem::SetText, void(zCMenuItem::*)(zSTRING const&, int, int), 0x004D3C80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenuItem, &zCMenuItem::SetText, void(zCMenuItem::*)(zCArray<zSTRING>, int), 0x004D4380);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::SetMinValue, 0x004D1EF0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::SetMaxValue, 0x004D1F00);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Enter, 0x004D4540);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Leave, 0x004D4550);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Draw, 0x004D4940);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::DrawFront, 0x004D4950);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Show, 0x004D3420);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Hide, 0x004D3460);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::HasBeenCanceled, 0x004D1F10);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Open, 0x004D34A0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Input, 0x004D4600);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::InsertInWin, 0x004D2B40);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::RemoveFromWin, 0x004D30F0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::UpdateContent, 0x004D4AA0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::UpdateFX, 0x004D4AB0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::HandleEvent, 0x004D4560);

	ZENGIN_REGISTER_CLASS(zCMenuItemInput);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::zCMenuItemInput_OnInit, 0x004D4EC0);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::SetValue, 0x004D5120);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::GetValue, 0x004D51A0);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::InitMenuItem, 0x004D51C0);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::Run, 0x004D53A0);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::Enter, 0x004D1F20);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::Leave, 0x004D1F30);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::HasBeenCanceled, 0x004D1F50);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::InsertInWin, 0x004D5370);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::HandleEvent, 0x004D1F40);

	ZENGIN_REGISTER_CLASS(zCMenuItemText);
	ZENGIN_REGISTER_METHOD(zCMenuItemText, &zCMenuItemText::zCMenuItemText_OnInit, 0x004D56D0);
	ZENGIN_REGISTER_METHOD(zCMenuItemText, &zCMenuItemText::FormatMultiline, 0x004D5850);
	ZENGIN_REGISTER_METHOD(zCMenuItemText, &zCMenuItemText::DrawMultiline, 0x004D5BD0);
	ZENGIN_REGISTER_METHOD(zCMenuItemText, &zCMenuItemText::InitMenuItem, 0x004D5F40);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenuItemText, &zCMenuItemText::SetText, void(zCMenuItemText::*)(zSTRING const&, int, int), 0x004D6430);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenuItemText, &zCMenuItemText::SetText, void(zCMenuItemText::*)(zCArray<zSTRING>, int), 0x004D66F0);
	ZENGIN_REGISTER_METHOD(zCMenuItemText, &zCMenuItemText::DrawFront, 0x004D5810);
	ZENGIN_REGISTER_METHOD(zCMenuItemText, &zCMenuItemText::SetEnum, 0x004D6100);
	ZENGIN_REGISTER_METHOD(zCMenuItemText, &zCMenuItemText::HandleEvent, 0x004D6280);

	ZENGIN_REGISTER_CLASS(zCMenuItemSlider);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::zCMenuItemSlider_OnInit, 0x004D6750);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::SetValue, 0x004D6E20);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::GetValue, 0x004D6EA0);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::InitMenuItem, 0x004D6AF0);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::ToggleValue, 0x004D6810);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::InsertInWin, 0x004D6BB0);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::RemoveFromWin, 0x004D6D90);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::SetIsActive, 0x004D1F60);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::HandleEvent, 0x004D1F80);

	ZENGIN_REGISTER_CLASS(zCMenuItemButton);
	ZENGIN_REGISTER_METHOD(zCMenuItemButton, &zCMenuItemButton::zCMenuItemButton_OnInit, 0x004D8090);
	ZENGIN_REGISTER_METHOD(zCMenuItemButton, &zCMenuItemButton::Toggle, 0x004D84C0);
	ZENGIN_REGISTER_METHOD(zCMenuItemButton, &zCMenuItemButton::InitMenuItem, 0x004D82F0);
	ZENGIN_REGISTER_METHOD(zCMenuItemButton, &zCMenuItemButton::Run, 0x004D86C0);
	ZENGIN_REGISTER_METHOD(zCMenuItemButton, &zCMenuItemButton::InsertInWin, 0x004D8930);
	ZENGIN_REGISTER_METHOD(zCMenuItemButton, &zCMenuItemButton::RemoveFromWin, 0x004D8970);

	ZENGIN_REGISTER_CLASS(zCMenuItemChoice);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::zCMenuItemChoice_OnInit, 0x004D6EB0);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::SetOptionByString, 0x004D7140);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::GetStringByOption, 0x004D7510);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::Resize, 0x004D7900);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::GetNumOptions, 0x004D7C10);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::InitMenuItem, 0x004D7F70);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::ToggleValue, 0x004D6F30);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::GetText, 0x004D7DF0);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::Draw, 0x004D79D0);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::DrawFront, 0x004D79E0);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::InsertInWin, 0x004D76A0);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::RemoveFromWin, 0x004D7870);

	ZENGIN_REGISTER_CLASS(zTMenuItemListElement);
	ZENGIN_REGISTER_METHOD(zTMenuItemListElement, &zTMenuItemListElement::zTMenuItemListElement_OnInit, 0x004D9FE0);

	ZENGIN_REGISTER_CLASS(zCMenuItemList);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::zCMenuItemList_OnInit, 0x004D8A30);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::DeleteContent, 0x004D8C80);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::InsertEnd, 0x004D8CD0);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::InsertFront, 0x004D8EE0);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::ShowContent, 0x004D98A0);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::JumpToNextEntry, 0x004D9A50);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::JumpToPrevEntry, 0x004D9A70);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::JumpToTopEntry, 0x004D9A90);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::JumpToLastEntry, 0x004D9AB0);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::InitMenuItem, 0x004D8BE0);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::Run, 0x004D8B50);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::Enter, 0x004D9300);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::Leave, 0x004D9310);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::DrawFront, 0x004D9330);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::Show, 0x004D8BF0);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::Hide, 0x004D8C40);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::InsertInWin, 0x004D90D0);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::RemoveFromWin, 0x004D9250);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::UpdateContent, 0x004D9320);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::HandleEvent, 0x004D9640);

} // namespace Gothic_I_Classic
