namespace Gothic_I_Classic {

	ZENGIN_REGISTER_CLASS(zCMenu);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenu, &zCMenu::zCMenu_OnInit, void(zCMenu::*)(), 0x004CD850);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenu, &zCMenu::zCMenu_OnInit, void(zCMenu::*)(zSTRING const&), 0x004CD9F0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::InitValues, 0x004CDD30);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::Release, 0x004CDF60);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::Register, 0x004CE1F0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::Unregister, 0x004CE420);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::IsRegistered, 0x004CE4C0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::ClearAllEvents, 0x004CE9B0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::PreviousOption, 0x004CE9D0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::NextOption, 0x004CEAA0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::RestartMusicTheme, 0x004CEB70);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::ForceSelAction, 0x004CF150);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::UpdateWindowGeometry, 0x004CF320);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::PrintInformation, 0x004CFE50);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::GetBackWorld, 0x004D0E80);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::GetBackDatFile, 0x004D0EC0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::GetActiveItem, 0x004D0EF0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::GetNumberOfActiveItem, 0x004D0F00);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::SetActiveItem, 0x004D0F70);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::GetName, 0x004D10D0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::SetName, 0x004D10E0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::HandleEvent, 0x004CEE10);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::HandleEnterItem, 0x004D1240);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::HandleLeaveItem, 0x004D1250);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::HandleActivateItem, 0x004D1260);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::Run, 0x004CEC30);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::Enter, 0x004CEB90);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::Leave, 0x004CEBF0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::Render, 0x004D0DA0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::RedrawItems, 0x004CFE20);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::HandleFrame, 0x004CF470);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::Activate, 0x004CF300);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::ScreenInit, 0x004CFF30);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::ScreenDone, 0x004D0B60);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::HandleAction, 0x004CF500);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::HandleSelAction, 0x004CF6E0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::SetByScript, 0x004CE720);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::ExecCommand, 0x004CFC10);

} // namespace Gothic_I_Classic
