namespace Gothic_I_Classic {

	ZENGIN_REGISTER_CLASS(zCModelMeshLib);
	ZENGIN_REGISTER_METHOD(zCModelMeshLib, &zCModelMeshLib::zCModelMeshLib_OnInit, 0x0057F3D0);
	ZENGIN_REGISTER_METHOD(zCModelMeshLib, &zCModelMeshLib::ReleaseData, 0x0057F570);
	ZENGIN_REGISTER_METHOD(zCModelMeshLib, &zCModelMeshLib::AllocNumNodeVisuals, 0x0057F5E0);
	ZENGIN_REGISTER_METHOD(zCModelMeshLib, &zCModelMeshLib::AddMeshSoftSkin, 0x0057F660);
	ZENGIN_REGISTER_METHOD(zCModelMeshLib, &zCModelMeshLib::AddNodeVisual, 0x0057F760);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelMeshLib, &zCModelMeshLib::ApplyToModel, void(zCModelMeshLib::*)(zCModel*), 0x0057F880);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelMeshLib, &zCModelMeshLib::ApplyToModel, void(zCModelMeshLib::*)(zCModelPrototype*), 0x0057F9E0);
	ZENGIN_REGISTER_METHOD(zCModelMeshLib, &zCModelMeshLib::RemoveFromModel, 0x0057FB60);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelMeshLib, &zCModelMeshLib::BuildFromModel, void(zCModelMeshLib::*)(zCModelPrototype*), 0x0057FC50);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelMeshLib, &zCModelMeshLib::BuildFromModel, void(zCModelMeshLib::*)(zCModel*), 0x0057FE70);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelMeshLib, &zCModelMeshLib::SaveMDM, void(zCModelMeshLib::*)(zCModelPrototype*), 0x005800D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelMeshLib, &zCModelMeshLib::SaveMDM, void(zCModelMeshLib::*)(zCFileBIN&, zCModelPrototype*), 0x005802E0);
	ZENGIN_REGISTER_METHOD(zCModelMeshLib, &zCModelMeshLib::_GetClassDef, 0x005649B0);

	ZENGIN_REGISTER_CLASS(zCModelAniEvent);
	ZENGIN_REGISTER_METHOD(zCModelAniEvent, &zCModelAniEvent::zCModelAniEvent_OnInit, 0x0056DA80);
	ZENGIN_REGISTER_METHOD(zCModelAniEvent, &zCModelAniEvent::Save, 0x0056DC00);
	ZENGIN_REGISTER_METHOD(zCModelAniEvent, &zCModelAniEvent::Load, 0x0056DD60);

	ZENGIN_REGISTER_CLASS(zCModelNode);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelNode, &zCModelNode::zCModelNode_OnInit, void(zCModelNode::*)(), 0x0056A110);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelNode, &zCModelNode::zCModelNode_OnInit, void(zCModelNode::*)(zCModelNode const&), 0x0056A250);
	ZENGIN_REGISTER_METHOD(zCModelNode, &zCModelNode::SetNodeVisualS, 0x0056A480);

	ZENGIN_REGISTER_CLASS(zCModelAni);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::zCModelAni_OnInit, 0x0056A870);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::PrecacheAniEventData, 0x0056AC80);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::GetAniVelocity, 0x0056AD50);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::GetAniTranslation, 0x0056AED0);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::AddTrafoMatrix, 0x0056B010);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::GetQuat, 0x0056B4A0);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::GetTrans, 0x0056B500);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::SetTrans, 0x0056B5A0);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::SetQuat, 0x0056B620);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::AddNodeList, 0x0056B6C0);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::SetFlags, 0x0056B740);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::SetBlendingSec, 0x0056B7F0);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::GetBlendingSec, 0x0056B850);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::CorrectRootNodeIdleMovement, 0x0056B8B0);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::CalcInPlaceFlag, 0x0056BA10);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::ResolveAlias, 0x0056BBF0);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::ResolveComb, 0x0056BED0);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::SaveMAN, 0x0056C560);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::LoadMAN, 0x0056CEB0);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::GetAniName, 0x0057E360);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::GetAniType, 0x0057E370);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::GetAniID, 0x006211C0);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::_GetClassDef, 0x0056AA10);

	ZENGIN_REGISTER_CLASS(zCModelPrototype);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::zCModelPrototype_OnInit, 0x0056DE10);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::Init, 0x0056E050);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::Clear, 0x0056E480);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReleaseMeshSoftSkinList, 0x0056E620);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReleaseMeshes, 0x0056E680);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::Release, 0x0056E710);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::GetModelProtoFileName, 0x0056E760);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::SetModelProtoName, 0x0056E770);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::SetFileSourceType, 0x0056E900);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::PrepareAsModelProtoOverlay, 0x0056ECE0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::CalcNodeListChecksum, 0x0056F0C0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::CollectNodeMeshes, 0x0056F120);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::SearchNode, 0x0056F360);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::FindMeshTreeNode, 0x0056F410);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::FindMeshTreeNodeIndex, 0x0056F4C0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::FindNodeListIndex, 0x0056F580);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::AddAni, 0x0056F620);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::SearchAniIndex, 0x0056F850);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::SearchAni, 0x0056F920);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::DescribeTree, 0x0056F940);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelPrototype, &zCModelPrototype::LoadMDH, int(zCModelPrototype::*)(zSTRING const&), 0x0056FB90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelPrototype, &zCModelPrototype::LoadMDH, int(zCModelPrototype::*)(zCFileBIN&), 0x0056FDF0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelPrototype, &zCModelPrototype::SaveMDH, void(zCModelPrototype::*)(), 0x00570490);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelPrototype, &zCModelPrototype::SaveMDH, void(zCModelPrototype::*)(zCFileBIN&), 0x00570690);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ConvertVec3, 0x00570BA0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ConvertAngle, 0x00570BC0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::SkipBlock, 0x00570BD0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::SkipBlockCmt, 0x00570C50);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadComment, 0x00570D20);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadScene, 0x00570D30);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadTriple, 0x005710D0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadNodeTM, 0x005712C0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadVertexList, 0x00571760);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadFaceList, 0x00571990);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadTVertexList, 0x00571E90);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadTFaceList, 0x005720A0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadSoftSkinVertList, 0x00572310);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadMesh, 0x00573480);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadMeshAnimation, 0x00573870);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadPosTrack, 0x005739F0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadRotTrack, 0x00573BD0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadTMAnimation, 0x00573E80);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::LocalizeTrafos, 0x005744C0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadMapDiffuse, 0x005745F0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadMaterial, 0x005749F0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadWireframeColor, 0x00575070);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::AssignMeshNodeMaterials, 0x00575330);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::TransformNodeVisual, 0x00575420);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ProcessMeshNode, 0x00575480);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadGeomobject, 0x005758A0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadMaterialList, 0x00576E40);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::Load3DSMAXAsc, 0x005770D0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::CalcAniBBox, 0x00577FF0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ResolveReferences, 0x00578510);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::SkipBlockMDS, 0x00578800);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadMeshAndTree, 0x00578880);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::RegisterMesh, 0x00578D00);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadStartMesh, 0x00578F40);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadAniEventTag, 0x005790E0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadAniEnum, 0x00579350);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadModel, 0x0057E410);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::LoadModelScript, 0x0057E570);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::LoadModelASC, 0x0057EB20);

	ZENGIN_REGISTER_CLASS(zCModelAniActive);
	ZENGIN_REGISTER_METHOD(zCModelAniActive, &zCModelAniActive::zCModelAniActive_OnInit, 0x0055D370);
	ZENGIN_REGISTER_METHOD(zCModelAniActive, &zCModelAniActive::SetDirection, 0x0055D480);
	ZENGIN_REGISTER_METHOD(zCModelAniActive, &zCModelAniActive::GetProgressPercent, 0x0055D4D0);
	ZENGIN_REGISTER_METHOD(zCModelAniActive, &zCModelAniActive::SetProgressPercent, 0x0055D510);
	ZENGIN_REGISTER_METHOD(zCModelAniActive, &zCModelAniActive::SetActFrame, 0x0055D560);
	ZENGIN_REGISTER_METHOD(zCModelAniActive, &zCModelAniActive::DoCombineAni, 0x00565D30);

	ZENGIN_REGISTER_CLASS(zCModelTexAniState);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::zCModelTexAniState_OnInit, 0x0055D5B0);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::DeleteTexList, 0x0055D5F0);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::UpdateTexList, 0x0055D610);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::SetChannelVariation, 0x0055D650);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::BuildTexListFromMeshLib, 0x0055D6C0);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::BuildTexListFromMesh, 0x0055D740);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::BuildTexListFromProgMesh, 0x0055D860);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::AddTexListFromMeshLib, 0x0055D9E0);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::AddTexListFromMesh, 0x0055DC70);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::AddTexListFromProgMesh, 0x0055DDF0);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::FinishTexList, 0x0055DF60);

	ZENGIN_REGISTER_CLASS(zCModelNodeInst);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelNodeInst, &zCModelNodeInst::zCModelNodeInst_OnInit, void(zCModelNodeInst::*)(), 0x0055E0A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelNodeInst, &zCModelNodeInst::zCModelNodeInst_OnInit, void(zCModelNodeInst::*)(zCModelNode*), 0x0055E170);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::Init, 0x0055E2E0);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::InitByModelProtoNode, 0x0055E370);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::SetNodeVisualS, 0x0055E420);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::AddNodeAni, 0x00564A70);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::RemoveAllNodeAnis, 0x00564CA0);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::RemoveNodeAni, 0x00564CB0);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::FindMasterAni, 0x00564DA0);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::FadeOutNodeAni, 0x00564E10);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::CalcWeights, 0x005653F0);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::AddToNodeAniWeight, 0x00565630);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::CalcBlending, 0x005656A0);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::GetNodeAniListIndex, 0x00565830);

	ZENGIN_REGISTER_CLASS(zTAniAttachment);
	ZENGIN_REGISTER_METHOD(zTAniAttachment, &zTAniAttachment::zTAniAttachment_OnInit, 0x00568AB0);

	ZENGIN_REGISTER_CLASS(zCModel);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::zCModel_OnInit, 0x0055E9F0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetAniFromAniID, 0x0046D1E0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::IsAniActive, 0x0046D220);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetAniIDFromAniName, 0x0047EC50);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::Init, 0x0055E7D0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CopyProtoNodeList, 0x0055EB90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::ApplyModelProtoOverlay, int(zCModel::*)(zSTRING const&), 0x0055EFB0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::ApplyModelProtoOverlay, int(zCModel::*)(zCModelPrototype*), 0x0055F000);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::HasAppliedModelProtoOverlay, int(zCModel::*)(zCModelPrototype*) const, 0x0055F210);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::HasAppliedModelProtoOverlay, int(zCModel::*)(zSTRING const&) const, 0x0055F240);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::RemoveModelProtoOverlay, void(zCModel::*)(zSTRING const&), 0x0055F3C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::RemoveModelProtoOverlay, void(zCModel::*)(zCModelPrototype*), 0x0055F5C0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CalcNodeListBBoxWorld, 0x0055F740);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetBBox3DNodeWorld, 0x0055F870);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetNodePositionWorld, 0x0055F8C0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CalcModelBBox3DWorld, 0x0055F8F0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetNodeVisual, 0x0055FA00);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetDynLightMode, 0x0055FA30);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RenderNodeList, 0x0055FA50);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CheckNodeCollisionList, 0x00560A10);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CheckNodeCollision, 0x00560AB0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetTrafoNodeToModel, 0x00560BF0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetRandAnisEnabled, 0x00560D20);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::GetActiveAni, zCModelAniActive*(zCModel::*)(int) const, 0x00560D90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::GetActiveAni, zCModelAniActive*(zCModel::*)(zCModelAni*) const, 0x00560DD0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::StopAni, void(zCModel::*)(int), 0x00560E10);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::StopAni, void(zCModel::*)(zCModelAni*), 0x00560E90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::StopAni, void(zCModel::*)(zCModelAniActive*), 0x00560EE0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetAniTransLerp, 0x005610A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::StartAni, void(zCModel::*)(zSTRING const&, int), 0x005611A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::StartAni, void(zCModel::*)(int, int), 0x005612A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::StartAni, void(zCModel::*)(zCModelAni*, int), 0x005612F0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::AssertActiveAniListAlloced, 0x005619C0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::DoAniEvents, 0x00561AF0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::AdvanceAni, 0x00562A10);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::AdvanceAnis, 0x00562CD0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetModelScale, 0x00563BC0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::IsStateActive, 0x00563D30);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SearchNode, 0x00563F80);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetNodeMeshTexture, 0x00564030);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetMeshLibTexture, 0x00564150);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RemoveMeshLibAll, 0x00564350);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RemoveMeshLib, 0x00564380);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::ApplyMeshLib, 0x00564590);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::UpdateMeshLibTexAniState, 0x005649F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::FadeOutAni, void(zCModel::*)(int), 0x00564ED0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::FadeOutAni, void(zCModel::*)(zCModelAni*), 0x00564F60);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::FadeOutAni, void(zCModel::*)(zCModelAniActive*), 0x00564FA0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::FadeOutAnisLayerRange, 0x00565170);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::StopAnisLayerRange, 0x005651C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::GetProgressPercent, float(zCModel::*)(zSTRING const&) const, 0x00565210);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::GetProgressPercent, float(zCModel::*)(int) const, 0x005652C0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetCombineAniXY, 0x00565330);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetCombineAniXY, 0x00565380);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CalcNodeListAniBlending, 0x00565800);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CalcTransBlending, 0x00565860);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::AttachChildVobToNode, 0x005665B0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RemoveChildVobFromNode, 0x00566720);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RemoveAllChildVobsFromNode, 0x005667A0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::UpdateAttachedVobs, 0x005667F0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RemoveStartedVobFX, 0x00566940);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetVelocityRing, 0x005669F0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::ResetVelocity, 0x00566A50);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetAniMinMaxWeight, 0x00566AE0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::PrintStatus, 0x00566D10);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::psb_WriteAniBlock, 0x00567360);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::psb_ReadAniBlock, 0x005674F0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::PackStateBinary, 0x00567740);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::UnpackStateBinary, 0x00567AB0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::ShowAniListAdd, 0x00568240);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::ShowAniList, 0x005682C0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SearchAniAttachList, 0x00568AF0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RemoveAniAttachment, 0x00568B70);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RemoveAllAniAttachments, 0x00568CB0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetCreateAniAttachment, 0x00568D00);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::DeleteRandAniList, 0x00568EC0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::InsertRandAni, 0x00568F40);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetRandAniFreq, 0x00569060);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetRandAniFreq, 0x005690F0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RecalcRootPosLocal, 0x00569110);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::_GetClassDef, 0x0055CE10);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::Render, 0x00560770);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::IsBBox3DLocal, 0x0055CE20);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetBBox3D, 0x00563EB0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetVisualName, 0x00563EF0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetVisualUsedBy, 0x0055EE80);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetRenderSortKey, 0x00568330);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CanTraceRay, 0x0055CE30);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::TraceRay, 0x00568350);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::HostVobRemovedFromWorld, 0x00561A40);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetFileExtension, 0x0055EEF0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::LoadVisualVirtual, 0x0055EF10);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::StartAnimation, 0x0055CE40);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::StopAnimation, 0x0055CE50);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::IsAnimationActive, 0x0055CEF0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetAnyAnimation, 0x00561050);

	ZENGIN_REGISTER_CLASS(zCModelConvertFileHandler);
	ZENGIN_REGISTER_METHOD(zCModelConvertFileHandler, &zCModelConvertFileHandler::zCModelConvertFileHandler_OnInit, 0x00581C00);
	ZENGIN_REGISTER_METHOD(zCModelConvertFileHandler, &zCModelConvertFileHandler::HandleFile, 0x00581D30);

} // namespace Gothic_I_Classic
