namespace Gothic_I_Classic {

	ZENGIN_REGISTER_CLASS(zCPar_TreeNode);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPar_TreeNode, &zCPar_TreeNode::zCPar_TreeNode_OnInit, void(zCPar_TreeNode::*)(), 0x006EDE40);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPar_TreeNode, &zCPar_TreeNode::zCPar_TreeNode_OnInit, void(zCPar_TreeNode::*)(int, int), 0x006EDE80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPar_TreeNode, &zCPar_TreeNode::zCPar_TreeNode_OnInit, void(zCPar_TreeNode::*)(int, zSTRING&, int), 0x006EDED0);
	ZENGIN_REGISTER_METHOD(zCPar_TreeNode, &zCPar_TreeNode::SetLeft, 0x006EE120);
	ZENGIN_REGISTER_METHOD(zCPar_TreeNode, &zCPar_TreeNode::SetRight, 0x006EE130);
	ZENGIN_REGISTER_METHOD(zCPar_TreeNode, &zCPar_TreeNode::SetNext, 0x006EE140);

	ZENGIN_REGISTER_CLASS(zCPar_File);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::zCPar_File_OnInit, 0x006E3DC0);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::IsNewerDate, 0x006E3E90);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::IsExactDate, 0x006E3F10);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::SetFileNumber, 0x006E3F90);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::GetFileNumber, 0x006E3FA0);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::GetName, 0x006E3FB0);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::EnableTreeLoad, 0x006E4000);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::Load, 0x006E4010);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::GetStartAddress, 0x006E42A0);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::GetEndAddress, 0x006E42B0);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::Dispose, 0x006E42C0);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::SetTree, 0x006E42E0);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::GetTree, 0x006E4320);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::SetLabelCount, 0x006E4330);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::GetLabelCount, 0x006E4340);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::SaveTree, 0x006E4350);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::SaveTreeNode, 0x006E45D0);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::LoadTreeNode, 0x006E4740);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::LoadTree, 0x006E4880);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::DeleteTree, 0x006E4C60);

	ZENGIN_REGISTER_CLASS(zCParser);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::zCParser_OnInit, 0x006E4CA0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SetMessageFunc, 0x006E5020);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SetStopOnError, 0x006E5030);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::Error, void(zCParser::*)(zSTRING&, int), 0x006E5040);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::Message, 0x006E5370);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::Error, int(zCParser::*)(), 0x006E54B0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SaveDat, 0x006E54C0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::LoadDat, 0x006E5680);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::Parse, 0x006E5920);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ParseSource, 0x006E5BA0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ParseFile, 0x006E63E0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ParseBlock, 0x006E6C00);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::CreatePCode, 0x006E6EB0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ShowSymbols, 0x006E7570);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::PushTree, 0x006E7580);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::PushOnStack, 0x006E75A0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SolveLabels, 0x006E8290);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::MergeFile, 0x006E82F0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::PopDataValue, 0x006E8550);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::PopFloatValue, 0x006E8580);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::PopVarAddress, 0x006E85B0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::PopString, 0x006E85E0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DoStack, 0x006E8600);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::CallFunc, void*(zCParser::*)(zSTRING const&), 0x006E9670);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::CallFunc, void*(__cdecl zCParser::*)(int, ...), 0x006E9690);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetCurrentFunc, 0x006E9B50);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::CreateInstance, int(zCParser::*)(zSTRING&, void*), 0x006E9B60);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::CreateInstance, int(zCParser::*)(int, void*), 0x006E9BE0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::CreatePrototype, int(zCParser::*)(zSTRING&, void*), 0x006E9C50);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::CreatePrototype, int(zCParser::*)(int, void*), 0x006E9CD0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::Reset, 0x006E9D40);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SetPercentDone, 0x006E9EB0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::CreateHelpers, 0x006E9F10);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::EnableTreeSave, 0x006EA090);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::EnableDatSave, 0x006EA0A0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::EnableTreeLoad, 0x006EA0B0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetIndex, 0x006EA0C0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::MatchClass, 0x006EA180);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetBaseClass, int(zCParser::*)(zCPar_Symbol*), 0x006EA200);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetBaseClass, int(zCParser::*)(int), 0x006EA260);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetBase, 0x006EA2C0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetPrototype, 0x006EA310);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetInstance, int(zCParser::*)(int, int), 0x006EA380);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetSymbolInfo, zSTRING(zCParser::*)(int, int&, int&), 0x006EA440);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetSymbolInfo, zCPar_Symbol*(zCParser::*)(int), 0x006EA500);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetSymbol, zCPar_Symbol*(zCParser::*)(int), 0x006EA510);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetSymbol, zCPar_Symbol*(zCParser::*)(zSTRING const&), 0x006EA520);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetClassVarInfo, zSTRING(zCParser::*)(int, int, int&, int&), 0x006EA5E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetClassVarInfo, void(zCParser::*)(int, zSTRING&, int&, int&), 0x006EA800);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetText, zSTRING(zCParser::*)(zSTRING&, int), 0x006EA9C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetText, zSTRING(zCParser::*)(int, int), 0x006EAA00);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetInt, 0x006EAAE0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetInstanceValue, zSTRING(zCParser::*)(zSTRING&, int, void*, int), 0x006EAB30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetInstanceValue, zSTRING(zCParser::*)(int, int, void*, int), 0x006EAC20);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::IsValid, 0x006EAE80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::CheckClassSize, int(zCParser::*)(zSTRING&, int), 0x006EAFF0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::CheckClassSize, int(zCParser::*)(int, int), 0x006EB010);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::AddClassOffset, 0x006EB280);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::SetInstance, int(zCParser::*)(zSTRING const&, void*), 0x006EB3C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::SetInstance, int(zCParser::*)(int, void*), 0x006EB400);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::AutoCompletion, 0x006EB440);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetNumFiles, 0x006EB650);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetFileName, 0x006EB660);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::IsStackFull, 0x006EB700);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetLastErrorLine, 0x006EB710);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::Reparse, 0x006EB720);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::SaveInstance, int(zCParser::*)(zSTRING&, void*), 0x006EB830);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::SaveInstance, int(zCParser::*)(int, void*), 0x006EB860);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::CloseViews, 0x006EC420);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ShowCode, 0x006EC450);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SaveInfoFile, 0x006EC5B0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SetInfoFile, 0x006ECBF0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::IsInAdditionalInfo, 0x006ECD80);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::WriteAdditionalInfo, 0x006ECF30);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ClearAllInstanceRefs, 0x006ED250);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ClearInstanceRefs, 0x006ED2C0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ResetGlobalVars, 0x006ED340);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::CreateVarReferenceList, 0x006ED3A0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ResetWithVarReferenceList, 0x006ED540);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SaveGlobalVars, 0x006ED5C0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::LoadGlobalVars, 0x006ED8C0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetOperatorString, 0x006EE260);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::FindNext, 0x006EE7F0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::PrevWord, 0x006EE960);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ReadWord, 0x006EE990);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::Match, 0x006EEC00);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ReadVarType, 0x006EED90);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ReadFuncType, 0x006EEFC0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ReadInt, 0x006EF1E0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ReadFloat, 0x006EF480);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ReadString, 0x006EF780);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ReadArray, 0x006EFA60);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::CreateLeaf, 0x006EFC60);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::CreateStringLeaf, 0x006EFCD0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::CreateFloatLeaf, 0x006EFF30);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetNextToken, 0x006F00D0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::Parse_Expression_Primary, 0x006F0850);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::Parse_Expression, 0x006F0E80);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ParseExpressionEx, 0x006F10A0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ParseExpression, 0x006F1110);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::EvalLeaf, 0x006F1130);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareVar, 0x006F15F0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareClass, 0x006F2AB0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareInstance, 0x006F2C90);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclarePrototype, 0x006F34C0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareIf, 0x006F39D0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareAssign, 0x006F3E40);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareAssignFunc, 0x006F45E0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareFunc, 0x006F48E0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareReturn, 0x006F4D90);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareFuncCall, 0x006F4F80);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SearchFuncWithStartAddress, 0x006F5970);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetNextCommand, 0x006F59E0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ShowPCodeSpy, 0x006F64C0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ShowPCode, 0x006F65F0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DefineExternal, 0x006F6840);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DefineExternalVar, 0x006F6BD0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetParameter, void(zCParser::*)(int&), 0x006F6DF0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetParameter, void(zCParser::*)(float&), 0x006F6E00);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetParameter, void(zCParser::*)(zSTRING&), 0x006F6E40);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetInstance, void*(zCParser::*)(), 0x006F6F80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::SetReturn, void(zCParser::*)(int), 0x006F6FB0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::SetReturn, void(zCParser::*)(float), 0x006F6FD0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::SetReturn, void(zCParser::*)(void*), 0x006F6FF0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::SetReturn, void(zCParser::*)(zSTRING&), 0x006F7020);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::FindInstanceVar, 0x006F7040);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetLastInstance, 0x006F7220);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::FindIndex, 0x006F7230);

} // namespace Gothic_I_Classic
