namespace Gothic_I_Classic {

	ZENGIN_REGISTER_CLASS(zSTRING);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(char const*), 0x004013A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(), 0x00402B30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(zSTRING const&), 0x00415F40);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(int), 0x00465810);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(long), 0x00465910);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(unsigned long), 0x00465A10);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(float, int), 0x00465B10);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(double, int), 0x00465C60);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(char), 0x0050AC70);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(zSTRING const*), 0x006E9570);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::ToChar, 0x0045E2E0);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Clear, 0x0057E220);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::IsEmpty, 0x0073F440);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Lower, 0x00465280);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Upper, 0x00465390);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::UpperFirstLowerRest, 0x004654A0);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Align, 0x004655F0);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::PickWord, 0x00465DB0);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::PickWordPos, 0x00466000);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::PickWord_Old, 0x00466170);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Insert, 0x00466230);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Inserted, 0x00466350);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Overwrite, 0x004664D0);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Overwritten, 0x004666C0);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::DeleteRight, 0x004667C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Delete, int(zSTRING::*)(unsigned int, unsigned long), 0x004668D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Deleted, zSTRING(zSTRING::*)(unsigned int, unsigned long) const, 0x004669E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Delete, int(zSTRING::*)(zSTRING const&, zTSTR_KIND), 0x00466B20);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Deleted, zSTRING(zSTRING::*)(zSTRING const&, zTSTR_KIND) const, 0x00466D10);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Copied, zSTRING(zSTRING::*)(unsigned int, unsigned long) const, 0x00466FA0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Copy, int(zSTRING::*)(zSTRING const&, zTSTR_KIND const&), 0x00467100);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Copy, int(zSTRING::*)(unsigned int, unsigned long), 0x00466DF0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Copied, zSTRING(zSTRING::*)(zSTRING const&, zTSTR_KIND const&) const, 0x00467380);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::TrimLeft, 0x00467460);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::TrimRight, 0x004675A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Search, int(zSTRING::*)(int, char const*, unsigned int) const, 0x00467750);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::SearchRev, 0x00467850);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Sprintf, 0x00467A90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Search, int(zSTRING::*)(zSTRING const&, unsigned int) const, 0x00489C00);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::ToInt, 0x0057E2F0);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::ToFloat, 0x0057E310);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Search, int(zSTRING::*)(char const*, unsigned int) const, 0x0057E330);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Init, 0x00737C50);

} // namespace Gothic_I_Classic
