namespace Gothic_I_Classic {

	ZENGIN_REGISTER_CLASS(zCOLOR);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCOLOR, &zCOLOR::zCOLOR_OnInit, void(zCOLOR::*)(int), 0x00401DE0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCOLOR, &zCOLOR::zCOLOR_OnInit, void(zCOLOR::*)(unsigned char, unsigned char, unsigned char, unsigned char), 0x006E1BC0);
	ZENGIN_REGISTER_METHOD(zCOLOR, &zCOLOR::Reset, 0x00559960);
	ZENGIN_REGISTER_METHOD(zCOLOR, &zCOLOR::GetDescription, 0x005CF9E0);
	ZENGIN_REGISTER_METHOD(zCOLOR, &zCOLOR::SetByDescription, 0x005CFC60);
	ZENGIN_REGISTER_METHOD(zCOLOR, &zCOLOR::GetDescriptionRGB, 0x005CFEE0);
	ZENGIN_REGISTER_METHOD(zCOLOR, &zCOLOR::SetRGB, 0x005FBB40);

	ZENGIN_REGISTER_CLASS(zTPlane);
	ZENGIN_REGISTER_METHOD(zTPlane, &zTPlane::EqualTo, 0x005D00F0);
	ZENGIN_REGISTER_METHOD(zTPlane, &zTPlane::Opposite, 0x005D01A0);
	ZENGIN_REGISTER_METHOD(zTPlane, &zTPlane::ClassifyPoint, 0x005D01E0);
	ZENGIN_REGISTER_METHOD(zTPlane, &zTPlane::ClassifyPointBSPBuild, 0x005D0230);
	ZENGIN_REGISTER_METHOD(zTPlane, &zTPlane::CalcSignbits, 0x005D0280);
	ZENGIN_REGISTER_METHOD(zTPlane, &zTPlane::Print, 0x005D02E0);
	ZENGIN_REGISTER_METHOD(zTPlane, &zTPlane::Intersection, 0x005D05C0);
	ZENGIN_REGISTER_METHOD(zTPlane, &zTPlane::IntersectionFront, 0x005D0690);
	ZENGIN_REGISTER_METHOD(zTPlane, &zTPlane::Calc, 0x005D0770);
	ZENGIN_REGISTER_METHOD(zTPlane, &zTPlane::GetOriginUpRight, 0x005D0850);

} // namespace Gothic_I_Classic
