namespace Gothic_I_Classic {

	ZENGIN_REGISTER_CLASS(zCVisual);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::zCVisual_OnInit, 0x005D9D70);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::AddNextLODVisual, 0x005D9F30);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::AddEndLODVisual, 0x005D9F60);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::_GetClassDef, 0x004C0D20);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::IsBBox3DLocal, 0x0054FB90);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::GetOBBox3D, 0x004C0D30);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::GetVisualDied, 0x004C0D40);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::SetVisualUsedBy, 0x0054FBA0);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::DynLightVisual, 0x004C0D50);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::GetRenderSortKey, 0x004C0D60);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::CanTraceRay, 0x004C0D70);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::TraceRay, 0x005D9FF0);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::HostVobRemovedFromWorld, 0x004C0D80);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::HostVobAddedToWorld, 0x004C0D90);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::GetFileExtension, 0x004C0DA0);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::GetLODVisualAndAlpha, 0x005D9F90);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::LoadVisualVirtual, 0x004C0DB0);

	ZENGIN_REGISTER_CLASS(zCVisualAnimate);
	ZENGIN_REGISTER_METHOD(zCVisualAnimate, &zCVisualAnimate::_GetClassDef, 0x0055CDE0);

	ZENGIN_REGISTER_CLASS(zCDecal);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::zCDecal_OnInit, 0x00541E20);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCDecal, &zCDecal::SetTexture, void(zCDecal::*)(zSTRING&), 0x00542240);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCDecal, &zCDecal::SetTexture, void(zCDecal::*)(zCTexture*), 0x00542250);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::SetDecalDim, 0x00542260);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::_GetClassDef, 0x00541E00);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::Archive, 0x00542590);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::Unarchive, 0x00542650);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::Render, 0x00542280);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::IsBBox3DLocal, 0x00541E10);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::GetBBox3D, 0x005423E0);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::GetVisualName, 0x00542430);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::SetVisualUsedBy, 0x005423C0);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::DynLightVisual, 0x00542480);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::GetRenderSortKey, 0x00542230);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::GetFileExtension, 0x00542070);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::LoadVisualVirtual, 0x005420D0);

	ZENGIN_REGISTER_CLASS(zCMesh);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::zCMesh_OnInit, 0x0054F970);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::LODRecalcEdge, 0x00528FC0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::LODGenerate, 0x005297D0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::DeleteAll, 0x0054FE00);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::VertexInMesh, 0x00550C40);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::AllocVerts, 0x00550D10);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::AllocPolys, 0x00550E10);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::AddVertex, zCVertex*(zCMesh::*)(zCVertex*), 0x00550EE0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::AddVertex, zCVertex*(zCMesh::*)(zVEC3&), 0x00551060);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::AddVertexSmart, 0x005511C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::AddPoly, zCPolygon*(zCMesh::*)(zVEC3&, zVEC3&, zVEC3&, zVEC2&, zVEC2&, zVEC2&), 0x005512F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::AddPoly, zCPolygon*(zCMesh::*)(zCVertex*, zCVertex*, zCVertex*), 0x005515A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::AddPoly, zCPolygon*(zCMesh::*)(zCVertex*, zCVertex*, zCVertex*, zCVertex*), 0x005516C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::AddPoly, zCPolygon*(zCMesh::*)(zCPolygon*), 0x005517F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::AddPoly, zCPolygon*(zCMesh::*)(), 0x005518A0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::DeletePoly, 0x005519A0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::DynLightScalePrelit, 0x00551A90);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::PrelightMesh, 0x00551AA0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SharePoly, 0x00551F10);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::CheckRayPolyIntersection, zCPolygon*(zCMesh::*)(zVEC3 const&, zVEC3 const&, zVEC3&), 0x00551F30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::CheckRayPolyIntersection, zCPolygon*(zCMesh::*)(zCCamera&, int, int, zVEC3&), 0x00551F90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::PickPolygon, zCPolygon*(zCMesh::*)(zVEC3 const&, zVEC3 const&, zVEC3&), 0x00552140);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::PickPolygon, zCPolygon*(zCMesh::*)(zCCamera&, int, int, zVEC3&), 0x00552210);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::CalcVertexNormals, 0x00552590);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::UnSmoothMesh, 0x00552C70);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SetDefaultPlanarMapping, 0x00552D10);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::CalcBBox3D, 0x00552DA0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::Center, 0x00552F10);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::TransformAllVerts, 0x00553060);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::MergeMesh, 0x00553120);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::CalcNormals, 0x005534E0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SetMaterial, 0x00553510);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::ScaleXZ, 0x00553570);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::Scale, 0x005535E0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::CheckForMaterials, 0x005536A0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::Render_novt, 0x00553860);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::RenderDecal, void(zCMesh::*)(float, float, float, int), 0x00553B40);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::RenderDecal, void(zCMesh::*)(zTRenderContext&, int), 0x00553D00);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::ResetStaticLight, 0x00553F50);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SetStaticLight, 0x00553F90);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SetLightDyn, 0x00553FD0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SetLightStatAlpha, 0x00554010);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::ResetLightDynToLightStat, 0x00554050);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::AddToLightDyn, 0x00554090);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::SaveMSH, void(zCMesh::*)(zCFileBIN&), 0x00555670);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::SaveMSH, void(zCMesh::*)(zSTRING const&), 0x00555690);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::LoadMSH, int(zCMesh::*)(zCFileBIN&, int), 0x00557280);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::LoadMSH, int(zCMesh::*)(zSTRING const&, int), 0x00558800);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::CreateListsFromArrays, 0x00558AB0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::ClearLists, 0x00558BB0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::ArraysToLists, 0x00558C10);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::ShareFeatures, 0x00558CF0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::UnshareFeatures, 0x005599D0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::FlipPolys, 0x00559AF0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SortPolysByMaterial, 0x00559B40);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SortPolysByList, 0x00559BF0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::DeletePolyAndVerts, void(zCMesh::*)(zCPolygon*), 0x0055A440);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::DeletePolyAndVerts, void(zCMesh::*)(unsigned long), 0x0055A4D0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::RemoveDegeneratePolys, 0x0055A660);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::CombineLightmaps, 0x0055A810);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::LightMesh, 0x005FB040);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::_GetClassDef, 0x0054FBB0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::Render, 0x005537E0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::GetBBox3D, 0x0054FC10);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::GetOBBox3D, 0x0054FC40);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::GetVisualName, 0x0054FBC0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::DynLightVisual, 0x00551A80);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::CanTraceRay, 0x0054FC50);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::TraceRay, 0x00552410);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::GetFileExtension, 0x0054FDD0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::LoadVisualVirtual, 0x0054FDF0);

} // namespace Gothic_I_Classic
