namespace Gothic_I_Classic {

	ZENGIN_REGISTER_CLASS(zCEventMessage);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCEventMessage, &zCEventMessage::zCEventMessage_OnInit, void(zCEventMessage::*)(), 0x00413590);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCEventMessage, &zCEventMessage::zCEventMessage_OnInit, void(zCEventMessage::*)(unsigned short), 0x005D8D10);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::GetMessageID, 0x005D8E80);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::PackToBuffer, 0x005D8EE0);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::GetSubType, 0x0073F4C0);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::_GetClassDef, 0x00401DF0);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::Archive, 0x005D8F70);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::Unarchive, 0x005D9170);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::IsOverlay, 0x00401E00);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::IsNetRelevant, 0x00401E10);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::IsHighPriority, 0x00401E20);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::IsJob, 0x00401E30);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::Delete, 0x00401E40);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::IsDeleteable, 0x00401E50);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::IsDeleted, 0x00401E60);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::SetCutsceneMode, 0x00401E70);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::GetCutsceneMode, 0x00401E80);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::MD_GetNumOfSubTypes, 0x00401E90);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::MD_GetSubTypeString, 0x00401EA0);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::MD_GetVobRefName, 0x00401EE0);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::MD_SetVobRefName, 0x00401F20);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::MD_SetVobParam, 0x00401F30);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::MD_GetTimeBehavior, 0x00401F40);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::MD_GetMinTime, 0x00401F50);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::Pack, 0x00401F60);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::Unpack, 0x00401F70);

	ZENGIN_REGISTER_CLASS(zCEventCore);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::Clear, 0x005D97D0);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::_GetClassDef, 0x00401FE0);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::Archive, 0x005D9C00);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::Unarchive, 0x005D9C70);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::IsNetRelevant, 0x00402000);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::MD_GetNumOfSubTypes, 0x00401FF0);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::MD_GetSubTypeString, 0x005D9A00);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::Pack, 0x005D9830);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::Unpack, 0x005D98E0);

	ZENGIN_REGISTER_CLASS(zCVob);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::zCVob_OnInit, 0x005D3030);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::GetPositionWorld, zVEC3(zCVob::*)() const, 0x0051B3C0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetAtVectorWorld, 0x0051B3E0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetUpVectorWorld, 0x0051B400);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetRightVectorWorld, 0x0051B420);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetVobID, 0x005D3720);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetAI, 0x005D3730);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetVobPresetName, 0x005D3780);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetVobPresetName, 0x005D3790);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetRigidBody, 0x005D37A0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ArchivePacked, 0x005D3820);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ArchiveVerbose, 0x005D3BB0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::UnarchivePacked, 0x005D3F90);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::UnarchiveVerbose, 0x005D43E0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetVobName, 0x005D4970);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetEM, 0x005D49B0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CalcLightSampleAtOrigin, 0x005D4CD0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetLightColorStat, 0x005D4D50);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetLightColorDyn, 0x005D4FE0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CalcStaticLight, 0x005D51E0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetSectorNameVobIsIn, 0x005D5690);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetGroundShadowSize, 0x005D57E0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetGroundShadowSize, 0x005D5830);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RenderGroundShadow, 0x005D5880);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetClassHelperVisual, 0x005D5D60);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CalcRenderAlpha, 0x005D5F60);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetLightColorAtCenter, 0x005D64E0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RemoveVobFromWorld, 0x005D6670);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RemoveVobSubtreeFromWorld, 0x005D6690);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::AddRefVobSubtree, 0x005D66F0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ReleaseVobSubtree, 0x005D6730);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RemoveWorldDependencies, 0x005D6790);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RemoveVobFromGlobalVobTree, 0x005D69E0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RemoveVobFromBspTree, 0x005D6AC0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetVobInfo, 0x005D6AE0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetSleeping, 0x005D7250);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::UpdateVisualDependencies, 0x005D7460);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::AddVobToWorld_CorrectParentDependencies, 0x005D74F0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ResetOnTimer, 0x005D7510);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetOnTimer, 0x005D7520);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::IsOnTimer, 0x005D7550);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ProcessOnTimer, 0x005D7570);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::DoFrameActivity, 0x005D75A0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CheckModelLimbCollision, 0x005D77B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::GetTrafoModelNodeToWorld, zMAT4(zCVob::*)(zSTRING const&), 0x005D83E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::GetTrafoModelNodeToWorld, zMAT4(zCVob::*)(zCModelNodeInst*), 0x005D84D0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetScreenBBox2D, 0x005D8560);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::PackStateBinary, 0x005D88D0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::UnpackStateBinary, 0x005D8980);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetVisual, 0x005E9A70);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CalcGroundPoly, 0x005ED8A0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetCollTypeDefaultFromVisual, 0x005ED9F0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::TouchMovement, 0x005EDB60);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::GetNewTrafoObjToWorld, zMAT4 const&(zCVob::*)() const, 0x005EDB80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::GetNewTrafoObjToWorld, zMAT4&(zCVob::*)(), 0x005EDBA0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetNewTrafoObjToWorld, 0x005EDBC0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetBBox3DWorld, 0x005EDBE0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetBBox3DLocal, 0x005EDC40);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetBBox3DLocal, 0x005EDCF0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::Move, 0x005EDDE0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::MoveWorld, 0x005EDE50);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::MoveLocal, 0x005EDEC0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetRotationWorld, 0x005EDFB0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RotateWorld, 0x005EE010);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RotateLocal, 0x005EE100);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RotateLocalX, 0x005EE1A0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RotateLocalY, 0x005EE210);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RotateLocalZ, 0x005EE280);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RotateWorldX, 0x005EE2F0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RotateWorldY, 0x005EE320);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RotateWorldZ, 0x005EE350);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::GetPositionWorld, void(zCVob::*)(float&, float&, float&) const, 0x005EE380);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetPositionLocal, 0x005EE3B0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetDistanceToVob, 0x005EE400);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetDistanceToVobApprox, 0x005EE460);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetDistanceToVob2, 0x005EE530);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetPositionLocal, 0x005EE590);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetPositionWorld, 0x005EE650);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetTrafo, 0x005EE6B0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetTrafoObjToWorld, 0x005EE760);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ResetRotationsLocal, 0x005EE7C0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ResetXZRotationsLocal, 0x005EE8E0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ResetRotationsWorld, 0x005EEAB0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ResetXZRotationsWorld, 0x005EEB40);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetHeadingYLocal, 0x005EEC60);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::SetHeadingYWorld, void(zCVob::*)(zVEC3 const&), 0x005EED30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::SetHeadingYWorld, void(zCVob::*)(zCVob*), 0x005EEF00);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetHeadingLocal, 0x005EF090);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::SetHeadingWorld, void(zCVob::*)(zVEC3 const&), 0x005EF150);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::SetHeadingWorld, void(zCVob::*)(zCVob*), 0x005EF210);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetHeadingAtLocal, 0x005EF2F0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::HasParentVob, 0x005EF620);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetHeadingAtWorld, 0x005EF640);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetCollDetStat, 0x005EF8D0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetCollDetDyn, 0x005EF9C0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CorrectTrafo, 0x005EFAC0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::DoneWithTrafoLocal, 0x005EFB30);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CreateTrafoLocal, 0x005EFB80);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetPhysicsEnabled, 0x005EFC20);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetVelocity, 0x005EFC50);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::UpdatePhysics, 0x005EFD60);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::DetectCollision, 0x005F0320);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetInMovement, 0x005F0460);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetInMovementMode, 0x005F04C0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::BeginMovement, 0x005F0510);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ResetToOldMovementState, 0x005F0690);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::UpdateTouchList, 0x005F06C0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CalcDestinationBBox3DWorld, 0x005F0970);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::AdoptCollObjResults, 0x005F0AB0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetCollisionObject, 0x005F1050);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetCollisionClass, 0x005F1080);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetCollisionObject, 0x005F10C0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CreateCollisionObject, 0x005F10D0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ResetCollisionObjectState, 0x005F1100);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::DestroyCollisionObject, 0x005F1140);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CheckEmergencyPutToSleep, 0x005F1180);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CollectCollisionContext_Vobs, 0x005F12D0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CollectCollisionContext_Static, 0x005F1530);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CollectCollisionContext, 0x005F1840);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CleanupCollisionContext, 0x005F18C0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::NotifyCollisionPair, 0x005F1930);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ExecuteCollisionResponse, 0x005F1A00);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CheckAndResolveCollisions, 0x005F1AE0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::IsColliding, 0x005F1F40);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetStaticVob, 0x00645000);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetVobType, 0x00645020);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetDrawBBox3D, 0x00645030);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetCollDet, 0x00645050);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetHomeWorld, 0x0073F4D0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::_GetClassDef, 0x00439220);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::Archive, 0x005D3ED0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::Unarchive, 0x005D4820);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnTrigger, 0x005D2FC0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnUntrigger, 0x005D2FD0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnTouch, 0x005D2FE0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnUntouch, 0x005D2FF0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnTouchLevel, 0x005D3000);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnDamage, 0x005D3010);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnMessage, 0x005D3020);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnTick, 0x00404130);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnTimer, 0x00439230);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::PostLoad, 0x00404140);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetCharacterClass, 0x00404150);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetSleepingMode, 0x005D7280);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::EndMovement, 0x005F0B60);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CanThisCollideWith, 0x00404160);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::Render, 0x005D6090);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::SetVisual, void(zCVob::*)(zCVisual*), 0x005D6E10);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::SetVisual, void(zCVob::*)(zSTRING const&), 0x005D6FA0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetScriptInstance, 0x00404170);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetByScriptInstance, 0x00404190);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetCSStateFlags, 0x004041A0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::TraceRay, 0x005D49E0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetTriggerTarget, 0x00439240);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ThisVobAddedToWorld, 0x005D66B0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ThisVobRemovedFromWorld, 0x005D66D0);

	ZENGIN_REGISTER_CLASS(zCVob::zTModelLimbColl);
	ZENGIN_REGISTER_METHOD(zCVob::zTModelLimbColl, &zCVob::zTModelLimbColl::zTModelLimbColl_OnInit, 0x005D8380);

	ZENGIN_REGISTER_CLASS(zCVobLightData);
	ZENGIN_REGISTER_METHOD(zCVobLightData, &zCVobLightData::zCVobLightData_OnInit, 0x005DDBA0);
	ZENGIN_REGISTER_METHOD(zCVobLightData, &zCVobLightData::SetLensFlareFXByName, 0x005DCC70);
	ZENGIN_REGISTER_METHOD(zCVobLightData, &zCVobLightData::GetLensFlareFXName, 0x005DCD70);
	ZENGIN_REGISTER_METHOD(zCVobLightData, &zCVobLightData::Archive, 0x005DCD90);
	ZENGIN_REGISTER_METHOD(zCVobLightData, &zCVobLightData::Unarchive, 0x005DD200);
	ZENGIN_REGISTER_METHOD(zCVobLightData, &zCVobLightData::SetRange, 0x005DDC80);

	ZENGIN_REGISTER_CLASS(zCVobLightPreset);
	ZENGIN_REGISTER_METHOD(zCVobLightPreset, &zCVobLightPreset::_GetClassDef, 0x005D24B0);
	ZENGIN_REGISTER_METHOD(zCVobLightPreset, &zCVobLightPreset::Archive, 0x005DCA90);
	ZENGIN_REGISTER_METHOD(zCVobLightPreset, &zCVobLightPreset::Unarchive, 0x005DCAC0);

	ZENGIN_REGISTER_CLASS(zCVobLight);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::zCVobLight_OnInit, 0x005DB4A0);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::DoAnimation, 0x005DB820);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::SetRange, 0x005DBAF0);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::AddThisToPresetList, 0x005DC0E0);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::SetByPreset, 0x005DC3C0);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::SetByPresetInUse, 0x005DC650);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::_GetClassDef, 0x005DB440);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::Archive, 0x005DC890);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::Unarchive, 0x005DC8E0);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::OnTrigger, 0x005DB6B0);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::OnUntrigger, 0x005DB780);

	ZENGIN_REGISTER_CLASS(zCVobLevelCompo);
	ZENGIN_REGISTER_METHOD(zCVobLevelCompo, &zCVobLevelCompo::zCVobLevelCompo_OnInit, 0x005D8A30);
	ZENGIN_REGISTER_METHOD(zCVobLevelCompo, &zCVobLevelCompo::HasIdentityTrafo, 0x005D8A90);
	ZENGIN_REGISTER_METHOD(zCVobLevelCompo, &zCVobLevelCompo::_GetClassDef, 0x005D2A80);
	ZENGIN_REGISTER_METHOD(zCVobLevelCompo, &zCVobLevelCompo::Archive, 0x005D8B10);
	ZENGIN_REGISTER_METHOD(zCVobLevelCompo, &zCVobLevelCompo::Unarchive, 0x005D8BC0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVobLevelCompo, &zCVobLevelCompo::SetVisual, void(zCVobLevelCompo::*)(zCVisual*), 0x005D8C90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVobLevelCompo, &zCVobLevelCompo::SetVisual, void(zCVobLevelCompo::*)(zSTRING const&), 0x005D8CD0);

} // namespace Gothic_I_Classic
