namespace Gothic_I_Classic {

	ZENGIN_REGISTER_CLASS(zCVobWaypoint);
	ZENGIN_REGISTER_METHOD(zCVobWaypoint, &zCVobWaypoint::zCVobWaypoint_OnInit, 0x00702FB0);
	ZENGIN_REGISTER_METHOD(zCVobWaypoint, &zCVobWaypoint::_GetClassDef, 0x00702FD0);

	ZENGIN_REGISTER_CLASS(zCWaypoint);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::zCWaypoint_OnInit, 0x00705B70);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWaypoint, &zCWaypoint::Init, void(zCWaypoint::*)(zVEC3&), 0x00705CA0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWaypoint, &zCWaypoint::Init, void(zCWaypoint::*)(float, float, float), 0x00705D00);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWaypoint, &zCWaypoint::Init, void(zCWaypoint::*)(zCVobWaypoint*), 0x00705D70);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::Free, 0x00705E10);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::GetPositionWorld, 0x00705F30);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::UpdatePositionWorld, 0x00705F40);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::SetName, 0x00705FB0);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::GetName, 0x00706110);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::GetVob, 0x00706270);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::CalcProperties, 0x00706280);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::CorrectHeight, 0x007064A0);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::InsertWay, 0x00706540);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::RemoveWay, 0x00706550);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::HasWay, 0x007065B0);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::GetNumberOfWays, 0x007065E0);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::GetWayList, 0x00706600);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::SetWaypointVob, 0x00706610);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::Draw, 0x00706650);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::_GetClassDef, 0x006D4FE0);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::Archive, 0x00706660);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::Unarchive, 0x007066C0);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::CanBeUsed, 0x00705C60);

	ZENGIN_REGISTER_CLASS(zCWay);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWay, &zCWay::zCWay_OnInit, void(zCWay::*)(), 0x00704C40);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWay, &zCWay::zCWay_OnInit, void(zCWay::*)(zCWaypoint*, zCWaypoint*), 0x00704CA0);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::Free, 0x00704DF0);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::GetGoalWaypoint, 0x00704EA0);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::EstimateCost, 0x00704EB0);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::GetLength, 0x00704F20);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::GetJumpDistance, 0x00704FD0);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::GetDistancePos, 0x00705090);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::Draw, 0x007051A0);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::GetFloor, 0x00705670);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::Init, 0x00704D50);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::CalcProperties, 0x00705710);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::GetChasm, 0x00705A00);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::CanJump, 0x00705A10);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::CanBeUsed, 0x00705190);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::IsObjectOnWay, 0x00704C60);

	ZENGIN_REGISTER_CLASS(zCWayNet);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::zCWayNet_OnInit, void(zCWayNet::*)(), 0x00703020);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::zCWayNet_OnInit, void(zCWayNet::*)(zCWorld*), 0x00703100);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::HasWaypoint, zCWaypoint*(zCWayNet::*)(float, float, float), 0x007032F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::HasWaypoint, int(zCWayNet::*)(zCWaypoint*), 0x00703360);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::HasWaypoint, zCWaypoint*(zCWayNet::*)(zVEC3&), 0x00703390);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::InsertWaypoint, zCWaypoint*(zCWayNet::*)(float, float, float), 0x007033E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::InsertWaypoint, void(zCWayNet::*)(zCWaypoint*), 0x007034F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::InsertWaypoint, void(zCWayNet::*)(zCWaypoint*, zCWaypoint*, zCWaypoint*), 0x00703520);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::DeleteWaypoint, 0x007036A0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::CreateWay, 0x00703810);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::DeleteWay, 0x007038E0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::GetNearestWaypoint, 0x00703A50);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::GetSecNearestWaypoint, 0x00703AE0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::CorrectHeight, 0x00703BA0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::Draw, 0x00703C60);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::UpdateVobDependencies, 0x00703C90);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::ClearVobDependencies, 0x00703EE0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::CreateVobDependencies, 0x007040E0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::MergeWaypoints, 0x00704380);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::CheckConsistency, 0x00704640);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::AddWays, 0x00704B40);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::GetWaypoint, 0x00706730);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::SearchWaypoint, 0x007068A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::FindRoute, zCRoute*(zCWayNet::*)(zVEC3 const&, zVEC3 const&, zCVob const*), 0x007068D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::FindRoute, zCRoute*(zCWayNet::*)(zVEC3 const&, zCWaypoint*, zCVob const*), 0x00706960);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::FindRoute, zCRoute*(zCWayNet::*)(zVEC3 const&, zSTRING const&, zCVob const*), 0x007069D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::FindRoute, zCRoute*(zCWayNet::*)(zCWaypoint*, zCWaypoint*, zCVob const*), 0x00706A40);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::FindRoute, zCRoute*(zCWayNet::*)(zSTRING const&, zSTRING const&, zCVob const*), 0x00706A80);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::InsertInOpen, 0x00706B00);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::IsInOpen, 0x00706B30);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::InsertInClosed, 0x00706B50);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::RemoveFromClosed, 0x00706B70);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::IsInClosed, 0x00706B80);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::IsInAnyList, 0x00706BA0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::EstimateCost, 0x00706BD0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::CreateRoute, 0x00706C30);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::AStar, 0x00706CF0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::GetWPList, 0x00706F70);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::CreateWPVobList, 0x00707100);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::RemoveUnusedWPVobs, 0x00707140);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::ArchiveOldFormat, 0x007072A0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::UnarchiveOldFormat, 0x00707A30);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::CalcProperties, 0x00708B20);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::_GetClassDef, 0x007030C0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::Archive, 0x007075B0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::Unarchive, 0x00708530);

	ZENGIN_REGISTER_CLASS(zCRoute);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::zCRoute_OnInit, 0x00708B60);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::SetStart, 0x00708BE0);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::GetNextWP, 0x00708BF0);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::GetTargetWP, 0x00708C60);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::GetCurrentWay, 0x00708C70);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::GetDesc, 0x00708C80);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::GetRemainingDesc, 0x00708E60);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::GetNumberOfWaypoints, 0x00709040);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::IsEmpty, 0x00709060);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::IsLastTarget, 0x00709080);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::GetInterpolatedPosition, 0x007090A0);

	ZENGIN_REGISTER_CLASS(zCVobSpot);
	ZENGIN_REGISTER_METHOD(zCVobSpot, &zCVobSpot::zCVobSpot_OnInit, 0x007092A0);
	ZENGIN_REGISTER_METHOD(zCVobSpot, &zCVobSpot::IsAvailable, 0x00709320);
	ZENGIN_REGISTER_METHOD(zCVobSpot, &zCVobSpot::MarkAsUsed, 0x007094A0);
	ZENGIN_REGISTER_METHOD(zCVobSpot, &zCVobSpot::_GetClassDef, 0x007092C0);

	ZENGIN_REGISTER_CLASS(zCVobStartpoint);
	ZENGIN_REGISTER_METHOD(zCVobStartpoint, &zCVobStartpoint::_GetClassDef, 0x00709C90);

} // namespace Gothic_I_Classic
