namespace Gothic_I_Classic {

	ZENGIN_REGISTER_CLASS(zCPatch);
	ZENGIN_REGISTER_METHOD(zCPatch, &zCPatch::DoTransfers, 0x006000D0);

	ZENGIN_REGISTER_CLASS(zCPatchMap);
	ZENGIN_REGISTER_METHOD(zCPatchMap, &zCPatchMap::CheckRaySurfaceIntersection, 0x005FD520);

	ZENGIN_REGISTER_CLASS(zCWorld);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::zCWorld_OnInit, 0x005F2410);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GetActiveSkyControler, 0x005F2C80);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SetSkyControlerIndoor, 0x005F2CB0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SetSkyControlerOutdoor, 0x005F2CF0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::AddZone, 0x005F2DA0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveZone, 0x005F2F30);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveAllZones, 0x005F3070);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::UpdateZone, 0x005F30E0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::ProcessZones, 0x005F30F0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::ShowZonesDebugInfo, 0x005F3700);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::ShowTextureStats, 0x005F3AE0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::Render, 0x005F3EC0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::TraceRayFirstHit, int(__fastcall zCWorld::*)(zVEC3 const&, zVEC3 const&, zCArray<zCVob*> const*, int), 0x005F40C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::TraceRayNearestHit, int(__fastcall zCWorld::*)(zVEC3 const&, zVEC3 const&, zCArray<zCVob*> const*, int), 0x005F42C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::TraceRayFirstHit, int(__fastcall zCWorld::*)(zVEC3 const&, zVEC3 const&, zCVob*, int), 0x005F4590);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::TraceRayNearestHit, int(__fastcall zCWorld::*)(zVEC3 const&, zVEC3 const&, zCVob*, int), 0x005F46E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::TraceRayFirstHitCache, int(__fastcall zCWorld::*)(zVEC3 const&, zVEC3 const&, zCArray<zCVob*> const*, int, zCRayCache*), 0x005F4830);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::TraceRayFirstHitCache, int(__fastcall zCWorld::*)(zVEC3 const&, zVEC3 const&, zCVob*, int, zCRayCache*), 0x005F48F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::TraceRayNearestHitCache, int(__fastcall zCWorld::*)(zVEC3 const&, zVEC3 const&, zCArray<zCVob*> const*, int, zCRayCache*), 0x005F4A10);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::TraceRayNearestHitCache, int(__fastcall zCWorld::*)(zVEC3 const&, zVEC3 const&, zCVob*, int, zCRayCache*), 0x005F4AD0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::PickScene, 0x005F4BF0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::TraverseBsp, 0x005F4E60);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SaveBspTreeMesh3DS, 0x005F4F60);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::CompileWorld, 0x005F4F90);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchZoneListByClass, 0x005F5F10);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchZoneDefaultByClass, 0x005F6060);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::ShouldAddThisVobToBsp, 0x005F62E0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::AddVobAsChild_novt, 0x005F6320);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::AddVob, 0x005F6340);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveVob_novt, 0x005F66F0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveVobSubtree_r, 0x005F6710);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveVobSubtree_novt, 0x005F68E0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::MoveVobSubtreeTo_novt, 0x005F69C0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::MoveVobSubtreeToWorldSpace, 0x005F69E0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveVobFromLists, 0x005F6A00);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::PrintStatus, 0x005F6BF0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::PrintGlobalVobTree, 0x005F74C0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::PrintActiveVobs, 0x005F7780);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::UpdateVobTreeBspDependencies, 0x005F7980);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::MoveVobs, 0x005F79F0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::AdvanceClock, 0x005F7A80);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SaveBspTree, 0x005F7AC0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::LoadBspTree, 0x005F7C40);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::DebugMarkOccluderPolys, 0x005F7D70);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::UnarcTraverseVobs, 0x005F7F40);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GetProgressBar, 0x005F82F0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::ArcTraverseVobs, 0x005F8D00);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::TraverseVobTree, 0x005F9690);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::GetVobHashIndex, unsigned long(zCWorld::*)(zSTRING const&), 0x005F96F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::GetVobHashIndex, unsigned long(zCWorld::*)(zCVob*), 0x005F9720);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::InsertVobHashTable, 0x005F9760);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveVobHashTable, 0x005F98A0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchVobHashTable, 0x005F9930);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchVobListHashTable, 0x005F9A10);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SetOwnerSession, 0x005F9BF0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GetOwnerSession, 0x005F9C40);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::ResetCutscenePlayer, 0x005F9C50);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RegisterPerFrameCallback, 0x005F9CA0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::UnregisterPerFrameCallback, 0x005F9DF0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::LightWorldStaticUncompiled, 0x005FB120);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::LightWorldStaticCompiled, 0x005FB530);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GenerateStaticVertexLighting, 0x005FBB60);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::LightingTestRay, 0x005FBE30);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GetSurfaceLightmapBBox2D, 0x005FBEF0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GetPhongNormal, 0x005FC350);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GeneratePatchMapFromSurface, 0x005FC710);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GenerateLightmapFromPatchMap, 0x005FD5C0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::LightPatchMap, 0x005FE870);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GenerateSurfaces, 0x005FED20);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::MakeTransfers, 0x005FF990);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GenerateLightmapsRadiosity, 0x00600220);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GenerateLightmaps, 0x00600470);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GenerateStaticWorldLighting, 0x00600B60);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::MakeVobLightingDirty, 0x00600BA0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GetBspTree, 0x006076F0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SetVobFarClipZScalability, 0x00607700);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::_GetClassDef, 0x005F2960);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::Archive, 0x005F9010);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::Unarchive, 0x005F8300);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::LoadWorld, 0x005F8A00);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SaveWorld, 0x005F9330);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::MergeVobSubtree, 0x005F8C40);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SaveVobSubtree, 0x005F95D0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::DisposeWorld, 0x005F5800);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::DisposeVobs, 0x005F55F0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::DisposeStaticWorld, 0x005F5790);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::AddVobAsChild, 0x005F60D0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveVob, 0x005F66C0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveVobSubtree, 0x005F68B0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::MoveVobSubtreeTo, 0x005F6900);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GetPlayerGroup, 0x005F2970);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchVob, 0x005F59E0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchVobByID, 0x005F5A30);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchVobByName, 0x005F5A80);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchVobListByName, 0x005F5B60);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchVobListByClass, 0x005F5D40);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchVobListByBaseClass, 0x005F5E20);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::VobAddedToWorld, 0x005F6360);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::VobRemovedFromWorld, 0x005F64C0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RenderWaynet, 0x005F2D30);

} // namespace Gothic_I_Classic
