namespace Gothic_II_Addon {

	ZENGIN_REGISTER_CLASS(oCAISound);
	ZENGIN_REGISTER_METHOD(oCAISound, &oCAISound::RemoveSlideSound, 0x0069EE80);
	ZENGIN_REGISTER_METHOD(oCAISound, &oCAISound::CheckSlideSound, 0x0069EEA0);
	ZENGIN_REGISTER_METHOD(oCAISound, &oCAISound::GetSoundMaterial, 0x0069EF30);
	ZENGIN_REGISTER_METHOD(oCAISound, &oCAISound::StartCollisionSound, 0x0069F0B0);
	ZENGIN_REGISTER_METHOD(oCAISound, &oCAISound::_GetClassDef, 0x0069F490);

	ZENGIN_REGISTER_CLASS(oCAIArrowBase);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::oCAIArrowBase_OnInit, 0x006A0120);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::AddIgnoreCDVob, 0x006A0390);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::ClearIgnoreCDVob, 0x006A03B0);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::CreateTrail, 0x006A0420);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::_GetClassDef, 0x006A0210);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::Archive, 0x006A0CD0);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::Unarchive, 0x006A0D50);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::DoAI, 0x006A0640);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::ReportCollisionToAI, 0x006A09C0);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::HasAIDetectedCollision, 0x006A0220);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::AICollisionResponseSelfDetected, 0x006A0230);
	ZENGIN_REGISTER_METHOD(oCAIArrowBase, &oCAIArrowBase::GetIsProjectile, 0x006A0240);

	ZENGIN_REGISTER_CLASS(oCAIArrow);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::oCAIArrow_OnInit, 0x006A0E10);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::SetTarget, 0x006A0FF0);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::ClearUsedVobs, 0x006A1030);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::SetupAIVob, 0x006A10E0);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::_GetClassDef, 0x006A0EC0);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::Archive, 0x006A1CC0);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::Unarchive, 0x006A1D90);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::DoAI, 0x006A1460);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::CanThisCollideWith, 0x006A1490);
	ZENGIN_REGISTER_METHOD(oCAIArrow, &oCAIArrow::ReportCollisionToAI, 0x006A1530);

	ZENGIN_REGISTER_CLASS(oCAIDrop);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::oCAIDrop_OnInit, 0x006A1EA0);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::AddIgnoreCDVob, 0x006A2130);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::ClearIgnoreCDVob, 0x006A2150);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::SetupAIVob, 0x006A21C0);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::SetVelocity, 0x006A24E0);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::SetStartPosition, 0x006A2590);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::_GetClassDef, 0x006A1F80);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::Archive, 0x006A2710);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::Unarchive, 0x006A2720);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::DoAI, 0x006A2420);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::CanThisCollideWith, 0x006A1FA0);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::ReportCollisionToAI, 0x006A2490);
	ZENGIN_REGISTER_METHOD(oCAIDrop, &oCAIDrop::HasAIDetectedCollision, 0x006A1F90);

	ZENGIN_REGISTER_CLASS(oCAIVobMove);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::oCAIVobMove_OnInit, 0x0069F220);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::AddIgnoreCDVob, 0x0069FBD0);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::ClearIgnoreCDVob, 0x0069FBF0);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::_GetClassDef, 0x0069F2F0);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::Archive, 0x0069FA80);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::Unarchive, 0x0069FAE0);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::DoAI, 0x0069F8C0);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::CanThisCollideWith, 0x0069F300);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::ReportCollisionToAI, 0x0069FA30);
	ZENGIN_REGISTER_METHOD(oCAIVobMove, &oCAIVobMove::Init, 0x0069F540);

	ZENGIN_REGISTER_CLASS(oCAIVobMoveTorch);
	ZENGIN_REGISTER_METHOD(oCAIVobMoveTorch, &oCAIVobMoveTorch::oCAIVobMoveTorch_OnInit, 0x0069FC60);
	ZENGIN_REGISTER_METHOD(oCAIVobMoveTorch, &oCAIVobMoveTorch::CheckWater, 0x0069FE90);
	ZENGIN_REGISTER_METHOD(oCAIVobMoveTorch, &oCAIVobMoveTorch::BurnedOut, 0x0069FF40);
	ZENGIN_REGISTER_METHOD(oCAIVobMoveTorch, &oCAIVobMoveTorch::_GetClassDef, 0x0069FCF0);
	ZENGIN_REGISTER_METHOD(oCAIVobMoveTorch, &oCAIVobMoveTorch::DoAI, 0x0069FE60);
	ZENGIN_REGISTER_METHOD(oCAIVobMoveTorch, &oCAIVobMoveTorch::Init, 0x0069FE40);

} // namespace Gothic_II_Addon
