namespace Gothic_II_Addon {

	ZENGIN_REGISTER_CLASS(oCItemContainer);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::oCItemContainer_OnInit, 0x00704D00);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetNextContainerLeft, 0x00704BC0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetNextContainerRight, 0x00704C60);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::JumpOffset, 0x00706AB0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::ActivateNextContainer, 0x0070A150);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::HandleEvent, 0x0070A640);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Open, 0x00708550);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::OpenPassive, 0x007086D0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetName, 0x00704F10);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::SetName, 0x00704F60);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetMode, 0x007050A0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::SetMode, 0x007050B0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Close, 0x00708F30);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Activate, 0x00709230);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Deactivate, 0x00709290);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::IsOpen, 0x00709200);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::IsActive, 0x007050D0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::IsEmpty, 0x00709E10);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::IsSplitScreen, 0x00709E40);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::SetContents, 0x007084F0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetContents, 0x00708540);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Insert, 0x00709360);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCItemContainer, &oCItemContainer::Remove, void(oCItemContainer::*)(oCItem*), 0x00709430);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCItemContainer, &oCItemContainer::Remove, oCItem*(oCItemContainer::*)(oCItem*, int), 0x007094E0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::RemoveByPtr, 0x007094D0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetSelectedItem, 0x007092C0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetSelectedItemCount, 0x007092F0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetSize, 0x00706A70);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::DisableManipulateItems, 0x007050E0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::CanManipulateItems, 0x007050F0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::DisableTransferMoreThanOneItem, 0x00705100);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::CanTransferMoreThanOneItem, 0x00705120);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::IsPassive, 0x00708F20);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetTransferCount, 0x00705130);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::SetTransferCount, 0x00705140);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::IncTransferCount, 0x00705150);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Archive, 0x0070A270);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Unarchive, 0x0070A460);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Init, 0x00706870);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::GetPosition, 0x00706A90);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::LoadGrafix, 0x00706430);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::DeleteContents, 0x00709590);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::NextItem, 0x00709740);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::NextItemLine, 0x007099A0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::PrevItem, 0x00709B00);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::PrevItemLine, 0x00709D30);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::CheckSelectedItem, 0x00709660);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::TransferItem, 0x00709F40);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::Draw, 0x007076B0);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::DrawCategory, 0x00706B60);
	ZENGIN_REGISTER_METHOD(oCItemContainer, &oCItemContainer::DrawItemInfo, 0x00706E40);

	ZENGIN_REGISTER_CLASS(oCStealContainer);
	ZENGIN_REGISTER_METHOD(oCStealContainer, &oCStealContainer::oCStealContainer_OnInit, 0x0070ABF0);
	ZENGIN_REGISTER_METHOD(oCStealContainer, &oCStealContainer::HandleEvent, 0x0070B090);
	ZENGIN_REGISTER_METHOD(oCStealContainer, &oCStealContainer::SetOwner, 0x0070ADB0);
	ZENGIN_REGISTER_METHOD(oCStealContainer, &oCStealContainer::GetOwner, 0x0070ADD0);
	ZENGIN_REGISTER_METHOD(oCStealContainer, &oCStealContainer::CreateList, 0x0070ADE0);

	ZENGIN_REGISTER_CLASS(oCNpcContainer);
	ZENGIN_REGISTER_METHOD(oCNpcContainer, &oCNpcContainer::oCNpcContainer_OnInit, 0x0070B3C0);
	ZENGIN_REGISTER_METHOD(oCNpcContainer, &oCNpcContainer::HandleEvent, 0x0070B6F0);
	ZENGIN_REGISTER_METHOD(oCNpcContainer, &oCNpcContainer::Insert, 0x0070B9F0);
	ZENGIN_REGISTER_METHOD(oCNpcContainer, &oCNpcContainer::Remove, 0x0070BA30);
	ZENGIN_REGISTER_METHOD(oCNpcContainer, &oCNpcContainer::CreateList, 0x0070B570);

	ZENGIN_REGISTER_CLASS(oCNpcInventory);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::oCNpcInventory_OnInit, 0x0082DF4B);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::ClearInventory, 0x0070BDB0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::SetOwner, 0x0070C320);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetOwner, 0x0070C330);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetNumItemsInCategory, 0x0070C340);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetItem, 0x0070C450);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetCategory, 0x0070C690);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetAmount, 0x0070C970);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::HandleTrade, 0x0070DE00);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::CheckForEquippedItems, 0x0070F390);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::CanCarry, 0x0070F4D0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::SetPackAbility, 0x0070F600);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::UnpackCategory, 0x0070F620);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetNumItemsInPackString, 0x0070F630);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetPackedItemBySlot, 0x0070F720);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::CreateFromPackString, 0x0070F860);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::GetPackedItemInfo, 0x0070F8F0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::PackSingleItem, 0x0070FCB0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::PackAllItems, 0x00710020);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::UnpackAllItems, 0x00710030);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::PackItemsInCategory, 0x00710040);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::UnpackItemsInCategory, 0x00710A20);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::HandleEvent, 0x0070E040);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::Open, 0x0070BF10);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::Close, 0x0070C2F0);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::Insert, 0x0070C730);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::Remove, oCItem*(oCNpcInventory::*)(int, int), 0x0070D080);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::Remove, oCItem*(oCNpcInventory::*)(zSTRING const&, int), 0x0070D170);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::RemoveByPtr, 0x0070CC70);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::Archive, 0x0070D210);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::Unarchive, 0x0070D550);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::Draw, 0x0070C310);
	ZENGIN_REGISTER_METHOD(oCNpcInventory, &oCNpcInventory::DrawCategory, 0x0070DBD0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::Remove, void(oCNpcInventory::*)(oCItem*), 0x0070CBE0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::Remove, oCItem*(oCNpcInventory::*)(oCItem*, int), 0x0070CE20);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::IsIn, oCItem*(oCNpcInventory::*)(oCItem*, int), 0x0070CA80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::IsIn, oCItem*(oCNpcInventory::*)(int, int), 0x0070CAF0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::IsIn, oCItem*(oCNpcInventory::*)(zSTRING const&, int), 0x0070CAC0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::IsEmpty, int(oCNpcInventory::*)(), 0x00709E10);
	ZENGIN_REGISTER_METHOD_EXPLICIT(oCNpcInventory, &oCNpcInventory::IsEmpty, int(oCNpcInventory::*)(int, int), 0x0070D1A0);

} // namespace Gothic_II_Addon
