namespace Gothic_II_Addon {

	ZENGIN_REGISTER_CLASS(oCSVMManager);
	ZENGIN_REGISTER_METHOD(oCSVMManager, &oCSVMManager::oCSVMManager_OnInit, 0x00779B70);
	ZENGIN_REGISTER_METHOD(oCSVMManager, &oCSVMManager::GetOU, 0x00779E50);

	ZENGIN_REGISTER_CLASS(oCSVM);
	ZENGIN_REGISTER_METHOD(oCSVM, &oCSVM::oCSVM_OnInit, 0x0077A260);
	ZENGIN_REGISTER_METHOD(oCSVM, &oCSVM::InitByScript, 0x0077A290);
	ZENGIN_REGISTER_METHOD(oCSVM, &oCSVM::GetOU, 0x0077A540);

} // namespace Gothic_II_Addon
