namespace Gothic_II_Addon {

	ZENGIN_REGISTER_CLASS(zTEngineStats);
	ZENGIN_REGISTER_METHOD(zTEngineStats, &zTEngineStats::PrintScreen, 0x0050ACF0);

	ZENGIN_REGISTER_CLASS(zCLineCache);
	ZENGIN_REGISTER_METHOD(zCLineCache, &zCLineCache::Line, 0x0050B320);
	ZENGIN_REGISTER_METHOD(zCLineCache, &zCLineCache::Flush, 0x0050B3B0);
	ZENGIN_REGISTER_METHOD(zCLineCache, &zCLineCache::Line3D, 0x0050B450);
	ZENGIN_REGISTER_METHOD(zCLineCache, &zCLineCache::LineCS3D, 0x0050B850);

	ZENGIN_REGISTER_CLASS(zCCamera);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::zCCamera_OnInit, 0x00549E60);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::Project, void(zCCamera::*)(zVEC3 const* const, float&, float&) const, 0x00530030);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::PushTransform, 0x0054A370);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::PopTransform, 0x0054A400);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::SetTransform, 0x0054A540);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::GetTransform, 0x0054A6A0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::Activate, 0x0054A700);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::CreateProjectionMatrix, 0x0054A810);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::UpdateProjectionMatrix, 0x0054A890);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::GetFOV, float(zCCamera::*)() const, 0x0054A8E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::GetFOV, void(zCCamera::*)(float&, float&) const, 0x0054A8F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::SetFOV, void(zCCamera::*)(float), 0x0054A920);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::SetFOV, void(zCCamera::*)(float, float), 0x0054A960);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::UpdateViewport, 0x0054AA90);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::SetRenderTarget, 0x0054ABD0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::SetRenderScreenFadeTex, 0x0054ABF0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::SetUpFrustum, 0x0054AD20);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::SetFarClipZ, 0x0054B200);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::BBox3DInFrustum, zTCam_ClipType(zCCamera::*)(zTBBox3D const&), 0x0054B3B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::BBox3DInFrustum, zTCam_ClipType(zCCamera::*)(zTBBox3D const&, int&), 0x0054B410);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::StopTremor, 0x0054B650);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::AddTremor, 0x0054B660);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::PreRenderProcessing, 0x0054B7D0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::PostRenderProcessing, 0x0054B920);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::GetCamPos, 0x0054B960);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::InitDrawPolySimple, 0x0054B990);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::CleanupDrawPolySimple, 0x0054BA50);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::DrawPolySimple, 0x0054BAB0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::SetRenderScreenFade, 0x0054BBC0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::SetRenderScreenFadeTexAniFPS, 0x0054BBE0);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::SetRenderScreenFadeTexBlendFunc, 0x0054BC10);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::SetRenderCinemaScope, 0x0054BC20);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::RenderScreenFade, 0x0054BC40);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::RenderCinemaScope, 0x0054BD30);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::ScreenProjectionTouchesPortalRough, 0x0054BE80);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::ScreenProjectionTouchesPortal, 0x0054C100);
	ZENGIN_REGISTER_METHOD(zCCamera, &zCCamera::ProjectClamp, 0x0056BD00);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::Project, void(zCCamera::*)(zVEC3 const* const, int&, int&), 0x0057A440);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCCamera, &zCCamera::Project, void(zCCamera::*)(zVEC3 const* const, float, float&, float&) const, 0x00604ED0);

	ZENGIN_REGISTER_CLASS(zCVertex);
	ZENGIN_REGISTER_METHOD(zCVertex, &zCVertex::zCVertex_OnInit, 0x005716A0);
	ZENGIN_REGISTER_METHOD(zCVertex, &zCVertex::Draw, 0x0050BB10);
	ZENGIN_REGISTER_METHOD(zCVertex, &zCVertex::CreateVertexTransform, 0x0050BC00);
	ZENGIN_REGISTER_METHOD(zCVertex, &zCVertex::ResetVertexTransform, 0x005C4A90);

	ZENGIN_REGISTER_CLASS(zCVertFeature);
	ZENGIN_REGISTER_METHOD(zCVertFeature, &zCVertFeature::zCVertFeature_OnInit, 0x0056D760);

	ZENGIN_REGISTER_CLASS(zCPolygon);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::zCPolygon_OnInit, 0x005B6FA0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::RenderPoly, 0x00529DD0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::ApplyMorphing, 0x0052A420);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::LightClippedPoly, 0x0052AD40);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TransformProjectLight, 0x0052B650);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TransformProject, 0x0052B820);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::SetMaterial, 0x00537910);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::ClipToPlane, 0x005B72F0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::ClipToPlane_Occluder, 0x005B7790);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::Unclip, 0x005B7A10);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::Unclip_Occluder, 0x005B7A90);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CopyClipFeaturesForTexAniMapping, 0x005B7AB0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::ClipToFrustum, 0x005B7B20);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::ClipToFrustum_Occluder, 0x005B7E60);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::ClassifyPlane, 0x005B8040);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::ClassifyPlaneBSPBuild, 0x005B80F0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CalcNormal, 0x005B8180);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CalcNormalApprox, 0x005B85A0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::GetScreenBBox2D, 0x005B89D0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::DrawWire, 0x005B8A70);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::LightDynCamSpace, 0x005B9250);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::GetLightStatAtPos, 0x005B9410);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CheckRayPolyIntersection, 0x005B9B20);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CheckRayPolyIntersection2Sided, 0x005B9EB0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::GetBBox3D, 0x005BA220);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::GetCenter, 0x005BA2F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPolygon, &zCPolygon::SetMapping, void(zCPolygon::*)(zVEC2 const&, zVEC2 const&, zVEC2 const&), 0x005BA370);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPolygon, &zCPolygon::SetMapping, void(zCPolygon::*)(int, zVEC2 const&), 0x005BA3C0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::Flip, 0x005BA3E0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::VertPartOfPoly, 0x005BA420);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::EdgePartOfPoly, 0x005BA450);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::EdgePositionsPartOfPoly, 0x005BA4A0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TexTranslate, 0x005BA4F0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TexSetTranslation, 0x005BA530);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPolygon, &zCPolygon::TexScale, void(zCPolygon::*)(float, float), 0x005BA570);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPolygon, &zCPolygon::TexScale, void(zCPolygon::*)(zVEC2&, float, float), 0x005BA5B0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TexRotate, 0x005BA670);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TexMirrorU, 0x005BA840);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TexMirrorV, 0x005BA870);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TexShearU, 0x005BA8A0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TexShearV, 0x005BA960);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPolygon, &zCPolygon::TexApplyPlanarMapping, void(zCPolygon::*)(zVEC3 const&, zVEC3 const&, zVEC3 const&, int), 0x005BAA20);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPolygon, &zCPolygon::TexApplyPlanarMapping, void(zCPolygon::*)(float, float, int), 0x005BABD0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::TexCorrectUV, 0x005BB1C0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::AllocVerts, 0x005BB310);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::AddVertex, 0x005BB480);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::AddVertexAndFeature, 0x005BB4A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPolygon, &zCPolygon::SetVertices, void(zCPolygon::*)(zCVertex*, zCVertex*, zCVertex*), 0x005BB4E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPolygon, &zCPolygon::SetVertices, void(zCPolygon::*)(zCVertex*, zCVertex*, zCVertex*, zCVertex*, int), 0x005BB540);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::SetVertex, 0x005BB5B0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::SetFeature, 0x005BB5F0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CopyValuesInto, 0x005BB630);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CopyPolyInto, 0x005BB6E0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::RemoveVerticesAndFeatures, 0x005BB740);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::GetArea, 0x005BB7D0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::GetLongestEdgeLen, 0x005BB870);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::ResetStaticLight, 0x005BB8E0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::SetStaticLight, 0x005BB920);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::SetLightDyn, 0x005BB950);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::SetLightStatAlpha, 0x005BB980);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::ResetLightDynToLightStat, 0x005BB9B0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::AddToLightDyn, 0x005BB9E0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CheckBBoxPolyIntersection, 0x005BBA70);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::CheckBSpherePolyIntersection, 0x005BBEF0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::SplitPoly, 0x005BC060);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::IsIntersectingProjection, 0x005BC5B0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::IsIntersecting, 0x005BCD20);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::IsNeighbourOf, 0x005BCDF0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::GetStaticLODPossible, 0x005BCEC0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::LightStatic, 0x00628EA0);
	ZENGIN_REGISTER_METHOD(zCPolygon, &zCPolygon::SmoothSectorBorder, 0x00629800);

	ZENGIN_REGISTER_CLASS(zCPortal);
	ZENGIN_REGISTER_METHOD(zCPortal, &zCPortal::zCPortal_OnInit, 0x005293B0);
	ZENGIN_REGISTER_METHOD(zCPortal, &zCPortal::RemoveFromBsp, 0x00529390);
	ZENGIN_REGISTER_METHOD(zCPortal, &zCPortal::Init, 0x0053ED80);

} // namespace Gothic_II_Addon
