namespace Gothic_II_Addon {

	ZENGIN_REGISTER_CLASS(zCArchiverBinSafe);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::zCArchiverBinSafe_OnInit, 0x0051BED0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::RestoreString, 0x0051B340);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteType, 0x0051B350);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ReadType, 0x0051B3C0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ClearChunkList, 0x0051BBF0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::InsertChunkInList, 0x0051BD70);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ResolveAndPosEntry, 0x0051BE00);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::DebugMessage, 0x0051C3C0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::CheckObjectListSize, 0x0051EEC0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::_GetClassDef, 0x0051C040);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteInt, 0x0051D020);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteByte, 0x0051D100);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteWord, 0x0051D1E0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteFloat, 0x0051D2C0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteBool, 0x0051D3A0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteString, 0x0051D480);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteVec3, 0x0051D5B0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteColor, 0x0051D8E0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteRaw, 0x0051D9C0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteRawFloat, 0x0051DAA0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteEnum, 0x0051DCC0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::WriteObject, void(__fastcall zCArchiverBinSafe::*)(zCObject*), 0x0051E830);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::WriteObject, void(__fastcall zCArchiverBinSafe::*)(char const*, zCObject*), 0x0051E7A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::WriteObject, void(__fastcall zCArchiverBinSafe::*)(char const*, zCObject&), 0x0051E560);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::WriteChunkStart, void(__fastcall zCArchiverBinSafe::*)(char const*, unsigned short), 0x0051E300);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::WriteChunkStart, void(__fastcall zCArchiverBinSafe::*)(char const*, char const*, unsigned short, unsigned long), 0x0051DEE0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteChunkEnd, 0x0051E320);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteGroupBegin, 0x0051DEC0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteGroupEnd, 0x0051DED0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadInt, void(__fastcall zCArchiverBinSafe::*)(char const*, int&), 0x00520C90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadInt, int(__fastcall zCArchiverBinSafe::*)(char const*), 0x00520A50);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadByte, void(__fastcall zCArchiverBinSafe::*)(char const*, unsigned char&), 0x00520CC0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadByte, unsigned char(__fastcall zCArchiverBinSafe::*)(char const*), 0x00520A70);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadWord, void(__fastcall zCArchiverBinSafe::*)(char const*, unsigned short&), 0x00520CF0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadWord, unsigned short(__fastcall zCArchiverBinSafe::*)(char const*), 0x00520A90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadFloat, void(__fastcall zCArchiverBinSafe::*)(char const*, float&), 0x00520C30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadFloat, float(__fastcall zCArchiverBinSafe::*)(char const*), 0x005209F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadBool, void(__fastcall zCArchiverBinSafe::*)(char const*, int&), 0x00520D20);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadBool, int(__fastcall zCArchiverBinSafe::*)(char const*), 0x00520AB0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadString, void(__fastcall zCArchiverBinSafe::*)(char const*, zSTRING&), 0x00520D50);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadString, zSTRING(__fastcall zCArchiverBinSafe::*)(char const*), 0x00520AD0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadVec3, void(__fastcall zCArchiverBinSafe::*)(char const*, zVEC3&), 0x00520C60);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadVec3, zVEC3(__fastcall zCArchiverBinSafe::*)(char const*), 0x00520A10);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadColor, void(__fastcall zCArchiverBinSafe::*)(char const*, zCOLOR&), 0x00520D80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadColor, zCOLOR(__fastcall zCArchiverBinSafe::*)(char const*), 0x00520B90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadEnum, void(__fastcall zCArchiverBinSafe::*)(char const*, int&), 0x00520DB0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadEnum, int(__fastcall zCArchiverBinSafe::*)(char const*), 0x00520BB0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ReadRaw, 0x00520BD0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ReadRawFloat, 0x00520C00);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadObject, zCObject*(__fastcall zCArchiverBinSafe::*)(zCObject*), 0x005201D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadObject, zCObject*(__fastcall zCArchiverBinSafe::*)(char const*, zCObject*), 0x0051FB50);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadChunkStart, int(__fastcall zCArchiverBinSafe::*)(zSTRING&, unsigned short&), 0x0051F9D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverBinSafe, &zCArchiverBinSafe::ReadChunkStart, int(__fastcall zCArchiverBinSafe::*)(char const*), 0x0051F430);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ReadChunkStartNamed, 0x0051FAF0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::SkipOpenChunk, 0x0051C050);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::GetCurrentChunkVersion, 0x0051FB20);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::GetFile, 0x0051C060);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::GetBufferString, 0x0051C920);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::GetBuffer, 0x0051CA90);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::EndOfArchive, 0x0051C890);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::Close, 0x0051C440);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::SetStringEOL, 0x0051C070);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::GetStringEOL, 0x0051C1F0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::IsStringValid, 0x0051CE00);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::GetChecksumEnabled, 0x0051C230);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::SetChecksumEnabled, 0x0051C240);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::SetNoReadSearchCycles, 0x0051C250);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::InProperties, 0x0051C260);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::InSaveGame, 0x0051C270);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::InBinaryMode, 0x0051C280);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::GetParentObject, 0x00520DE0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::OpenWriteBuffer, 0x0051CAA0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::OpenWriteFile, 0x0051CC60);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteHeader, 0x0051CD80);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteHeaderNumObj, 0x0051C3E0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::WriteASCIILine, 0x0051CE40);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::StoreBuffer, 0x0051CCC0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::StoreString, 0x0051CCF0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::StoreStringEOL, 0x0051CD70);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::StoreGetPos, 0x0051CD20);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::StoreSeek, 0x0051CD40);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::OpenReadBuffer, 0x0051E840);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::OpenReadFile, 0x0051EA10);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::GetClassDefByString, 0x0051F030);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::CreateObject, 0x0051EF60);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::SkipChunk, 0x005201E0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ReadChunkStartASCII, 0x0051F1D0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ReadChunkEnd, 0x0051FB40);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ReadEntryASCII, 0x005203B0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::ReadHeader, 0x0051EB20);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::RestoreBuffer, 0x0051EA70);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::RestoreStringEOL, 0x0051EAA0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::RestoreString0, 0x0051EAB0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::RestoreGetPos, 0x0051EAC0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::RestoreSeek, 0x0051EAE0);
	ZENGIN_REGISTER_METHOD(zCArchiverBinSafe, &zCArchiverBinSafe::DeleteBuffer, 0x0051C900);

} // namespace Gothic_II_Addon
