namespace Gothic_II_Addon {

	ZENGIN_REGISTER_CLASS(zCArchiverGeneric);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::zCArchiverGeneric_OnInit, 0x00521E30);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::DebugMessage, 0x005222F0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::CheckObjectListSize, 0x00525A50);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::_GetClassDef, 0x00521F50);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteInt, 0x00522E30);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteByte, 0x00522FD0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteWord, 0x00523170);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteFloat, 0x00523310);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteBool, 0x005234D0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteString, 0x00523670);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteVec3, 0x005236D0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteColor, 0x00523A10);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteRaw, 0x00523D80);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteRawFloat, 0x00523F50);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteEnum, 0x00524220);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::WriteObject, void(__fastcall zCArchiverGeneric::*)(zCObject*), 0x00524EC0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::WriteObject, void(__fastcall zCArchiverGeneric::*)(char const*, zCObject*), 0x00524E20);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::WriteObject, void(__fastcall zCArchiverGeneric::*)(char const*, zCObject&), 0x00524C10);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::WriteChunkStart, void(__fastcall zCArchiverGeneric::*)(char const*, unsigned short), 0x00524950);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::WriteChunkStart, void(__fastcall zCArchiverGeneric::*)(char const*, char const*, unsigned short, unsigned long), 0x00524490);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteChunkEnd, 0x00524970);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteGroupBegin, 0x00524ED0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteGroupEnd, 0x00524FB0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadInt, void(__fastcall zCArchiverGeneric::*)(char const*, int&), 0x00527B80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadInt, int(__fastcall zCArchiverGeneric::*)(char const*), 0x005274C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadByte, void(__fastcall zCArchiverGeneric::*)(char const*, unsigned char&), 0x00527BD0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadByte, unsigned char(__fastcall zCArchiverGeneric::*)(char const*), 0x005274E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadWord, void(__fastcall zCArchiverGeneric::*)(char const*, unsigned short&), 0x00527C20);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadWord, unsigned short(__fastcall zCArchiverGeneric::*)(char const*), 0x00527500);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadFloat, void(__fastcall zCArchiverGeneric::*)(char const*, float&), 0x00527AD0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadFloat, float(__fastcall zCArchiverGeneric::*)(char const*), 0x00527460);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadBool, void(__fastcall zCArchiverGeneric::*)(char const*, int&), 0x00527C70);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadBool, int(__fastcall zCArchiverGeneric::*)(char const*), 0x00527520);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadString, void(__fastcall zCArchiverGeneric::*)(char const*, zSTRING&), 0x00527CD0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadString, zSTRING(__fastcall zCArchiverGeneric::*)(char const*), 0x00527540);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadVec3, void(__fastcall zCArchiverGeneric::*)(char const*, zVEC3&), 0x00527B20);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadVec3, zVEC3(__fastcall zCArchiverGeneric::*)(char const*), 0x00527480);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadColor, void(__fastcall zCArchiverGeneric::*)(char const*, zCOLOR&), 0x00527D00);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadColor, zCOLOR(__fastcall zCArchiverGeneric::*)(char const*), 0x00527600);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadEnum, void(__fastcall zCArchiverGeneric::*)(char const*, int&), 0x00527D90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadEnum, int(__fastcall zCArchiverGeneric::*)(char const*), 0x00527620);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::ReadRaw, 0x00527640);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::ReadRawFloat, 0x005278D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadObject, zCObject*(__fastcall zCArchiverGeneric::*)(zCObject*), 0x00526DF0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadObject, zCObject*(__fastcall zCArchiverGeneric::*)(char const*, zCObject*), 0x00526560);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadChunkStart, int(__fastcall zCArchiverGeneric::*)(zSTRING&, unsigned short&), 0x005263E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCArchiverGeneric, &zCArchiverGeneric::ReadChunkStart, int(__fastcall zCArchiverGeneric::*)(char const*), 0x00525FB0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::ReadChunkStartNamed, 0x00526500);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::SkipOpenChunk, 0x00521F60);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::GetCurrentChunkVersion, 0x00526530);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::GetFile, 0x00521F70);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::GetBufferString, 0x005226E0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::GetBuffer, 0x00522850);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::EndOfArchive, 0x00522650);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::Close, 0x00522470);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::SetStringEOL, 0x00521F80);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::GetStringEOL, 0x00522100);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::IsStringValid, 0x00522C00);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::GetChecksumEnabled, 0x00522140);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::SetChecksumEnabled, 0x00522150);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::SetNoReadSearchCycles, 0x00522160);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::InProperties, 0x00522170);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::InSaveGame, 0x00522180);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::InBinaryMode, 0x00522190);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::GetParentObject, 0x00528800);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::OpenWriteBuffer, 0x00522860);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::OpenWriteFile, 0x00522A30);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteHeader, 0x00522B90);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteHeaderNumObj, 0x00522310);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::WriteASCIILine, 0x00522C40);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::StoreBuffer, 0x00522AA0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::StoreString, 0x00522AD0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::StoreStringEOL, 0x00522B60);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::StoreGetPos, 0x00522B10);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::StoreSeek, 0x00522B30);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::OpenReadBuffer, 0x00525090);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::OpenReadFile, 0x00525260);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::GetClassDefByString, 0x00525BC0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::CreateObject, 0x00525AF0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::SkipChunk, 0x00526E00);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::ReadChunkStartASCII, 0x00525D60);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::ReadChunkEnd, 0x00526550);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::ReadEntryASCII, 0x00527000);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::ReadHeader, 0x00525750);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::RestoreBuffer, 0x005252D0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::RestoreStringEOL, 0x00525300);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::RestoreString0, 0x005256E0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::RestoreGetPos, 0x005256F0);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::RestoreSeek, 0x00525710);
	ZENGIN_REGISTER_METHOD(zCArchiverGeneric, &zCArchiverGeneric::DeleteBuffer, 0x005226C0);

} // namespace Gothic_II_Addon
