namespace Gothic_II_Addon {

	ZENGIN_REGISTER_CLASS(zFILE_VDFS);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::zFILE_VDFS_OnInit, void(zFILE_VDFS::*)(), 0x00448BF0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::zFILE_VDFS_OnInit, void(zFILE_VDFS::*)(zSTRING const&), 0x00448E20);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::Init, 0x00448BB0);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::HandleError, 0x00449110);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::GetFullPath, 0x00449D20);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::SetCurrentDir, 0x00449AD0);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::ChangeDir, 0x00449E70);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::SearchFile, 0x00449E80);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::FindFirst, 0x0044A300);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::FindNext, 0x0044A5B0);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::IsOpened, 0x00448FF0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::Open, int(zFILE_VDFS::*)(bool), 0x00449120);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::Open, int(zFILE_VDFS::*)(zSTRING const&, bool), 0x00448D30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::Exists, bool(zFILE_VDFS::*)(), 0x00449020);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::Exists, bool(zFILE_VDFS::*)(zSTRING const&), 0x00448DA0);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::Close, 0x004493A0);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::Reset, 0x00449400);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::Append, 0x00449AB0);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::Size, 0x00449410);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::Pos, 0x00449A50);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::Seek, 0x00449490);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::Eof, 0x00449470);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::GetStats, 0x0044A2F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::Read, long(zFILE_VDFS::*)(void*, long), 0x0044ABF0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::Read, int(zFILE_VDFS::*)(char*), 0x0044A8D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zFILE_VDFS, &zFILE_VDFS::Read, int(zFILE_VDFS::*)(zSTRING&), 0x0044AA80);
	ZENGIN_REGISTER_METHOD(zFILE_VDFS, &zFILE_VDFS::SeekText, 0x00449870);

} // namespace Gothic_II_Addon
