namespace Gothic_II_Addon {

	ZENGIN_REGISTER_CLASS(zERROR);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::zERROR_OnInit, 0x0044BD40);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::Init, 0x0044BFA0);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::SendToSpy, 0x0044C850);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zERROR, &zERROR::Report, int(zERROR::*)(zERROR_LEVEL, int, zSTRING const&, signed char, unsigned int, int, char*, char*), 0x0044C8C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zERROR, &zERROR::Report, int(zERROR::*)(zERROR_TYPE, int, zSTRING const&, signed char, unsigned int, int, char*, char*), 0x0044C8D0);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::BlockBegin, 0x0044D060);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::BlockEnd, 0x0044D290);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::Separator, 0x0044D6B0);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::ShowSpy, 0x0044D8C0);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::Message, 0x0044DA10);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::Warning, 0x0044DA50);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::Fatal, 0x0044DA80);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::Fault, 0x0044DAB0);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::SetFilterFlags, 0x0044DAE0);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::SetFilterAuthors, 0x0044DC00);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::SetFilterLevel, 0x0044DDA0);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::SetTarget, 0x0044DF50);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::GetTargetDescription, 0x0044E1D0);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::GetFilterFlagDescription, 0x0044E3F0);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::GetFilterAuthors, 0x0044E5F0);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::SearchForSpy, 0x0044E640);
	ZENGIN_REGISTER_METHOD(zERROR, &zERROR::GetFilterLevel, 0x0059D130);

} // namespace Gothic_II_Addon
