namespace Gothic_II_Addon {

	ZENGIN_REGISTER_CLASS(zRandom_Gauss);
	ZENGIN_REGISTER_METHOD(zRandom_Gauss, &zRandom_Gauss::zRandom_Gauss_OnInit, 0x0055ACE0);
	ZENGIN_REGISTER_METHOD(zRandom_Gauss, &zRandom_Gauss::RandomUniform, 0x0055AE30);
	ZENGIN_REGISTER_METHOD(zRandom_Gauss, &zRandom_Gauss::GetGaussian, 0x0055AEB0);
	ZENGIN_REGISTER_METHOD(zRandom_Gauss, &zRandom_Gauss::GetInt, 0x0055AFA0);
	ZENGIN_REGISTER_METHOD(zRandom_Gauss, &zRandom_Gauss::GetFloat, 0x0055AFD0);
	ZENGIN_REGISTER_METHOD(zRandom_Gauss, &zRandom_Gauss::StepForward, 0x0055AFF0);
	ZENGIN_REGISTER_METHOD(zRandom_Gauss, &zRandom_Gauss::UnRandomUniform, 0x0055B070);
	ZENGIN_REGISTER_METHOD(zRandom_Gauss, &zRandom_Gauss::StepBack, 0x0055B140);
	ZENGIN_REGISTER_METHOD(zRandom_Gauss, &zRandom_Gauss::rand24, 0x0055B200);
	ZENGIN_REGISTER_METHOD(zRandom_Gauss, &zRandom_Gauss::unRand24, 0x0055B210);
	ZENGIN_REGISTER_METHOD(zRandom_Gauss, &zRandom_Gauss::GetGaussAt, 0x0055B220);

	ZENGIN_REGISTER_CLASS(zCFFT);
	ZENGIN_REGISTER_METHOD(zCFFT, &zCFFT::zCFFT_OnInit, 0x00559E40);
	ZENGIN_REGISTER_METHOD(zCFFT, &zCFFT::CalcWave2D, 0x00559FC0);
	ZENGIN_REGISTER_METHOD(zCFFT, &zCFFT::IsPowerOfTwo, 0x0055A160);
	ZENGIN_REGISTER_METHOD(zCFFT, &zCFFT::NumberOfBitsNeeded, 0x0055A180);
	ZENGIN_REGISTER_METHOD(zCFFT, &zCFFT::ReverseBits, 0x0055A1D0);
	ZENGIN_REGISTER_METHOD(zCFFT, &zCFFT::Index_to_frequency, 0x0055A200);
	ZENGIN_REGISTER_METHOD(zCFFT, &zCFFT::CreateWaveMap, 0x0055A270);
	ZENGIN_REGISTER_METHOD(zCFFT, &zCFFT::FillH0Array, 0x0055A2B0);
	ZENGIN_REGISTER_METHOD(zCFFT, &zCFFT::AnimateWaveMap, 0x0055A520);
	ZENGIN_REGISTER_METHOD(zCFFT, &zCFFT::fft_float, 0x0055A710);
	ZENGIN_REGISTER_METHOD(zCFFT, &zCFFT::SetFrameCtr, 0x0055A970);
	ZENGIN_REGISTER_METHOD(zCFFT, &zCFFT::SetSpeed, 0x0055A980);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCFFT, &zCFFT::GetWaveHeight, zComplex&(zCFFT::*)(int, int), 0x0055A990);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCFFT, &zCFFT::GetWaveHeight, zComplex&(zCFFT::*)(float, float, float), 0x0055A9E0);
	ZENGIN_REGISTER_METHOD(zCFFT, &zCFFT::GetWaveHeightSmooth, 0x0055AA80);
	ZENGIN_REGISTER_METHOD(zCFFT, &zCFFT::CreateArray, 0x0055AC00);
	ZENGIN_REGISTER_METHOD(zCFFT, &zCFFT::FreeArray, 0x0055ACA0);

} // namespace Gothic_II_Addon
