namespace Gothic_II_Addon {

	ZENGIN_REGISTER_CLASS(zCFileCSV);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCFileCSV, &zCFileCSV::zCFileCSV_OnInit, void(zCFileCSV::*)(zSTRING const&), 0x0044E930);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCFileCSV, &zCFileCSV::zCFileCSV_OnInit, void(zCFileCSV::*)(), 0x0044EAF0);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::InitCSV, 0x0044EDF0);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::SetFormat, 0x0044EF10);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::AddNextField, 0x0044F050);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::AddNextHeader, 0x0044F1E0);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::WriteSet, 0x0044F390);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::GetNextField, 0x0044F550);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::ReadSet, 0x0044F980);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::ReadHeader, 0x0044F9D0);
	ZENGIN_REGISTER_METHOD(zCFileCSV, &zCFileCSV::WriteHeader, 0x0044FBB0);

} // namespace Gothic_II_Addon
