namespace Gothic_II_Addon {

	ZENGIN_REGISTER_CLASS(zCFile3DS);
	ZENGIN_REGISTER_METHOD(zCFile3DS, &zCFile3DS::Load3DS, 0x0055D660);
	ZENGIN_REGISTER_METHOD(zCFile3DS, &zCFile3DS::Save3DS, 0x0055F010);

	ZENGIN_REGISTER_CLASS(zCFileQuakeBSP);
	ZENGIN_REGISTER_METHOD(zCFileQuakeBSP, &zCFileQuakeBSP::zCFileQuakeBSP_OnInit, 0x00560BE0);
	ZENGIN_REGISTER_METHOD(zCFileQuakeBSP, &zCFileQuakeBSP::LoadQuakeBSP, 0x00560C10);

	ZENGIN_REGISTER_CLASS(zCFileBIN);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::zCFileBIN_OnInit, 0x00567F50);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinCreate, 0x00567FF0);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinClose, 0x00568020);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinStartChunk, 0x0056FFE0);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinEndChunk, 0x00570080);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinWriteSrcFileStats, 0x005875A0);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinWriteString, 0x005884C0);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinReadCompareSrcFileStats, 0x0058A970);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinWriteFloat, 0x0059D180);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinWriteInt, 0x0059D1A0);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinSkipChunk, 0x0059DDA0);
	ZENGIN_REGISTER_METHOD(zCFileBIN, &zCFileBIN::BinSetFile, 0x006270B0);

} // namespace Gothic_II_Addon
