namespace Gothic_II_Addon {

	ZENGIN_REGISTER_CLASS(zCGfx);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCGfx, &zCGfx::zCGfx_OnInit, void(zCGfx::*)(zSTRING const&), 0x0078A4B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCGfx, &zCGfx::zCGfx_OnInit, void(zCGfx::*)(int, int), 0x0078A670);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::LoadRaw, 0x0078AF50);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::Readbyte, 0x0078AFF0);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::LoadPcx, 0x0078B060);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::LoadTga, 0x0078B510);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::SaveRaw, 0x0078C7F0);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::Save, 0x0078C850);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::LoadGfx, 0x0078C9F0);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::GetSizex, 0x0078CD70);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::GetSizey, 0x0078CD80);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::GetDataPtr, 0x0078CD90);
	ZENGIN_REGISTER_METHOD(zCGfx, &zCGfx::GetPixel, 0x0078CDA0);

} // namespace Gothic_II_Addon
