namespace Gothic_II_Addon {

	ZENGIN_REGISTER_CLASS(zCMenuItem);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenuItem, &zCMenuItem::zCMenuItem_OnInit, void(zCMenuItem::*)(zSTRING const&), 0x004DEE20);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenuItem, &zCMenuItem::zCMenuItem_OnInit, void(zCMenuItem::*)(), 0x004DF030);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Release, 0x0047D620);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetSelItem, 0x004DE780);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Init, 0x004DF410);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::SetByScript, 0x004DF790);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetDimX, 0x004E0090);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetDimY, 0x004E0190);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::InitView, 0x004E0280);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Close, 0x004E0410);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetType, 0x004E0460);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenuItem, &zCMenuItem::SetName, void(zCMenuItem::*)(zSTRING const&), 0x004E0540);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetName, 0x004E0680);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetCoords, 0x004E0690);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetSelActionType, 0x004E06A0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetSelActionString, 0x004E06B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenuItem, &zCMenuItem::SetName, void(zCMenuItem::*)(zSTRING&), 0x004E06D0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Register, 0x004E0830);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Unregister, 0x004E09E0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::IsRegistered, 0x004E0B10);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::UpdateSize, 0x004E1200);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetEventFunc, 0x004E1BF0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::SetIsActive, 0x004E1C00);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::SetIsSelectable, 0x004E1D10);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetIsSelectable, 0x004E1D60);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::SetIsDisabled, 0x004E1DE0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetIsDisabled, 0x004E1DF0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::SetIsVisible, 0x004E1E30);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetIsVisible, 0x004E1E40);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::DrawItems, 0x004E1A20);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::InitMenuItem, 0x004E01F0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::ToggleValue, 0x004E0430);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Run, 0x004E14F0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::GetText, 0x004E0470);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenuItem, &zCMenuItem::SetText, void(zCMenuItem::*)(zSTRING const&, int, int), 0x004E0BB0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenuItem, &zCMenuItem::SetText, void(zCMenuItem::*)(zCArray<zSTRING>, int), 0x004E12D0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::SetMinValue, 0x004DED80);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::SetMaxValue, 0x004DED90);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Enter, 0x004E1490);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Leave, 0x004E14A0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Draw, 0x004E18C0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::DrawFront, 0x004E18E0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Show, 0x004E0360);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Hide, 0x004E03A0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::HasBeenCanceled, 0x004DEDA0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Open, 0x004E03E0);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::Input, 0x004E1550);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::InsertInWin, 0x004DFA90);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::RemoveFromWin, 0x004E0030);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::UpdateContent, 0x004E1A50);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::UpdateFX, 0x004E1A60);
	ZENGIN_REGISTER_METHOD(zCMenuItem, &zCMenuItem::HandleEvent, 0x004E14B0);

	ZENGIN_REGISTER_CLASS(zCMenuItemInput);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::zCMenuItemInput_OnInit, 0x004E1E80);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::SetValue, 0x004E20E0);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::GetValue, 0x004E2160);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::InitMenuItem, 0x004E2180);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::Run, 0x004E2360);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::Enter, 0x004DEDB0);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::Leave, 0x004DEDC0);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::HasBeenCanceled, 0x004DEDE0);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::InsertInWin, 0x004E2330);
	ZENGIN_REGISTER_METHOD(zCMenuItemInput, &zCMenuItemInput::HandleEvent, 0x004DEDD0);

	ZENGIN_REGISTER_CLASS(zCMenuItemText);
	ZENGIN_REGISTER_METHOD(zCMenuItemText, &zCMenuItemText::zCMenuItemText_OnInit, 0x004E26D0);
	ZENGIN_REGISTER_METHOD(zCMenuItemText, &zCMenuItemText::FormatMultiline, 0x004E2860);
	ZENGIN_REGISTER_METHOD(zCMenuItemText, &zCMenuItemText::DrawMultiline, 0x004E2BE0);
	ZENGIN_REGISTER_METHOD(zCMenuItemText, &zCMenuItemText::InitMenuItem, 0x004E3000);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenuItemText, &zCMenuItemText::SetText, void(zCMenuItemText::*)(zSTRING const&, int, int), 0x004E34F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenuItemText, &zCMenuItemText::SetText, void(zCMenuItemText::*)(zCArray<zSTRING>, int), 0x004E37B0);
	ZENGIN_REGISTER_METHOD(zCMenuItemText, &zCMenuItemText::DrawFront, 0x004E2810);
	ZENGIN_REGISTER_METHOD(zCMenuItemText, &zCMenuItemText::SetEnum, 0x004E31C0);
	ZENGIN_REGISTER_METHOD(zCMenuItemText, &zCMenuItemText::HandleEvent, 0x004E3340);

	ZENGIN_REGISTER_CLASS(zCMenuItemSlider);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::zCMenuItemSlider_OnInit, 0x004E3810);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::SetValue, 0x004E3F70);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::GetValue, 0x004E3FF0);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::InitMenuItem, 0x004E3C50);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::ToggleValue, 0x004E38D0);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::InsertInWin, 0x004E3D10);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::RemoveFromWin, 0x004E3EE0);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::SetIsActive, 0x004DEDF0);
	ZENGIN_REGISTER_METHOD(zCMenuItemSlider, &zCMenuItemSlider::HandleEvent, 0x004DEE10);

	ZENGIN_REGISTER_CLASS(zCMenuItemButton);
	ZENGIN_REGISTER_METHOD(zCMenuItemButton, &zCMenuItemButton::zCMenuItemButton_OnInit, 0x004E52D0);
	ZENGIN_REGISTER_METHOD(zCMenuItemButton, &zCMenuItemButton::Toggle, 0x004E5700);
	ZENGIN_REGISTER_METHOD(zCMenuItemButton, &zCMenuItemButton::InitMenuItem, 0x004E5530);
	ZENGIN_REGISTER_METHOD(zCMenuItemButton, &zCMenuItemButton::Run, 0x004E5900);
	ZENGIN_REGISTER_METHOD(zCMenuItemButton, &zCMenuItemButton::InsertInWin, 0x004E5B70);
	ZENGIN_REGISTER_METHOD(zCMenuItemButton, &zCMenuItemButton::RemoveFromWin, 0x004E5BB0);

	ZENGIN_REGISTER_CLASS(zCMenuItemChoice);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::zCMenuItemChoice_OnInit, 0x004E4000);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::SetOptionByString, 0x004E4310);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::GetStringByOption, 0x004E4750);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::Resize, 0x004E4B30);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::GetNumOptions, 0x004E4E50);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::InitMenuItem, 0x004E51B0);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::ToggleValue, 0x004E4080);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::GetText, 0x004E5030);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::Draw, 0x004E4C00);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::DrawFront, 0x004E4C20);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::InsertInWin, 0x004E48E0);
	ZENGIN_REGISTER_METHOD(zCMenuItemChoice, &zCMenuItemChoice::RemoveFromWin, 0x004E4AA0);

	ZENGIN_REGISTER_CLASS(zTMenuItemListElement);
	ZENGIN_REGISTER_METHOD(zTMenuItemListElement, &zTMenuItemListElement::zTMenuItemListElement_OnInit, 0x004E71C0);

	ZENGIN_REGISTER_CLASS(zCMenuItemList);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::zCMenuItemList_OnInit, 0x004E5C70);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::DeleteContent, 0x004E5EC0);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::InsertEnd, 0x004E5F10);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::InsertFront, 0x004E6120);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::ShowContent, 0x004E6AB0);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::JumpToNextEntry, 0x004E6C60);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::JumpToPrevEntry, 0x004E6C80);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::JumpToTopEntry, 0x004E6CA0);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::JumpToLastEntry, 0x004E6CC0);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::InitMenuItem, 0x004E5E20);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::Run, 0x004E5D90);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::Enter, 0x004E6520);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::Leave, 0x004E6530);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::DrawFront, 0x004E6550);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::Show, 0x004E5E30);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::Hide, 0x004E5E80);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::InsertInWin, 0x004E6310);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::RemoveFromWin, 0x004E6470);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::UpdateContent, 0x004E6540);
	ZENGIN_REGISTER_METHOD(zCMenuItemList, &zCMenuItemList::HandleEvent, 0x004E6860);

} // namespace Gothic_II_Addon
