namespace Gothic_II_Addon {

	ZENGIN_REGISTER_CLASS(zCMenu);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenu, &zCMenu::zCMenu_OnInit, void(zCMenu::*)(), 0x004DA470);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMenu, &zCMenu::zCMenu_OnInit, void(zCMenu::*)(zSTRING const&), 0x004DA610);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::InitValues, 0x004DA950);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::Release, 0x004DAB80);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::Register, 0x004DAE00);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::Unregister, 0x004DB020);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::IsRegistered, 0x004DB0C0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::ClearAllEvents, 0x004DB5A0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::PreviousOption, 0x004DB5C0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::NextOption, 0x004DB690);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::RestartMusicTheme, 0x004DB760);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::ForceSelAction, 0x004DBE20);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::UpdateWindowGeometry, 0x004DC070);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::PrintInformation, 0x004DCD00);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::GetBackWorld, 0x004DDD10);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::GetBackDatFile, 0x004DDD50);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::GetActiveItem, 0x004DDD80);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::GetNumberOfActiveItem, 0x004DDD90);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::SetActiveItem, 0x004DDE00);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::GetName, 0x004DDF60);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::SetName, 0x004DDF70);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::HandleEvent, 0x004DBB70);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::HandleEnterItem, 0x004DE0D0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::HandleLeaveItem, 0x004DE0E0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::HandleActivateItem, 0x004DE0F0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::Run, 0x004DB9A0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::Enter, 0x004DB780);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::Leave, 0x004DB910);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::Render, 0x004DDC20);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::RedrawItems, 0x004DCCD0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::HandleFrame, 0x004DC1C0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::Activate, 0x004DBFD0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::ScreenInit, 0x004DCDE0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::ScreenDone, 0x004DD9E0);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::HandleAction, 0x004DC250);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::HandleSelAction, 0x004DC430);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::SetByScript, 0x004DB320);
	ZENGIN_REGISTER_METHOD(zCMenu, &zCMenu::ExecCommand, 0x004DCAC0);

} // namespace Gothic_II_Addon
