namespace Gothic_II_Addon {

	ZENGIN_REGISTER_CLASS(zCModelMeshLib);
	ZENGIN_REGISTER_METHOD(zCModelMeshLib, &zCModelMeshLib::zCModelMeshLib_OnInit, 0x00593B30);
	ZENGIN_REGISTER_METHOD(zCModelMeshLib, &zCModelMeshLib::ReleaseData, 0x0059F090);
	ZENGIN_REGISTER_METHOD(zCModelMeshLib, &zCModelMeshLib::AllocNumNodeVisuals, 0x0059F100);
	ZENGIN_REGISTER_METHOD(zCModelMeshLib, &zCModelMeshLib::AddMeshSoftSkin, 0x0059F170);
	ZENGIN_REGISTER_METHOD(zCModelMeshLib, &zCModelMeshLib::AddNodeVisual, 0x0059F250);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelMeshLib, &zCModelMeshLib::ApplyToModel, void(zCModelMeshLib::*)(zCModel*), 0x0059F350);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelMeshLib, &zCModelMeshLib::ApplyToModel, void(zCModelMeshLib::*)(zCModelPrototype*), 0x0059F4C0);
	ZENGIN_REGISTER_METHOD(zCModelMeshLib, &zCModelMeshLib::RemoveFromModel, 0x0059F620);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelMeshLib, &zCModelMeshLib::BuildFromModel, void(zCModelMeshLib::*)(zCModelPrototype*), 0x0059F710);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelMeshLib, &zCModelMeshLib::BuildFromModel, void(zCModelMeshLib::*)(zCModel*), 0x0059F900);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelMeshLib, &zCModelMeshLib::SaveMDM, void(zCModelMeshLib::*)(zCModelPrototype*), 0x0059FB30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelMeshLib, &zCModelMeshLib::SaveMDM, void(zCModelMeshLib::*)(zCFileBIN&, zCModelPrototype*), 0x0059FD40);
	ZENGIN_REGISTER_METHOD(zCModelMeshLib, &zCModelMeshLib::_GetClassDef, 0x0057EA30);

	ZENGIN_REGISTER_CLASS(zCModelAniEvent);
	ZENGIN_REGISTER_METHOD(zCModelAniEvent, &zCModelAniEvent::zCModelAniEvent_OnInit, 0x00588280);
	ZENGIN_REGISTER_METHOD(zCModelAniEvent, &zCModelAniEvent::Save, 0x00588400);
	ZENGIN_REGISTER_METHOD(zCModelAniEvent, &zCModelAniEvent::Load, 0x00588560);

	ZENGIN_REGISTER_CLASS(zCModelNode);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelNode, &zCModelNode::zCModelNode_OnInit, void(zCModelNode::*)(), 0x005849C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelNode, &zCModelNode::zCModelNode_OnInit, void(zCModelNode::*)(zCModelNode const&), 0x00584B00);
	ZENGIN_REGISTER_METHOD(zCModelNode, &zCModelNode::SetNodeVisualS, 0x00584D30);

	ZENGIN_REGISTER_CLASS(zCModelAni);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::zCModelAni_OnInit, 0x00585120);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::PrecacheAniEventData, 0x00585530);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::GetAniVelocity, 0x00585600);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::GetAniTranslation, 0x00585780);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::AddTrafoMatrix, 0x005858C0);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::GetQuat, 0x00585D60);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::GetTrans, 0x00585DC0);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::SetTrans, 0x00585E60);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::SetQuat, 0x00585EE0);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::AddNodeList, 0x00585F80);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::SetFlags, 0x00585FF0);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::SetBlendingSec, 0x005860A0);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::GetBlendingSec, 0x00586100);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::CorrectRootNodeIdleMovement, 0x00586160);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::CalcInPlaceFlag, 0x005862C0);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::ResolveAlias, 0x005864A0);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::ResolveComb, 0x00586780);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::SaveMAN, 0x00586E80);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::LoadMAN, 0x00587740);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::GetAniName, 0x0059D160);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::GetAniType, 0x0059D170);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::GetAniID, 0x006A9800);
	ZENGIN_REGISTER_METHOD(zCModelAni, &zCModelAni::_GetClassDef, 0x005852C0);

	ZENGIN_REGISTER_CLASS(zCModelPrototype);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::zCModelPrototype_OnInit, 0x00588610);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::Init, 0x00588850);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::Clear, 0x00588C50);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReleaseMeshSoftSkinList, 0x00588DF0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReleaseMeshes, 0x00588E50);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::Release, 0x00588EE0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::GetModelProtoFileName, 0x00588F30);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::SetModelProtoName, 0x00588F40);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::SetFileSourceType, 0x005890D0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::PrepareAsModelProtoOverlay, 0x005894A0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::CalcNodeListChecksum, 0x00589870);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::CollectNodeMeshes, 0x005898D0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::SearchNode, 0x00589AF0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::FindMeshTreeNode, 0x00589BA0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::FindMeshTreeNodeIndex, 0x00589C50);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::FindNodeListIndex, 0x00589D10);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::AddAni, 0x00589DB0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::SearchAniIndex, 0x00589FC0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::SearchAni, 0x0058A090);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::DescribeTree, 0x0058A0B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelPrototype, &zCModelPrototype::LoadMDH, int(zCModelPrototype::*)(zSTRING const&), 0x0058A300);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelPrototype, &zCModelPrototype::LoadMDH, int(zCModelPrototype::*)(zCFileBIN&), 0x0058A560);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelPrototype, &zCModelPrototype::SaveMDH, void(zCModelPrototype::*)(), 0x0058ABC0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelPrototype, &zCModelPrototype::SaveMDH, void(zCModelPrototype::*)(zCFileBIN&), 0x0058ADC0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ConvertVec3, 0x0058B2E0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ConvertAngle, 0x0058B300);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::SkipBlock, 0x0058B310);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::SkipBlockCmt, 0x0058B390);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadComment, 0x0058B460);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadScene, 0x0058B470);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadTriple, 0x0058B810);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadNodeTM, 0x0058BA00);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadVertexList, 0x0058BEA0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadFaceList, 0x0058C0D0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadTVertexList, 0x0058C5D0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadTFaceList, 0x0058C7D0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadSoftSkinVertList, 0x0058CA40);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadMesh, 0x0058DC00);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadMeshAnimation, 0x0058DFE0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadPosTrack, 0x0058E160);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadRotTrack, 0x0058E340);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadTMAnimation, 0x0058E5F0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::LocalizeTrafos, 0x0058EC30);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadMapDiffuse, 0x0058ED60);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadMaterial, 0x0058F1D0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadWireframeColor, 0x0058F840);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::AssignMeshNodeMaterials, 0x0058FAE0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::TransformNodeVisual, 0x0058FBD0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ProcessMeshNode, 0x0058FC30);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadGeomobject, 0x00590040);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadMaterialList, 0x005915C0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::Load3DSMAXAsc, 0x00591850);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::CalcAniBBox, 0x005928D0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ResolveReferences, 0x00592E00);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::SkipBlockMDS, 0x00593100);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadMeshAndTreeMSB, 0x00593180);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadMeshAndTree, 0x005935C0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::RegisterMesh, 0x00593C40);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadAniEnumMSB, 0x00593ED0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadAniEnum, 0x00596C00);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadModelMSB, 0x0059D250);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::ReadModel, 0x0059D4C0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::LoadModelScriptMSB, 0x0059D7B0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::LoadModelScript, 0x0059DDD0);
	ZENGIN_REGISTER_METHOD(zCModelPrototype, &zCModelPrototype::LoadModelASC, 0x0059E760);

	ZENGIN_REGISTER_CLASS(zCModelAniActive);
	ZENGIN_REGISTER_METHOD(zCModelAniActive, &zCModelAniActive::zCModelAniActive_OnInit, 0x00576B00);
	ZENGIN_REGISTER_METHOD(zCModelAniActive, &zCModelAniActive::SetDirection, 0x00576C10);
	ZENGIN_REGISTER_METHOD(zCModelAniActive, &zCModelAniActive::GetProgressPercent, 0x00576C60);
	ZENGIN_REGISTER_METHOD(zCModelAniActive, &zCModelAniActive::SetProgressPercent, 0x00576CA0);
	ZENGIN_REGISTER_METHOD(zCModelAniActive, &zCModelAniActive::SetActFrame, 0x00576CF0);
	ZENGIN_REGISTER_METHOD(zCModelAniActive, &zCModelAniActive::DoCombineAni, 0x0057FDB0);

	ZENGIN_REGISTER_CLASS(zCModelTexAniState);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::zCModelTexAniState_OnInit, 0x00576D40);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::DeleteTexList, 0x00576D80);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::UpdateTexList, 0x00576DA0);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::SetChannelVariation, 0x00576DE0);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::BuildTexListFromMeshLib, 0x00576E50);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::BuildTexListFromMesh, 0x00576ED0);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::BuildTexListFromProgMesh, 0x00577060);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::AddTexListFromMeshLib, 0x005771D0);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::AddTexListFromMesh, 0x00577430);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::AddTexListFromProgMesh, 0x00577590);
	ZENGIN_REGISTER_METHOD(zCModelTexAniState, &zCModelTexAniState::FinishTexList, 0x005776E0);

	ZENGIN_REGISTER_CLASS(zCModelNodeInst);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelNodeInst, &zCModelNodeInst::zCModelNodeInst_OnInit, void(zCModelNodeInst::*)(), 0x00577870);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModelNodeInst, &zCModelNodeInst::zCModelNodeInst_OnInit, void(zCModelNodeInst::*)(zCModelNode*), 0x00577940);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::Init, 0x00577AB0);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::InitByModelProtoNode, 0x00577B40);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::SetNodeVisualS, 0x00577BF0);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::AddNodeAni, 0x0057EAF0);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::RemoveAllNodeAnis, 0x0057ED20);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::RemoveNodeAni, 0x0057ED30);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::FindMasterAni, 0x0057EE20);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::FadeOutNodeAni, 0x0057EE90);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::CalcWeights, 0x0057F470);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::AddToNodeAniWeight, 0x0057F6B0);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::CalcBlending, 0x0057F720);
	ZENGIN_REGISTER_METHOD(zCModelNodeInst, &zCModelNodeInst::GetNodeAniListIndex, 0x0057F8B0);

	ZENGIN_REGISTER_CLASS(zTAniAttachment);
	ZENGIN_REGISTER_METHOD(zTAniAttachment, &zTAniAttachment::zTAniAttachment_OnInit, 0x00583360);

	ZENGIN_REGISTER_CLASS(zCModel);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::zCModel_OnInit, 0x00578240);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetAniFromAniID, 0x00472F50);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::IsAniActive, 0x00472F90);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::Init, 0x00577FD0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CopyProtoNodeList, 0x00578400);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::ApplyModelProtoOverlay, int(zCModel::*)(zSTRING const&), 0x005787F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::ApplyModelProtoOverlay, int(zCModel::*)(zCModelPrototype*), 0x00578840);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::HasAppliedModelProtoOverlay, int(zCModel::*)(zCModelPrototype*) const, 0x00578A90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::HasAppliedModelProtoOverlay, int(zCModel::*)(zSTRING const&) const, 0x00578AC0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::RemoveModelProtoOverlay, void(zCModel::*)(zSTRING const&), 0x00578C40);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::RemoveModelProtoOverlay, void(zCModel::*)(zCModelPrototype*), 0x00578E40);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CalcNodeListBBoxWorld, 0x00578FC0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetBBox3DNodeWorld, 0x005790F0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetNodePositionWorld, 0x00579140);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CalcModelBBox3DWorld, 0x00579170);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetNodeVisual, 0x005792A0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetDynLightMode, 0x005792D0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetupLowestLOD, 0x005792F0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetLowestLODNumPolys, 0x00579490);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetLowestLODPoly, 0x005794B0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetMaterial, 0x005794F0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetNumMaterials, 0x00579530);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RenderNodeList, 0x00579560);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CheckNodeCollisionList, 0x0057A7D0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CheckNodeCollision, 0x0057A870);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetTrafoNodeToModel, 0x0057A9C0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetRandAnisEnabled, 0x0057AAF0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::GetActiveAni, zCModelAniActive*(zCModel::*)(int) const, 0x0057AB60);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::GetActiveAni, zCModelAniActive*(zCModel::*)(zCModelAni*) const, 0x0057ABA0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::StopAni, void(zCModel::*)(int), 0x0057ABE0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::StopAni, void(zCModel::*)(zCModelAni*), 0x0057AC60);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::StopAni, void(zCModel::*)(zCModelAniActive*), 0x0057ACB0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetAniTransLerp, 0x0057AE70);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::StartAni, void(zCModel::*)(zSTRING const&, int), 0x0057AF70);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::StartAni, void(zCModel::*)(int, int), 0x0057B070);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::StartAni, void(zCModel::*)(zCModelAni*, int), 0x0057B0C0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::AssertActiveAniListAlloced, 0x0057B770);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::DoAniEvents, 0x0057B890);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::AdvanceAni, 0x0057C7D0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::AdvanceAnis, 0x0057CA90);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetModelScale, 0x0057DC30);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::IsStateActive, 0x0057DDA0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SearchNode, 0x0057DFF0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetNodeMeshTexture, 0x0057E0A0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetMeshLibTexture, 0x0057E1D0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RemoveMeshLibAll, 0x0057E3D0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RemoveMeshLib, 0x0057E400);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::ApplyMeshLib, 0x0057E610);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::UpdateMeshLibTexAniState, 0x0057EA70);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::FadeOutAni, void(zCModel::*)(int), 0x0057EF50);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::FadeOutAni, void(zCModel::*)(zCModelAni*), 0x0057EFE0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::FadeOutAni, void(zCModel::*)(zCModelAniActive*), 0x0057F020);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::FadeOutAnisLayerRange, 0x0057F1F0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::StopAnisLayerRange, 0x0057F240);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::GetProgressPercent, float(zCModel::*)(zSTRING const&) const, 0x0057F290);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCModel, &zCModel::GetProgressPercent, float(zCModel::*)(int) const, 0x0057F340);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetCombineAniXY, 0x0057F3B0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetCombineAniXY, 0x0057F400);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CalcNodeListAniBlending, 0x0057F880);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CalcTransBlending, 0x0057F8E0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::AttachChildVobToNode, 0x005806A0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RemoveChildVobFromNode, 0x005807F0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetAttachedNodeVob, 0x00580870);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RemoveAllChildVobsFromNode, 0x005808B0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::UpdateAttachedVobs, 0x00580900);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RemoveStartedVobFX, 0x00580A50);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetVelocityRing, 0x00580B00);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::ResetVelocity, 0x00580B60);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetAniMinMaxWeight, 0x00580BF0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::PrintStatus, 0x00580E90);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CorrectAniFreezer, 0x005815E0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::psb_WriteAniBlock, 0x00581850);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::psb_ReadAniBlock, 0x005819E0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::PackStateBinary, 0x00581C30);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::UnpackStateBinary, 0x00581F80);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::ShowAniListAdd, 0x00582700);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::ShowAniList, 0x00582770);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SearchAniAttachList, 0x005833A0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RemoveAniAttachment, 0x00583420);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RemoveAllAniAttachments, 0x00583570);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RemoveAllVobFX, 0x005835C0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetCreateAniAttachment, 0x00583650);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::DeleteRandAniList, 0x005838A0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::InsertRandAni, 0x00583930);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetRandAniFreq, 0x00583A30);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetRandAniFreq, 0x00583AC0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::RecalcRootPosLocal, 0x00583AE0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetAniIDFromAniName, 0x00612070);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::_GetClassDef, 0x005765B0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::Render, 0x0057A4E0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::IsBBox3DLocal, 0x005765C0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetBBox3D, 0x0057DF20);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetVisualName, 0x0057DF60);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::SetVisualUsedBy, 0x005786C0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetRenderSortKey, 0x005827E0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::CanTraceRay, 0x005765D0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::TraceRay, 0x00582800);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::HostVobRemovedFromWorld, 0x0057B7E0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetFileExtension, 0x00578740);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::LoadVisualVirtual, 0x00578760);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::StartAnimation, 0x005765E0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::StopAnimation, 0x005765F0);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::IsAnimationActive, 0x00576690);
	ZENGIN_REGISTER_METHOD(zCModel, &zCModel::GetAnyAnimation, 0x0057AE20);

	ZENGIN_REGISTER_CLASS(zCModelConvertFileHandler);
	ZENGIN_REGISTER_METHOD(zCModelConvertFileHandler, &zCModelConvertFileHandler::zCModelConvertFileHandler_OnInit, 0x005A1610);
	ZENGIN_REGISTER_METHOD(zCModelConvertFileHandler, &zCModelConvertFileHandler::HandleFile, 0x005A1740);

} // namespace Gothic_II_Addon
