namespace Gothic_II_Addon {

	ZENGIN_REGISTER_CLASS(zCPar_TreeNode);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPar_TreeNode, &zCPar_TreeNode::zCPar_TreeNode_OnInit, void(zCPar_TreeNode::*)(), 0x00797980);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPar_TreeNode, &zCPar_TreeNode::zCPar_TreeNode_OnInit, void(zCPar_TreeNode::*)(int, int), 0x007979C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCPar_TreeNode, &zCPar_TreeNode::zCPar_TreeNode_OnInit, void(zCPar_TreeNode::*)(int, zSTRING&, int), 0x00797A10);
	ZENGIN_REGISTER_METHOD(zCPar_TreeNode, &zCPar_TreeNode::SetLeft, 0x00797C60);
	ZENGIN_REGISTER_METHOD(zCPar_TreeNode, &zCPar_TreeNode::SetRight, 0x00797C70);
	ZENGIN_REGISTER_METHOD(zCPar_TreeNode, &zCPar_TreeNode::SetNext, 0x00797C80);

	ZENGIN_REGISTER_CLASS(zCPar_File);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::zCPar_File_OnInit, 0x0078D020);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::IsNewerDate, 0x0078D0F0);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::IsExactDate, 0x0078D170);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::SetFileNumber, 0x0078D1F0);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::GetFileNumber, 0x0078D200);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::GetName, 0x0078D210);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::EnableTreeLoad, 0x0078D260);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::Load, 0x0078D270);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::GetStartAddress, 0x0078D4F0);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::GetEndAddress, 0x0078D500);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::Dispose, 0x0078D510);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::SetTree, 0x0078D530);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::GetTree, 0x0078D570);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::SetLabelCount, 0x0078D580);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::GetLabelCount, 0x0078D590);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::SaveTree, 0x0078D5A0);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::SaveTreeNode, 0x0078D820);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::LoadTreeNode, 0x0078D990);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::LoadTree, 0x0078DAC0);
	ZENGIN_REGISTER_METHOD(zCPar_File, &zCPar_File::DeleteTree, 0x0078DE90);

	ZENGIN_REGISTER_CLASS(zCParser);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::zCParser_OnInit, 0x0078DED0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SetMessageFunc, 0x0078E250);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SetStopOnError, 0x0078E260);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::Error, void(zCParser::*)(zSTRING&, int), 0x0078E270);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::Message, 0x0078E5F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::Error, int(zCParser::*)(), 0x0078E730);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SaveDat, 0x0078E740);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::LoadDat, 0x0078E900);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::Parse, 0x0078EBA0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ParseSource, 0x0078EE20);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ParseFile, 0x0078F660);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ParseBlock, 0x0078FE30);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::CreatePCode, 0x007900E0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ShowSymbols, 0x00790810);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::PushTree, 0x00790820);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::PushOnStack, 0x00790840);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SolveLabels, 0x007915F0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::MergeFile, 0x00791650);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::PopDataValue, 0x007918B0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::PopFloatValue, 0x007918E0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::PopVarAddress, 0x00791910);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::PopString, 0x00791940);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DoStack, 0x00791960);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::CallFunc, void*(zCParser::*)(zSTRING const&), 0x007929D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::CallFunc, void*(__cdecl zCParser::*)(int, ...), 0x007929F0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetCurrentFunc, 0x00792F10);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::CreateInstance, int(zCParser::*)(zSTRING&, void*), 0x00792F20);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::CreateInstance, int(zCParser::*)(int, void*), 0x00792FA0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::CreatePrototype, int(zCParser::*)(zSTRING&, void*), 0x00793010);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::CreatePrototype, int(zCParser::*)(int, void*), 0x00793090);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::Reset, 0x00793100);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SetPercentDone, 0x00793270);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::CreateHelpers, 0x007932D0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::EnableTreeSave, 0x00793440);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::EnableDatSave, 0x00793450);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::EnableTreeLoad, 0x00793460);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetIndex, 0x00793470);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::MatchClass, 0x00793530);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetBaseClass, int(zCParser::*)(zCPar_Symbol*), 0x007935B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetBaseClass, int(zCParser::*)(int), 0x00793610);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetBase, 0x00793670);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetPrototype, 0x007936C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetInstance, int(zCParser::*)(int, int), 0x00793730);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetSymbolInfo, zSTRING(zCParser::*)(int, int&, int&), 0x007937F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetSymbolInfo, zCPar_Symbol*(zCParser::*)(int), 0x007938B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetSymbol, zCPar_Symbol*(zCParser::*)(int), 0x007938C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetSymbol, zCPar_Symbol*(zCParser::*)(zSTRING const&), 0x007938D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetClassVarInfo, zSTRING(zCParser::*)(int, int, int&, int&), 0x00793990);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetClassVarInfo, void(zCParser::*)(int, zSTRING&, int&, int&), 0x00793BB0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetText, zSTRING(zCParser::*)(zSTRING&, int), 0x00793D70);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetText, zSTRING(zCParser::*)(int, int), 0x00793DB0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetInt, 0x00793E90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetInstanceValue, zSTRING(zCParser::*)(zSTRING&, int, void*, int), 0x00793EE0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetInstanceValue, zSTRING(zCParser::*)(int, int, void*, int), 0x00793FD0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::IsValid, 0x007942E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::CheckClassSize, int(zCParser::*)(zSTRING&, int), 0x00794450);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::CheckClassSize, int(zCParser::*)(int, int), 0x00794470);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::AddClassOffset, 0x00794730);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::SetInstance, int(zCParser::*)(zSTRING const&, void*), 0x00794870);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::SetInstance, int(zCParser::*)(int, void*), 0x00794910);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::AutoCompletion, 0x00794950);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetNumFiles, 0x00794B60);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetFileName, 0x00794B70);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::IsStackFull, 0x00794C10);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetLastErrorLine, 0x00794C20);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::Reparse, 0x00794C30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::SaveInstance, int(zCParser::*)(zSTRING&, void*), 0x00794D40);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::SaveInstance, int(zCParser::*)(int, void*), 0x00794D70);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::CloseViews, 0x00795A30);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ShowCode, 0x00795A60);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SaveInfoFile, 0x00795BB0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SetInfoFile, 0x00796200);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::IsInAdditionalInfo, 0x00796390);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::WriteAdditionalInfo, 0x00796540);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ClearAllInstanceRefs, 0x007968D0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ClearInstanceRefs, 0x00796940);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ResetGlobalVars, 0x007969C0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::CreateVarReferenceList, 0x00796A40);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ResetWithVarReferenceList, 0x00796BC0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SaveGlobalVars, 0x00796C40);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::LoadGlobalVars, 0x00797170);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetOperatorString, 0x00797D80);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::FindNext, 0x00798310);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::PrevWord, 0x00798480);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ReadWord, 0x007984B0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::Match, 0x00798720);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ReadVarType, 0x007988B0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ReadFuncType, 0x00798AE0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ReadInt, 0x00798D00);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ReadFloat, 0x00798FA0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ReadString, 0x007992E0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ReadArray, 0x007995C0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::CreateLeaf, 0x007997C0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::CreateStringLeaf, 0x00799820);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::CreateFloatLeaf, 0x00799A70);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetNextToken, 0x00799C10);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::Parse_Expression_Primary, 0x0079A390);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::Parse_Expression, 0x0079A940);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ParseExpressionEx, 0x0079AB50);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ParseExpression, 0x0079ABC0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::EvalLeaf, 0x0079ABE0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareVar, 0x0079B0A0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareClass, 0x0079C3D0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareInstance, 0x0079C5A0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclarePrototype, 0x0079CD80);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareIf, 0x0079D270);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareAssign, 0x0079D6D0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareAssignFunc, 0x0079DE50);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareFunc, 0x0079E140);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareReturn, 0x0079E5D0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DeclareFuncCall, 0x0079E7B0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::SearchFuncWithStartAddress, 0x0079F180);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetNextCommand, 0x0079F1F0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ShowPCodeSpy, 0x0079FE10);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::ShowPCode, 0x0079FF40);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DefineExternal, 0x007A0190);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::DefineExternalVar, 0x007A0550);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetParameter, void(zCParser::*)(int&), 0x007A0760);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetParameter, void(zCParser::*)(float&), 0x007A0770);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetParameter, void(zCParser::*)(zSTRING&), 0x007A07B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::GetInstance, void*(zCParser::*)(), 0x007A08F0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetInstanceAndIndex, 0x007A0920);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::SetReturn, void(zCParser::*)(int), 0x007A0960);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::SetReturn, void(zCParser::*)(float), 0x007A0980);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::SetReturn, void(zCParser::*)(void*), 0x007A09A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCParser, &zCParser::SetReturn, void(zCParser::*)(zSTRING&), 0x007A09D0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::FindInstanceVar, 0x007A09F0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::GetLastInstance, 0x007A0BD0);
	ZENGIN_REGISTER_METHOD(zCParser, &zCParser::FindIndex, 0x007A0BE0);

} // namespace Gothic_II_Addon
