namespace Gothic_II_Addon {

	ZENGIN_REGISTER_CLASS(zSTRING);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(), 0x00402AF0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(char const* vec), 0x004010C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(zSTRING const&), 0x00416500);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(int val), 0x00435870);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(float val, int rad), 0x00435970);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(double val, int rad), 0x00454680);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(unsigned long val), 0x00461E90);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(char val), 0x0051AC80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(long val), 0x006CFE50);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::zSTRING_OnInit, void(zSTRING::*)(zSTRING const* val), 0x007928D0);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::ToChar, 0x004639D0);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Clear, 0x0059D010);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::IsEmpty, 0x00674210);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Lower, 0x0046A9F0);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Upper, 0x0046AB00);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::UpperFirstLowerRest, 0x0046AC10);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Align, 0x0046AD60);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::PickWord, 0x0046AF80);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::PickWordPos, 0x0046B1D0);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::PickWord_Old, 0x0046B340);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Insert, 0x0046B400);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Inserted, 0x0046B520);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Overwrite, 0x0046B6A0);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Overwritten, 0x0046B890);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::DeleteRight, 0x0046B990);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Delete, int(zSTRING::*)(unsigned int, unsigned long), 0x0046BAA0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Deleted, zSTRING(zSTRING::*)(unsigned int, unsigned long) const, 0x0046BBB0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Delete, int(zSTRING::*)(zSTRING const&, zTSTR_KIND), 0x0046BCF0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Deleted, zSTRING(zSTRING::*)(zSTRING const&, zTSTR_KIND) const, 0x0046BEE0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Copied, zSTRING(zSTRING::*)(unsigned int, unsigned long) const, 0x0046C170);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Copy, int(zSTRING::*)(zSTRING const&, zTSTR_KIND const&), 0x0046C2D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Copy, int(zSTRING::*)(unsigned int index, unsigned long length), 0x0046BFC0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Copied, zSTRING(zSTRING::*)(zSTRING const&, zTSTR_KIND const&) const, 0x0046C550);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::TrimLeft, 0x0046C630);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::TrimRight, 0x0046C770);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Search, int(zSTRING::*)(int, char const*, unsigned int) const, 0x0046C920);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::SearchRev, 0x0046CA20);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Sprintf, 0x0046CC60);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Search, int(zSTRING::*)(zSTRING const&, unsigned int) const, 0x00492680);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::ToFloat, 0x004936C0);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::ToInt, 0x0059D0F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zSTRING, &zSTRING::Search, int(zSTRING::*)(char const*, unsigned int) const, 0x0059D110);
	ZENGIN_REGISTER_METHOD(zSTRING, &zSTRING::Init, 0x006D9B80);

} // namespace Gothic_II_Addon
