namespace Gothic_II_Addon {

	ZENGIN_REGISTER_CLASS(zCOLOR);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCOLOR, &zCOLOR::zCOLOR_OnInit, void(zCOLOR::*)(int), 0x00401F20);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCOLOR, &zCOLOR::zCOLOR_OnInit, void(zCOLOR::*)(unsigned char, unsigned char, unsigned char, unsigned char), 0x0078AEF0);
	ZENGIN_REGISTER_METHOD(zCOLOR, &zCOLOR::Reset, 0x00572900);
	ZENGIN_REGISTER_METHOD(zCOLOR, &zCOLOR::GetDescription, 0x005FABA0);
	ZENGIN_REGISTER_METHOD(zCOLOR, &zCOLOR::SetByDescription, 0x005FAF10);
	ZENGIN_REGISTER_METHOD(zCOLOR, &zCOLOR::GetDescriptionRGB, 0x005FB190);
	ZENGIN_REGISTER_METHOD(zCOLOR, &zCOLOR::SetRGB, 0x0062A740);

	ZENGIN_REGISTER_CLASS(zTPlane);
	ZENGIN_REGISTER_METHOD(zTPlane, &zTPlane::CalcSignbits, 0x0054B1A0);
	ZENGIN_REGISTER_METHOD(zTPlane, &zTPlane::ClassifyPointBSPBuild, 0x005FB440);
	ZENGIN_REGISTER_METHOD(zTPlane, &zTPlane::Print, 0x005FB490);
	ZENGIN_REGISTER_METHOD(zTPlane, &zTPlane::Calc, 0x005FB870);
	ZENGIN_REGISTER_METHOD(zTPlane, &zTPlane::GetOriginUpRight, 0x005FB950);

} // namespace Gothic_II_Addon
