namespace Gothic_II_Addon {

	ZENGIN_REGISTER_CLASS(zCVisual);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::zCVisual_OnInit, 0x00606660);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::AddNextLODVisual, 0x00606820);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::AddEndLODVisual, 0x00606850);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::_GetClassDef, 0x004CA040);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::IsBBox3DLocal, 0x00566FF0);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::GetOBBox3D, 0x004CA050);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::GetVisualDied, 0x004CA060);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::SetVisualUsedBy, 0x00567000);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::DynLightVisual, 0x004CA070);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::GetRenderSortKey, 0x004CA080);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::CanTraceRay, 0x004CA090);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::TraceRay, 0x006068E0);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::HostVobRemovedFromWorld, 0x004CA0A0);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::HostVobAddedToWorld, 0x004CA0B0);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::GetFileExtension, 0x004CA0C0);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::GetLODVisualAndAlpha, 0x00606880);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::GetAlphaTestingEnabled, 0x004CA0D0);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::SetAlphaTestingEnabled, 0x004CA0E0);
	ZENGIN_REGISTER_METHOD(zCVisual, &zCVisual::LoadVisualVirtual, 0x004CA0F0);

	ZENGIN_REGISTER_CLASS(zCVisualAnimate);
	ZENGIN_REGISTER_METHOD(zCVisualAnimate, &zCVisualAnimate::_GetClassDef, 0x00576580);

	ZENGIN_REGISTER_CLASS(zCDecal);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::zCDecal_OnInit, 0x00556570);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCDecal, &zCDecal::SetTexture, void(zCDecal::*)(zSTRING&), 0x00556950);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCDecal, &zCDecal::SetTexture, void(zCDecal::*)(zCTexture*), 0x00556960);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::SetDecalDim, 0x00556970);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::_GetClassDef, 0x00556550);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::Archive, 0x00556D70);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::Unarchive, 0x00556E60);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::Render, 0x00556990);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::IsBBox3DLocal, 0x00556560);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::GetBBox3D, 0x00556B30);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::GetVisualName, 0x00556B80);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::SetVisualUsedBy, 0x00556B10);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::DynLightVisual, 0x00556C60);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::GetRenderSortKey, 0x00556940);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::GetFileExtension, 0x005567A0);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::GetAlphaTestingEnabled, 0x00556BE0);
	ZENGIN_REGISTER_METHOD(zCDecal, &zCDecal::LoadVisualVirtual, 0x00556800);

	ZENGIN_REGISTER_CLASS(zCMesh);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::zCMesh_OnInit, 0x00566D90);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::DeleteAll, 0x00567290);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::VertexInMesh, 0x00568350);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::AllocVerts, 0x00568500);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::AllocPolys, 0x005685F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::AddVertex, zCVertex*(zCMesh::*)(zCVertex*), 0x005686B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::AddVertex, zCVertex*(zCMesh::*)(zVEC3&), 0x005688F0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::AddVertexSmart, 0x00568B80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::AddPoly, zCPolygon*(zCMesh::*)(zVEC3&, zVEC3&, zVEC3&, zVEC2&, zVEC2&, zVEC2&), 0x00568C10);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::AddPoly, zCPolygon*(zCMesh::*)(zCVertex*, zCVertex*, zCVertex*), 0x00568EA0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::AddPoly, zCPolygon*(zCMesh::*)(zCVertex*, zCVertex*, zCVertex*, zCVertex*), 0x00568FB0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::AddPoly, zCPolygon*(zCMesh::*)(zCPolygon*), 0x005690C0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::AddPoly, zCPolygon*(zCMesh::*)(), 0x00569170);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::DeletePoly, 0x00569250);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::DynLightScalePrelit, 0x00569340);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::PrelightMesh, 0x00569350);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SharePoly, 0x00569760);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::CheckRayPolyIntersection, zCPolygon*(zCMesh::*)(zVEC3 const&, zVEC3 const&, zVEC3&), 0x00569780);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::CheckRayPolyIntersection, zCPolygon*(zCMesh::*)(zCCamera&, int, int, zVEC3&), 0x005697E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::PickPolygon, zCPolygon*(zCMesh::*)(zVEC3 const&, zVEC3 const&, zVEC3&), 0x00569990);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::PickPolygon, zCPolygon*(zCMesh::*)(zCCamera&, int, int, zVEC3&), 0x00569A60);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::CalcVertexNormals, 0x00569DE0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::UnSmoothMesh, 0x0056A4E0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SetDefaultPlanarMapping, 0x0056A580);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::CalcBBox3D, 0x0056A610);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::Center, 0x0056A7A0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::TransformAllVerts, 0x0056A8F0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::MergeMesh, 0x0056A9B0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::CalcNormals, 0x0056AE90);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SetMaterial, 0x0056AEC0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::ScaleXZ, 0x0056AF20);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::Scale, 0x0056AF90);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::CheckForMaterials, 0x0056B050);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::Render_novt, 0x0056B210);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::RenderHorizon, 0x0056B4F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::RenderDecal, void(zCMesh::*)(float, float, float, int), 0x0056B7A0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::RenderDecalHorizon, 0x0056B980);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::RenderDecal, void(zCMesh::*)(zTRenderContext&, int), 0x0056BDA0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::ResetStaticLight, 0x0056C000);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SetStaticLight, 0x0056C040);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SetLightDyn, 0x0056C080);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SetLightStatAlpha, 0x0056C0C0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::ResetLightDynToLightStat, 0x0056C100);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::AddToLightDyn, 0x0056C140);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::SaveMSH, void(zCMesh::*)(zCFileBIN&), 0x0056D790);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::SaveMSH, void(zCMesh::*)(zSTRING const&), 0x0056D7B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::LoadMSH, int(zCMesh::*)(zCFileBIN&, int), 0x005700E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::LoadMSH, int(zCMesh::*)(zSTRING const&, int), 0x005716B0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::CreateListsFromArrays, 0x00571980);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::ClearLists, 0x00571A50);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::ArraysToLists, 0x00571AB0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::ShareFeatures, 0x00571B90);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::UnshareFeatures, 0x00572970);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::FlipPolys, 0x00572A90);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SortPolysByMaterial, 0x00572D10);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SortPolysByList, 0x00572DC0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::DeletePolyAndVerts, void(zCMesh::*)(zCPolygon*), 0x00573650);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCMesh, &zCMesh::DeletePolyAndVerts, void(zCMesh::*)(unsigned long), 0x005736E0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::RemoveDegeneratePolys, 0x00573860);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::CombineLightmaps, 0x00573A90);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::LightMesh, 0x00629A50);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::_GetClassDef, 0x00567010);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::Render, 0x0056B190);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::GetBBox3D, 0x00567070);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::GetOBBox3D, 0x005670A0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::GetVisualName, 0x00567020);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::DynLightVisual, 0x00569330);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::CanTraceRay, 0x005670B0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::TraceRay, 0x00569C60);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::GetFileExtension, 0x00567250);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::GetAlphaTestingEnabled, 0x005670C0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::SetAlphaTestingEnabled, 0x005670D0);
	ZENGIN_REGISTER_METHOD(zCMesh, &zCMesh::LoadVisualVirtual, 0x00567270);

} // namespace Gothic_II_Addon
