namespace Gothic_II_Addon {

	ZENGIN_REGISTER_CLASS(zCEventMessage);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCEventMessage, &zCEventMessage::zCEventMessage_OnInit, void(zCEventMessage::*)(), 0x00413B60);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCEventMessage, &zCEventMessage::zCEventMessage_OnInit, void(zCEventMessage::*)(unsigned short), 0x00605560);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::GetMessageID, 0x006056D0);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::PackToBuffer, 0x00605730);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::GetSubType, 0x00674290);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::_GetClassDef, 0x00401F30);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::Archive, 0x006057C0);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::Unarchive, 0x006059C0);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::IsOverlay, 0x00401F40);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::IsNetRelevant, 0x00401F50);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::IsHighPriority, 0x00401F60);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::IsJob, 0x00401F70);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::GetIgnoreCutsceneMode, 0x00401F80);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::Delete, 0x00401F90);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::IsDeleteable, 0x00401FA0);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::IsDeleted, 0x00401FB0);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::SetCutsceneMode, 0x00401FC0);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::GetCutsceneMode, 0x00401FD0);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::MD_GetNumOfSubTypes, 0x00401FE0);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::MD_GetSubTypeString, 0x00401FF0);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::MD_GetVobRefName, 0x00402030);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::MD_SetVobRefName, 0x00402070);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::MD_SetVobParam, 0x00402080);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::MD_GetTimeBehavior, 0x00402090);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::MD_GetMinTime, 0x004020A0);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::Pack, 0x004020B0);
	ZENGIN_REGISTER_METHOD(zCEventMessage, &zCEventMessage::Unpack, 0x004020C0);

	ZENGIN_REGISTER_CLASS(zCEventCore);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::Clear, 0x006060C0);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::_GetClassDef, 0x00402130);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::Archive, 0x006064F0);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::Unarchive, 0x00606560);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::IsNetRelevant, 0x00402150);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::MD_GetNumOfSubTypes, 0x00402140);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::MD_GetSubTypeString, 0x006062F0);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::Pack, 0x00606120);
	ZENGIN_REGISTER_METHOD(zCEventCore, &zCEventCore::Unpack, 0x006061D0);

	ZENGIN_REGISTER_CLASS(zCVob);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::zCVob_OnInit, 0x005FE1E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::GetPositionWorld, zVEC3(zCVob::*)() const, 0x0052DC90);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetAtVectorWorld, 0x0052DCB0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetUpVectorWorld, 0x0052DCD0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetRightVectorWorld, 0x0052DCF0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetVobID, 0x005FE8E0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetAI, 0x005FE8F0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetVobPresetName, 0x005FE940);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetVobPresetName, 0x005FE950);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetRigidBody, 0x005FE960);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ArchivePacked, 0x005FE9D0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ArchiveVerbose, 0x005FEDB0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::UnarchivePacked, 0x005FF200);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::UnarchiveVerbose, 0x005FF720);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetVobName, 0x005FFDD0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetEM, 0x005FFE10);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CalcLightSampleAtOrigin, 0x00600130);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetLightColorStat, 0x006001B0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetLightColorStatGroundPoly, 0x00600440);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetLightColorDyn, 0x00600470);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CalcStaticLight, 0x00600650);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetSectorNameVobIsIn, 0x00600AE0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetGroundShadowSize, 0x00600C30);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetGroundShadowSize, 0x00600C80);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RenderGroundShadow, 0x00600CD0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetClassHelperVisual, 0x006011E0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CalcRenderAlpha, 0x006013E0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetLightColorAtCenter, 0x00601AC0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RemoveVobFromWorld, 0x00601C40);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RemoveVobSubtreeFromWorld, 0x00601C60);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::AddRefVobSubtree, 0x00601CC0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ReleaseVobSubtree, 0x00601D40);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RemoveWorldDependencies, 0x00601DA0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RemoveVobFromGlobalVobTree, 0x00601FF0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RemoveVobFromBspTree, 0x006020E0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetVobInfo, 0x00602100);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetSleeping, 0x00602930);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::UpdateVisualDependencies, 0x00602B20);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::AddVobToWorld_CorrectParentDependencies, 0x00602BB0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ResetOnTimer, 0x00602BD0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetOnTimer, 0x00602BE0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::IsOnTimer, 0x00602C10);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ProcessOnTimer, 0x00602C30);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::DoFrameActivity, 0x00602C60);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CheckModelLimbCollision, 0x00602ED0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CheckModelLimbCollisionLevel, 0x00603A80);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CheckModelLimbCollisionPolys, 0x00604710);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::GetTrafoModelNodeToWorld, zMAT4(zCVob::*)(zSTRING const&), 0x00604960);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::GetTrafoModelNodeToWorld, zMAT4(zCVob::*)(zCModelNodeInst*), 0x00604A50);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetScreenBBox2D, 0x00604AE0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::PackStateBinary, 0x00605110);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::UnpackStateBinary, 0x006051C0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetIsProjectile, 0x00606C00);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetVisual, 0x00616B20);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CalcGroundPoly, 0x0061ACD0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CalcWaterVob, 0x0061AE20);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetCollTypeDefaultFromVisual, 0x0061AEF0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::TouchMovement, 0x0061B060);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::GetNewTrafoObjToWorld, zMAT4 const&(zCVob::*)() const, 0x0061B080);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::GetNewTrafoObjToWorld, zMAT4&(zCVob::*)(), 0x0061B0A0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetNewTrafoObjToWorld, 0x0061B0C0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetBBox3DWorld, 0x0061B0E0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetBBox3DLocal, 0x0061B140);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetBBox3DLocal, 0x0061B1F0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::Move, 0x0061B2E0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::MoveWorld, 0x0061B350);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::MoveLocal, 0x0061B3C0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetRotationWorld, 0x0061B4C0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RotateWorld, 0x0061B520);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RotateLocal, 0x0061B610);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RotateLocalX, 0x0061B6B0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RotateLocalY, 0x0061B720);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RotateLocalZ, 0x0061B790);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RotateWorldX, 0x0061B800);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RotateWorldY, 0x0061B830);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::RotateWorldZ, 0x0061B860);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::GetPositionWorld, void(zCVob::*)(float&, float&, float&) const, 0x0061B890);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetPositionLocal, 0x0061B8C0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetDistanceToVob, 0x0061B910);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetDistanceToVobApprox, 0x0061B970);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetDistanceToVob2, 0x0061BA40);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetPositionLocal, 0x0061BAA0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetPositionWorld, 0x0061BB70);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetTrafo, 0x0061BBD0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetTrafoObjToWorld, 0x0061BC80);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ResetRotationsLocal, 0x0061BCF0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ResetXZRotationsLocal, 0x0061BE20);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ResetRotationsWorld, 0x0061C000);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ResetXZRotationsWorld, 0x0061C090);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetHeadingYLocal, 0x0061C1B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::SetHeadingYWorld, void(zCVob::*)(zVEC3 const&), 0x0061C280);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::SetHeadingYWorld, void(zCVob::*)(zCVob*), 0x0061C450);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetHeadingLocal, 0x0061C5E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::SetHeadingWorld, void(zCVob::*)(zVEC3 const&), 0x0061C6B0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::SetHeadingWorld, void(zCVob::*)(zCVob*), 0x0061C780);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetHeadingAtLocal, 0x0061C860);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::HasParentVob, 0x0061CBA0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetHeadingAtWorld, 0x0061CBC0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetCollDetStat, 0x0061CE50);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetCollDetDyn, 0x0061CF40);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CorrectTrafo, 0x0061D040);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::DoneWithTrafoLocal, 0x0061D0B0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CreateTrafoLocal, 0x0061D100);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetPhysicsEnabled, 0x0061D190);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetVelocity, 0x0061D1C0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::UpdatePhysics, 0x0061D2D0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::DetectCollision, 0x0061D890);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetInMovement, 0x0061D9D0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetInMovementMode, 0x0061DA30);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::BeginMovement, 0x0061DA80);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ResetToOldMovementState, 0x0061DC00);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::UpdateTouchList, 0x0061DC30);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CalcDestinationBBox3DWorld, 0x0061DEE0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::AdoptCollObjResults, 0x0061E020);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetCollisionObject, 0x0061E5E0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetCollisionClass, 0x0061E610);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetCollisionObject, 0x0061E650);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CreateCollisionObject, 0x0061E660);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ResetCollisionObjectState, 0x0061E690);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::DestroyCollisionObject, 0x0061E6D0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CheckEmergencyPutToSleep, 0x0061E710);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CollectCollisionContext_Vobs, 0x0061E870);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CollectCollisionContext_Static, 0x0061EAD0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CollectCollisionContext, 0x0061EDC0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CleanupCollisionContext, 0x0061EE40);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::NotifyCollisionPair, 0x0061EEB0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ExecuteCollisionResponse, 0x0061EF80);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CheckAndResolveCollisions, 0x0061F060);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::IsColliding, 0x0061F4F0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetHomeWorld, 0x006742A0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetStaticVob, 0x006CFFB0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetVobType, 0x006CFFD0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetDrawBBox3D, 0x006CFFE0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetCollDet, 0x006D0000);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::_GetClassDef, 0x0043CCB0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::Archive, 0x005FF140);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::Unarchive, 0x005FFC70);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnTrigger, 0x005FE170);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnUntrigger, 0x005FE180);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnTouch, 0x005FE190);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnUntouch, 0x005FE1A0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnTouchLevel, 0x005FE1B0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnDamage, 0x005FE1C0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnMessage, 0x005FE1D0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnTick, 0x00404270);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::OnTimer, 0x0043CCC0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::PostLoad, 0x00404280);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetCharacterClass, 0x00404290);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetSleepingMode, 0x00602960);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::EndMovement, 0x0061E0D0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::CanThisCollideWith, 0x004042A0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::Render, 0x006015D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::SetVisual, void(zCVob::*)(zCVisual*), 0x006024F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVob, &zCVob::SetVisual, void(zCVob::*)(zSTRING const&), 0x00602680);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetScriptInstance, 0x004042B0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::SetByScriptInstance, 0x004042D0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetCSStateFlags, 0x004042E0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::TraceRay, 0x005FFE40);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::GetTriggerTarget, 0x0043CCD0);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ThisVobAddedToWorld, 0x00601C80);
	ZENGIN_REGISTER_METHOD(zCVob, &zCVob::ThisVobRemovedFromWorld, 0x00601CA0);

	ZENGIN_REGISTER_CLASS(zCVob::zTModelLimbColl);
	ZENGIN_REGISTER_METHOD(zCVob::zTModelLimbColl, &zCVob::zTModelLimbColl::zTModelLimbColl_OnInit, 0x00603A20);

	ZENGIN_REGISTER_CLASS(zCVobLightData);
	ZENGIN_REGISTER_METHOD(zCVobLightData, &zCVobLightData::zCVobLightData_OnInit, 0x0060A970);
	ZENGIN_REGISTER_METHOD(zCVobLightData, &zCVobLightData::SetLensFlareFXByName, 0x00609970);
	ZENGIN_REGISTER_METHOD(zCVobLightData, &zCVobLightData::GetLensFlareFXName, 0x00609A70);
	ZENGIN_REGISTER_METHOD(zCVobLightData, &zCVobLightData::Archive, 0x00609A90);
	ZENGIN_REGISTER_METHOD(zCVobLightData, &zCVobLightData::Unarchive, 0x00609FA0);
	ZENGIN_REGISTER_METHOD(zCVobLightData, &zCVobLightData::SetRange, 0x0060AA60);

	ZENGIN_REGISTER_CLASS(zCVobLightPreset);
	ZENGIN_REGISTER_METHOD(zCVobLightPreset, &zCVobLightPreset::_GetClassDef, 0x005FD690);
	ZENGIN_REGISTER_METHOD(zCVobLightPreset, &zCVobLightPreset::Archive, 0x00609790);
	ZENGIN_REGISTER_METHOD(zCVobLightPreset, &zCVobLightPreset::Unarchive, 0x006097C0);

	ZENGIN_REGISTER_CLASS(zCVobLight);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::zCVobLight_OnInit, 0x00607D10);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::DoAnimation, 0x006081C0);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::SetRange, 0x00608320);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::AddThisToPresetList, 0x00608910);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::SetByPreset, 0x00608BE0);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::SetByPresetInUse, 0x00608E60);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::_GetClassDef, 0x00607E00);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::Archive, 0x006090B0);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::Unarchive, 0x00609100);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::OnTrigger, 0x00608050);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::OnUntrigger, 0x00608120);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::EndMovement, 0x006092B0);
	ZENGIN_REGISTER_METHOD(zCVobLight, &zCVobLight::ThisVobAddedToWorld, 0x00609530);

	ZENGIN_REGISTER_CLASS(zCVobLevelCompo);
	ZENGIN_REGISTER_METHOD(zCVobLevelCompo, &zCVobLevelCompo::zCVobLevelCompo_OnInit, 0x00605280);
	ZENGIN_REGISTER_METHOD(zCVobLevelCompo, &zCVobLevelCompo::HasIdentityTrafo, 0x006052E0);
	ZENGIN_REGISTER_METHOD(zCVobLevelCompo, &zCVobLevelCompo::_GetClassDef, 0x005FDC30);
	ZENGIN_REGISTER_METHOD(zCVobLevelCompo, &zCVobLevelCompo::Archive, 0x00605360);
	ZENGIN_REGISTER_METHOD(zCVobLevelCompo, &zCVobLevelCompo::Unarchive, 0x00605410);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVobLevelCompo, &zCVobLevelCompo::SetVisual, void(zCVobLevelCompo::*)(zCVisual*), 0x006054E0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCVobLevelCompo, &zCVobLevelCompo::SetVisual, void(zCVobLevelCompo::*)(zSTRING const&), 0x00605520);

} // namespace Gothic_II_Addon
