namespace Gothic_II_Addon {

	ZENGIN_REGISTER_CLASS(zCVobWaypoint);
	ZENGIN_REGISTER_METHOD(zCVobWaypoint, &zCVobWaypoint::zCVobWaypoint_OnInit, 0x007ACBC0);
	ZENGIN_REGISTER_METHOD(zCVobWaypoint, &zCVobWaypoint::_GetClassDef, 0x007ACBE0);

	ZENGIN_REGISTER_CLASS(zCWaypoint);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::zCWaypoint_OnInit, 0x007AF770);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWaypoint, &zCWaypoint::Init, void(zCWaypoint::*)(zVEC3&), 0x007AF8A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWaypoint, &zCWaypoint::Init, void(zCWaypoint::*)(float, float, float), 0x007AF900);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWaypoint, &zCWaypoint::Init, void(zCWaypoint::*)(zCVobWaypoint*), 0x007AF970);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::Free, 0x007AFA10);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::GetPositionWorld, 0x007AFB30);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::UpdatePositionWorld, 0x007AFB40);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::SetName, 0x007AFBB0);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::GetName, 0x007AFD10);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::GetVob, 0x007AFE70);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::CalcProperties, 0x007AFE80);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::CorrectHeight, 0x007B00A0);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::InsertWay, 0x007B0140);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::RemoveWay, 0x007B0150);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::HasWay, 0x007B01B0);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::GetNumberOfWays, 0x007B01E0);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::GetWayList, 0x007B0200);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::SetWaypointVob, 0x007B0210);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::Draw, 0x007B0250);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::_GetClassDef, 0x0077DF10);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::Archive, 0x007B0260);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::Unarchive, 0x007B02C0);
	ZENGIN_REGISTER_METHOD(zCWaypoint, &zCWaypoint::CanBeUsed, 0x007AF860);

	ZENGIN_REGISTER_CLASS(zCWay);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWay, &zCWay::zCWay_OnInit, void(zCWay::*)(), 0x007AE830);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWay, &zCWay::zCWay_OnInit, void(zCWay::*)(zCWaypoint*, zCWaypoint*), 0x007AE890);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::Free, 0x007AE9E0);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::GetGoalWaypoint, 0x007AEA90);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::EstimateCost, 0x007AEAA0);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::GetLength, 0x007AEB10);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::GetJumpDistance, 0x007AEBC0);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::GetDistancePos, 0x007AEC80);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::Draw, 0x007AED90);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::GetFloor, 0x007AF270);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::Init, 0x007AE940);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::CalcProperties, 0x007AF310);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::GetChasm, 0x007AF600);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::CanJump, 0x007AF610);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::CanBeUsed, 0x007AED80);
	ZENGIN_REGISTER_METHOD(zCWay, &zCWay::IsObjectOnWay, 0x007AE850);

	ZENGIN_REGISTER_CLASS(zCWayNet);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::zCWayNet_OnInit, void(zCWayNet::*)(), 0x007ACC30);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::zCWayNet_OnInit, void(zCWayNet::*)(zCWorld*), 0x007ACD10);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::HasWaypoint, zCWaypoint*(zCWayNet::*)(float, float, float), 0x007ACF00);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::HasWaypoint, int(zCWayNet::*)(zCWaypoint*), 0x007ACF70);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::HasWaypoint, zCWaypoint*(zCWayNet::*)(zVEC3&), 0x007ACFA0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::InsertWaypoint, zCWaypoint*(zCWayNet::*)(float, float, float), 0x007ACFF0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::InsertWaypoint, void(zCWayNet::*)(zCWaypoint*), 0x007AD100);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::InsertWaypoint, void(zCWayNet::*)(zCWaypoint*, zCWaypoint*, zCWaypoint*), 0x007AD130);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::DeleteWaypoint, 0x007AD2B0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::CreateWay, 0x007AD420);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::DeleteWay, 0x007AD4F0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::GetNearestWaypoint, 0x007AD660);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::GetSecNearestWaypoint, 0x007AD6F0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::CorrectHeight, 0x007AD7B0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::Draw, 0x007AD870);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::UpdateVobDependencies, 0x007AD8A0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::ClearVobDependencies, 0x007ADAF0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::CreateVobDependencies, 0x007ADCF0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::MergeWaypoints, 0x007ADF70);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::CheckConsistency, 0x007AE230);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::AddWays, 0x007AE730);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::GetWaypoint, 0x007B0330);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::SearchWaypoint, 0x007B04A0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::FindRoute, zCRoute*(zCWayNet::*)(zVEC3 const&, zVEC3 const&, zCVob const*), 0x007B04D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::FindRoute, zCRoute*(zCWayNet::*)(zVEC3 const&, zCWaypoint*, zCVob const*), 0x007B0560);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::FindRoute, zCRoute*(zCWayNet::*)(zVEC3 const&, zSTRING const&, zCVob const*), 0x007B05D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::FindRoute, zCRoute*(zCWayNet::*)(zCWaypoint*, zCWaypoint*, zCVob const*), 0x007B0640);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWayNet, &zCWayNet::FindRoute, zCRoute*(zCWayNet::*)(zSTRING const&, zSTRING const&, zCVob const*), 0x007B0680);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::InsertInOpen, 0x007B0700);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::IsInOpen, 0x007B0730);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::InsertInClosed, 0x007B0750);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::RemoveFromClosed, 0x007B0770);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::IsInClosed, 0x007B0780);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::IsInAnyList, 0x007B07A0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::EstimateCost, 0x007B07D0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::CreateRoute, 0x007B0830);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::AStar, 0x007B08D0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::GetWPList, 0x007B0B50);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::CreateWPVobList, 0x007B0CB0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::RemoveUnusedWPVobs, 0x007B0CF0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::ArchiveOldFormat, 0x007B0E40);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::UnarchiveOldFormat, 0x007B16F0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::CalcProperties, 0x007B2820);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::_GetClassDef, 0x007ACCD0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::Archive, 0x007B11D0);
	ZENGIN_REGISTER_METHOD(zCWayNet, &zCWayNet::Unarchive, 0x007B2200);

	ZENGIN_REGISTER_CLASS(zCRoute);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::zCRoute_OnInit, 0x007B2860);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::SetStart, 0x007B28E0);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::GetNextWP, 0x007B28F0);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::GetTargetWP, 0x007B2960);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::GetCurrentWay, 0x007B2970);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::GetDesc, 0x007B2980);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::GetRemainingDesc, 0x007B2B60);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::GetNumberOfWaypoints, 0x007B2D40);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::IsEmpty, 0x007B2D60);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::IsLastTarget, 0x007B2D80);
	ZENGIN_REGISTER_METHOD(zCRoute, &zCRoute::GetInterpolatedPosition, 0x007B2DA0);

	ZENGIN_REGISTER_CLASS(zCVobSpot);
	ZENGIN_REGISTER_METHOD(zCVobSpot, &zCVobSpot::zCVobSpot_OnInit, 0x007B2FA0);
	ZENGIN_REGISTER_METHOD(zCVobSpot, &zCVobSpot::IsAvailable, 0x007B3020);
	ZENGIN_REGISTER_METHOD(zCVobSpot, &zCVobSpot::MarkAsUsed, 0x007B31A0);
	ZENGIN_REGISTER_METHOD(zCVobSpot, &zCVobSpot::_GetClassDef, 0x007B2FC0);

	ZENGIN_REGISTER_CLASS(zCVobStartpoint);
	ZENGIN_REGISTER_METHOD(zCVobStartpoint, &zCVobStartpoint::_GetClassDef, 0x007B3940);

} // namespace Gothic_II_Addon
