namespace Gothic_II_Addon {

	ZENGIN_REGISTER_CLASS(zCPatch);
	ZENGIN_REGISTER_METHOD(zCPatch, &zCPatch::zCPatch_OnInit, 0x0062C0C0);
	ZENGIN_REGISTER_METHOD(zCPatch, &zCPatch::DoTransfers, 0x0062F000);

	ZENGIN_REGISTER_CLASS(zCPatchMap);
	ZENGIN_REGISTER_METHOD(zCPatchMap, &zCPatchMap::CheckRaySurfaceIntersection, 0x0062C110);

	ZENGIN_REGISTER_CLASS(zCWorld);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::zCWorld_OnInit, 0x0061FA40);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GetActiveSkyControler, 0x006203A0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SetSkyControlerIndoor, 0x006203D0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SetSkyControlerOutdoor, 0x00620410);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::AddZone, 0x006204C0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveZone, 0x00620630);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveAllZones, 0x00620770);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::UpdateZone, 0x006207E0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::ProcessZones, 0x006207F0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::ShowZonesDebugInfo, 0x00620E60);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::ShowTextureStats, 0x00621280);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::Render, 0x00621700);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::TraceRayFirstHit, int(__fastcall zCWorld::*)(zVEC3 const&, zVEC3 const&, zCArray<zCVob*> const*, int), 0x00621960);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::TraceRayNearestHit, int(__fastcall zCWorld::*)(zVEC3 const&, zVEC3 const&, zCArray<zCVob*> const*, int), 0x00621B80);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::TraceRayFirstHit, int(__fastcall zCWorld::*)(zVEC3 const&, zVEC3 const&, zCVob*, int), 0x00621E70);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::TraceRayNearestHit, int(__fastcall zCWorld::*)(zVEC3 const&, zVEC3 const&, zCVob*, int), 0x00621FA0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::TraceRayFirstHitCache, int(__fastcall zCWorld::*)(zVEC3 const&, zVEC3 const&, zCArray<zCVob*> const*, int, zCRayCache*), 0x006220D0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::TraceRayFirstHitCache, int(__fastcall zCWorld::*)(zVEC3 const&, zVEC3 const&, zCVob*, int, zCRayCache*), 0x00622230);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::TraceRayNearestHitCache, int(__fastcall zCWorld::*)(zVEC3 const&, zVEC3 const&, zCArray<zCVob*> const*, int, zCRayCache*), 0x006223F0);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::TraceRayNearestHitCache, int(__fastcall zCWorld::*)(zVEC3 const&, zVEC3 const&, zCVob*, int, zCRayCache*), 0x00622550);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::PickScene, 0x00622710);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::TraverseBsp, 0x00622980);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::TraverseBspAddVobsToMesh, 0x00622A80);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SaveBspTreeMesh3DS, 0x00622E90);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::CompileWorld, 0x00622EC0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchZoneListByClass, 0x00624400);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchZoneDefaultByClass, 0x00624530);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::ShouldAddThisVobToBsp, 0x006247B0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::AddVobAsChild_novt, 0x006247F0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::AddVob, 0x00624810);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveVob_novt, 0x00624BA0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveVobSubtree_r, 0x00624BC0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveVobSubtree_novt, 0x00624D90);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::MoveVobSubtreeTo_novt, 0x00624E70);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::MoveVobSubtreeToWorldSpace, 0x00624E90);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveVobFromLists, 0x00624EB0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::PrintStatus, 0x00625080);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::PrintGlobalVobTree, 0x00625AE0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::PrintActiveVobs, 0x00625DA0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::UpdateVobTreeBspDependencies, 0x00625FE0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::MoveVobs, 0x00626050);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::AdvanceClock, 0x006260E0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SaveBspTree, 0x00626120);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::LoadBspTree, 0x006262A0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::DebugMarkOccluderPolys, 0x006263D0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::UnarcTraverseVobs, 0x00626570);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GetProgressBar, 0x006269C0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::ArcTraverseVobs, 0x006274A0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::TraverseVobTree, 0x00627F10);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::GetVobHashIndex, unsigned long(zCWorld::*)(zSTRING const&), 0x00627F70);
	ZENGIN_REGISTER_METHOD_EXPLICIT(zCWorld, &zCWorld::GetVobHashIndex, unsigned long(zCWorld::*)(zCVob*), 0x00627FA0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::InsertVobHashTable, 0x00627FE0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveVobHashTable, 0x00628100);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchVobHashTable, 0x00628190);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchVobListHashTable, 0x00628270);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SetOwnerSession, 0x00628430);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GetOwnerSession, 0x00628480);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::ResetCutscenePlayer, 0x00628490);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RegisterPerFrameCallback, 0x006284E0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::UnregisterPerFrameCallback, 0x00628610);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::LightWorldStaticUncompiled, 0x00629B30);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::LightWorldStaticCompiled, 0x00629F70);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GenerateStaticVertexLighting, 0x0062A760);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::LightingTestRay, 0x0062AA70);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GetSurfaceLightmapBBox2D, 0x0062AB30);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GetPhongNormal, 0x0062AF90);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GeneratePatchMapFromSurface, 0x0062B350);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GenerateLightmapFromPatchMap, 0x0062C1B0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::LightPatchMap, 0x0062D4C0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GenerateSurfaces, 0x0062D970);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::MakeTransfers, 0x0062E800);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GenerateLightmapsRadiosity, 0x0062F150);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GenerateLightmaps, 0x0062F3A0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GenerateStaticWorldLighting, 0x0062FB70);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::MakeVobLightingDirty, 0x0062FE60);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SetVobFarClipZScalability, 0x00637210);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GetBspTree, 0x006D0020);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::_GetClassDef, 0x00620040);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::Archive, 0x00627890);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::Unarchive, 0x006269D0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::LoadWorld, 0x006270D0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SaveWorld, 0x00627BB0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::MergeVobSubtree, 0x006273E0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SaveVobSubtree, 0x00627E50);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::DisposeWorld, 0x00623D30);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::DisposeVobs, 0x00623960);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::DisposeVobsDbg, 0x00623AF0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::DisposeStaticWorld, 0x00623C80);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::AddVobAsChild, 0x006245A0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveVob, 0x00624B70);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RemoveVobSubtree, 0x00624D60);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::MoveVobSubtreeTo, 0x00624DB0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::GetPlayerGroup, 0x00620050);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchVob, 0x00623F10);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchVobByID, 0x00623F60);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchVobByName, 0x00623FB0);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchVobListByName, 0x00624090);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchVobListByClass, 0x00624250);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::SearchVobListByBaseClass, 0x00624320);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::VobAddedToWorld, 0x00624830);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::VobRemovedFromWorld, 0x00624970);
	ZENGIN_REGISTER_METHOD(zCWorld, &zCWorld::RenderWaynet, 0x00620450);

} // namespace Gothic_II_Addon
