#ifndef SQUIRRELINCLUDES_H
#define SQUIRRELINCLUDES_H
#include <squirrel.h>
#include <sqstdio.h>
#include <sqstdmath.h>
#include <sqstdstring.h>
#include <sqstdsystem.h>
#include <sqstdblob.h>
#include <sqstdaux.h>
#endif //SQUIRRELINCLUDES_H
